### ISSUE TITLE
"template must be a function"

### ISSUE THREAD

**Issue by stebru** [emberjs/ember.js#10423] opened 2015-02-11 15:21 UTC
I'm getting the following error in the console after upgrading to Ember 1.10.0:

```
Uncaught Error: Assertion Failed: template must be a function. Did you mean to call Ember.Handlebars.compile("...") or specify templateName instead?
```

I guess this has something to do with the new HTMLBars engine? I'm using gulp-ember-templates https://github.com/swelham/gulp-ember-templates for precompiling my templates. Should I file an issue over there? Is there perhaps an easy way to create my own gulp task for this?

**Comment by btecu** [comment] 2015-02-11 17:15
It's possible that the cause is one of the addons you're using that hasn't been updated .

**Comment by surpmillet** [comment] 2015-02-11 17:42
i got the same error

**Comment by joeruello** [comment] 2015-02-12 00:02
That package seems to be outdated, try https://github.com/mattma/gulp-htmlbars

**Comment by mixonic** [comment] 2015-02-12 03:35
I'm going to close this based on the presumption that @joeruello has pointed out a more up-to-date library. But please re-open if I've missed something!

**Closed by mixonic** 2015-02-12 03:35 UTC

**Comment by jesuskwice** [comment] 2015-02-12 20:20
Hi all,

I'm getting the same error via ember-rails.. (i.e., not referencing any EmberCLI/Bower addons)?

Here's what I'm running: 
Ember: 1.10.0
Ember Data: 1.0.0-beta.14.1
jQuery: 1.10.2
Ember-Rails: 0.16.2 (This looks ok no?: https://github.com/emberjs/ember-rails/tree/master/lib/ember/handlebars)

Any help greatly appreciated!

**Comment by inexuscore** [comment] 2015-02-17 12:03
I've been using Ember for the past two months and haven't had a problem with it. Today I downloaded the starter kit (v1.10) and created a new project. everything worked fine till i installed some libraries to pre-compile my templates. here's my **gruntfile.js**:
```
module.exports = function(grunt) {
	grunt.initConfig({
		pkg: grunt.file.readJSON('package.json'),
		emberTemplates: {
			compile: {
				options: {
					templateBasePath: /app\/templates\//
				},
				files: {
					"dist/js/templates.js": "app/templates/*.hbs"
				}
			}
		},
		watch: {
			emberTemplates: {
				files: 'app/templates/**/*.hbs',
				tasks: ['emberTemplates']
			}
		}
	});

	grunt.loadNpmTasks('grunt-ember-templates');
	grunt.loadNpmTasks('grunt-contrib-watch');

	grunt.registerTask('default', ['emberTemplates', 'watch']);
}
```

I've examined the output files and my templates are compiled correctly, but i get the same error:
```
Error: Assertion Failed: template must be a function. Did you mean to call Ember.Handlebars.compile("...") or specify templateName instead?
```
I've no idea how to resolve this issue and i haven't been able to find anything helpful on the internet so far, so if someone could clear this up i would really appreciate it.

Thanks

**Comment by fivetanley** [comment] 2015-02-17 14:09
@inexuscore Robert from the core team did a great writeup here: http://emberjs.com/blog/2015/02/05/compiling-templates-in-1-10-0.html if you search for grunt-ember-templates on the page and follow the link to that PR you should find what you're looking for.

**Comment by inexuscore** [comment] 2015-02-18 13:15
@fivetanley Yes I've read that post just today, but I'm still having trouble compiling my templates. I've updated my grunt task accordingly, and my templates are compiled fine. but when i start the app i get this error:
```
Assertion Failed: template must be a function. Did you mean to call Ember.Handlebars.compile("...") or specify templateName instead?
```
I've posted about this under that PR, any clues?
Thanks
