### ISSUE TITLE
Ember.run.later sometimes does not execute callback on time

### ISSUE THREAD

**Issue by dschmidt** [emberjs/ember.js#10479] opened 2015-02-17 12:34 UTC
Hi,

I'm seeing something that looks like a race condition to me that sometimes stops run.later from working.
More concretely:
It looks like runs get stuck in the runloop, they aren't executed after the specified time but only when something else starts a new runloop, for example if I click on something and the DOM changes or even more interesting, it's even enough to put another ```Ember.run.later``` into the JS console: then it looks like a runloop is started again and the scheduled runs are processed.

This is the minimal example I could reproduce this with:
http://emberjs.jsbin.com/siboromaho/1/edit
I need to run it up to 80 times to trigger the behaviour ... :-\
When you see that ```some foo``` isn't printed to the console you can press the "start runloop" button and it will get printed to the console immediately.

The next example is closer to what I'm doing in my app but it is also slightly more complicated, you don't need to include the SomeView but if you do, it's triggered way more often. 
http://emberjs.jsbin.com/xulibakupe/1/edit

The examples look a bit artificial but it's what happens in my app through setting properties and observers. AFAICT I need the Promise in there and also the new ```Èmber.run.later``` in the then function, without it I can't reproduce in my app even - or it just reduces the probability so far that if you remove it you hardly ever trigger it. 
FWIW I'm on Chromium 39

Best regards,
Domme

**Comment by stefanpenner** [comment] 2015-02-17 14:56
ouch, something seems funky. I suspect this may be an issue with https://github.com/ebryn/backburner.js

**Comment by ppcano** [comment] 2015-03-07 19:29
I confirm this issue, we use multiple Pollers which makes use of `run.later` to execute a function periodically.  Then, a `run.later callback` randomly stops all other `run.later callbacks` of being executed and they will only be restarted when the stopper Poller is executed again.

**Comment by chesterlaw** [comment] 2015-04-01 01:02
Can confirm as well. We use `run.later`'s to poll an API, as well as do animations in components, and all of them stop at the same time.

**Comment by stefanpenner** [comment] 2015-04-01 02:42
Is this cross platform or just a specific browser? If there is a repro it'll be easier to debug. Otherwise someone needs to audit back burners timers

**Comment by dschmidt** [comment] 2015-04-01 14:33
@stefanpenner well, I provided those jsbins?
I saw it in Chromium on Linux and @oxidus reported to me several times that he had issues with ```Ember.run.later``` not firing and he is on OSX.
He usually is on Chrome, not sure if he tested exactly that with e.g. Safari. Anyway replacing it with setTimeout always circumvented the issue for us

**Comment by stefanpenner** [comment] 2015-04-01 14:38
> @stefanpenner well, I provided those jsbins?

oops didn't notice, added to my queue for later this week.

**Comment by raytiley** [comment] 2015-04-03 18:18
Just ran into this too.

**Comment by igorT** [comment] 2015-04-23 21:13
I think I just run into this as well. Not sure what the cause is

**Comment by igorT** [comment] 2015-04-24 01:28
I can consistently reproduce it in a friend's app, will have a chance to take a look wednesday

**Comment by igorT** [comment] 2015-04-24 01:56
Here is a JSBin that can consistently reproduce the issue:
http://emberjs.jsbin.com/vasafovuxo/1/edit

**Comment by rwjblue** [comment] 2015-08-10 16:06
Looks like there is an issue open upstream for this now.  I'm not sure anyone has time to dig in though...

**Comment by reemasaluja** [comment] 2015-08-10 18:49
with Ember.run.next(this,functionName) callbacks are inconsistent

**Comment by rwjblue** [comment] 2015-08-10 19:05
@reemasaluja - Not sure that is related to this issue.

**Comment by workmanw** [comment] 2015-10-06 20:50
@reemasaluja @rwjblue FWIW I think `Ember.run.next` is related in this case. We experienced this issue too with `Ember.run.next` and updating backburner.js seem to resolve the issue (See: emberjs/ember.js#12193).

**Comment by reemasaluja** [comment] 2015-10-06 22:11
Thanks

**Comment by rwjblue** [comment] 2016-04-13 23:34
This was fixed in https://github.com/ebryn/backburner.js/pull/151.

**Closed by rwjblue** 2016-04-13 23:34 UTC
Labels: Bug
