### ISSUE TITLE
Router class isn't used

### ISSUE THREAD

**Issue by MajorBreakfast** [emberjs/ember.js#10526] opened 2015-02-24 23:42 UTC
On 1.11.0-beta.2

``` JavaScript
var Router = Ember.Router.extend({ /* ... */ })
var App = Ember.Application.extend({ Router: Router }) // Passing in the router class stopped working
```

@machty

**Comment by rwjblue** [comment] 2015-02-25 00:02
Definitely a regression. Most likely caused by one of these PR's:

https://github.com/emberjs/ember.js/pull/10297/files
https://github.com/emberjs/ember.js/pull/10271

I'll try to dig into it a bit more later this evening.

**Comment by tomdale** [comment] 2015-02-25 05:11
Almost certainly related to our work, but we kept this particular API in mind so it should be an easy fix and is likely just a dumb oversight on our part.

**Comment by stefanpenner** [comment] 2015-02-25 05:21
https://github.com/emberjs/ember.js/blob/master/packages/ember-application/lib/system/application.js#L294-L298

**Comment by stefanpenner** [comment] 2015-02-25 05:27
^^ likely needs to be  `this.Router = this.Router || Router.extend`

**Comment by stefanpenner** [comment] 2015-02-25 05:28
I don't see where the router is registered and then subsequently resolved, where is this code now?

**Comment by rwjblue** [comment] 2015-02-25 05:49
Will be fixed by https://github.com/emberjs/ember.js/pull/10528.

**Closed** 2015-02-25 06:08 UTC
Labels: Bug, Regression

**Comment by MajorBreakfast** [comment] 2015-02-25 08:41
Nice!
