### ISSUE TITLE
Ember 2.18 regression - TargetObject refactor breaks action propagation with target property defined

### ISSUE THREAD

**Issue by Dhaulagiri** [emberjs/ember.js#15966] opened 2017-12-11 15:15 UTC
Came across an odd situation trying out 2.18.0-beta.2 in our app where the action we fire to close modals no longer work.  I traced it to, I think, [this change](https://github.com/emberjs/ember.js/commit/24a32b14d25c2d2b6dcf845fc22bc450f4e14ae1) to how `getTarget` finds the target of an action.  It seems that if the object that invokes the action has a `target` property defined on it for whatever reason the action gets swallowed.

For our case I traced it to where ember-modal-dialog has a `target` property on [its base component](https://github.com/yapplabs/ember-modal-dialog/blob/c6c783c7a4caa7e70cf5c7cca15e4f4a595386ac/addon/components/modal-dialog.js#L151), but I was also able to create [this very bare bones twiddle](https://ember-twiddle.com/fc7fc1b2fc21db41404b515fea7357b4?openFiles=components.my-component.js%2Ctemplates.components.my-component.hbs) to reproduce the problem.  If you comment out the `target` property on the component in the twiddle you'll see the action correctly propagate and show an alert but with the property in place clicking the link does nothing.

**Comment by rwjblue** [comment] 2017-12-11 16:50
Thanks for reporting. I’m traveling today and likely won’t habe a ton of time to dig in, but it does sound like a regression to me. Thanks for testing beta and reporting before the regression is released!

**Comment by Dhaulagiri** [comment] 2017-12-14 22:32
I'm able to work around this for now by setting `target: ''` (entire test suite is green then too!), but let me know if I can assist tracking this down more concretely.

**Comment by acorncom** [comment] 2018-01-25 02:52
Confirmed that commenting out that `target` in the Twiddle does indeed lead to things working. Thanks @Dhaulagiri !

**Comment by pixelhandler** [comment] 2018-09-28 17:54
@Dhaulagiri @acorncom @rwjblue @slannigan is this still an issue, perhaps we should close or create a new reproduction of this, what do you think?

**Comment by Dhaulagiri** [comment] 2018-09-28 18:28
This still happens in Ember 3.4 but also the workaround is so trivial that I am not too hung up on fixing this myself

**Comment by pixelhandler** [comment] 2018-10-12 16:10
I updated the twiddle with example using Ember 3.4 https://ember-twiddle.com/34cbed606f611c3b679794f56a5c4ab9?fileTreeShown=false&openFiles=components.my-component.js%2C

**Comment by jbailey4** [comment] 2018-10-24 13:07
Recently ran into this as well. My app was setting a string action on `modal-dialog`'s `onClose` attr, which relied on the pre-2.18 `sendAction` semantics. Using the `action` helper and setting an actual function to the `onClose` attr fixed the problem for me.

Not sure if this regression would be consider a breaking change though, since the `Component.target` prop was private and undocumented...

**Comment by sandstrom** [comment] 2021-03-20 21:09
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? With the new glimmer / angle bracket components being "the future", maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.

**Comment by sandstrom** [comment] 2023-07-30 21:35
This repo has a lot of open issues, some that that have been open for several years. 

The reality is that this is an open-source project, and the time of core team members is very limited. We all want them to focus on moving the framework forward (high-leverage things).

I'll be closing this for now, to keep the list of open issues manageable. I hope you understand!

If you disagree, we can reopen, but in that case, your help in fixing this would be appreciated (for example a PR with a bugfix).

**Closed by sandstrom** 2023-07-30 21:35 UTC
Labels: Bug, Regression, Has Reproduction
