### ISSUE TITLE
[Bug] Query param sticky value lost

### ISSUE THREAD

**Issue by patsy-issa** [emberjs/ember.js#19307] opened 2020-12-15 13:29 UTC
### 🐞 Describe the Bug
Query parameters lose their sticky value and revert to the default defined within the controller of the parent route when transitioning to a child route. Both the parent and child route have slow model hooks and loading substates. The last working version that does not have this bug is ember-source `2.22.0`, all versions since then up to `2.24.0-beta.2` contain this bug.

#19249 was aimed at resolving this issue but it seems the use case presented in the reproduction might have slipped by.

### 🔬 Minimal Reproduction
- Checkout the [reproduction repository](https://github.com/patsy-issa/ember-qp-bug-reproduction)
- `yarn install` & `yarn start`
- Navigate to `/media`
- click on the movies link
- select an item from the movie list

### 😕 Actual Behavior

During the transition the list will revert back to the albums for a short duration before transitioning into the correct route. This is due to the `filter` query parameter's value being set to its [default value](https://github.com/patsy-issa/ember-qp-bug-reproduction/blob/1b1f23e5068059e20feb91c60bab0cdb87614b5f/app/controllers/media.js#L6) when the loading route is activating.

![ember-qp-bug](https://user-images.githubusercontent.com/4568519/102220951-cb0b2100-3ee1-11eb-853c-245b634ac48a.gif)

### 🤔 Expected Behavior
The `filter` query parameter's value does not change when the loading route is active.

### 🌍 Environment

- Ember: `^2.22.1`
- Node.js/npm: 14.1.0/6.14.4
- OS: macOS Catalina 10.15.6
- Browser: Brave Version 1.18.70

### ➕ Related issues

- #14438
- #16986
- #12107
- #11857

**Comment by rreckonerr** [comment] 2020-12-15 22:44
Yeah, router_js [v7.1.1](https://github.com/tildeio/router.js/compare/v7.1.0...v7.1.1) is the cause for it. Specifically, https://github.com/tildeio/router.js/pull/308 that aimed to deal with query params serialization errors and introduced this bug. Apparently, tests didn't take into account the intermediate state when query params were reset to default values. 😥

cc @rwjblue

**Comment by rreckonerr** [comment] 2020-12-17 19:35
Somehow we're losing QP's for intermediate transitions (like `medium_loading` from your example). Was debugging router.js today and appeared that assigning QP's from old state to the new one fixes your issue and router.js/ember.js test suits are still passing.
https://github.com/tildeio/router.js/blob/3b5638087818fca1dde25e7cea890f08884f7123/lib/router/router.ts#L231-L234
```diff
     if (isIntermediate) {
+      newState.queryParams = oldState!.queryParams;
       let transition = new InternalTransition(this, undefined, newState);
       this.toReadOnlyInfos(transition, newState);
       this.setupContexts(newState, transition);
```
Will try to investigate it further.

**Comment by rreckonerr** [comment] 2021-02-13 17:59
Seems like this issue got fixed somewhere along the way. Tested it on `3.25.0-canary` and here's the result:
![Feb-13-2021 18-56-44](https://user-images.githubusercontent.com/30495731/107857238-e9d05a00-6e35-11eb-9da1-ebd7d38b7fd2.gif)

**Comment by sly7-7** [comment] 2021-03-02 08:43
@rreckonerr I just hoped 3.25 would resolve my issue as well, but it doesn't 😢  I don't remember seeing this on 3.22

**Comment by rreckonerr** [comment] 2021-03-02 09:06
@sly7-7 I just symlinked `3.27.0-alpha.1` and it seems to work.

- ember-qp-bug-reproduction output
  ```bash
  Package: ember-source
    * Specified: ~3.23.1
    * Symlinked: 3.27.0-alpha.1
  ```
- `yarn.lock` contents in symlinked ember.js `3.27.0-alpha.1`
  ```bash
  router_js@^7.1.1:
    version "7.1.1"
    resolved "https://registry.yarnpkg.com/router_js/-/router_js-7.1.1.tgz#cb7614a96cfb6bc65c066668b2dd32e3ad7ca38d"
  ```

---

Can you check out if it works for you following the steps below?

### Steps to reproduce

1. Clone ember.js repo
2. `git checkout v3.27.0-alpha.1`
3. `yarn install`
4. `yarn link`
5. Go to `ember-qp-bug-reproduction` folder and link `yarn link ember-source`
6. `yarn install --force`
7. `ember s`
8. Check your browser

**Comment by sly7-7** [comment] 2021-03-02 09:53
@rreckonerr this is perfect timing :) I've just reproduced against 3.25 on a minimal repo. The bug seems to occur only if there is a loading template. I'm checking with this version right now

**Comment by sly7-7** [comment] 2021-03-02 13:27
@rreckonerr I've created https://github.com/sly7-7/bug-query-params where the bug is still here, even against ember's master branch.

**Comment by rreckonerr** [comment] 2021-03-02 13:42
@sly7-7 It might be that the fix is included in not yet release 3.27.x. 👇

> Seems like this issue got fixed somewhere along the way. Tested it on 3.27.0 and here's the result

Were you able to fix the issue by linking the ember.js repo?

**Comment by sly7-7** [comment] 2021-03-02 13:49
@rreckonerr I've ran against master, so this should be the same result ? Anyway, I'll try :)

**Comment by rreckonerr** [comment] 2021-03-02 15:26
Appears that I was still running ember 3.25 even after yarn linking 3.27. The bug is still there, thanks @sly7-7

**Comment by sly7-7** [comment] 2021-03-04 09:10
@rreckonerr @patsy-issa , if that could help, as a workaround for now, I removed the `loading` template, and replace it by a loading action on the parent route which set a `isLoading` flag on the controller, coupled with an

```handlebars
 {{#if this.isLoading}}
   <LoadingComponent>
{{else}}
  {{outlet}}
{{/if}}
```

in the template.

**Comment by sly7-7** [comment] 2021-03-04 18:06
@patsy-issa This should be solved now, but we have to wait a new release of the router, and a bugfix release of ember.js

**Comment by rreckonerr** [comment] 2021-03-04 18:25
Yup, tested it against https://github.com/patsy-issa/ember-qp-bug-reproduction and it works! 
Thanks, @sly7-7 🎉🎉🎉

**Closed** 2021-03-07 20:19 UTC
