### ISSUE TITLE
Template/layout resolution docs

### ISSUE THREAD

**Issue by stavarotti** [emberjs/ember.js#11237] opened 2015-05-20 18:00 UTC
The docs currently state that you can specify a different [layout/layoutName](http://emberjs.com/api/classes/Ember.Component.html#property_layout) however, specifying a different `layout` and/or `layoutName` seems to have no effect unless set within `init`.

Should the docs be updated or am I misunderstanding the usage?

**Comment by rwjblue** [comment] 2015-05-20 18:00
Duplicate of https://github.com/emberjs/ember.js/issues/11186.

**Closed by rwjblue** 2015-05-20 18:00 UTC

**Comment by stavarotti** [comment] 2015-05-20 18:06
@rwjblue I saw that issue however, this does not work in 1.12.0
