### ISSUE TITLE
Glimmer/Angle-Bracket splattributes problems

### ISSUE THREAD

**Issue by gossi** [emberjs/ember.js#17147] opened 2018-10-24 07:45 UTC
After a discussion yesterday with @rwjblue on discord I had some problems with `...attributes` not being displayed. So he ensured them with a test in #17145 

This morning I tried to recreate the tests in my code and was able to replicate the results. This got me thinking and I run more tests.
Bascially, I have template-only-glimmer components (I do have a class according to it but it has an empty body =). Here are my findings:

**Template 1 (div)**:

```hbs
<div local-class="button--primary" type="button" ...attributes>
  {{yield}}
</div>
```

---

Invocation 1.1:

```hbs
<Button disabled data-bar type="submit" />
```

Result 1.1:

```html
<div class="_button-primary_x5ocvo _button_x5ocvo" type="submit" disabled data-bar></div>
```

---

Invocation 1.2:

```hbs
<Button data-bar/>
```

Result 1.2:

```html
<div class="_button-primary_x5ocvo _button_x5ocvo" type="button" data-bar></div>
```

---

**Template 2 (original template: button)**:

```hbs
<button local-class="button--primary" type="button" ...attributes>
  {{yield}}
</button>
```

---

Invocation 2.1:

```hbs
<Button data-bar/>
```

Result 2.1:

```html
<button class="_button-primary_x5ocvo _button_x5ocvo" type="button" data-bar></button>
```

---

Invocation 2.2:

```hbs
<Button disabled data-bar type="submit" />
```

Result 2.2:

```html
<button class="_button-primary_x5ocvo _button_x5ocvo" type="submit" data-bar></button>
```

---

Invocation 2.3:

```hbs
<Button data-bar disabled="disabled"/>
```

Result 2.3:

```html
<button class="_button-primary_x5ocvo _button_x5ocvo" type="button" disabled data-bar></button>
```

**Comment by rwjblue** [comment] 2018-10-24 10:34
@gossi - Would you mind submitting a failing test case like the ones I added in https://github.com/emberjs/ember.js/pull/17145?

**Comment by rwjblue** [comment] 2018-10-24 10:36
From what I can see in the description above, you are seeing that `disabled` when passed in the invocation without a value doesn’t get added to the `button` element (but it does if the element in question is `div`), is that right?

**Comment by gossi** [comment] 2018-10-24 13:31
I was visually inspecting the DOM tree with the "Elements" tab from chrome devtools. But additionally I was testing for CSS `:disabled` state. They weren't triggered, so I am pretty sure, it didn't work.

Will provide a failing test later on.

**Comment by cibernox** [comment] 2019-02-01 20:08
I believe this might have been fixed recently in the latest patch version of 3.4 and 3.7. @gossi can you confirm?

**Comment by gossi** [comment] 2019-02-02 11:38
I attached a PR with tests to demo the bug

**Comment by rwjblue** [comment] 2019-02-02 19:19
FWIW, the test added in that PR is currently passing (the PR failed due to a linting error, but all of the actual tests passed).

**Comment by gossi** [comment] 2019-02-02 20:07
I was kinda guessing, what the tests would look like (I applied your suggestions). Locally they failed for me (with and without your applied suggestions):

<img width="1635" alt="bildschirmfoto 2019-02-02 um 21 02 25" src="https://user-images.githubusercontent.com/283700/52168753-399bc700-272e-11e9-8dcd-3d84a43c11eb.png">

My [comment](https://github.com/emberjs/ember.js/issues/17147#issuecomment-459957285) above was manual testing, inspecting in the browser.

What's going wrong here?

**Comment by chancancode** [comment] 2019-04-06 01:05
I confirmed that this is not the same thing as #17870. The test not failing issue should be fixed by #17847. If you rebase, it should fail on dev as well.

**Comment by gossi** [comment] 2019-04-07 09:10
Thanks for investigation, I rebased my PR.

**Comment by locks** [comment] 2019-05-30 17:06
I am closing this issue as resolve due to my understanding of the above discussion. Please reopen if otherwise!

**Closed by locks** 2019-05-30 17:06 UTC
Labels: Needs Reproduction

**Comment by rwjblue** [comment] 2019-05-30 19:19
It is not resolved, but the failing test PR (https://github.com/emberjs/ember.js/pull/17551) is probably fine for tracking the underlying issue.
