### ISSUE TITLE
Performing a transition during another transition may result in a page refresh

### ISSUE THREAD

**Issue by Dremora** [emberjs/ember.js#13383] opened 2016-04-20 13:47 UTC
[Ember Twidde](https://ember-twiddle.com/a82519ec00b9644883c6daaa2922032c)

I was able to narrow the circumstances down to the following:
* There should be an element performing a transition when it's clicked
  * click handler should be placed inside an action. Having it at the root of the component (the `click()` method) doesn't work as the method doesn't get called. 
* One of the children of this element should be `{{link-to}}` helper performing the same transition.

Clicking on the outside element works as expected. Clicking on a link throws the following exception in Ember Twiddle:
```
Uncaught SecurityError: Failed to execute 'replaceState' on 'History': A history state object with URL 'https://ember-twiddle.com/foo' cannot be created in a document with origin 'null' and UR
```

In a proper Ember app this results in a page refresh.

**Comment by pixelhandler** [comment] 2016-04-22 18:38
@Dremora I don't think this is an Ember bug. At least in the example it appears to do two of the same thing two different ways; which may need some additional logic to only do one transition.

This example shows adding a condition to prevent doing the extra transition that results in a page reload, https://ember-twiddle.com/0d5b3a8f344509313125ac19166e474f?openFiles=controllers.index.js%2C&route=%2Ffoo

**Comment by Dremora** [comment] 2016-04-26 13:51
Our workaround was to move the click handler inside the `click` method in the component. It seems weird to me that this works, while handling the event via an action doesn't. There's a bug somewhere unless the difference in behaviour between `<div click={{action "handleClick"}}>` and `click(e)` is known and documented.

**Comment by pixelhandler** [comment] 2016-06-17 18:58
@Dremora there is not a bug it's just that your example results in double transition and is recovered by a reload.

I'll close this out.

**Closed by pixelhandler** 2016-06-17 18:58 UTC
Labels: Has Reproduction, Needs Bug Verification
