### ISSUE TITLE
[Bug] RouteInfo.find() produces undefined items

### ISSUE THREAD

**Issue by nelstrom** [emberjs/ember.js#20140] opened 2022-07-13 11:43 UTC
### 🐞 Describe the Bug

The documentation for the [RouteInfo.find()](https://api.emberjs.com/ember/4.3/classes/RouteInfo/methods/find?anchor=find) method says:

> Allows you to traverse through the linked list of RouteInfos from the topmost to leafmost. Returns the first RouteInfo in the linked list for which the callback returns true.
> 
> The callback method you provide should have the following signature (all parameters are optional):
>
>     function(item, index, array);

Up until `v4.2` of Ember, this callback function worked as expected. Since `v4.3` of Ember, the callback sometimes produces an `undefined` value for the `item`.

### 🔬 Minimal Reproduction

I've created a [minimal reproduction](https://github.com/nelstrom/ember-route-info-bug-reproduction).

The [`beforeModel` hook in the `'accounts.account'` route](https://github.com/nelstrom/ember-route-info-bug-reproduction/blob/16f8e16d365f39bd5f160c518f40865b753a3196/app/routes/accounts/account.js#L4-L13) demonstrates the bug:

```js
  beforeModel({ to }) {
    to.find(function (item, index, array) {
      console.log('accounts.account#beforeModel:', {
        item,
        index,
        array,
        parent: item?.parent,
      });
    });
  }
```

To exercise this code, check out the repository and run the tests.

### 😕 Actual Behavior

The `RouteInfo.find()` callback produces an `undefined` value for the `item`.

![ember-bug-report](https://user-images.githubusercontent.com/7069/178721566-790a725d-b5ee-4301-b53a-a2ae0f11632c.png)

This screenshot was created while running the minimal reproduction against Ember 4.5.

### 🤔 Expected Behavior

The `RouteInfo.find()` callback should always provide a value for the `item`:

![Screenshot 2022-07-13 at 12 31 57](https://user-images.githubusercontent.com/7069/178724210-14af87e5-19d9-43ac-a84b-de47afbc4362.png)

This screenshot was created while running the minimal reproduction against Ember 4.2.

### 🌍 Environment

- Ember: -4.3
- Node.js/npm: v16.13.0/8.1.0
- OS: Mac OS 12.1
- Browser: Chrome v103

### ➕ Additional Context

We used `git bisect` to find [the commit that introduced this problem](https://github.com/emberjs/ember.js/commit/a47efb0356441c151c4c9a985059659975d4caf1). Here's the output from our bisect session:

<details>
<summary>Git bisect output</summary>
<pre><code>
a47efb0356441c151c4c9a985059659975d4caf1 is the first bad commit
commit a47efb0356441c151c4c9a985059659975d4caf1
Date:   Thu Jan 27 15:29:23 2022 -0800

    Future public @ember/routing types

 package.json                                       |   2 +-
 .../-internals/glimmer/lib/components/link-to.ts   |  12 +-
 packages/@ember/-internals/routing/index.ts        |   8 +-
 .../-internals/routing/lib/ext/controller.ts       |  10 +-
 .../-internals/routing/lib/services/router.ts      | 222 ++++----
 .../-internals/routing/lib/services/routing.ts     |  24 +-
 .../-internals/routing/lib/system/route-info.ts    |   4 +-
 .../@ember/-internals/routing/lib/system/route.ts  | 605 +++++++++++----------
 .../@ember/-internals/routing/lib/system/router.ts | 141 ++---
 .../-internals/routing/lib/system/router_state.ts  |  22 +-
 packages/@ember/-internals/routing/lib/utils.ts    |  54 +-
 .../@ember/controller/lib/controller_mixin.d.ts    |   5 +-
 packages/@ember/routing/auto-location.js           |   1 -
 packages/@ember/routing/auto-location.ts           |   1 +
 packages/@ember/routing/hash-location.js           |   1 -
 packages/@ember/routing/hash-location.ts           |   1 +
 packages/@ember/routing/location.js                |   1 -
 packages/@ember/routing/location.ts                |   1 +
 packages/@ember/routing/none-location.js           |   1 -
 packages/@ember/routing/none-location.ts           |   1 +
 packages/@ember/routing/route.js                   |   1 -
 packages/@ember/routing/route.ts                   |   1 +
 packages/@ember/routing/router-service.ts          |   5 +
 packages/@ember/routing/router.js                  |   1 -
 packages/@ember/routing/router.ts                  |   1 +
 .../routing/type-tests/auto-location.test.ts       |  10 +
 .../routing/type-tests/hash-location.test.ts       |  10 +
 .../routing/type-tests/history-location.test.ts    |  10 +
 packages/@ember/routing/type-tests/link-to.test.ts |   6 +
 .../@ember/routing/type-tests/location.test.ts     |  40 ++
 .../routing/type-tests/none-location.test.ts       |  10 +
 .../@ember/routing/type-tests/route/index.test.ts  |  72 +++
 .../routing/type-tests/route/overrides.test.ts     |  47 ++
 .../routing/type-tests/route/query-params.test.ts  |  34 ++
 .../@ember/routing/type-tests/route/send.test.ts   |  30 +
 .../routing/type-tests/router-service.test.ts      |  94 ++++
 .../@ember/routing/type-tests/router/index.test.ts |  44 ++
 .../@ember/routing/type-tests/router/map.test.ts   |  26 +
 yarn.lock                                          |   8 +-
 39 files changed, 1023 insertions(+), 544 deletions(-)
 delete mode 100644 packages/@ember/routing/auto-location.js
 create mode 100644 packages/@ember/routing/auto-location.ts
 delete mode 100644 packages/@ember/routing/hash-location.js
 create mode 100644 packages/@ember/routing/hash-location.ts
 delete mode 100644 packages/@ember/routing/location.js
 create mode 100644 packages/@ember/routing/location.ts
 delete mode 100644 packages/@ember/routing/none-location.js
 create mode 100644 packages/@ember/routing/none-location.ts
 delete mode 100644 packages/@ember/routing/route.js
 create mode 100644 packages/@ember/routing/route.ts
 create mode 100644 packages/@ember/routing/router-service.ts
 delete mode 100644 packages/@ember/routing/router.js
 create mode 100644 packages/@ember/routing/router.ts
 create mode 100644 packages/@ember/routing/type-tests/auto-location.test.ts
 create mode 100644 packages/@ember/routing/type-tests/hash-location.test.ts
 create mode 100644 packages/@ember/routing/type-tests/history-location.test.ts
 create mode 100644 packages/@ember/routing/type-tests/link-to.test.ts
 create mode 100644 packages/@ember/routing/type-tests/location.test.ts
 create mode 100644 packages/@ember/routing/type-tests/none-location.test.ts
 create mode 100644 packages/@ember/routing/type-tests/route/index.test.ts
 create mode 100644 packages/@ember/routing/type-tests/route/overrides.test.ts
 create mode 100644 packages/@ember/routing/type-tests/route/query-params.test.ts
 create mode 100644 packages/@ember/routing/type-tests/route/send.test.ts
 create mode 100644 packages/@ember/routing/type-tests/router-service.test.ts
 create mode 100644 packages/@ember/routing/type-tests/router/index.test.ts
 create mode 100644 packages/@ember/routing/type-tests/router/map.test.ts
</code></pre>
</details>

We came across this bug while upgrading our Ember app from 4.2 to 4.3. Here's a (simplified) sample of the code that drew our attention to the issue:

```js
import Route from '@ember/routing/route';
import { assert } from '@ember/debug';

export default class AccountsAccountRoute extends Route {

  beforeModel({ to }) {
    let routeInfo = to.find(({ name }) => name === 'accounts.account');
    let { account_id } = routeInfo?.params;
    assert("Couldn't find account_id parameter", account_id);
    // ...etc...
  }
}
```

As a work around, we've rewritten the call to `find()` as follows:

```
let routeInfo = to.find((item) => item?.name === 'accounts.account');
```

**Comment by chriskrycho** [comment] 2022-08-03 15:42
Looks like a duplicate of #20056?

**Comment by m3l1x** [comment] 2022-08-03 15:44
> Looks like a duplicate of #20056?

Yes, it is, but a more detailed one. I could close mine if it's desired.

**Comment by chriskrycho** [comment] 2022-08-03 16:42
Yeah, if you could pull your comment over onto that thread, that would be helpful from a maintenance POV! Thank you!

**Closed by chriskrycho** 2022-08-03 16:42 UTC

**Comment by sly7-7** [comment] 2022-08-25 10:11
@chriskrycho 🤔 I think this is still an issue, maybe you wanted to close the other one ?

**Comment by chriskrycho** [comment] 2022-08-25 12:12
It *is* still an issue, yes; but it's the *same* issue as the other one. 😄

**Comment by sly7-7** [comment] 2022-08-25 12:15
Yes, sorry, so that mean you close this one as purpose, even if it has more details than the other.
