### ISSUE TITLE
Ember.computed.uniqBy not accessible in v2.6.0 but documented

### ISSUE THREAD

**Issue by psteininger** [emberjs/ember.js#13664] opened 2016-06-14 08:51 UTC
Per Ember documentation: http://emberjs.com/api/classes/Ember.computed.html#method_uniqBy, `Ember.computed.uniqBy` should be available. However, it is still made unavailable by this logic:
```
if (_emberMetalFeatures.default('ember-runtime-computed-uniq-by')) {
    EmComputed.uniqBy = _emberRuntimeComputedReduce_computed_macros.uniqBy;
  }
```
in ember-runtime.js. It is also not possible to enable this feature in the release build either. It should be either enabled (or allowed to be enabled) OR removed from documentation.

**Comment by Serabe** [comment] 2016-06-14 12:11
`Ember.computed.uniqBy` is introduced in Ember 2.7 beta as of [the announcement post](http://emberjs.com/blog/2016/06/08/ember-2-6-and-2-7-beta-released.html). If any, the documentation should be updated to reflect so.

**Comment by rwjblue** [comment] 2016-06-19 02:42
Yeah, sorry about the confusion here. We need help on https://github.com/emberjs/ember.js/issues/13101 to ensure that documentation added for new features is not accidentally shipped to the website. 

I'm going to go ahead and close this as a duplicate of https://github.com/emberjs/ember.js/issues/13101...

**Closed by rwjblue** 2016-06-19 02:42 UTC
Labels: Documentation, Needs Team Response
