### ISSUE TITLE
Does not properly generate `*-test` blueprints.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#14936] opened 2017-02-16 20:57 UTC
Repro (assuming ember-cli@2.11 or higher):

```
ember new foo
cd foo
ember g acceptance-test bar
```

No files are created.

---

Prior to ember-source@2.11.1 this works properly (which means that ember-cli-legacy-blueprints were working properly and ember-source is not).

**Comment by rwjblue** [comment] 2017-02-16 20:57
@Turbo87 - Do you happen to have time to dig into this?

**Comment by Turbo87** [comment] 2017-02-16 20:58
@rwjblue maybe after the meeting or tomorrow morning

this looks like a duplicate of https://github.com/emberjs/ember.js/issues/14935 btw

**Closed** 2017-02-19 16:36 UTC
Labels: Bug

**Comment by Turbo87** [comment] 2017-02-23 11:16
@rwjblue reminder that we still have to release Ember v2.11.2 to fix this issue

**Comment by rwjblue** [comment] 2017-02-23 11:20
2.11.2 was released with this fix a few days ago, please confirm?

**Comment by Turbo87** [comment] 2017-02-23 11:25
oh, nevermind, I was on the latest 2.12-beta which doesn't seem to have the fix yet

**Comment by Dhaulagiri** [comment] 2017-02-23 14:25
confirmed that this does work in 2.11.2
