### ISSUE TITLE
error creating new project

### ISSUE THREAD

**Issue by DerManoMann** [emberjs/ember.js#18473] opened 2019-10-08 03:44 UTC
Hi there,

I am trying to create a new project fowllowing the getting started guide and get the following error....
```
>:~/projects/ember-quickstart$ npm install
npm ERR! addLocal Could not install /home/xxx/projects/ember-quickstart/@ember-data/-build-infra@3.13.1
npm ERR! Linux 5.0.0-29-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! path /home/xxx/projects/ember-quickstart/@ember-data/-build-infra@3.13.1
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/xxx/projects/ember-quickstart/@ember-data/-build-infra@3.13.1'
npm ERR! enoent ENOENT: no such file or directory, open '/home/xxx/projects/ember-quickstart/@ember-data/-build-infra@3.13.1'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/xxx/projects/ember-quickstart/npm-debug.log

```

**Comment by rwjblue** [comment] 2019-10-08 14:38
Hmm, looks like there was an issue installing the dependencies. Maybe try to `rm -rf node_modules && npm install`?

**Comment by DerManoMann** [comment] 2019-10-08 20:17
Nah, same result. This is already the more refined test :) - The same happens running `ember new` for a new, non existing project (ie the folder doesn't exist yet).

**Comment by drewcovi** [comment] 2019-10-12 21:49
I can second this. Other modules don't have any issues, this seems specific to ember-data. This using `code-server` in docker which i believe is just using an Ubuntu base image.

**Comment by drewcovi** [comment] 2019-10-12 22:03
confirmed issue on Ubuntu 18.04.2 LTS

**Comment by rwjblue** [comment] 2019-10-13 14:03
What is your `ember-cli` version here? Can you push up a demo project that has this issue to GitHub?

**Comment by drewcovi** [comment] 2019-10-13 14:28
Fresh install yesterday of nodejs npm and then ember-cli. All I did then is create a folder and `ember init`

**Comment by drewcovi** [comment] 2019-10-13 14:31
As an aside I was able to install various other dependencies independently. It chokes on ember-data even on a direct install outside an ember project.

**Comment by drewcovi** [comment] 2019-10-13 14:38
Quick test using `yarn 1.19.1` and `npm 3.5.2`

yarn works, npm fails.

```bash
➜  testing yarn add ember-data
yarn add v1.19.1
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "ember-data > ember-inflector > ember-cli-babel > babel-plugin-debug-macros@0.2.0" has unmet peer dependency "@babel/core@^7.0.0-beta.42".
warning "ember-data > ember-cli-typescript > @babel/plugin-transform-typescript@7.4.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "ember-data > @ember-data/-build-infra > @babel/plugin-transform-block-scoping@7.6.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "ember-data > ember-cli-typescript > @babel/plugin-transform-typescript > @babel/plugin-syntax-typescript@7.3.3" has unmet peer dependency "@babel/core@^7.0.0-0".
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 251 new dependencies.
info Direct dependencies
└─ ember-data@3.13.1
info All dependencies
├─ @babel/core@7.6.4
├─ @babel/generator@7.6.4
├─ @babel/helper-builder-binary-assignment-operator-visitor@7.1.0
├─ @babel/helper-call-delegate@7.4.4
├─ @babel/helper-create-class-features-plugin@7.6.0
├─ @babel/helper-define-map@7.5.5
├─ @babel/helper-explode-assignable-expression@7.1.0
├─ @babel/helper-wrap-function@7.2.0
├─ @babel/helpers@7.6.2
├─ @babel/highlight@7.5.0
├─ @babel/parser@7.6.4
├─ @babel/plugin-proposal-async-generator-functions@7.2.0
├─ @babel/plugin-proposal-class-properties@7.5.5
├─ @babel/plugin-proposal-decorators@7.6.0
├─ @babel/plugin-proposal-dynamic-import@7.5.0
├─ @babel/plugin-proposal-json-strings@7.2.0
├─ @babel/plugin-proposal-object-rest-spread@7.6.2
├─ @babel/plugin-proposal-optional-catch-binding@7.2.0
├─ @babel/plugin-proposal-unicode-property-regex@7.6.2
├─ @babel/plugin-syntax-decorators@7.2.0
├─ @babel/plugin-syntax-typescript@7.3.3
├─ @babel/plugin-transform-arrow-functions@7.2.0
├─ @babel/plugin-transform-async-to-generator@7.5.0
├─ @babel/plugin-transform-block-scoped-functions@7.2.0
├─ @babel/plugin-transform-block-scoping@7.6.3
├─ @babel/plugin-transform-classes@7.5.5
├─ @babel/plugin-transform-computed-properties@7.2.0
├─ @babel/plugin-transform-destructuring@7.6.0
├─ @babel/plugin-transform-dotall-regex@7.6.2
├─ @babel/plugin-transform-duplicate-keys@7.5.0
├─ @babel/plugin-transform-exponentiation-operator@7.2.0
├─ @babel/plugin-transform-for-of@7.4.4
├─ @babel/plugin-transform-function-name@7.4.4
├─ @babel/plugin-transform-literals@7.2.0
├─ @babel/plugin-transform-member-expression-literals@7.2.0
├─ @babel/plugin-transform-modules-amd@7.5.0
├─ @babel/plugin-transform-modules-commonjs@7.6.0
├─ @babel/plugin-transform-modules-systemjs@7.5.0
├─ @babel/plugin-transform-modules-umd@7.2.0
├─ @babel/plugin-transform-named-capturing-groups-regex@7.6.3
├─ @babel/plugin-transform-new-target@7.4.4
├─ @babel/plugin-transform-object-super@7.5.5
├─ @babel/plugin-transform-parameters@7.4.4
├─ @babel/plugin-transform-property-literals@7.2.0
├─ @babel/plugin-transform-regenerator@7.4.5
├─ @babel/plugin-transform-reserved-words@7.2.0
├─ @babel/plugin-transform-runtime@7.6.2
├─ @babel/plugin-transform-shorthand-properties@7.2.0
├─ @babel/plugin-transform-spread@7.6.2
├─ @babel/plugin-transform-sticky-regex@7.2.0
├─ @babel/plugin-transform-template-literals@7.4.4
├─ @babel/plugin-transform-typeof-symbol@7.2.0
├─ @babel/plugin-transform-typescript@7.4.5
├─ @babel/plugin-transform-unicode-regex@7.6.2
├─ @babel/preset-env@7.6.3
├─ @babel/runtime@7.6.3
├─ @ember-data/canary-features@3.13.1
├─ @ember-data/model@3.13.1
├─ @ember-data/serializer@3.13.1
├─ @ember/ordered-set@2.0.3
├─ @glimmer/env@0.1.7
├─ @types/broccoli-plugin@1.3.0
├─ @types/estree@0.0.39
├─ @types/minimatch@3.0.3
├─ @types/node@12.7.12
├─ @types/symlink-or-copy@1.2.0
├─ acorn@7.1.0
├─ amd-name-resolver@1.3.1
├─ ansi-styles@3.2.1
├─ ansi-to-html@0.6.11
├─ array-equal@1.0.0
├─ async@2.6.3
├─ babel-generator@6.26.1
├─ babel-helper-builder-binary-assignment-operator-visitor@6.24.1
├─ babel-helper-call-delegate@6.24.1
├─ babel-helper-define-map@6.26.0
├─ babel-helper-explode-assignable-expression@6.24.1
├─ babel-helper-remap-async-to-generator@6.24.1
├─ babel-helpers@6.24.1
├─ babel-plugin-check-es2015-constants@6.22.0
├─ babel-plugin-debug-macros@0.2.0
├─ babel-plugin-ember-modules-api-polyfill@2.12.0
├─ babel-plugin-feature-flags@0.3.1
├─ babel-plugin-filter-imports@3.0.0
├─ babel-plugin-module-resolver@3.2.0
├─ babel-plugin-syntax-async-functions@6.13.0
├─ babel-plugin-syntax-exponentiation-operator@6.13.0
├─ babel-plugin-syntax-trailing-function-commas@6.22.0
├─ babel-plugin-transform-async-to-generator@6.24.1
├─ babel-plugin-transform-es2015-arrow-functions@6.22.0
├─ babel-plugin-transform-es2015-block-scoped-functions@6.22.0
├─ babel-plugin-transform-es2015-block-scoping@6.26.0
├─ babel-plugin-transform-es2015-classes@6.24.1
├─ babel-plugin-transform-es2015-computed-properties@6.24.1
├─ babel-plugin-transform-es2015-destructuring@6.23.0
├─ babel-plugin-transform-es2015-duplicate-keys@6.24.1
├─ babel-plugin-transform-es2015-for-of@6.23.0
├─ babel-plugin-transform-es2015-function-name@6.24.1
├─ babel-plugin-transform-es2015-literals@6.22.0
├─ babel-plugin-transform-es2015-modules-amd@6.24.1
├─ babel-plugin-transform-es2015-modules-commonjs@6.26.2
├─ babel-plugin-transform-es2015-modules-systemjs@6.24.1
├─ babel-plugin-transform-es2015-modules-umd@6.24.1
├─ babel-plugin-transform-es2015-object-super@6.24.1
├─ babel-plugin-transform-es2015-parameters@6.24.1
├─ babel-plugin-transform-es2015-shorthand-properties@6.24.1
├─ babel-plugin-transform-es2015-spread@6.22.0
├─ babel-plugin-transform-es2015-sticky-regex@6.24.1
├─ babel-plugin-transform-es2015-template-literals@6.22.0
├─ babel-plugin-transform-es2015-typeof-symbol@6.23.0
├─ babel-plugin-transform-es2015-unicode-regex@6.24.1
├─ babel-plugin-transform-exponentiation-operator@6.24.1
├─ babel-plugin-transform-regenerator@6.26.0
├─ babel-plugin-transform-strict-mode@6.24.1
├─ babel-polyfill@6.26.0
├─ babel-preset-env@1.7.0
├─ babel-register@6.26.0
├─ babel6-plugin-strip-class-callcheck@6.0.0
├─ balanced-match@1.0.0
├─ binaryextensions@2.1.2
├─ brace-expansion@1.1.11
├─ broccoli-babel-transpiler@7.3.0
├─ broccoli-debug@0.6.5
├─ broccoli-file-creator@2.1.1
├─ broccoli-kitchen-sink-helpers@0.3.1
├─ broccoli-persistent-filter@2.3.1
├─ broccoli-rollup@4.1.1
├─ browserslist@4.7.0
├─ calculate-cache-key-for-tree@2.0.0
├─ caniuse-lite@1.0.30000999
├─ chalk@2.4.2
├─ clean-up-path@1.0.0
├─ color-convert@1.9.3
├─ color-name@1.1.3
├─ concat-map@0.0.1
├─ convert-source-map@1.6.0
├─ core-js-compat@3.2.1
├─ cross-spawn@6.0.5
├─ define-properties@1.1.3
├─ detect-indent@4.0.0
├─ editions@1.3.4
├─ electron-to-chromium@1.3.282
├─ ember-cli-babel-plugin-helpers@1.1.0
├─ ember-cli-string-utils@1.1.0
├─ ember-cli-version-checker@2.2.0
├─ ember-compatibility-helpers@1.2.0
├─ ember-data@3.13.1
├─ ember-inflector@3.0.1
├─ ember-rfc176-data@0.3.12
├─ end-of-stream@1.4.4
├─ ensure-posix-path@1.1.1
├─ entities@1.1.2
├─ escape-string-regexp@1.0.5
├─ esm@3.2.25
├─ estree-walker@0.6.1
├─ execa@1.0.0
├─ fast-ordered-set@1.0.3
├─ find-babel-config@1.2.0
├─ find-up@2.1.0
├─ fs-extra@7.0.1
├─ fs-tree-diff@0.5.9
├─ fs-updater@1.0.4
├─ fs.realpath@1.0.0
├─ function-bind@1.1.1
├─ get-stream@4.1.0
├─ git-repo-info@2.1.0
├─ glob@7.1.4
├─ graceful-fs@4.2.2
├─ has-ansi@2.0.0
├─ has-flag@3.0.0
├─ has-symbols@1.0.0
├─ hash-for-dep@1.5.1
├─ home-or-tmp@2.0.0
├─ inflection@1.12.0
├─ is-finite@1.0.2
├─ is-stream@1.1.0
├─ isexe@2.0.0
├─ istextorbinary@2.1.0
├─ js-levenshtein@1.1.6
├─ js-tokens@4.0.0
├─ jsonfile@4.0.0
├─ jsonify@0.0.0
├─ locate-path@2.0.0
├─ lodash@4.17.15
├─ loose-envify@1.4.0
├─ matcher-collection@1.1.2
├─ merge-trees@2.0.0
├─ minimatch@3.0.4
├─ minimist@0.0.8
├─ mktemp@0.4.0
├─ ms@2.0.0
├─ nice-try@1.0.5
├─ node-modules-path@1.0.2
├─ node-releases@1.1.35
├─ npm-git-info@1.0.3
├─ npm-run-path@2.0.2
├─ number-is-nan@1.0.1
├─ object-hash@1.3.1
├─ object-keys@1.1.1
├─ object.assign@4.1.0
├─ once@1.4.0
├─ os-homedir@1.0.2
├─ os-tmpdir@1.0.2
├─ p-finally@1.0.0
├─ p-limit@1.3.0
├─ p-locate@2.0.0
├─ p-try@1.0.0
├─ path-key@2.0.1
├─ path-parse@1.0.6
├─ path-root-regex@0.1.2
├─ pkg-up@2.0.0
├─ pump@3.0.0
├─ quick-temp@0.1.8
├─ regenerate-unicode-properties@8.1.0
├─ regenerator-transform@0.14.1
├─ regjsgen@0.5.0
├─ regjsparser@0.6.0
├─ repeating@2.0.1
├─ reselect@3.0.1
├─ resolve-package-path@1.2.7
├─ rollup-pluginutils@2.8.2
├─ rollup@1.23.1
├─ safe-buffer@5.1.2
├─ shebang-command@1.2.0
├─ shebang-regex@1.0.0
├─ signal-exit@3.0.2
├─ silent-error@1.1.1
├─ slash@1.0.0
├─ source-map-support@0.4.18
├─ source-map@0.5.7
├─ sprintf-js@1.1.2
├─ stagehand@1.0.0
├─ strip-ansi@3.0.1
├─ strip-eof@1.0.0
├─ supports-color@5.5.0
├─ sync-disk-cache@1.3.3
├─ textextensions@2.5.0
├─ tmp@0.0.28
├─ to-fast-properties@2.0.0
├─ tree-sync@1.4.0
├─ trim-right@1.0.1
├─ underscore.string@3.3.5
├─ unicode-canonical-property-names-ecmascript@1.0.4
├─ unicode-match-property-ecmascript@1.0.4
├─ unicode-match-property-value-ecmascript@1.1.0
├─ unicode-property-aliases-ecmascript@1.0.5
├─ universalify@0.1.2
├─ util-deprecate@1.0.2
├─ walk-sync@0.3.4
├─ which@1.3.1
└─ workerpool@3.1.2
Done in 7.04s.
➜  testing ls -lathr
total 160K
drwxrwxr-x 252 drew drew  12K Oct 13 09:37 node_modules
-rw-rw-r--   1 drew drew 133K Oct 13 09:37 yarn.lock
-rw-rw-r--   1 drew drew   56 Oct 13 09:37 package.json
drwxrwxr-x   3 drew drew 4.0K Oct 13 09:37 .
drwxr-xr-x  48 drew drew 4.0K Oct 13 09:37 ..
➜  testing rm -rf ./*
zsh: sure you want to delete all 3 files in /home/drew/testing/. [yn]? y
➜  testing ls -lathr
total 8.0K
drwxrwxr-x  2 drew drew 4.0K Oct 13 09:37 .
drwxr-xr-x 48 drew drew 4.0K Oct 13 09:37 ..
➜  testing npm install --save-dev ember-data
npm ERR! addLocal Could not install /home/drew/testing/@ember-data/-build-infra@3.13.1
npm ERR! Linux 4.15.0-65-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--save-dev" "ember-data"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! path /home/drew/testing/@ember-data/-build-infra@3.13.1
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/drew/testing/@ember-data/-build-infra@3.13.1'
npm ERR! enoent ENOENT: no such file or directory, open '/home/drew/testing/@ember-data/-build-infra@3.13.1'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/drew/testing/npm-debug.log
➜  testing 
```

**Comment by rwjblue** [comment] 2019-10-14 13:57
Ahh, gotcha. So the issue is something with `npm@3` most likely (though we should also test with a newer npm to confirm).

**Comment by rwjblue** [comment] 2019-10-14 13:59
I'm going to close this issue, we'll track conversation over in https://github.com/emberjs/data/issues/6589 (since the fixes will almost certainly have to happen in `ember-data`).

Thank you @drewcovi for digging in here, and helping isolate the reproduction!

**Closed by rwjblue** 2019-10-14 13:59 UTC
