### ISSUE TITLE
Passing numbers "too big" to helpers causes their "truncation"

### ISSUE THREAD

**Issue by MichalBryxi** [emberjs/ember.js#18544] opened 2019-11-13 09:10 UTC
When I create a simple helper, use that helper in a template and pass in "big enough" number, what the helper code receives is completely different number. For example:

```hbs
// template.hbs
{{format-number 1234567890}}
```

```js
// helpers/format-number.js
export function formatNumber(params) {
  console.log('params: ', params); // params: [160826066]
  return params;
}
```

Created a twiddle with way more examples: https://ember-twiddle.com/d64554f5d97cd8063fd117808a82d145?openFiles=templates.application.hbs%2C

There does not seem to be an easy observable rule as what will happen to the number, because it sometimes passes in higher number than `160826066` correctly.

**Comment by rwjblue** [comment] 2019-11-15 16:12
This is a duplicate of https://github.com/emberjs/ember.js/issues/15635 (lots of discussion / explanation over in that issue), going to close this one...

**Closed by rwjblue** 2019-11-15 16:12 UTC
