### ISSUE TITLE
Confusing warning message for computed.mapBy('foo', 'bar.baz')

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember.js#13622] opened 2016-06-08 09:19 UTC
When using a computed property like `computed.mapBy('foo', 'bar.baz')` I'm getting the following warning:

> WARNING: Dependent keys containing `@each` only work one level deep. You cannot use nested forms like `todos.@each.owner.name` or `todos.@each.owner.@each.name`. Please create an intermediary computed property.

It took me quite a while to figure out that the `mapBy` is actually the problem and using `@each` under the hood. It might be worth it to throw a more descriptive warning if `mapBy` is used improperly (i.e. with a nested path).

**Comment by rwjblue** [comment] 2016-06-08 11:33
Agreed

**Comment by swastik** [comment] 2016-06-09 18:59
I took a shot at this [here](https://github.com/emberjs/ember.js/pull/13629).

I wasn't too sure what to tag the commit—it isn't a new feature, not a bugfix; it's likely enhanced documentation, but I wasn't sure—so I've left it untagged.

I've also added a test. Let me know if I should change anything! :smiley:

**Comment by GavinJoyce** [comment] 2016-11-26 13:20
@rwjblue I believe that https://github.com/emberjs/ember.js/pull/14639 allows us to close this too

**Comment by rwjblue** [comment] 2016-11-26 17:09
Sounds good, thanks!

**Closed by rwjblue** 2016-11-26 17:09 UTC
Labels: Has PR
