### ISSUE TITLE
"Wrapped" Ember Inputs do not fire "enter key up" events

### ISSUE THREAD

**Issue by jtmckibb** [emberjs/ember.js#15865] opened 2017-11-21 15:05 UTC
We've been using Ember inputs across our app, and a small bug we found has been leading us to avoid using `keyUp` events for our components including these inputs. Essentially, native inputs behave differently from Ember inputs when wrapped in a component. See below:

When you're using a native input and you press and release the return key you get the following events:
```js
// Return key pressed
jQuery.Event {originalEvent: KeyboardEvent, type: 'keydown', ... keyCode: 13}
jQuery.Event {originalEvent: KeyboardEvent, type: 'keypress', ... keyCode: 13}
jQuery.Event {originalEvent: KeyboardEvent, type: 'keyup', ...  keyCode: 13}
```
When using an Ember input, you get the following events as well:
```js
// Return key pressed
jQuery.Event {originalEvent: KeyboardEvent, type: 'keydown', ... keyCode: 13}
jQuery.Event {originalEvent: KeyboardEvent, type: 'keypress', ... keyCode: 13}
jQuery.Event {originalEvent: KeyboardEvent, type: 'keyup', ...  keyCode: 13}
```
However, when using a wrapped Ember input, you only get the following events:
```js
// Return key pressed
jQuery.Event {originalEvent: KeyboardEvent, type: 'keydown', ... keyCode: 13}
jQuery.Event {originalEvent: KeyboardEvent, type: 'keypress', ... keyCode: 13}
```

Feel free to do your own exploration in this Ember Twiddle: [Keyboard Event Twiddle](https://ember-twiddle.com/c881580c7de8fbaf7c1d7697ab6b30a0?openFiles=templates.application.hbs%2Ctemplates.components.input-wrapper.hbs).

**Comment by bekzod** [comment] 2017-11-22 05:24
@jtmckibb you need to use `{{input bubbles=true}}` to allow `keyUp` event to propagate else it will be translated to `enter` and `insert-newline` events when `enter key` is clicked, not sure if it is correct behavior and if there is need for `bubbles=true` exist, it is better to clarify with @rwjblue

**Comment by jtmckibb** [comment] 2017-11-22 16:41
Should Ember inputs not mimic the behavior of native inputs? Also why is the default behavior for Ember inputs `bubbles=false` if the default behavior for other Ember components is `bubbles=true`?

**Comment by Serabe** [comment] 2017-11-30 09:17
[Modifying a bit your twiddle](https://ember-twiddle.com/11d64e224f9d82b5378644e0d9c23f3a?openFiles=templates.application.hbs%2C) to see the logs directly in screen, they all behave the same

**Comment by jtmckibb** [comment] 2017-12-01 00:16
Oops there was a typo in the Twiddle (I mislabelled the inputs). If you hit Enter on the last input (the `wrapped-ember-input`), you'll notice that `keyUp` doesn't fire: [Keyboard Event Twiddle](https://ember-twiddle.com/c881580c7de8fbaf7c1d7697ab6b30a0?openFiles=templates.application.hbs%2Ctemplates.components.input-wrapper.hbs)

**Comment by Serabe** [comment] 2017-12-01 19:31
If only happens with letter Enter that's because keyUp for Enter is mapped to `enter` + `insert-newline`.

Closing this as is not a bug. Thank you!

**Closed by Serabe** 2017-12-01 19:31 UTC
Labels: Needs Submitter Response

**Comment by jtmckibb** [comment] 2017-12-01 20:01
But should it not behave the same as a native input? This has caused some unintended behavior for us while developing, and seems like an anti-pattern.

**Comment by Serabe** [comment] 2017-12-01 20:05
No necessarily, specially after 2.3, where using plain `<input>` is supported.

**Comment by jtmckibb** [comment] 2017-12-01 20:10
Also, should the newline not be inserted on input/keyDown vs on keyUp? Why is it mapped to keyUp? I don't think that is the problem. I think the problem is here: https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/mixins/text_support.js#L174

The default is not to propagate keyUp events for the return key, but that misaligns with how Ember components work everywhere else where they do propagate by default.

**Comment by Serabe** [comment] 2017-12-01 20:16
That property has been false since Ember 1.0.

**Comment by jtmckibb** [comment] 2017-12-01 20:18
Ah got it. Okay thanks so much for looking into this!
