### ISSUE TITLE
why dependent keys cache is not cleared in dependentKeysDidChange method?

### ISSUE THREAD

**Issue by udhayakumargururaj** [emberjs/ember.js#18102] opened 2019-06-18 05:54 UTC
Hi,

using ember - 2.14.2
Dependent keys cache is not cleared and the old object is returned everytime. is this expected behavior or is it issue.

**Comment by rwjblue** [comment] 2019-06-18 16:15
I don't think we can answer in the abstract, can you provide us a demo or other reproduction?

**Comment by locks** [comment] 2020-04-19 11:23
Closing due to lack of details.

**Closed by locks** 2020-04-19 11:23 UTC
Labels: Needs Submitter Response
