### ISSUE TITLE
1.13.2: queryParams declared on route aren't (always) sticky (in the URL)

### ISSUE THREAD

**Issue by jamesarosen** [emberjs/ember.js#11597] opened 2015-06-29 22:36 UTC
JSBin: http://emberjs.jsbin.com/bumocu/2/edit?html,js

When you access it at http://emberjs.jsbin.com/bumocu/2#/page1?routeParam=foo&controllerParam=bar and then click "Page Two", you get taken to http://emberjs.jsbin.com/bumocu#/page2?controllerParam=bar

However, if you access it at http://emberjs.jsbin.com/bumocu/2?routeParam=foo&controllerParam=bar#/page1 and then click "Page Two", you get taken to http://emberjs.jsbin.com/bumocu?routeParam=foo&controllerParam=bar#/page2

With `History` location, it always acts like the first case -- transitions lose query params declared on `route:application`.

**Comment by jamesarosen** [comment] 2015-06-29 23:01
On [ember-canary](http://builds.emberjs.com/canary/ember.debug.js), I get
```
Error while processing route: page1 Cannot read property 'routeParam' of undefined TypeError: Cannot read property 'routeParam' of undefined
    at get (http://builds.emberjs.com/canary/ember.debug.js:18388:26)
    at lazyGet (http://builds.emberjs.com/canary/ember.debug.js:12674:46)
    at Object.ChainNode.value (http://builds.emberjs.com/canary/ember.debug.js:12687:23)
    at Object.ChainNode (http://builds.emberjs.com/canary/ember.debug.js:12644:29)
    at Object.ChainNode.chain (http://builds.emberjs.com/canary/ember.debug.js:12789:30)
    at Object.ChainNode.chain (http://builds.emberjs.com/canary/ember.debug.js:12798:14)
    at Object.ChainNode.add (http://builds.emberjs.com/canary/ember.debug.js:12750:12)
    at watchPath (http://builds.emberjs.com/canary/ember.debug.js:21232:25)
    at watch (http://builds.emberjs.com/canary/ember.debug.js:21277:43)
    at addObserver (http://builds.emberjs.com/canary/ember.debug.js:17595:35)
```
That seems to be because `controller:application`'s `meta` is `undefined` when Ember is trying to set up an observer on `routeParam.[]`.

**Comment by jamesarosen** [comment] 2015-07-06 06:03
Possibly related: #10838

**Comment by jamesarosen** [comment] 2015-07-12 04:54
Possibly also related to @rwjblue's #11535, which was meant to address #10838.

**Comment by mmun** [comment] 2016-04-14 02:23
Can someone verify whether this bug is still occurring in latest Ember 2.x?

**Comment by pixelhandler** [comment] 2016-06-17 19:38
@jamesarosen can you provide an updated example (reproduction of the issue) using a current release of Ember.js or the LTS release (2.4.6) ?

**Comment by Serabe** [comment] 2016-07-22 17:11
In 2.6.2 and beta:

1. Got to http://output.jsbin.com/siqiwo#/page1?routeParam=foo&controllerParam=bar
2. Press link _Page Two_
3. You get to http://output.jsbin.com/siqiwo#/page2?controllerParam=bar&routeParam=foo

I am closing this since it looks like it has been fixed.

**Closed by Serabe** 2016-07-22 17:11 UTC
Labels: Ember 1.13, Needs Bug Verification, Query Params
