### ISSUE TITLE
input helper does not expand bound handlebars subexpressions

### ISSUE THREAD

**Issue by cowboyd** [emberjs/ember.js#10620] opened 2015-03-13 20:51 UTC
Given a helper that concatenates strings, the following template
```hbs
{{input class=(string-concat "color-" boundName)}}
```

ought to render `<input class="color-blue"/>` provided that the `boundName` resolves to `"blue"`. If the helper is invoked with static strings: 

```hbs
{{input class=(string-concat "color-" "blue")}}
```

the input renders as expected: `<input class="color-blue"/>`.

Reproduction here:

http://jsbin.com/lamakeraro/edit?html,js,output

**Comment by mixonic** [comment] 2015-03-14 21:23
I've simplified this by removing the loop:

http://jsbin.com/fijixoheje/1/edit?html,js,output

@mmun it appears that the bound helper is not executed when an id is passed as the second argument. Very funky.

**Comment by rwjblue** [comment] 2015-03-14 23:06
More details later, but the issue is with 'class' not the input helper.

**Comment by rwjblue** [comment] 2015-03-14 23:55
For example, see here that the bound helper concats properly for `placeholder`: http://jsbin.com/pamaho/2/edit?html,js,output

**Comment by rwjblue** [comment] 2015-03-15 01:52
Should be fixed by https://github.com/emberjs/ember.js/pull/10627.

**Closed** 2015-03-15 16:52 UTC

**Comment by cowboyd** [comment] 2015-03-16 15:17
Y'all are the best! :kissing_cat:
