### ISSUE TITLE
`link-to` `current-when` attribute does not accept a true value

### ISSUE THREAD

**Issue by Skwai** [emberjs/ember.js#16142] opened 2018-01-17 22:41 UTC
Running Ember 3.0.0-beta.1

The following does not work, despite the documentation stating that I can pass a `true` to the `current-when` attribute.

```
{{#link-to "foo.bar" current-when=true}}Foo Bar{{/link-to}}
```

**Comment by MaxFlower** [comment] 2018-01-23 09:56
I find description:
// always returns false for `get` because (due to the `set` just below)
// the cached return value from the set will prevent this getter from _ever_
// being called after a set has occured

**Comment by bekzod** [comment] 2018-01-23 11:22
updated tests to make sure that there is no regression https://github.com/emberjs/ember.js/pull/16167 they are passing

**Comment by Serabe** [comment] 2018-02-09 14:05
@Skwai we cannot reproduce this issue, can you please provide one?

**Comment by Serabe** [comment] 2018-02-21 12:17
@Skwai ping.

**Comment by Serabe** [comment] 2018-03-09 18:06
Closing this according to [our triage policy](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#triaging-policy). Please, provide a reproduction so we can follow up on this.

Thank you!

**Closed by Serabe** 2018-03-09 18:06 UTC
Labels: Needs Submitter Response
