### ISSUE TITLE
Get helper not working when passing an integer instead of a string to access arrays

### ISSUE THREAD

**Issue by Glennvd** [emberjs/ember.js#14490] opened 2016-10-18 09:05 UTC
When using the get helper to access an array, the helper silently fails unless the parameter is a string. Workaround is doing a `(concat "" integer)` inside the helper.

Reproduced here: https://ember-twiddle.com/b944e2e5e876a69edd2c9843a4cfa49d?openFiles=templates.application.hbs%2C

**Comment by btecu** [comment] 2016-10-18 17:43
Doesn't seem to be an issue according to the [documentation](http://emberjs.com/api/classes/Ember.Templates.helpers.html#method_get).

> 
Dynamically look up a property on an object. The second argument to {{get}} should have a string value, although it can be bound.

**Comment by pixelhandler** [comment] 2016-10-22 22:53
@Glennvd the link @btecu does indicate that a string is expected. I'll close this for now, the issue is not an Ember bug.

**Closed by pixelhandler** 2016-10-22 22:53 UTC
