### ISSUE TITLE
Operand over 16-bits. Got 72000.

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember.js#16269] opened 2018-02-22 18:47 UTC
Using the latest 3.1 beta version I'm seeing an error "Operand over 16-bits. Got 72000." in one of our tests which does this:

```
render(hbs`{{some-component foo=9000}}`);
```

It seems that the maximum value for literal numbers has decreased significantly in the 3.1-beta 🤔 

https://github.com/emberjs/ember.js/issues/15635 might also be related to this.

**Comment by rwjblue** [comment] 2018-02-23 01:04
FWIW - This is ultimately a glimmer-vm issue...

**Comment by Turbo87** [comment] 2018-02-24 15:23
Still needs release and update here, right?

**Comment by rwjblue** [comment] 2018-02-24 16:37
Yes, I didn’t close this intentionally...

**Comment by rwjblue** [comment] 2018-02-25 15:51
Fixed by https://github.com/emberjs/ember.js/pull/16286

**Closed by rwjblue** 2018-02-25 15:51 UTC

**Comment by jdurand** [comment] 2018-09-14 23:36
I opened an issue https://github.com/cibernox/ember-ast-helpers/issues/23 but I'm going to log this here just in case this is a regression.

I started having these issues when I upgraded my app to ember-source@3.3.2 (and ember-data@3.4.0 mentioning because from the little I could understand one side effect could be broken hasMany relationships)

Here's a production stack trace: https://sentry.io/share/issue/b3223fa152b04552bf19ab519fcd2218/

I haven't seen this error yet for users that I rolled back to ember-source@3.1.4 & ember-data@3.1.2. I'll report back if I see something else.

**Comment by jdurand** [comment] 2018-10-26 20:03
Rolled back to ember-source@3.1.4 (without touching anything else) this morning and the error stopped popping up in my logs.
