### ISSUE TITLE
3.11 increased ember-source filesize (~7kb)

### ISSUE THREAD

**Issue by makepanic** [emberjs/ember.js#18151] opened 2019-06-26 19:39 UTC
It seems like `3.11` increased the ember-source `dist/ember.min.js` size:

version | size in bytes
---------|--------
3.10.0 | 415300
3.11.0 | 422050

```json
[{
  "3.10.0": {
    "version": "3.10.0",
    "time": "2019-05-13T20:41:53.602Z",
    "size": {
      "raw": 415300,
    }
  },
  "3.11.0-beta.1": {
    "version": "3.11.0-beta.1",
    "time": "2019-05-14T02:37:19.525Z",
    "size": {
      "raw": 421529,
    }
  },
  "3.11.0-beta.2": {
    "version": "3.11.0-beta.2",
    "time": "2019-06-03T20:07:24.587Z",
    "size": {
      "raw": 421564,
    }
  },
  "3.11.0-beta.3": {
    "version": "3.11.0-beta.3",
    "time": "2019-06-11T11:04:23.517Z",
    "size": {
      "raw": 422035,
    }
  },
  "3.11.0-beta.4": {
    "version": "3.11.0-beta.4",
    "time": "2019-06-18T05:53:59.727Z",
    "size": {
      "raw": 422041,
    }
  },
  "3.11.0": {
    "version": "3.11.0",
    "time": "2019-06-25T03:53:05.991Z",
    "size": {
      "raw": 422050,
    }
  }
}]
```

looks like this when plotted:

![20190626-220614](https://user-images.githubusercontent.com/1205444/60211268-f8cc5800-985e-11e9-8182-3996b3f6a155.png)

**Comment by rwjblue** [comment] 2019-06-26 20:08
Thanks for reporting! Do you happen to have the min+gz sizes handy also?

**Comment by rwjblue** [comment] 2019-06-26 20:08
I think next steps here would be to diff the `ember.prod.js` files between 3.10 and 3.11.

**Comment by makepanic** [comment] 2019-06-26 20:16
`ember.prod.js`

![20190626-220625](https://user-images.githubusercontent.com/1205444/60211708-f0c0e800-985f-11e9-84db-cfa841dd635d.png)

```json
{
  "3.10.2": {
    "version": "3.10.2",
    "time": "2019-06-18T14:06:08.009Z",
    "size": {
      "raw": 1778999,
      "gzip": -1
    }
  },
  "3.11.0-beta.1": {
    "version": "3.11.0-beta.1",
    "time": "2019-05-14T02:37:19.525Z",
    "size": {
      "raw": 1819144,
      "gzip": -1
    }
  },
  "3.11.0-beta.2": {
    "version": "3.11.0-beta.2",
    "time": "2019-06-03T20:07:24.587Z",
    "size": {
      "raw": 1819186,
      "gzip": -1
    }
  },
  "3.11.0-beta.3": {
    "version": "3.11.0-beta.3",
    "time": "2019-06-11T11:04:23.517Z",
    "size": {
      "raw": 1820362,
      "gzip": -1
    }
  },
  "3.11.0-beta.4": {
    "version": "3.11.0-beta.4",
    "time": "2019-06-18T05:53:59.727Z",
    "size": {
      "raw": 1824611,
      "gzip": -1
    }
  },
  "3.11.0": {
    "version": "3.11.0",
    "time": "2019-06-25T03:53:05.991Z",
    "size": {
      "raw": 1824623,
      "gzip": -1
    }
  }
}
```

**Comment by rwjblue** [comment] 2019-06-27 02:52
Just did a quick diff of `ember.prod.js` between 3.10.1 and 3.11.0, looks like the main issue is that the feature flags aren't being stripped. Not sure why yet, will have to dig in in the morning...

**Comment by rwjblue** [comment] 2019-06-27 03:22
OK, tried to do a better job of reading the diffs. Looks like there are a few categories of things that are making the 3.11 assets larger:

1. {{on}} and {{fn}} landed for the first time, introducing a decent amount of new code (not a bug per-se)
  * https://github.com/emberjs/ember.js/blob/master/packages/%40ember/-internals/glimmer/lib/modifiers/on.ts
  * https://github.com/emberjs/ember.js/blob/master/packages/@ember/-internals/glimmer/lib/helpers/fn.ts
2. Some of the support code for tracked properties seems to be present but not guarded in feature flag guards.
  * https://github.com/emberjs/ember.js/blob/master/packages/@ember/-internals/metal/lib/tracked.ts

Everything else looks pretty good.  I think 1) is "fine", but we can definitely do something about 2).

**Comment by rwjblue** [comment] 2019-06-28 21:11
Looks like @makepanic has revived and published an updated ember-source size tracker: 

> I've rebuild the old ember-size-tracker (https://github.com/ilkkao/ember-size-tracker) to use the ember-source npm package and deployed it on github: https://makepanic.github.io/ember-size-tracker/ 
> You can find the source at https://github.com/makepanic/ember-size-tracker

While the size of ember.prod.js has gone up, the size of ember.min.js with gzipping has gone down. If compression still treats us favorably and the "in reality" sizes are lower, I think this is probably a non-issue. 

Thoughts?

**Comment by makepanic** [comment] 2019-06-29 20:54
> the size of ember.min.js with gzipping has gone down

I'm not sure if that's true. From the source:

```
    "version": "3.10.2",
    "files": [
      {
        "size": {
          "raw": 415690,
          "gzip": 115419
        },
        "name": "package/dist/ember.min.js"
      },
```

``` 
    "version": "3.11.1",
    "files": [
      {
        "size": {
          "raw": 422073,
          "gzip": 117392
        },
        "name": "package/dist/ember.min.js"
      }
```

**Comment by locks** [comment] 2020-04-19 11:25
Thanks everyone for the discussion. Due to the release schedule, I am closing this and suggest we focus the discussion in https://github.com/emberjs/ember.js/issues/18796, since we seem to have had another regression!

**Closed by locks** 2020-04-19 11:25 UTC
