### ISSUE TITLE
[Docs] CONTRIBUTING.md Reporting A Bug outdated

### ISSUE THREAD

**Issue by Alonski** [emberjs/ember.js#18460] opened 2019-10-03 10:43 UTC
Here: https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#reporting-a-bug
Number 3: States that a Twiddle or JSBin should be provided to showcase the bug.

This should be updated as those aren't necessarily the best ways to showcase a bug.

Possible solutions:
- Remove JSBin and add CodeSandbox.
- Remove Twiddle and JSBin and suggest users create a demo repository on GitHub.

**Comment by pzuraq** [comment] 2019-10-03 14:57
I agree that these seem like the best things folks can do at the moment, since twiddle doesn’t work with the most recent versions of Ember

**Comment by rwjblue** [comment] 2019-10-04 13:45
I'd personally prefer to suggest "making a demo repo on GitHub". I wish CodeSandbox was a good enough suggestion, but I just don't find it stable enough to be able to use it to quickly dig into a reported issue.

**Comment by mehulkar** [comment] 2019-10-05 00:14
I’ve been adding `ember-possible-bug` to my repro repos! Might be useful to recommend? https://github.com/topics/ember-possible-bug

**Comment by alexeykostevich** [comment] 2020-03-30 13:58
You've raised a very good issue, @Alonski !

Currently, [Contributing](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md) docs mention 2 tools:
- [ember-twiddle](http://ember-twiddle.com), which supports multiple versions of Ember.js and Ember CLI.
- [JS Bin](http://emberjs.jsbin.com/?html,js,output), which uses pure Ember.js 1.x.

To cover the whole range of possible issues, it would be ideal if a reproduction environment:
- supported Ember CLI projects to allow to reproduce issues in the framework and build tools
- worked online and didn't require a multi-step setup
- supported external dependencies to reproduce integration issues and issues in community's libraries
- provided a familiar development experience to let people with different backgrounds (e.g. Angular) to start quickly

Unfortunately, it seems there is no ideal solution right now. The following tools could be a good solutions but need some investment from the community:
- [StackBlitz](https://stackblitz.com/) — an online IDE with JS/TS, Angular and React support. There is an issue (https://github.com/stackblitz/core/issues/647) for Ember.js support but there is no progress on this so far.
- [CodeSandbox](https://codesandbox.io/) — an online IDE with a wide range of supported frameworks (including Ember.js) but it looks a bit unstable at this point.

From my point of view, while there is no good support of Ember.js in online IDEs, [ember-twiddle](http://ember-twiddle.com) is still a very good option for reproducing simple issues quickly. For more complex scenarios, the docs could recommend a GitHub repository with an Ember CLI project.

However, as @mike-north [mentioned](https://github.com/stackblitz/core/issues/647#issue-350621344), ember-twiddle requires much development/maintenance effort, and it is specific for Ember.js. Therefore, it is likely worth the price to eventually migrate to one of the popular multipurpose online IDEs. Thank you, @mike-north, for all your awesome job on this!

**Comment by rwjblue** [comment] 2020-05-23 20:54
Closed by https://github.com/emberjs/ember.js/pull/18930

**Closed by rwjblue** 2020-05-23 20:54 UTC
