### ISSUE TITLE
actions in  Built-in Components - <Input />, <TextArea/> not firing

### ISSUE THREAD

**Issue by MalayaliRobz** [emberjs/ember.js#18846] opened 2020-03-30 16:12 UTC
Actions not being fired for events in <Input/> or<TextArea/> components.

say you have a controller action
```
@action
sampleAction(key) {
    alert(`you typed ${key}`)
 }
```
and in the template, you have 
```
<Input 
  @type="text"
  @key-up={{this.sampleAction}}/>
```

But `sampleAction` does not fire on key-up event of the input or any other events.

Twiddle:
https://ember-twiddle.com/9c54aefd24f95e34984133d96e4c3d3c?openFiles=templates.application%5C.hbs%2C

Ember Guides on <Input/>
https://guides.emberjs.com/release/components/built-in-components/#toc_binding-dynamic-attribute

**Comment by locks** [comment] 2020-03-31 11:23
Thank you for reporting! This seems like a duplicate of https://github.com/emberjs/ember.js/issues/18654 and so let's track the conversation over there :)

**Closed by locks** 2020-03-31 11:23 UTC
