### ISSUE TITLE
`queryParams` with `refreshModel` property in route creates unexpected result

### ISSUE THREAD

**Issue by LucasZheng** [emberjs/ember.js#14792] opened 2017-01-06 07:30 UTC
In Controller I used a map property:

    queryParams: {
        anetSiteId: 'anet-site-id'
    },
    anetSiteId: null,
    .......

and in Route I used `refreshModel` to update page when `anet-site-id` param changed:

    queryParams: {
        anetSiteId: {
            refreshModel: true
        }
    },
    .....

this functionality works, but when I change the value of `anetSiteId` in Controller, the `transition` property gets unexpected value in `beforeModel(transition) {` hook in Route, the `queryParams` object in `transition` param will gets two properties: `anet-site-id:"43"` and `anetSiteId:"undefined"`,  the second is not what I  wanted.  Also all the `link-to`  helper in template will generates url as: `http://localhost:4200/memberships/people/6022-43-698731?anet-site-id=43&anetSiteId=undefined`, is there a better way to remove the `anetSiteId=undefined` query param in url?

**Comment by pixelhandler** [comment] 2017-01-06 16:23
@LucasZheng One of the best ways to dig into an issue is to create a sharable reproduction of the issue you have using https://ember-twiddle.com/

Would you mind creating a simple example. Also, have you reached out in the https://embercommity.slack.com/ #-help chat room ?

**Comment by LucasZheng** [comment] 2017-01-07 15:20
@pixelhandler , please refer to https://ember-twiddle.com/f0b7bc5a578853c28c427e7893f39f53, when you click the `Click Me` button twice, you can see the `queryParams` object which contain `anetSiteId:"undefined"` from the console.

**Comment by pixelhandler** [comment] 2017-11-03 17:09
@LucasZheng does this issue still exist in Ember 2.16.x ?

**Comment by rwjblue** [comment] 2017-11-05 16:23
Seems to be working properly in Ember 2.16.2 (likely was fixed by https://github.com/emberjs/ember.js/pull/15613).

**Closed by rwjblue** 2017-11-05 16:23 UTC
Labels: Has Reproduction, Query Params

**Comment by LucasZheng** [comment] 2017-11-06 01:07
@pixelhandler , it's fixed.
