### ISSUE TITLE
Some unconsumed computed properties are triggering observers

### ISSUE THREAD

**Issue by bendemboski** [emberjs/ember.js#9265] opened 2014-10-03 01:14 UTC
I'm not sure if this is a bug, or an intentional change and the documentation hasn't been updated, but it broke a bunch of my code when I updated to Ember 1.7 so I figured I'd point it out to either have it fixed, or have the documentation updated.

http://emberjs.com/guides/object-model/observers/#toc_unconsumed-computed-properties-do-not-trigger-observers explains that unconsumed computed properties do not trigger observers. However, it appears that as of Ember 1.7, this isn't true of certain computed properties, namely `Ember.computed.alias()`, `Ember.computed.readOnly()` and `Ember.computed.oneWay()` (maybe others -- I've only tested a few).

Consider the following script snippet:

``` javascript
var Object = Ember.Object.extend({
    value: "initial value",
    alias: Ember.computed.alias('value'),
    oneWay: Ember.computed.oneWay('value'),
    readOnly: Ember.computed.readOnly('value'),
    bool: Ember.computed.bool('value'),
    manual: Ember.computed('value', function () { return this.get('value'); }),
    computedDidChange: Ember.observer('alias', 'oneWay', 'readOnly', 'bool', 'manual', function (obj, key) {
        console.log("Observer fired for: " + key);
    })
});
var object = Object.create();
object.set("value", "new value");
```

When I run this under Ember 1.6.1, it produces no console output. When I run it under Ember 1.7.0, it produces:

```
Observer fired for: alias
Observer fired for: oneWay
Observer fired for: readOnly
```

All the computed properties are unconsumed, but the alias, oneWay and readOnly computed properties triggered observers, while the bool and manually-specified computed properties did not.

Perhaps this is desired and the documentation just needs updating, but is it really intentional that it would be inconsistent, and certain computed properties trigger observers when unconsumed while others do not?

**Comment by Serabe** [comment] 2016-04-17 23:42
This bug still exists in [canary](https://ember-twiddle.com/d9772c2c6801236375f1a8c6f5143f8f?openFiles=twiddle.json%2C). Any news, @stefanpenner or @krisselden?

**Comment by stefanpenner** [comment] 2016-04-18 00:52
still exists

**Comment by cbou** [comment] 2017-03-11 21:04
Why unconsumed computed properties shouldn't trigger observers? To me it seems to be more a bug rather than a feature...

**Comment by stefanpenner** [comment] 2017-03-11 21:35
@cbou the idea is, observers should not have side effects, and computed properties should be lazy. Which when combined means unconsumed computed properties don't emit observer changes.

**Comment by cbou** [comment] 2017-03-12 06:50
Thanks for your answer @stefanpenner. My idea is observer should observe ;) To me it seems clear that lazy loaded stuff will be loaded if you observe them. The `state of the world` is not changed when lazy stuff are loaded. It's just about performance.

It could frustrated for EmberJS beginners which are not aware about this.

**Comment by stefanpenner** [comment] 2017-03-12 08:09
> My idea is observer should observe ;) 

Yes observers should observe, just as accessors should be lazy/on-demand. If accessors need not be lazily, then they should just be properties set within the constructor `init()`. If a computed property (an enhanced accessor) happens to be required eagerly, the developer can opt into this behavior explicitly but accessing the property when appropriate (maybe within the `init` or in the appropriate hook).

This allows for all existing behavior to continue to work, and eagerness to be explicit and opt-in.

```js

export default Ember.Object.extend({
  init() {
    this._super(...arguments);

    this.get('fullName'); // ensure fullName is initialized eagerly
  },

  fullName: computed('first', 'last', function() {
    return `${this.get('first')} ${this.get('last')}`
  })
});
```

That being said, using observers should be quite rare and far between – typically for when writing to 3rd party libraries like d3 or similar (I speak about this in more detail [here](https://www.youtube.com/watch?v=vvZEddrClAQ))

> The state of the world is not changed 

The order data is loaded is very much state changing.

>  It's just about performance.

Which shouldn't be dismissed, its a real constraint.

**Comment by cbou** [comment] 2017-03-12 09:03
Thanks for your long answer and your talk, I learned very useful tips. I will try not to use too much `observer`.

However I'm still convinced that computed shouldn't be lazy when they are observed. This is too hidden for developers.

> The order data is loaded is very much state changing.

You are right. To me observe something implicitly means `I'm ok that this computed is not lazy anymore` otherwise you can't observe it.

> Which shouldn't be dismissed, its a real constraint.

If only observed computed that are loaded it shouldn't be a big performance issue.

Now I better understand what the Ember way is. Thanks a lot.

**Comment by stefanpenner** [comment] 2017-03-12 16:17
@cbou ya it's abit of a balancing act.  Hopefully the above context helps a tad.

**Comment by cbou** [comment] 2017-03-12 18:03
Yes it helps a lot. Do you think a warning message could be possible in dev environment?

**Comment by btecu** [comment] 2018-04-26 02:43
Even after Glimmer 2, the issue is still present in Ember 3.1.1.
https://github.com/btecu/ember-issues/tree/9265

cc @stefanpenner @krisselden

**Comment by pixelhandler** [comment] 2018-09-28 18:14
@bendemboski @btecu @cbou @npars @stefanpenner @wagenet is this still an issue, perhaps we should close or create a new reproduction of this, what do you think?

**Comment by bendemboski** [comment] 2018-09-28 18:37
I don't think it's really high priority at all (observers? what are those? I dimly recall... 😉 ), but it does still happen. [Here](https://ember-twiddle.com/49a5ebe041c139932f6628b2da80ba25)'s a twiddle.

**Comment by locks** [comment] 2018-12-20 10:45
I am closing this since Octane and tracked are on the horizon. Thanks for the reproduction! If anyone picks it up, I'll reopen the issue.

**Closed by locks** 2018-12-20 10:45 UTC
Labels: Bug, Has Reproduction
