### ISSUE TITLE
No compatible version found: ember-source@^2.11.0-beta.3

### ISSUE THREAD

**Issue by enniel** [emberjs/ember.js#14694] opened 2016-12-08 16:19 UTC
it looks like you forgot to upload to npm

**Comment by pixelhandler** [comment] 2016-12-09 17:09
@enniel can you add to the description the steps to reproduce your issue?

**Comment by pgrippi** [comment] 2016-12-14 15:58
@pixelhandler I'm not sure there are really steps to reproduce. I believe starting with Ember 2.11 we should be able to use the `ember-source` npm package instead of the `ember` bower package (when using ember-cli >= 2.10.0)

The last two 2.11 beta releases have not been published to npm:

```bash
$ npm info ember-source versions --json
[
  "2.10.0-alpha.1",
  "2.11.0-alpha.1",
  "2.11.0-beta.1",
  "2.11.0-beta.2"
]
```

**Comment by tchak** [comment] 2016-12-26 13:35
I would even suggest that some older versions should be published to `npm`. At least the LTS versions to ease transition to bower less `ember-cli` for addons with `ember-try` tests.

**Comment by locks** [comment] 2016-12-27 14:29
@tchak if we could've done it before, we would've ;P Checking the unreleased betas.

**Comment by tchak** [comment] 2016-12-27 21:49
@locks I am not sure what you mean. Is it:
- The core team did not yet have time to deal with older versions but will do in the future
or
- There is no plan to release older versions as `ember-source` because some good reason

In both case much appreciated your work and was not intended as a ASAP request. Just trying to gather some information about the plan :)

**Comment by locks** [comment] 2016-12-27 21:57
@tchak oops, I hadn't realised how ambiguous it sounded! The changes necessary to the ember project so it could be published as an npm packaged only happened before the first alpha, so there won't be earlier versions released afaik. 
Th betas though, were lack of time/lapse.

**Comment by locks** [comment] 2017-02-24 00:52
Closing as I believe we're back on track.

**Closed by locks** 2017-02-24 00:52 UTC
