### ISSUE TITLE
application_loading named substate requires a route entry?

### ISSUE THREAD

**Issue by lukemelia** [emberjs/ember.js#10756] opened 2015-03-29 04:26 UTC
I just tried to use the `application_loading` named substate feature in 1.11.0, and was surprised to discover that it is not good enough to have a template named `application_loading.hbs`, but your app must also explicitly define a route named `application_loading`.

JSBin demonstrating this: http://emberjs.jsbin.com/yuqetefeti/1/edit?html,js,output

Is this as designed?

**Comment by fivetanley** [comment] 2015-03-29 05:02
Seems odd since ember usually autogenerates these things for you.

Also odd that it is using `application_loading` instead of `application-loading`

**Comment by thejameskyle** [comment] 2015-03-29 05:04
Looking into this it comes down to [this line](https://github.com/emberjs/ember.js/blob/980fa0f24bfa2653ad4d903f0a717ed6df0eb8fe/packages/ember-routing/lib/system/router.js#L808). While exploring this I found that `application_error` has not only this issue but another where you are required to define a path as well:

```js
this.route('application_error'); // More context objects were passed than there are dynamic segments for the route: application_error
this.route('application_error', { path: '/error/:error' }); // success
```

Regardless, based on [this comment](https://github.com/emberjs/ember.js/issues/9510#issuecomment-61989185) from @rwjblue it appears this used to work without a defined route and this change doesn't appear to be as designed.

**Comment by thejameskyle** [comment] 2015-03-29 05:27
[Maybe not](https://github.com/emberjs/ember.js/issues/10644#issuecomment-82006030). Looks like the following would ["fix"](http://emberjs.jsbin.com/yawuyu/1/edit) the issue. (Obviously not a good thing to do)

```js
App.registry.resolver.moduleBasedResolver = true;
```



It's interesting that doesn't insert it within the application template's outlet. I can't tell if that's intentional.

**Comment by owilliams** [comment] 2015-04-02 19:46
Just ran into to this too. Also doesn't play nice with `ember generate` as it won't generate an `application_loading` but `application_loading`.

There didn't seem to be any docs on this yet. The [Loading / Error Substates](http://guides.emberjs.com/v1.11.0/routing/loading-and-error-substates/) page would likely be a good location for some docs.

**Comment by tim-evans** [comment] 2015-04-03 01:04
@lukemelia AFAIK, the feature is broken. https://github.com/emberjs/ember.js/issues/10644

**Comment by Bargs** [comment] 2015-04-09 21:53
I ran into this problem as well. Defining a route with a path for the error state was the only way I could get it to work. Definitely seems like it's not working as intended, otherwise extra documentation is needed.

**Comment by seawatts** [comment] 2015-04-21 16:09
I was able to get it to work with `ember g template application_loading` which creates `application-loading.hbs` I thought it was suppose to look for `application_loading.hbs` But when I looked in the inspector it's looking for `application-loading.hbs`

As stated above, to get this feature to work I had to add:
```js
export default Router.map(function() {
  this.route('application_loading');
});
```

**Comment by rwjblue** [comment] 2015-05-22 02:59
@lukemelia - can you confirm that this was fixed by #10944?

**Comment by lukemelia** [comment] 2015-05-22 04:32
@rwjblue yes, looks like this takes care of it.

**Comment by rwjblue** [comment] 2015-05-22 09:09
Thank you for checking!

**Closed by rwjblue** 2015-05-22 09:09 UTC

**Comment by lolmaus** [comment] 2017-08-03 17:03
I ran into this issue on Ember 2.14 after running `ember g route application-error`. Deleting the unnecessary route entry from `app/router.js` resolved the issue for me.
