### ISSUE TITLE
Deprecation for separate CP getter and setter can be unhelpful

### ISSUE THREAD

**Issue by wagenet** [emberjs/ember.js#11048] opened 2015-05-06 19:25 UTC
When the offending CP is in the app code, it's not too hard to find where it comes from in the trace, but when it is from something like the Ember inspector it's much less obvious. See the attached trace which I believe is from the inspector:

![Trace](https://monosnap.com/file/P4zhiSJLV6RdfubX3ydb12XtlBKijG.png)

For non-expert users, these sorts of warnings will be quite frustrating.

**Comment by rwjblue** [comment] 2015-05-06 19:26
@cibernox - Do you think we can get the `key` and `this` into the deprecation message?

**Comment by rwjblue** [comment] 2015-05-06 19:30
The only way to get better debugging experience might be to wrap the function in debug mode so that it can emit the deprecation when used.  But that means that the deprecations will only fire when `get` or `set` is called on the CP and not at extend time.  The tradeoff might be worth it?

**Comment by cibernox** [comment] 2015-05-06 20:14
We can add `key` and `this` to the deprecation message very easily, but I'm not sure how helpful will it be. I'll check later.

**Comment by rwjblue** [comment] 2015-05-06 20:20
My last comment is referring to the fact that neither the `key` or the object is known at the time of the deprecation (because it could be in any context). We only know those things when it is invoked.

**Comment by cibernox** [comment] 2015-05-06 20:36
Having deprecations complaining in runtime might be better (better debug information), but also worse.

If you have deprecations in code you don't use often you won't see the deprecation. If you're using the property your log will be flooded by the repeated deprecation warnings.

Just because of the first reason I would disregard the idea. I think that defeats the purpose of the deprecation.

**Comment by rwjblue** [comment] 2015-05-06 20:42
> Having deprecations complaining in runtime might be better (better debug information), but also worse.

The current deprecation gives you absolutely no indication of what to fix.  The stack trace is useful when using Ember CLI (because of sourcemaps), but only if they come from application code.

> If you're using the property your log will be flooded by the repeated deprecation warnings.

We keep a flag on the CP instance that it has already logged.  This prevents multiple deprecations for a single CP (on every access).

**Comment by flyswatter** [comment] 2015-05-18 05:50
This warning's ambiguity has basically halted my ability to port a sizable project to canary and try out Glimmer.  It just has too many ember-addons to track down where the offense is taking place.  I get that there are some tradeoffs being weighed, and I'll just enjoy the luxury of not knowing the details and simply say:  There's got to be a better way.

Either there should be a way of printing what file the error is coming from during "extend time", or there should be a way to "force build" through errors, so more informative run-time errors can be captured, or *something*.

I'd go as far as to say that features shouldn't be merged if the migration path is this hazy.  Useful deprecation warnings should be considered part of the feature.

**Comment by raido** [comment] 2015-05-18 14:41
I am getting the same message, no idea where to look.

**Comment by cibernox** [comment] 2015-05-18 14:47
Ok, seems that the pain is generalized, we'll try to find a solution to give a better hint of the location of the issue. 

When the stack trace it's helpful when the problem is in your code. Only when the code that triggers a deprecation lives outside your app is when you are clueless. You can assume your code is fine, I'll try to find time this afternoon to pursue other solutions to give better information.

**Comment by rwjblue** [comment] 2015-08-19 02:17
The deprecation has been removed in 2.0.0 so I guess we didn't get this fixed.  Sorry folks...

**Closed by rwjblue** 2015-08-19 02:17 UTC
