### ISSUE TITLE
mouseEnter is fired when actually mouse is leaving the element

### ISSUE THREAD

**Issue by GoygovRustam** [emberjs/ember.js#18330] opened 2019-08-29 20:22 UTC
I have the case when I want to show something on **mouseEnter**, but want to show something else when mouse is not hovered. For some reason **mouseEnter** is called on the same element when I'm actually leaving the element.

Here is the **Twiddle**: https://ember-twiddle.com/6389580b96718779df094ba72b75a0da?openFiles=components.item-component.js%2Ctemplates.components.item-component.hbs

**Comment by ygongdev** [comment] 2019-09-09 21:37
I see  the problem, I think it's because of the extra `<div>` you have around the text, so since `mouseEnter` and `mouseLeave` does not bubble, it actually is called more than once.

If you remove the `<div>`, the hover works as expected.

**Comment by rwjblue** [comment] 2019-09-10 14:07
Sorry to ping you @simonihmig, but I haven't had much time to dig into this and thoguht _maybe_ you would have a bit of context. I'm mostly trying to confirm if we do think of this as a bug...

**Comment by GoygovRustam** [comment] 2019-09-10 21:35
@ygongdev yes it works without the div (just with plain text), but when you need show and hide something more complex than a text, it does not work. Also the problem is related to **#each** , because if I just hardcode multiple items, it works flawlessly.

**Comment by simonihmig** [comment] 2019-09-11 08:30
@rwjblue Sorry, but I just left for two weeks of vacation "unfortunately" 😎. So most likely not able to look into this before being back.

**Comment by rwjblue** [comment] 2019-09-11 19:12
No problem! Please have a great vacation!

**Comment by amk221** [comment] 2020-01-08 11:34
I'm also experiencing this, with a Star-Rating component, that highlights stars when the mouse enters a star, but resets them on mouseleave of the parent element.

**Comment by locks** [comment] 2023-07-22 20:53
The framework has moved on to Glimmer components and `{{on}}` for event handling binding, so I'm closing this issue. Thanks for the clear reproduction!

**Closed by locks** 2023-07-22 20:53 UTC
