### ISSUE TITLE
Two-way binding of aliased properties doesn't work with components

### ISSUE THREAD

**Issue by DaveDuchene** [emberjs/ember.js#12069] opened 2015-08-12 22:22 UTC
See: http://emberjs.jsbin.com/nafabuwuzi/edit?html,js,output

In our application we have a hierarchy of date and time picker components, and some of the sub-classes alias properties of their superclass for clarity in binding (think {{date-picker date=foo}} vs {{time-picker time=foo}}). These components are broken for us in 1.13 (and possibly earlier versions of Ember) due to the behaviour shown in the JS bin. Updates to the context side of bound values are communicated to the components, but updates to the component side of bound values are not communicated back to the context.

**Comment by dylanmensaert** [comment] 2015-08-13 11:46
This is unsupported by default in latest versions:

http://emberjs.com/blog/2015/05/10/run-up-to-two-oh.html#toc_one-way-values-by-default

**Comment by DaveDuchene** [comment] 2015-08-13 12:10
This is Ember 1.13, not 2.0. And, as per the example, it doesn't work with mut either.

**Comment by dylanmensaert** [comment] 2015-08-13 12:39
I believe default 2-way support has been deprecated before v2.0.0 .
Documentation seems incorrect on many areas.

You should implement mut helper to push changes to parent: http://emberjs.com/blog/2015/05/10/run-up-to-two-oh.html#toc_the-code-mut-code-helper

jsbin with some examples: http://emberjs.jsbin.com/cotero/edit?html,js,output

**Comment by OrKoN** [comment] 2015-08-13 12:52
@DaveDuchene  The jsbin you provided uses `2.0.0-canary+c53e68f7`. I believe 2-way bindings are still supported in 1.13 (works for me).

**Comment by DaveDuchene** [comment] 2015-08-13 12:52
Your examples are working because you're not using an aliased property! Everything works fine with unaliased properties. My initial JS bin includes a demonstration of the problem with usage of the mut helper, as I said before.

**Comment by DaveDuchene** [comment] 2015-08-13 12:54
@OrKoN I'm seeing the behaviour with 1.13-5. My bad with the JS bin - I'll updated it to use latest 1.13 build.

**Comment by DaveDuchene** [comment] 2015-08-13 13:10
@dylanmensaert Sorry, I misread your bin - I see now that you are binding the aliased property after all. I wonder if my real problem is that I'm relying on legacy behaviour vis the attrs hash?

**Comment by dylanmensaert** [comment] 2015-08-13 13:36
@DaveDuchene Using legacy behaviour does not seem to be the problem. I can use observers to check if bar changed and still push to parent by using set: http://emberjs.jsbin.com/libodu/edit?html,js,output *-you could use this as a simple but annoying workaround-*

```computed.alias``` seem to be broken compared to earlier versions. I tried v1.11.1, which works as you mentioned. It updates the aliased property, but does not trigger an update on the parent.

**solution**
It seems you can use ```computed.deprecatingAlias```, which does work as expected: http://emberjs.com/api/classes/Ember.computed.html#method_deprecatingAlias

jsbin: http://emberjs.jsbin.com/sejuhe/edit?html,js,output

**Comment by DaveDuchene** [comment] 2015-08-13 13:58
@dylanmensaert Thanks for the suggestions. I've updated the bin in the original bug report to use 1.13-7, and will use either your observer workaround, or a computed property that emulates Em.computed.alias().

**Comment by dylanmensaert** [comment] 2015-08-13 14:05
@DaveDuchene I advice you to use ```computed.deprecatingAlias ``` or the mut helper http://emberjs.jsbin.com/cotero/edit?html,js,output so it works in v2.x.

**Comment by DaveDuchene** [comment] 2015-08-13 14:10
I thought I only needed the mut helper when invoking a component via angle brackets? One way or another, I don't think the mut helper is making any difference here.

Why not the observer?

**Comment by dylanmensaert** [comment] 2015-08-13 14:24
```mut helper``` documentation states that you have to call ```.update``` yourself to push changes to the parent. There is also a good explanation, but not one I agree with, to why they implemented it as such.

Using only the observer will not work when two-way binding is no longer supported in v2.x, so you will have to use ```observes``` in combination with ```mut helper``` to make it work in the long run.

**Comment by rwjblue** [comment] 2015-08-13 14:37
OK, hold on here.  If this worked in 1.x with curly bracket invocation and two way binding, it should still work in 1.13.8 and 2.0.0 without major refactoring.  Angle bracket components will definitely require one way bindings, mut, et al but not curly invocation.

Ultimately, I believe that this is a duplicate of https://github.com/emberjs/ember.js/pull/11225.

@DaveDuchene - Could you double check that failing test PR and see if you think it is the same issue?  If yes, can you comment over there that it also affects `Ember.computed.alias` (not just setter CP's) and cross-link this issue?

**Comment by DaveDuchene** [comment] 2015-08-13 14:50
@rwjblue Apologies, but what's a CP?

I don't know enough about Ember internals to really judge if this is the same issue, but fwiw, the problem that I'm reporting only occurs when a property defined by Em.computed.alias() is bound. Other properties, including static and computed properties that emulate Em.computed.alias() work fine and exhibit the expected two-way binding behaviour.

**Comment by rwjblue** [comment] 2015-08-13 14:54
CP is a computed property. I am fairly sure that this is the same issue as that failing test PR is demonstrating.

**Comment by DaveDuchene** [comment] 2015-08-13 15:01
@rwjblue Looking at the unit test in that PR, I'm really not sure that it's the same issue. If I implement a computed property that emulates Em.computed.alias() in my component, two way bindings work fine with it. That would be the last work-around demonstrated in the JS bin linked from the initial bug report.

I defer to your judgement though ...

**Comment by ppcano** [comment] 2015-08-19 08:52
@rwjblue http://jsbin.com/zejuro/7/edit?html,js,output is another case which demonstrate a similar and/or related problem.

@mixonic described the possible cause at #11225 

`CP not being watched, and therefore no property change notification being fired`

However, this failing example does NOT work with v2.0.0 version but it does with 1.13.8 version,
then, this issue is likely different than #11225 which was reported for 1.13 version.

I also wonder if anybody has also reported this issue (probably common case) for version 2.0.0.

**Comment by locks** [comment] 2016-04-25 22:33
I am closing this issue as it doesn't seem like an Ember bug, and the discussion got stale.
Feel free to re-open the issue if you think it's still justified, thank you!

**Closed by locks** 2016-04-25 22:33 UTC
