### ISSUE TITLE
Ember 1.13.7: click events in components are not triggered

### ISSUE THREAD

**Issue by MichaelVdheeren** [emberjs/ember.js#12063] opened 2015-08-12 10:23 UTC
```
export default Em.Component.extend({
  tagName: 'a',
  classNames: ['btn', 'btn_primary'],
  classNameBindings: ['disabled'],

  click: function(){
    this.sendAction();
  },
});
```

The click is not triggered when clicking on the component in 1.13.7. This works in 1.13.6

**Comment by rwjblue** [comment] 2015-08-12 12:08
Seems to be working here: http://emberjs.jsbin.com/dumura/edit?html,js,output.

How are you invoking the component?

**Comment by MichaelVdheeren** [comment] 2015-08-12 12:35
```{{save-button action="sendInvite" disabled=canNotSend classNames="btn btn_primary pull-right" regularText=regularText disabledText=disabledText}}```

**Comment by MichaelVdheeren** [comment] 2015-08-12 12:40
Doesn't work here, classNames problem
http://emberjs.jsbin.com/fodifofeba/edit?html,js,output

**Comment by rwjblue** [comment] 2015-08-12 12:43
Gotcha, then this isn't about declaration of your component, it is about invocation.  Switching to `class=` instead of `classNames=` should work.

**Comment by rwjblue** [comment] 2015-08-12 12:44
Duplicate of:

* https://github.com/emberjs/ember.js/issues/12047
* https://github.com/emberjs/ember.js/issues/12039
* https://github.com/emberjs/ember.js/issues/12008

**Closed by rwjblue** 2015-08-12 12:44 UTC
