### ISSUE TITLE
Error from v1.12.0 -> v1.13.0 (Cannot read property 'match' of null inside fetchSourceMap)

### ISSUE THREAD

**Issue by sarus** [emberjs/ember.js#11490] opened 2015-06-17 18:30 UTC
Just tried upgrading from Ember v1.12.0 to v1.13.0 and have some errors being thrown (outside of expected deprecation warnings).  In particular the following is occurring:

```
TypeError: Cannot read property 'match' of null
    at <anonymous>:881:35
    at Array.exports.default._emberMetalMixin.Mixin.create.find (ember.debug.js:33253)
    at <anonymous>:880:33
    at tryCatch (ember.debug.js:54695)
    at invokeCallback (ember.debug.js:54710)
    at publish (ember.debug.js:54678)
    at ember.debug.js:31502
    at Queue.invoke (ember.debug.js:901)
    at Object.Queue.flush (ember.debug.js:965)
    at Object.DeferredActionQueues.flush (ember.debug.js:765)onerrorDefault @ ember.debug.js:31541exports.default.trigger @ ember.debug.js:55323Promise._onerror @ ember.debug.js:56275publishRejection @ ember.debug.js:54609(anonymous function) @ ember.debug.js:31502Queue.invoke @ ember.debug.js:901Queue.flush @ ember.debug.js:965DeferredActionQueues.flush @ ember.debug.js:765Backburner.end @ ember.debug.js:158(anonymous function)
```

When stepping through the debugger it ends up here where `item.source` is null.

```
    fetchSourceMap: function(stackStr) {
      var self = this;
      if (this.get('emberCliConfig') && this.get('emberCliConfig.environment') === 'development') {
        return this.get('sourceMap').map(stackStr).then(function(mapped) {
          if (mapped && mapped.length > 0) {
            var source = mapped.find(function(item) {
              //item.source is null
              return !!item.source.match(new RegExp(self.get('emberCliConfig.modulePrefix')));
            });
            if (source) {
              source.found = true;
            } else {
              source = mapped.get('firstObject');
              source.found = false;
            }
            return source;
          }
        });
      } else {
        return RSVP.resolve(null, 'ember-inspector');
      }

    },
```

Here are the versions I'm using:

```
DEBUG: -------------------------------
ember.debug.js:5361 DEBUG: Ember                     : 1.13.0
ember.debug.js:5361 DEBUG: Ember Data                : 1.13.0
ember.debug.js:5361 DEBUG: jQuery                    : 1.11.3
ember.debug.js:5361 DEBUG: Ember Simple Auth         : 0.8.0-beta.3
ember.debug.js:5361 DEBUG: Ember Simple Auth Testing : 0.8.0-beta.3
ember.debug.js:5361 DEBUG: -------------------------------
```

If someone can point me in the right direction I'm happy to further debug.  I have not been able to figure out what part of my application code could be causing the issue.

Thank you!

**Comment by rwjblue** [comment] 2015-06-17 18:35
Seems to be an error from within the ember-inspector.

@teddyzeenny - Do you agree?

**Comment by sarus** [comment] 2015-06-17 18:43
Thanks for the quick response!

Just disabled `ember-inspector` and the error went away so that does seem to be the culprit.  Should I submit a new issue over there?

**Comment by teddyzeenny** [comment] 2015-06-17 18:43
Confirmed. This is inspector code.

**Comment by mmahalwy** [comment] 2015-06-27 00:24
Getting the same error too!

**Comment by locks** [comment] 2016-04-20 00:59
I am closing this issue as Teddy confirmed it's Inspector-related.
Feel free to re-open the issue if you think it's still justified, thank you!

**Closed by locks** 2016-04-20 00:59 UTC
Labels: Ember 1.13
