### ISSUE TITLE
[3.17.0 beta regression] Array Proxy not updating

### ISSUE THREAD

**Issue by patocallaghan** [emberjs/ember.js#18750] opened 2020-02-20 15:26 UTC
I've found what appears to be a regression with `ArrayProxy` that was introduced in this commit https://github.com/emberjs/ember.js/pull/18703 in **3.17.0-beta.3**. **3.17.0-beta.2** is working as expected.

These changes were also backported in https://github.com/emberjs/ember.js/pull/18721 to 3.16.2 which means the regression is also on 3.16.2, but works on 3.16.1.

I've got a reproducing test in my repo here. While the test is a bit convoluted this is a bare bones reproduction of some code in our app where we are seeing the issue.

https://github.com/patocallaghan/array-proxy-regression/blob/master/tests/unit/array-proxy-test.js

It seems that modifying the ArrayProxy internally is not picking up all the changes.

/cc @pzuraq

**Comment by pzuraq** [comment] 2020-02-20 15:58
Thanks for this thorough bug report! I have a reproduction with a unit test locally, very strange. Will be taking a look as soon as I have time.

**Comment by rwjblue** [comment] 2020-02-28 13:41
Closed by https://github.com/emberjs/ember.js/pull/18770

**Closed by rwjblue** 2020-02-28 13:41 UTC
Labels: Bug, Has Reproduction, Regression

**Comment by DuBistKomisch** [comment] 2020-03-02 03:38
Any plans to backport this fix to 3.16(.4)?

**Comment by pzuraq** [comment] 2020-03-02 16:10
Yes, the fix is marked for `release`. We are currently waiting to make sure it works as expected and doesn’t cause further issues.

**Comment by jonathannewman** [comment] 2020-03-19 23:42
Any update on plans to backport this to 3.16?

**Comment by deanylev** [comment] 2020-03-23 04:16
Seems this wasn't backported to 3.16.4? :/

**Comment by jonathannewman** [comment] 2020-03-23 15:25
I just tried the new 3.16.5 against our codebase and am still seeing the failures related to this in our tests.  @pzuraq @rwjblue any chance of getting this fix in?  We would like to update to the 3.16 LTS.

**Comment by pzuraq** [comment] 2020-03-23 15:27
I’m working on it today

**Comment by rwjblue** [comment] 2020-03-23 16:11
Ya, I chatted with @pzuraq about this last night. I wanted to get the other fixes out (fixing an issue with Babel 7.9.x, and an observer memory leak issue), and @pzuraq is going to work on backporting the fix for this into `lts-3-16` branch today and we'll get _yet another_ patch release out (hopefully today). Good news though: we won't run out of numbers! :smiley:

**Comment by jonathannewman** [comment] 2020-03-23 16:22
Awesome!  Thank you!

**Comment by BillyRayPreachersSon** [comment] 2021-04-06 12:40
Has there been any news on backporting this fix to the LTS 3.16 release?

We're in the process of upgrading from 3.12 LTS to 3.16 LTS, and are finding [this](https://github.com/DockYard/ember-composable-helpers/issues/349) `ember-composable-helpers` bug is still an issue - something that was believed to have been caused by this problem.

We've got `ember-cli` `3.16.2` and `ember-source` `3.16.10` specified in our `package.json` file.
