### ISSUE TITLE
Updating a bound property of a component triggers observers for all bound properties of the component

### ISSUE THREAD

**Issue by laynegt** [emberjs/ember.js#11491] opened 2015-06-17 18:38 UTC
This is in 1.13.  I have a component with several bound properties from a controller.  I also have  observers on these properties inside the component.  When any of the properties are updated in the controller, the observers for all of the bound properties are fired (in the component, twice).

Example: http://emberjs.jsbin.com/hicowe/edit?html,js,console,output
A and B are bound to properties in the controller.  C is an internal property to the component only.

**Comment by vvisheshd** [comment] 2015-06-18 16:32
I have exactly the same issue! 
http://jsbin.com/yugaxezone/edit?html,js,output . 
Observers for all the bound properties are fired and that too TWICE. 

http://discuss.emberjs.com/t/ember-1-13-attrs-call-property-change-on-all-observers/8212

**Comment by hussasad** [comment] 2015-07-12 17:01
I am having the same issue. is there any work around for this?

**Comment by stefanpenner** [comment] 2015-07-12 23:35
this is a regression, likely caused by the attrs proxy.

**Comment by rwjblue** [comment] 2015-07-12 23:41
@stefanpenner - Exactly, I agree it is almost certainly related to the attrs proxy.

A little background from a prior spelunking: any time an attribute is changed, we set the entire `this.attrs` object which then triggers all root attributes via the attrs proxy.

**Comment by stefanpenner** [comment] 2015-07-13 14:51
yes, this new code has issues in 2 phases.

1. component initialization <-- I am pretty sure I have a solution for this – and i plan to work on this this week.
2. post initialization changes <-- I have an idea, but haven't thoroughly investigated it.

**Comment by jcope2013** [comment] 2015-07-13 17:34
seeing same issue

**Comment by rounders** [comment] 2015-07-16 22:41
also seeing this issue. 
Ember 1.12 - works as expected:
http://emberjs.jsbin.com/jotacururu/edit?html,js,console,output

Ember 1.13 - initialization of component causes observer to fire and observers fired twice everytime a bound property is changed:
http://emberjs.jsbin.com/nedixehuho/1/edit?html,css,js,output

**Comment by tehmaestro** [comment] 2015-08-03 07:52
Hi, I noticed this too. Also, in the `init` hook of a component, it seems that if I change a bound property, the observer is not triggered for the parentView. Could this be related?
```
    // app/controllers/my-controller.hbs
    {{my-component property=property}}

    // app/components/my-component.js
   doSomething: function() {
     this.set('property', false);
   }.on('init')
```
   Here, the bound `property` in the controller is not being updated when the component updates it. I tried to use other component hooks, and it only worked in `didInsertElement`

**Comment by rwjblue** [comment] 2015-08-03 14:20
Thanks for providing all these demos/examples, it definitely made it easy to confirm things were fixed here.  The double observer firing issue was resolved by https://github.com/emberjs/ember.js/pull/11946.

@rounders - Updated [JSBin](http://rwjblue.jsbin.com/ritafa/edit?html,js,output) with current release branch, double firing observers are solved.

@tehmaestro - Your example seems unrelated to this issue (since its about double firing observers), but does seem to be a legitimate issue on its own.  Can you report separately?

@vvisheshd - Your [JSBin](http://rwjblue.jsbin.com/yugaxezone/1/edit?html,js,output) works properly (only fires once) with the latest release builds.

@laynegt - Your [JSBin](http://rwjblue.jsbin.com/vocifo/edit?html,js,console,output) works properly on the latest release builds.

**Closed by rwjblue** 2015-08-03 14:20 UTC
Labels: Bug, Regression

**Comment by tehmaestro** [comment] 2015-08-03 14:30
Thanks for the fix. Opened issue #11967

**Comment by rounders** [comment] 2015-08-04 00:20
@rwjblue, @ef4 :+1: thanks!!
