### ISSUE TITLE
`filterBy` should maybe ignore `undefined` values

### ISSUE THREAD

**Issue by YoranBrondsema** [emberjs/ember.js#14953] opened 2017-02-23 16:53 UTC
See https://ember-twiddle.com/73a0a73f824535e32d0afd2d419a2ccb?numColumns=2&openFiles=controllers.application.js%2Ctemplates.application.hbs

I have an array with an `undefined` value as a member. Personally I expected `filterBy` to ignore this value but it throws an error instead.

````
Assertion Failed: Cannot call get with 'type' on an undefined object.
````

**Comment by Serabe** [comment] 2017-02-24 15:53
Behaviour is as it would be in plain JS, trying to get a property from `undefined` raises an error. You can use `Ember.computed.filter` with a custom function instead.

Closing. Not a bug.

**Closed by Serabe** 2017-02-24 15:53 UTC

**Comment by YoranBrondsema** [comment] 2017-02-24 17:48
No worries. I was just surprised at the inconsistency between `Ember.computed.reads` and the array functions. If you do `Ember.computed.reads('someProp.name')` where the property is `undefined`, it doesn't throw an error like the array functions do but simply returns `undefined`. Conceptually I was expecting the array functions to work in a similar way to `Ember.computed.reads` in that respect.

**Comment by Serabe** [comment] 2017-02-24 18:58
It is consistent. You can pass a deep property path to `filterBy` and [won't complain about `undefined`s in that chains](https://ember-twiddle.com/382d6e0b9ce7926ef7f33a855ad92c13?openFiles=templates.application.hbs%2C). It will complain about a property too deep after the `@each`.

**Comment by YoranBrondsema** [comment] 2017-02-24 19:09
Alright, thanks for explaining.
