### ISSUE TITLE
Ember 3.18 - Cycles in tags are not allowed [query params]

### ISSUE THREAD

**Issue by lifeart** [emberjs/ember.js#18981] opened 2020-05-18 19:48 UTC
![image](https://user-images.githubusercontent.com/1360552/82253446-aa81e500-9959-11ea-8611-6825f7c0df7b.png)

reproduction: https://ember-twiddle.com/4106c69bb441077e93a8fcbba5fb3620?openFiles=templates.application%5C.hbs%2C

 click on link 1, click on 2, and check console

**Comment by gabrielgrant** [comment] 2020-05-22 16:52
arg, think i've been running into this the past couple days thinking I was doing something silly. Any suggestions on a workaround?

**Comment by chancancode** [comment] 2020-05-27 16:04
Great reproduction @lifeart. I narrowed down the reproduction a little and left some comments on what I found, both in the template and in the controller code. This seems to specifically impact array-typed QPs backed by tracked properties, with links that uses the default QP value.

https://ember-twiddle.com/1390a8f5eefe3b9ce755944bf989afcc?openFiles=templates.application%5C.hbs%2C

I think this clearly seems like a bug, but if you are desperate for a work around, since the QP only affect array-typed QPs, I suppose you can do something like this to manually convert it into a string-typed QP to avoid the issue:

```js
// Don't copy this code as-is, without testing, I just typed-out-loud on the issue thread!

class MyController extends Controller {
  queryParams = [{ _projects: 'projects' }];

  @tracked _projects = '';

  get projects() {
    if (this._projects === '') {
      return [];
    } else {
      return JSON.parse(`[${this._projects}]`);
    }
  }

  set projects(array) {
    if (Array.isArray(array) && array.length > 0) {
      this._projects = JSON.stringify(array).slice(1, -1);
    } else {
      this._projects = '';
    }
  }
}
```

**Comment by arunyegappan** [comment] 2020-07-17 12:15
I face the same issue. Any updates on this?

**Comment by s-chiriac** [comment] 2020-09-07 08:32
Is there any chance this will get looked at soon? I'd love to contribute, but I'm not familiar enough with the codebase to find a solution. It's preventing my team from upgrading to 3.20

**Comment by Samsinite** [comment] 2020-10-07 21:34
Looks like a fix is in 3.21, just appears to need back-ported to a few LTS releases.

**Comment by rwjblue** [comment] 2020-10-07 22:57
Ya, the fix introduced regressions that we are still working on fixing (https://github.com/emberjs/ember.js/pull/19178 fixed some, but introduced https://github.com/emberjs/ember.js/issues/19179 which ATM is still unfixed).

**Comment by anlumo** [comment] 2020-10-28 22:41
I'm currently in the process of updating my application from ember 3.14 to 3.22. I get the same exception at the same place, but even when I disable all my query parameters for the whole application, it's still there.

Is there any other situation where this exception could be thrown? I'm working on a giant application here, so isolating anything is very difficult, and the stack trace doesn't tell me anything.

**Comment by javve** [comment] 2020-12-04 12:04
I got this error when I accidentally had made a computed property that depended on itself. This didn't generate an error in Ember <= 3.17
```javascript
imageContainerSize: computed('imageContainerSize', 'minWidth', 'minHeight', function () {})
```

**Comment by rwjblue** [comment] 2020-12-04 13:40
Ya, it is fixed in current releases (and back ported to 3.20).

**Closed** 2020-12-04 13:40 UTC
Labels: Bug, Has Reproduction, Query Params, Regression, Rendering

**Comment by juan-m-medina** [comment] 2021-01-29 02:42
Any hints on where to start looking if this issue happens while using 3.22?

**Comment by pzuraq** [comment] 2021-01-29 16:22
@juan-m-medina creating a minimal reproduction would be ideal, this is a pretty advanced issue when it happens usually, the last time we found it out it was a really weird interaction between query parameters, computed properties, and tracked properties, essentially.

**Comment by jcardali** [comment] 2021-03-03 18:59
Still seeing this in 3.22 and above like @juan-m-medina

**Comment by waissbluth** [comment] 2021-03-03 19:01
@jcardali are you seeing this on 3.24.2 (LTS)?
