### ISSUE TITLE
Blank render in IE when using attributeBindings

### ISSUE THREAD

**Issue by ChrisHonniball** [emberjs/ember.js#11417] opened 2015-06-11 19:03 UTC
Just a report that I have found a solution to a problem I have stumbled on.

If you have:

```javascript
attributeBindings: ['disabled:disabled:'],
```

IE fails with:

![2015-06-11-ie-console](https://cloud.githubusercontent.com/assets/3345374/8115612/913adeb4-104a-11e5-836a-bc5e82c76ca7.png)

Offending line:

![2015-06-11-vendor-js-lines](https://cloud.githubusercontent.com/assets/3345374/8115635/bf65fa62-104a-11e5-86ef-e9dd260046a5.png)

Removing the last `:` fixes the issue. No other browser breaks with this code.

Again, just a report. Maybe fix it so that it doesn't crash IE? Thanks for all the hard work.

**Comment by rwjblue** [comment] 2015-08-21 04:10
What are the versions of Ember and IE that you tested with?  Can you provide a JSBin demo to aid in tracking this down?

**Comment by ChrisHonniball** [comment] 2015-08-21 11:43
@rwjblue I can do that. I'm not sure if the problem is still present since I know how to avoid it. I'll report back once I make a demo.

**Comment by Serabe** [comment] 2016-04-18 07:20
@ChrisHonniball can you please check this bug is still present? Thank you!

**Comment by acorncom** [comment] 2016-04-29 23:18
I'm going to close this issue for now, if the issue is still there we'll be happy to re-open it.  If we do have this bug still, getting a Twiddle showing the issue would be great 👍

**Closed by acorncom** 2016-04-29 23:18 UTC
Labels: Needs Submitter Response
