### ISSUE TITLE
[BUG beta] `isDestroying` flag out of sync with the `_state` property.

### ISSUE THREAD

**Issue by cibernox** [emberjs/ember.js#14000] opened 2016-08-02 11:14 UTC
Tests in EmberPowerSelect started to fail when 2.8-beta.1 was released. 

The error started in the view: `Uncaught TypeError: Cannot read property 'scheduleRevalidate' of null`. However I saw this failure at the end of the tests when all assertions ran. 

I tracked the failure to an action `onBlur` action that ties to set a property in the component. That `onblur` action is triggered by the destruction of the component (strange, I know, but it's expected behaviour in browsers).

By the time this action was called the `willDestroyElement` hook was already called, and the `_state` property of the component is "destroying". However the `isDestroying` flag is false.
I've checked it and in 2.7, that same flag was true.

Somehow that flag got out of sync with the internal state of the component in beta.

I've been able to create a minimum twiddle to prove the regression: https://ember-twiddle.com/11c1ce8fc3cb9695d5c51a6e00754f24?openFiles=components.my-component.js%2Ctemplates.components.my-component.hbs

**Comment by martndemus** [comment] 2016-08-02 11:33
This is probably a duplicate of #13846

**Comment by cibernox** [comment] 2016-08-02 12:17
@martndemus Maybe it's the same issue, but I don't see any mention in the other issue of the `isDestroying` flag. Perhaps that other issue is the caused this regression. 

By example the example I posted doesn't trigger any error in the console but the logs in the console show how the behaviour of the `isDestroyed` field changed.

**Comment by cibernox** [comment] 2016-08-04 00:09
Ok, I've bisected this to [this commit](https://github.com/emberjs/ember.js/pull/13775/commits/186be31d3ce565f6d4b1e374a70b78695d71866c) of the PR #13775

The test I'm using to detect this failure:
```js
  ['@test it calls willDestroyElement and isDestroying is not out of sync'](assert) {
    assert.expect(2);
    let FooBarComponent = Component.extend({
      didInsertElement() {
        this.element.querySelector('input').focus();
      },

      actions: {
        inputBlur() {
          assert.ok(this.get('isDestroying'), 'The component isDestroying flag is true');
          assert.equal(this._state, 'destroying', 'The component _state is destroying');
        }
      }
    });

    this.registerComponent('foo-bar', {
      ComponentClass: FooBarComponent,
      template: 'hello <input type="text" onblur={{action "inputBlur"}} />'
    });

    this.render('{{#if switch}}{{foo-bar}}{{/if}}', { switch: true });

    this.runTask(() => set(this.context, 'switch', false));
  }
```

It is worth noticing that this test **passes in glimmer but fails in HTMLbars**

@krisselden I haven't even tried to dig into this, I just bisected. But if you can see anything that could make the `isDestroying` flag to be false even when the `_state` is `"destroying"` when the blur action is called, be my guess.

**Comment by krisselden** [comment] 2016-08-04 05:54
This is not a bug, _state means the dom is destroying isDestroying is an object model thing. isDestroying should only be true if the object model destroy method is called this is rare in practice to happen first was buggy before when it did.

**Comment by krisselden** [comment] 2016-08-04 05:58
I'm going to close this as a duplicate bug and because the title of this one is wrong as well.  The bug is scheduleRevalidate can run on a view that has already been torn down

**Closed by krisselden** 2016-08-04 05:58 UTC

**Comment by cibernox** [comment] 2016-08-04 08:07
@krisselden ok. In any case, since this seems to be a manifestation of that other bug, this bisect is still valuable. I'll add a comment in the other issue.
👏
