### ISSUE TITLE
Using {{each}} block with nested array property causes glimmer error.

### ISSUE THREAD

**Issue by n8n8baby** [emberjs/ember.js#17048] opened 2018-10-05 20:35 UTC
It appears that glimmer has a bug when dealing with nested array properties such as:
```
 {{#each nested.options as |option|}}
     <option value={{option.value}} selected={{if option.selected "selected"}}>{{option.label}}</option>
{{/each}}
```

There is no error when "nested.options" is replaced with "options" (given the data binding is also updated).

There were some similar characteristics in my development repo to a recently solved issue at https://github.com/emberjs/ember.js/issues/16314, in that the errors reported are similar.

I have set up a twiddle to illustrate the problem at https://ember-twiddle.com/ec8ab99a672b6d11261219b1bb84e081. It does not display all of the errors that my development repo does, but does produce errors.

In my development repo, replacing the nested reference with equivalent of `options: alias('nested.options')` avoids the issue.

Please let me know if I can be of any assistance.

**Comment by yininge** [comment] 2018-10-12 16:28
@n8n8baby Thank you for reporting this issue. Can you make your gist for the twiddle public? I am not able to view your twiddle, it says "The gist is missing or secret."

**Comment by pixelhandler** [comment] 2018-10-12 17:15
@n8n8baby Also a thought, perhaps do not use a variable name in a template which could mask an HTML element (angle bracket components).

```hbs
{{#each nested.options as |opt|}}
     <option value={{opt.value}} selected={{if opt.selected "selected"}}>{{opt.label}</option>
{{/each}}
```

**Comment by pixelhandler** [comment] 2018-10-19 17:13
@n8n8baby can you make the gist for your twiddle public? no one can see your example reproduction

**Comment by rwjblue** [comment] 2018-10-22 10:48
Sounds like it may be a duplicate of https://github.com/emberjs/ember.js/issues/16826?

**Comment by pixelhandler** [comment] 2018-12-07 16:57
@n8n8baby yeah I think the fix is:

Don't do this....

```
{{#each nested.options as |option|}}
  <option value={{option.value}} selected={{if option.selected "selected"}}>{{option.label}}</option>
{{/each}}
```

Treat variable names in .hbs templates with care, they cannot shadow the name of an HTML element, e.g `option`.

Instead do...

```
{{#each nested.options as |opt|}}
     <option value={{opt.value}} selected={{if opt.selected "selected"}}>{{opt.label}}</option>
{{/each}}
```

**Comment by rwjblue** [comment] 2018-12-07 17:47
Closing for now, as a duplicate of the regression being tracked in #16826

**Closed by rwjblue** 2018-12-07 17:47 UTC
Labels: Needs Reproduction, Needs Submitter Response
