### ISSUE TITLE
visit() discards original stack trace on rejection

### ISSUE THREAD

**Issue by asakusuma** [emberjs/ember.js#18983] opened 2020-05-18 22:45 UTC
When `visit()` rejects without an active transition, it [creates a new error and discards the origin stack trace](https://github.com/emberjs/ember.js/blob/e8de71f7204724a23363e270af59ac2cb81f2d64/packages/%40ember/application/instance.js#L268). This is problematic when there's an error that is not reproducible locally, but is only observed via production logs. Without the stack trace in the log, can be difficult to find the source of the error.

**Comment by rwjblue** [comment] 2020-05-19 22:44
Can you share a reproduction that we can use to fully understand what you mean (and confirm any fixes actually work)?

**Comment by locks** [comment] 2023-07-22 21:22
Closing due to lack of reproduction.

**Closed by locks** 2023-07-22 21:22 UTC
