### ISSUE TITLE
Windows newlines cause extra whitespace in 1.8, 1.9 and Safari/Chrome

### ISSUE THREAD

**Issue by michaljagielski-sc** [emberjs/ember.js#9945] opened 2014-12-16 11:21 UTC
I have a problem in the app that I'm working on, since I upgraded EmberJS from 1.6.1 to 1.8.1. It happens only under Chrome. The issue is that somehow my templates are being rendered with lots of additional spaces surrounding each html node. So to say... instead of:

    <div>
    [tab]<span>Hello</span>
    </div>

I get something like this rendered:

    <div>[ ][ ][ ][ ][ ][ ][ ][ ][ ]
    [ ][ ][ ][ ]<span>Hello</span>[ ][ ][ ][ ]
    </div>[ ][ ][ ][ ]

Or maybe you'll see it here: An example:
![untitled](https://cloud.githubusercontent.com/assets/8087737/5452664/e46bd588-851d-11e4-99ec-d570f52ce16b.png)

That obviously breaks styling a lot. The funny thing is that when I remove at least one space from such strange construct, then magically the styling for given section is back (even though other spaces are still there).

Just to mention. I'm using ember-grunt-templates 0.4.21 to compile. I know that there are new versions of it (0.4.23 I think...) and I tried to update it as well, but it doesn't help.

I know that there was a mention here: http://emberjs.com/blog/2014/11/04/ember-1-8-1-released.html about whitespace issue in Chrome, but it says that people get the opposite effect of missing spaces due to some bug in Chrome. ;> Is my Chrome instance consuming and gathering all other people whitespaces or what? :-)

**Update 1:**

I tried to update to:

 - Ember 1.9
 - Handlebars 2.0
 - Grunt-Ember-Templates 0.5 alpha

That fixes few occurrences of whitespace issue, but some are still present. I.e. that results in a space in front of rendered text:

    <span class="someClass">
        {{#if condition}}{{someProperty}}{{else}}{{t 'translationKey'}}{{/if}}
    </span>

And that doesn't:

    <span class="someClass">{{#if condition}}{{someProperty}}{{else}}{{t 'translationKey'}}{{/if}}</span>

:expressionless:

**Comment by mixonic** [comment] 2015-01-08 03:35
Can you see if this behavior persists in 1.10?

**Comment by mixonic** [comment] 2015-01-08 03:51
So, this is a 1.9 regression. It has nothing to do with HTMLBars, and is fixed in 1.10.

* A bad-behaving JSBin with 1.9: http://emberjs.jsbin.com/pebemegona/1/edit?html,css,js,output note the space before the list
* A well-behaving JSBin with 1.10: http://emberjs.jsbin.com/dizidoyebi/1/edit?html,css,js,output no space before the list

The bad behavior in 1.9 is a quirk from the way we use `parseHTML` on each template in isolation combined with a bug in the rendering engines of Chrome and Safari (check the first JSBin, it is fine in FireFox).

If we had a clean fix (and I don't think dropping `\r` from all 1.9 Handlebars template before compiling them is clean? Or it is?) I think this would justify a point release.

Regardless, the behavior is correct in 1.10.

**Comment by jonnii** [comment] 2015-01-08 03:56
@mixonic I don't think this justifies a point release, this mainly affects windows users (as far as I can see) and there's a perfectly good work around which is to remove the `\r` when compiling templates. With 1.10 around the corner I think anyone who has run into this can wait.

**Comment by jayphelps** [comment] 2015-01-16 23:55
IMO I think a `v1.9.1` *should* be cut. If I was bitten by this, it's not always trivial to just upgrade to the next sub version. Many large apps make use of public/private APIs that have been fluxing a lot lately and while it's not the core teams job to keep private APIs stable, providing patches for regressions shows the community we all take them seriously and know the answer isn't always "well just upgrade". I'm happy to help if there's anything I can do.

**Comment by mixonic** [comment] 2015-01-19 19:27
@jayphelps We discussed a few options. The best one would be stripping windows newlines out of templates when compiling them. I don't develop on Windows, so I don't feel comfortable landing that patch on my own. It may have other side-effects. It needs testing.

The "offending area" is the rendering engines in Chrome and Safari. They incorrectly consider `\r` to be significant whitespace when inserting it after insignificant whitespace. I haven't opened up a ticket for them and I should.

@jayphelps I'm really sorry if you feel we are letting you or the community down here. We need to choose where to focus our efforts, and please don't think we're not serious about fixing bugs. IMO it is an unwarranted of a reaction. I spent a significant amount of my own time nailing down the problem to something reproducible and specific.

There are a lot of people on this thread who use Windows with Ember, and I'm happy to help any of them land a patch. I'm also happy to advocate for a 1.9.1 release. Nothing is ruled out.

**Comment by jayphelps** [comment] 2015-01-19 19:50
@mixonic Sorry for the confusion, I thought my edit clarified that I mistakenly thought we had a trivial, known fix already in place for 1.10.0 but were choosing not to back port it. After digging into it quite a bit as well, I came to all the same conclusions you did. Also--my comment was in response to @jonnii's comment.

**Comment by mixonic** [comment] 2015-01-19 20:04
If @jayphelps is happy I am happy :-)

**Comment by rwjblue** [comment] 2015-08-09 19:48
Closing since this is fixed in 1.10+ (and there is a work around for 1.8 and 1.9).

**Closed by rwjblue** 2015-08-09 19:48 UTC
Labels: Needs Label Review, Regression
