### ISSUE TITLE
.trigger() from Evented Mixin always fires queued listeners in reverse order

### ISSUE THREAD

**Issue by gfmartinez** [emberjs/ember.js#16334] opened 2018-03-07 14:16 UTC
https://github.com/emberjs/ember.js/blob/ce3324570a9d6f1ee6525d53cdbf42c1dcaad345/packages/ember-metal/lib/events.js#L130

The flattened actions always loop in reverse order from the queued order of listeners.

I see in the note that this was intended for events registered as ONCE. But use of `.on()` or `.one()` to register an event results in the same reverse order call for queued events.

Suggest a check before the calling of queued listeners as to direction: reverse or forward. Unless specified, I would expect the listeners to be called in the order in which they were registered.

**Comment by Serabe** [comment] 2018-03-09 18:05
[This has been so for more than five years](https://github.com/emberjs/ember.js/commit/d47b71885effb93a4a78a4024cea22de40875b72#diff-51288c2d53949fb28968c1272921ea44L70). Closing as this is not a bug.

Thank you!

**Closed by Serabe** 2018-03-09 18:05 UTC

**Comment by gfmartinez** [comment] 2018-03-09 18:12
@Serabe Thanks. I see it's not considered a bug. Shall I submit a feature request then?

We use Evented for several services in our app and we have to hack work arounds because of the reverse firing order. Would be great to have a way to designate which direction the listeners fire.

**Comment by Serabe** [comment] 2018-03-09 18:19
You can open an RFC to change the behaviour, but when doing so, please research what the impact on current codebase will be. You can learn more about the [RFC process](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#requesting-a-feature) in the [CONTRIBUTING file](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md)

**Comment by houfeng0923** [comment] 2019-03-13 07:01
It is an implicit knowledge in trigger  once event !  ye it's not a bug , but it 's not friendly.  
we expect it executed in ordered  intuitively.
