### ISSUE TITLE
App crashes tab if devtools open on initial load

### ISSUE THREAD

**Issue by knownasilya** [emberjs/ember.js#10889] opened 2015-04-16 14:27 UTC
Not really sure how to debug it. Submitted an issue here: https://code.google.com/p/chromium/issues/detail?id=477686

Tried all of the logs, but nothing too obvious. This also happens with 1.11.1.

**Comment by fivetanley** [comment] 2015-04-16 14:35
The issue is 404'ing for me :(

**Comment by knownasilya** [comment] 2015-04-16 14:37
@fivetanley says it's in restricted mode.. Here's what it says:

```no-highlight
Chrome Version: 42.0.2311.90
Operating System: "Mac OSX 10.10.3"

URL (if applicable) where crash occurred: http://maldenma.mapgeo.alpha1.appgeo.com/

Can you reproduce this crash?

What steps will reproduce this crash? (or if it's not reproducible, what were you doing just before the crash)?

1. Open devtools
2. Visit http://maldenma.mapgeo.alpha1.appgeo.com/
3. Wait for crash


I'm using Ember.js in this app, other similar apps do not behave this way.

****DO NOT CHANGE BELOW THIS LINE****
report_id:10f1915d019f91ff
```

**Comment by knownasilya** [comment] 2015-04-16 14:41
Hum, it works in canary version of chrome.

**Comment by knownasilya** [comment] 2015-04-16 14:45
Doing the extension dance...

**Comment by knownasilya** [comment] 2015-04-16 14:57
So the only extension left is "GoToMeeting for Google Calendar" which is company enabled, so i can't disable it to test.

**Comment by knownasilya** [comment] 2015-04-16 19:07
Ok, extensions ruled out (at least enabled, since i didn't uninstall).

**Comment by OrKoN** [comment] 2015-04-16 19:41
This happens for me from time to time(not each time) for various apps including Google's gmail. Dunno why I have a debugger opened for gmail though... Btw, the link to the app you posted does not work any more

**Comment by stefanpenner** [comment] 2015-04-16 21:34
this is clearly a chrome bug. is there a related issue open on its tracker?

**Comment by rwjblue** [comment] 2015-08-15 19:07
Seems like a browser bug, and I don't really think there is much we can do about it on our end.  Also, the test URL (http://maldenma.mapgeo.alpha1.appgeo.com/) works properly in current Chrome.

Closing for now (happy to reopen if this is something on our side)...

**Closed by rwjblue** 2015-08-15 19:07 UTC
