### ISSUE TITLE
Feature: Guard against non KVO-Compliant methods

### ISSUE THREAD

**Issue by RobIsHere** [emberjs/ember.js#13889] opened 2016-07-26 08:17 UTC
I just searched for an error in my code. A deeply chained computed property was not updating as expected. After looking everywhere for about two hours it came down to a simple .push(newObj) instead of a .pushObject(newObj). ( It was an array constructed using Ember.A() )

Because I'm also using a ton of other things in JS, not only Ember, I'm used to methods like .push(). And I can look directly at this LOC while my gut is telling me: everything ok here! So it's kind of hard to notice. And I would wonder if I was the only one. Shit happens ;)

So the quesition is:
1. is it possible to make methods like push() just work as expected? (I'm sure you had a reason, why it doesn't?)
2. if not possible is there a way to log a notice or do an assert?
3. if (2) is not possible cross browser, is it possible in any browser? For debugging that would be enough.

I think computed property chains are one of the hardest things to debug. And especially Ember beginners have a lot of trouble (see that when new programmer join the project). So more help/guards against errors would be great. Let's discuss how that could be done.

**Comment by pixelhandler** [comment] 2016-07-26 14:11
@RobIsHere you make a good point that computed properties can be hard to debug and the differences between using `push` and `pushObject` require reading the docs. One might expect `push` to behave as in the same way `pushObject` does, but then there would be no need for the two.  `pushObject` is necessary to use for notifying computed properties of the changes. It has been this way for a long time. 

> 1. is it possible to make methods like push() just work as expected? (I'm sure you had a reason, why it doesn't?)

No, the API is what it is by design.

> 2. if not possible is there a way to log a notice or do an assert?

Sounds like a recommendation for an enhancement, but again the API is documented that using `pushObject` is needed to notify of property changes. 

I'd suggest the opposing question should `pushObject` have an assert that asks the developer if they really wanted to ignore property changes, if so they should use `push` instead.

> 3. if (2) is not possible cross browser, is it possible in any browser? For debugging that would be enough. 

`Ember.assert` isn't a method that depends on browser support.

I think that answers the questions you raised, if you'd like to propose an enhancement to the `Array.push` method the best way would be via an RFC issue (not PR). See https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#requesting-a-feature you can create an issue here https://github.com/emberjs/rfcs/issues if you like.

I'll close this out for now the Ember issue tracker is mainly for tracking bugs.

**Closed by pixelhandler** 2016-07-26 14:11 UTC
Labels: Needs Team Response, wontfix
