### ISSUE TITLE
Override "value" property does not bind values in TextField.

### ISSUE THREAD

**Issue by khomyakov42** [emberjs/ember.js#12621] opened 2015-11-17 00:30 UTC
``` javascript
App.MyInput1Component = Ember.TextField.extend({

  value: Ember.computed({
    get(key) {
      return this.get('dirtyValue');
    },
    set(key, value) {
      return this.set('dirtyValue', value);
    }
  })
});
```

``` handlebars
{{my-input1 value=myValue1}} = {{myValue1}}<br/>
```

myValue1 not changed

http://jsbin.com/hureroqeje/edit?html,js,output

**Comment by Emrvb** [comment] 2015-11-19 10:27
I can confirm this. Works in 1.12, broken in versions above (the jsbin is written sloppy though).

As far I was able to trace it, it looks like a problem with the legacy view bindings causing the computed property not to be watched properly (but thats just a guess).

At this time, an elegant workaround would be wrapping the TextField, using a component that doesn't extend TextField to add the computed property which in its turn uses the TextField in its template.

Another workaround would be changing the setter of the computed property:

 set(key, value) {
      this.set('dirtyValue', value);
      this.notifyPropertyChange('value');
      return value;
    }

**Comment by pixelhandler** [comment] 2015-11-20 17:44
@khomyakov42 seems like there should be a way to workaround this issue. Or maybe a different implementation.

Why do you need to make `value` computed from `dirtyValue` ? for added behaviors to how a value is bound to a property that I pass into a text input component I sometimes am creative about what I bind to the value, sometimes it's a proxied property or a controller property than I apply that value to the model later (buffer the changes).

**Comment by rwjblue** [comment] 2015-11-20 18:33
This is a duplicate of https://github.com/emberjs/ember.js/pull/11225 I believe.

**Comment by Emrvb** [comment] 2015-11-20 18:59
@rwjblue could be. But here its specifically caused by the way the textfields value property gets bound. Doing the same thing with regular components and their CPs works fine.

**Comment by locks** [comment] 2016-04-19 00:42
@Emrvb is this still relevant?

**Comment by pixelhandler** [comment] 2016-05-05 03:06
@locks Yeah I have this issue in my app as well.

My use case is extending a TextField to use `type="number"` and a computed property for the `value` to `parseInt` and force the value of the input to be a Number.

Using the computed property with `get` and `set` for the values requires I use a local property for storing the value. My best guess is that since the value is a primitive (number / string) it's copying not a reference the bound value.

My workaround is that I use event handing with `focusOut` and `mouseLeave` to sent the Number value back using the `action` passed into my `number-input` component that extends `Ember.TextField`.

**Comment by pixelhandler** [comment] 2017-09-08 19:18
@khomyakov42 did the fixes in #13293 resolve this issue?

**Comment by pixelhandler** [comment] 2017-09-08 19:19
@toddjordan do you know if this issue should be closed per a fix?

**Comment by toddjordan** [comment] 2017-09-08 19:25
I'm happy closing if we can get a confirmation that the issue is indeed resolved.  if you, @khomyakov42 or @Emrvb can verify lets close (or if no responses come in).

**Comment by Emrvb** [comment] 2017-09-15 14:29
@toddjordan and @pixelhandler I just stumbled upon this report while researching for another problem.

I partially recreated the jsbin as a twiddle (https://ember-twiddle.com/7af4e33e1af56bc9dc0c45c31c778052). It's broken in 1.13.13 and it seems to work just fine in 2.12.0. But I can't tell you whether that particular pull fixed it.

**Comment by rwjblue** [comment] 2017-10-05 02:53
Thank you all for confirming this is fixed. Sorry this was such a pain.

**Closed** 2017-10-05 02:52 UTC
Labels: Bug
