### ISSUE TITLE
Closure action causes unnecessary rerender

### ISSUE THREAD

**Issue by scottmessinger** [emberjs/ember.js#14335] opened 2016-09-22 17:25 UTC
Hi! Thanks for all the hard work on Glimmer 2! I know it's taken a ton of work and I really appreciate it.

In using Glimmer 2 in my app, I think I've found a bug. If a component passes a closure action to its children and we change a property of the component, all the children are forced to rerender even  though we didn't pass that property to them (and thus none of their attrs (or internal state) changed).

For example, if I have a component (A) that has a `counter` property and I increment it, all of A's children will rerender even if I didn't pass them the counter property as long as I did pass them a closure action.

Here's the test case: open the console to see `didRender` being logged
https://ember-twiddle.com/5e495e8b7e6cb9ec8d56400f7b2d72ff

Notably, if you stop passing the closure action to `expensive-outline`, it will still rerender when `counter` is changed. This seems like a different bug but possibly related.

**Comment by rwjblue** [comment] 2016-09-24 17:26
Thank you for the awesome writeup and reproduction, @chancancode and I were able to track this down and fix in #14345.  Can you test the latest canary/alpha builds (in ~ 15 minutes when CI finishes) to confirm?

**Comment by rwjblue** [comment] 2016-09-24 19:21
I reviewed this after that CI build finished, and we still have the same issue.

To save myself time when I pick this back up again, let me try to explain the issue:

The way Glimmer 2 tracks changes and triggers rerenders, is by having a "tag" on each object that is used in a template. Think of these tags as a counter that just gets `counter++` and if the value is different then we actually do a rerender.

In the case of the example, the `{{expensive-outline`'s tag increments because it receives `counter`.  We are then passing `this.onAction` down to the `{{expensive-outline-item` component, and since the `expensive-outline` component's tag increments (and therefore the args for `{{expensive-outline-item`'s tag changes) which causes a rerender of the `expensive-outline-item`.

**Comment by kanongil** [comment] 2016-10-05 14:00
I would just like to chime in that this effects my code as well in canary, causing significant re-rendering, and is likely to block updating my app to 2.9+, if not resolved.

**Comment by rwjblue** [comment] 2016-10-05 14:31
I mentioned some of this in https://github.com/emberjs/ember.js/pull/14410#issuecomment-251687821, but I think having a way to absorb the difference (between per object and per property invalidation) would definitely be useful. The bet that we are making with Glimmer 2 is that tracking all individual properties for changes is actually more costly than recomputing.  We just need an escape hatch if that isn't the case (for targeted scenarios).

**Comment by stefanpenner** [comment] 2016-10-12 17:57
may be related to the fixes happening [here](https://github.com/emberjs/ember.js/tree/finer-grained-experiment)  (@krisselden mentioned this to me)

**Comment by kanongil** [comment] 2016-10-13 09:37
@stefanpenner While #14461 fixes most of the performance regressions I have experienced, it doesn't fix this specific issue.

**Comment by chancancode** [comment] 2016-10-27 22:56
@scottmessinger @kanongil I believe this is fixed now – the twiddle now works as expected. If you think I am wrong please let me know and I can reopen.

**Closed by chancancode** 2016-10-27 22:56 UTC
Labels: Glimmer2

**Comment by scottmessinger** [comment] 2016-10-28 01:20
@chancancode It works!!! Thanks so much!
