### ISSUE TITLE
Nesting `loading` under application doesn't work

### ISSUE THREAD

**Issue by batjaa** [emberjs/ember.js#13053] opened 2016-03-04 19:09 UTC
As the title says, having `application/loading/template.hbs` is not working but `application-loading/template.hbs` does. According to the docs routes and loading states can be nested.

**Comment by pixelhandler** [comment] 2016-03-04 20:12
@batjaa can you try to make an ember-twiddle.com example showing the loading not working? See the lookup conventions for the loading template here -> https://guides.emberjs.com/v2.4.0/routing/loading-and-error-substates/#toc_code-loading-code-substates

**Comment by batjaa** [comment] 2016-03-04 20:43
- [ ] application/loading/template.hbs - https://ember-twiddle.com/248ff8e9332f02fcbd45?openFiles=application.loading.template.hbs%2C

- [ ] application-loading/template.hbs - https://ember-twiddle.com/248ff8e9332f02fcbd45?openFiles=application.route.js%2C

**Comment by nathanhammond** [comment] 2016-03-08 00:49
Can confirm that this is an issue. Reproduction for both error and loading substates:
https://github.com/nathanhammond/error-loading-test

Working on a resolution now.

**Comment by nathanhammond** [comment] 2016-03-08 05:24
Okay, I have no idea what's going on here. I could reproduce it, and then I couldn't. If it's useful you can use my linked repo as a starting point for a repro.

**Comment by locks** [comment] 2016-04-15 19:37
@batjaa is your app using pods, like the sample Twiddle? if so, that's part of the "problem", as we don't cover pods in the documentation.

I am closing this issue because it seems to be behaving as expected.
Feel free to re-open the issue if you think it's still justified, thank you.

**Closed by locks** 2016-04-15 19:37 UTC

**Comment by batjaa** [comment] 2016-04-16 18:12
Fair enough, anyone who stops by this post, use `...-loading` naming convention.
