### ISSUE TITLE
npm start error - Developing on Ember master (linked locally)

### ISSUE THREAD

**Issue by jimbeaudoin** [emberjs/ember.js#10749] opened 2015-03-28 18:28 UTC
### The Steps

```sh
(master)jim@jim-hp:dev$ git clone git@github.com:emberjs/ember.js
(master)jim@jim-hp:dev$ cd ember.js
(master)jim@jim-hp:ember.js$ npm link ember-cli
(master)jim@jim-hp:ember.js$ ember -v
version: 0.2.1-master-61fa7429d5
node: 0.12.1
npm: 2.7.3
(master)jim@jim-hp:ember.js$ npm install
npm WARN package.json ember@1.12.0-beta.1+canary No repository field.
|
> ember@1.12.0-beta.1 postinstall /home/jim/dev/ember.js
> bower install

bower cached        https://github.com/ebryn/backburner.js.git#f4bd6a2df2
bower validate      f4bd6a2df2 against https://github.com/ebryn/backburner.js.git#f4bd6a2df221240ed36d140f0c53c036a7ecacad
bower cached        https://github.com/tildeio/rsvp.js.git#3.0.14
bower validate      3.0.14 against https://github.com/tildeio/rsvp.js.git#3.0.14
bower cached        https://github.com/tildeio/router.js.git#ed45bc5c5e
bower validate      ed45bc5c5e against https://github.com/tildeio/router.js.git#ed45bc5c5e055af0ab875ef2c52feda792ee23e4
bower cached        https://github.com/krisselden/dag-map.git#e307363256
bower validate      e307363256 against https://github.com/krisselden/dag-map.git#e307363256fe918f426e5a646cb5f5062d3245be
bower cached        https://github.com/emberjs/ember-dev.git#1a1ef3e180
bower validate      1a1ef3e180 against https://github.com/emberjs/ember-dev.git#1a1ef3e1806be21dd554d285521abc0b13cdfe20
bower cached        git://github.com/jonkemp/qunit-phantomjs-runner.git#1.2.0
bower validate      1.2.0 against git://github.com/jonkemp/qunit-phantomjs-runner.git#1.2.0
bower cached        git://github.com/jquery/qunit.git#1.17.1
bower validate      1.17.1 against git://github.com/jquery/qunit.git#~1.17.1
bower cached        git://github.com/jquery/jquery.git#1.11.2
bower validate      1.11.2 against git://github.com/jquery/jquery.git#~1.11.1
bower install       backburner#f4bd6a2df2
bower install       router.js#ed45bc5c5e
bower install       dag-map#e307363256
bower install       ember-dev#1a1ef3e180
bower install       qunit-phantom-runner#1.2.0
bower install       qunit#1.17.1
bower install       jquery#1.11.2
bower install       rsvp#3.0.14

backburner#f4bd6a2df2 bower_components/backburner

router.js#ed45bc5c5e bower_components/router.js

dag-map#e307363256 bower_components/dag-map

ember-dev#1a1ef3e180 bower_components/ember-dev

qunit-phantom-runner#1.2.0 bower_components/qunit-phantom-runner

qunit#1.17.1 bower_components/qunit

jquery#1.11.2 bower_components/jquery

rsvp#3.0.14 bower_components/rsvp
npm WARN unmet dependency /home/jim/dev/ember.js/node_modules/ember-cli/node_modules/bower requires rimraf@'~2.2.0' but will load
npm WARN unmet dependency /home/jim/dev/ember.js/node_modules/ember-cli/node_modules/rimraf,
npm WARN unmet dependency which is version 2.3.2
npm WARN unmet dependency /home/jim/dev/ember.js/node_modules/ember-cli/node_modules/quick-temp requires rimraf@'~2.2.6' but will load
npm WARN unmet dependency /home/jim/dev/ember.js/node_modules/ember-cli/node_modules/rimraf,
npm WARN unmet dependency which is version 2.3.2
npm WARN unmet dependency /home/jim/dev/ember.js/node_modules/ember-cli/node_modules/temp requires rimraf@'~2.2.6' but will load
npm WARN unmet dependency /home/jim/dev/ember.js/node_modules/ember-cli/node_modules/rimraf,
npm WARN unmet dependency which is version 2.3.2
npm WARN unmet dependency /home/jim/dev/ember.js/node_modules/ember-cli/node_modules/ember-cli-ncp requires mocha@'^1.15.1' but will load
npm WARN unmet dependency /home/jim/dev/ember.js/node_modules/ember-cli/node_modules/mocha,
npm WARN unmet dependency which is version 2.2.1
npm WARN unmet dependency /home/jim/dev/ember.js/node_modules/ember-cli/node_modules/bower/node_modules/bower-registry-client requires rimraf@'~2.2.0' but will load
npm WARN unmet dependency /home/jim/dev/ember.js/node_modules/ember-cli/node_modules/rimraf,
npm WARN unmet dependency which is version 2.3.2
qunit-extras@1.4.1 node_modules/qunit-extras

ember-publisher@0.0.7 node_modules/ember-publisher

qunitjs@1.17.1 node_modules/qunitjs

route-recognizer@0.1.5 node_modules/route-recognizer

chalk@0.5.1 node_modules/chalk
├── ansi-styles@1.1.0
├── escape-string-regexp@1.0.3
├── supports-color@0.2.0
├── strip-ansi@0.3.0 (ansi-regex@0.2.1)
└── has-ansi@0.1.0 (ansi-regex@0.2.1)

simple-dom@0.1.3 node_modules/simple-dom

ember-cli-dependency-checker@0.0.7 node_modules/ember-cli-dependency-checker
└── semver@4.3.3

glob@4.3.5 node_modules/glob
├── inherits@2.0.1
├── once@1.3.1 (wrappy@1.0.1)
├── inflight@1.0.4 (wrappy@1.0.1)
└── minimatch@2.0.4 (brace-expansion@1.1.0)

express@4.12.3 node_modules/express
├── merge-descriptors@1.0.0
├── utils-merge@1.0.0
├── cookie-signature@1.0.6
├── methods@1.1.1
├── cookie@0.1.2
├── fresh@0.2.4
├── escape-html@1.0.1
├── range-parser@1.0.2
├── content-type@1.0.1
├── finalhandler@0.3.4
├── vary@1.0.0
├── parseurl@1.3.0
├── serve-static@1.9.2
├── content-disposition@0.5.0
├── path-to-regexp@0.1.3
├── depd@1.0.0
├── qs@2.4.1
├── on-finished@2.2.0 (ee-first@1.1.0)
├── debug@2.1.3 (ms@0.7.0)
├── etag@1.5.1 (crc@3.2.1)
├── send@0.12.2 (destroy@1.0.3, ms@0.7.0, mime@1.3.4)
├── proxy-addr@1.0.7 (forwarded@0.1.0, ipaddr.js@0.1.9)
├── accepts@1.2.5 (negotiator@0.5.1, mime-types@2.0.10)
└── type-is@1.6.1 (media-typer@0.3.0, mime-types@2.0.10)

github@0.2.3 node_modules/github

rsvp@3.0.18 node_modules/rsvp

htmlbars@0.11.2 node_modules/htmlbars

aws-sdk@2.1.20 node_modules/aws-sdk
├── xmlbuilder@0.4.2
└── xml2js@0.2.6 (sax@0.4.2)

bower@1.3.12 node_modules/bower
├── is-root@1.0.0
├── junk@1.0.1
├── stringify-object@1.0.1
├── which@1.0.9
├── chmodr@0.1.0
├── abbrev@1.0.5
├── osenv@0.1.0
├── archy@0.0.2
├── opn@1.0.1
├── rimraf@2.2.8
├── bower-logger@0.2.2
├── lru-cache@2.5.0
├── bower-endpoint-parser@0.2.2
├── graceful-fs@3.0.6
├── lockfile@1.0.0
├── nopt@3.0.1
├── retry@0.6.0
├── tmp@0.0.23
├── q@1.0.1
├── request-progress@0.3.0 (throttleit@0.0.2)
├── chalk@0.5.0 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
├── shell-quote@1.4.3 (array-filter@0.0.1, array-map@0.0.0, array-reduce@0.0.0, jsonify@0.0.0)
├── bower-json@0.4.0 (intersect@0.0.3, deep-extend@0.2.11, graceful-fs@2.0.3)
├── semver@2.3.2
├── fstream@1.0.4 (inherits@2.0.1)
├── p-throttler@0.1.0 (q@0.9.7)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── promptly@0.2.0 (read@1.0.5)
├── bower-config@0.5.2 (osenv@0.0.3, graceful-fs@2.0.3, optimist@0.6.1)
├── fstream-ignore@1.0.2 (inherits@2.0.1, minimatch@2.0.4)
├── tar-fs@0.5.2 (pump@0.3.5, tar-stream@0.4.7)
├── decompress-zip@0.0.8 (nopt@2.2.1, mkpath@0.1.0, touch@0.0.2, readable-stream@1.1.13, binary@0.3.0)
├── request@2.42.0 (caseless@0.6.0, json-stringify-safe@5.0.0, forever-agent@0.5.2, aws-sign2@0.5.0, stringstream@0.0.4, oauth-sign@0.4.0, tunnel-agent@0.4.0, qs@1.2.2, node-uuid@1.4.3, mime-types@1.0.2, form-data@0.1.4, bl@0.9.4, http-signature@0.10.1, tough-cookie@0.12.1, hawk@1.1.1)
├── glob@4.0.6 (inherits@2.0.1, once@1.3.1, minimatch@1.0.0)
├── bower-registry-client@0.2.4 (graceful-fs@2.0.3, request-replay@0.2.0, lru-cache@2.3.1, async@0.2.10, mkdirp@0.3.5, request@2.51.0)
├── cardinal@0.4.0 (redeyed@0.4.4)
├── mout@0.9.1
├── update-notifier@0.2.0 (semver-diff@0.1.0, string-length@0.1.2, latest-version@0.2.0, configstore@0.3.2)
├── handlebars@2.0.0 (optimist@0.3.7, uglify-js@2.3.6)
├── inquirer@0.7.1 (figures@1.3.5, mute-stream@0.0.4, through@2.3.6, readline2@0.1.1, lodash@2.4.1, cli-color@0.3.3, rx@2.4.7)
└── insight@0.4.3 (object-assign@1.0.0, chalk@0.5.1, async@0.9.0, lodash.debounce@2.4.1, os-name@1.0.3, tough-cookie@0.12.1, configstore@0.3.2, inquirer@0.6.0)

ember-cli-yuidoc@0.4.0 node_modules/ember-cli-yuidoc
├── git-repo-version@0.0.1 (git-repo-info@1.0.2)
├── rsvp@3.0.14
├── broccoli-merge-trees@0.2.1 (promise-map-series@0.2.1, symlink-or-copy@1.0.1, broccoli-writer@0.1.1)
├── broccoli-caching-writer@0.5.5 (core-object@0.0.3, promise-map-series@0.2.1, symlink-or-copy@1.0.1, debug@2.1.3, rimraf@2.3.2, broccoli-kitchen-sink-helpers@0.2.6, quick-temp@0.1.2, lodash-node@2.4.1)
└── yuidocjs@0.5.0 (graceful-fs@2.0.3, marked@0.3.3, minimatch@2.0.4, rimraf@2.3.2, yui@3.18.1)

emberjs-build@0.0.43 node_modules/emberjs-build
├── core-object@0.0.4
├── js-string-escape@1.0.0
├── broccoli-string-replace@0.0.2
├── broccoli-use-strict-remover@1.0.1
├── git-repo-version@0.1.2 (git-repo-info@1.0.4)
├── broccoli-funnel@0.1.7 (core-object@0.0.2, walk-sync@0.1.3, symlink-or-copy@1.0.1, mkdirp@0.5.0, minimatch@2.0.4, rimraf@2.3.2)
├── broccoli-kitchen-sink-helpers@0.2.6 (mkdirp@0.3.5, glob@4.0.4)
├── broccoli-stew@0.1.8 (walk-sync@0.1.3, debug@2.1.3, minimatch@2.0.4, fs-extra@0.13.0)
├── es6-module-transpiler@0.4.0 (through@2.3.6, optimist@0.3.7)
├── broccoli-file-creator@0.1.0 (broccoli-writer@0.1.1)
├── broccoli-filter@0.1.12 (broccoli-writer@0.1.1, promise-map-series@0.2.1, walk-sync@0.1.3, mkdirp@0.3.5, quick-temp@0.1.2)
├── broccoli-merge-trees@0.2.1 (promise-map-series@0.2.1, symlink-or-copy@1.0.1, broccoli-writer@0.1.1)
├── broccoli-es6-module-transpiler@0.1.1 (broccoli-filter@0.1.6)
├── esperanto@0.6.22 (minimist@1.1.1, chalk@1.0.0, magic-string@0.4.6, sander@0.2.2, acorn@1.0.1)
├── broccoli-uglify-sourcemap@0.2.1 (source-map-url@0.3.0, walk-sync@0.1.3, symlink-or-copy@1.0.1, mkdirp@0.5.0, broccoli-writer@0.1.1, uglify-js@2.4.17)
├── broccoli-sourcemap-concat@0.4.3 (combined-stream@0.0.7, mkdirp@0.5.0, broccoli-writer@0.1.1, broccoli-caching-writer@0.5.3, fast-sourcemap-concat@0.2.3)
├── broccoli-defeatureify@1.0.0 (defeatureify@0.2.2)
├── lodash-node@2.4.1
├── broccoli-jshint@0.5.5 (chalk@0.4.0, mkdirp@0.4.2, findup-sync@0.1.3, jshint@2.6.3)
├── broccoli@0.13.3 (broccoli-slow-trees@1.1.0, copy-dereference@1.0.0, promise-map-series@0.2.1, mime@1.3.4, commander@2.7.1, connect@3.3.5, tiny-lr@0.1.5, findup-sync@0.1.3, handlebars@2.0.0)
├── broccoli-derequire@0.1.0 (derequire@2.0.0)
├── broccoli-jscs@0.0.20 (path@0.11.14, ember-cli-version-checker@1.0.2, minimatch@2.0.4, broccoli-static-compiler@0.2.1, jscs@1.12.0)
├── babel-core@4.7.16 (slash@1.0.0, to-fast-properties@1.0.1, shebang-regex@1.0.0, trim-right@1.0.0, path-is-absolute@1.0.0, fs-readdir-recursive@0.1.1, leven@1.0.1, private@0.1.6, globals@6.4.1, esutils@1.1.6, estraverse@1.9.3, convert-source-map@0.5.1, js-tokens@1.0.0, line-numbers@0.2.0, commander@2.7.1, chalk@1.0.0, debug@2.1.3, is-integer@1.0.4, ast-types@0.7.2, detect-indent@3.0.1, repeating@1.1.2, output-file-sync@1.1.0, acorn-babel@0.11.1-38, source-map@0.4.2, source-map-support@0.2.10, core-js@0.6.1, regexpu@1.1.2, regenerator-babel@0.8.13-2, lodash@3.6.0)
├── broccoli-es3-safe-recast@1.0.0 (es3-safe-recast@1.0.0)
└── ember-cli-yuidoc@0.3.1 (git-repo-version@0.0.1, rsvp@3.0.14, broccoli-caching-writer@0.5.5, yuidocjs@0.3.50)
```
### The Error
```sh
(master)jim@jim-hp:ember.js$ npm start

> ember@1.12.0-beta.1 start /home/jim/dev/ember.js
> ember serve

version: 0.2.1-master-61fa7429d5
Cannot convert a Symbol value to a string
TypeError: Cannot convert a Symbol value to a string
    at RegExp.test (native)
    at Symbol.hasOwnProperty (/home/jim/dev/ember.js/node_modules/emberjs-build/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:163:43)
    at /home/jim/dev/ember.js/node_modules/emberjs-build/node_modules/babel-core/node_modules/core-js/library.js:133:17
    at setToStringTag (/home/jim/dev/ember.js/node_modules/emberjs-build/node_modules/babel-core/node_modules/core-js/library.js:89:13)
    at /home/jim/dev/ember.js/node_modules/emberjs-build/node_modules/babel-core/node_modules/core-js/library.js:652:3
    at /home/jim/dev/ember.js/node_modules/emberjs-build/node_modules/babel-core/node_modules/core-js/library.js:673:2
    at Object.<anonymous> (/home/jim/dev/ember.js/node_modules/emberjs-build/node_modules/babel-core/node_modules/core-js/library.js:2339:2)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

npm ERR! Linux 3.16.0-33-generic
npm ERR! argv "/home/jim/.nvm/versions/node/v0.12.1/bin/node" "/home/jim/.nvm/versions/node/v0.12.1/bin/npm" "start"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! ember@1.12.0-beta.1 start: `ember serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ember@1.12.0-beta.1 start script 'ember serve'.
npm ERR! This is most likely a problem with the ember package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ember serve
npm ERR! You can get their info via:
npm ERR!     npm owner ls ember
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jim/dev/ember.js/npm-debug.log

```

### The NPM Debug Log
```sh
0 info it worked if it ends with ok
1 verbose cli [ '/home/jim/.nvm/versions/node/v0.12.1/bin/node',
1 verbose cli   '/home/jim/.nvm/versions/node/v0.12.1/bin/npm',
1 verbose cli   'start' ]
2 info using npm@2.5.1
3 info using node@v0.12.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart ember@1.12.0-beta.1
6 info start ember@1.12.0-beta.1
7 verbose unsafe-perm in lifecycle true
8 info ember@1.12.0-beta.1 Failed to exec start script
9 verbose stack Error: ember@1.12.0-beta.1 start: `ember serve`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/home/jim/.nvm/versions/node/v0.12.1/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/home/jim/.nvm/versions/node/v0.12.1/lib/node_modules/npm/lib/utils/spawn.js:14:12)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1008:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
10 verbose pkgid ember@1.12.0-beta.1
11 verbose cwd /home/jim/dev/ember.js
12 error Linux 3.16.0-33-generic
13 error argv "/home/jim/.nvm/versions/node/v0.12.1/bin/node" "/home/jim/.nvm/versions/node/v0.12.1/bin/npm" "start"
14 error node v0.12.1
15 error npm  v2.5.1
16 error code ELIFECYCLE
17 error ember@1.12.0-beta.1 start: `ember serve`
17 error Exit status 1
18 error Failed at the ember@1.12.0-beta.1 start script 'ember serve'.
18 error This is most likely a problem with the ember package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     ember serve
18 error You can get their info via:
18 error     npm owner ls ember
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

```

**Comment by rwjblue** [comment] 2015-03-28 18:35
I am unsure what you are shooting for (why link ember-cli locally to work on Ember itself?), but this error is caused by using a newer Node than v0.10.  

This is a duplicate of https://github.com/emberjs/ember.js/issues/10674, getting it fixed is being tracked in https://github.com/emberjs/emberjs-build/issues/87.

**Closed by rwjblue** 2015-03-28 18:35 UTC

**Comment by jimbeaudoin** [comment] 2015-03-28 18:44
Because I was looking to work with the latest version of the CLI & the latest version of ember linked locally inside my project. I can git pull to update and use the latest version for my project. Anyway, thanks for your time.

**Comment by rwjblue** [comment] 2015-03-28 18:47
No problem!  I have a gist that I generally point to folks on using the latest builds of Ember in an ember-cli project, maybe it will help..

https://gist.github.com/rwjblue/9216101d3d15a9134bdd

**Comment by jimbeaudoin** [comment] 2015-03-28 18:51
:smile: This is what I was trying to follow but I was not aware about the node v0.10 requirement. Thank You & Keep the Good Work!
