### ISSUE TITLE
{{#each}} param names conflict with HTML tag names

### ISSUE THREAD

**Issue by vasilionjea** [emberjs/ember.js#17420] opened 2019-01-02 05:51 UTC
Not sure if this is a known issue but param names in the `{{#each}}` helper seem to conflict with HTML tag names. 

Here is an example (_open dev tools_): 
https://ember-twiddle.com/68d14f783933489680e3b7faecb83290?openFiles=templates.application.hbs

- `ember-source: ~3.6.0`
- `ember-cli-htmlbars: ^3.0.0`

**Comment by chancancode** [comment] 2019-01-02 06:02
This is “expected” in that it should be _legal_ to yield a single contextual component, name it `button` and try to invoke it with angle brackets in the block. However:

- it’s a bad idea to name components like that with lower case names and should be linted against by default

- the error message need to be much better (something like the value of `button` is not a component)

In your case, since you’re not trying to yield components, you should rename the block param.

See https://github.com/emberjs/rfcs/blob/master/text/0311-angle-bracket-invocation.md#dynamic-invocations

**Comment by rwjblue** [comment] 2019-01-02 15:41
Closing as a duplicate of https://github.com/emberjs/ember.js/issues/16826. Specifically see https://github.com/emberjs/ember.js/issues/16826#issuecomment-408504435 for the current status.

**Closed by rwjblue** 2019-01-02 15:41 UTC
