### ISSUE TITLE
classNames on components output class twice in DOM (1.13.8)

### ISSUE THREAD

**Issue by stacylondon** [emberjs/ember.js#12146] opened 2015-08-19 13:08 UTC
When you set classNames on a component they are being output twice in the DOM in 1.13.8.  Here is a jsbin with an example:
http://emberjs.jsbin.com/tiruwo/edit?html,css,js,output

Expected DOM
`[..] class="ember-view default-class special-class" [..]`

Generated DOM
`[..] class="special-class ember-view default-class special-class" [..]`

**Comment by fpauser** [comment] 2015-08-19 13:28
This is a duplicate of #11600, the failing test is here: #11609

**Comment by rwjblue** [comment] 2015-08-19 14:43
@fpauser - Thanks for linking! I'm going to take a look at that failing test now...

**Closed** 2015-08-23 14:17 UTC
