### ISSUE TITLE
[Bug] Silent failure in router when transitioning w/o providing model

### ISSUE THREAD

**Issue by mike-north** [emberjs/ember.js#10926] opened 2015-04-22 07:37 UTC
Example w/ canary: http://emberjs.jsbin.com/gefazesago/19/

In this scenario, I'm making the mistake of attempting to transition to a route with a dynamic segment, without providing a record or id as a second argument to `this.transitionTo`. The bug I'm reporting is that **no errors are logged, no promises are rejected, etc... so there's no clear feedback to the developer of where the failure happened** 

### Instructions to reproduce succeeding path:
* Go to http://emberjs.jsbin.com/gefazesago/19/
* click "Fruit". Your URL should now be `/list/1`
* click "New Item". You will find yourself at the URL `/list/1/items/new`
* click "Good Cancel"

You will find yourself back at the list of items, with the correct URL
`/list/1`

### Instructions to reproduce failing path:
* Go to http://emberjs.jsbin.com/gefazesago/19/
* click "Fruit". Your URL should now be `/list/1`
* click "New Item". You will find yourself at the URL `/list/1/items/new`
* click "Bad Cancel"

You will find yourself still at the "New Item" page, but the URL will now be `/list/1`. 
The Ember inspector will also indicate multiple leaf-level "current" routes
![screen shot 2015-04-22 at 12 33 25 am](https://cloud.githubusercontent.com/assets/558005/7269271/46eb6cec-e887-11e4-8079-2cc401374a50.png)

The difference between these two actions, is that one fails to pass the required model (or id) to populate the destination route path's dynamic segment.
```js
    cancelItemCreate_bad: function () {
      this.transitionTo('list.items');
    },
    cancelItemCreate_good: function () {
      this.transitionTo('list.items', this.get('currentModel.list'));
    }
```

**Comment by stefanpenner** [comment] 2015-04-22 10:39
cc @machty

**Comment by richmolj** [comment] 2015-07-26 16:45
Following up here, turns out the referenced issue does not fix this (though would have been needed as step 1). The original jsbin no longer works, [here is an updated one](http://emberjs.jsbin.com/webuqi/1).

I spent a little time trying to figure this out. I'm quite new to Ember so take the below with a grain of salt.

* `transitionTo` delegates to [here](https://github.com/tildeio/router.js/blob/ed45bc5c5e055af0ab875ef2c52feda792ee23e4/lib/router/router.js#L220) in the [router.js](https://github.com/tildeio/router.js) microlib.
* `TransitionTo` hits `doTransition` which hits [transitionByIntent](https://github.com/tildeio/router.js/blob/ed45bc5c5e055af0ab875ef2c52feda792ee23e4/lib/router/router.js#L144-L150). Note the `catch` here.
* `TransitionByIntent` hits `applyState` on a `TransitionIntent` object, for our example a `NamedTransitionIntent`. `applyToState` calls `applyToHandlers` and finally `getHandlerInfoForDynamicSegment`.
* This example would now [purposefully not throw an error](https://github.com/tildeio/router.js/blob/ed45bc5c5e055af0ab875ef2c52feda792ee23e4/lib/router/transition-intent/named-transition-intent.js#L142-L149). For convenience, here is the comment:

  > Ideally we should throw this error to provide maximal information to the user that not enough context objects were provided, but this proves too cumbersome in Ember in cases where inner template helpers are evaluated before parent helpers un-render, in which cases this error somewhat prematurely fires.

What this boils down to: router.js is purposefully not throwing an error here. But even if it was, the `catch` in `transitionByIntent` would swallow it. This is still slightly better since you can now see the rejected promise error, i.e.

```javascript
transitionTo('showPost').catch(function(e) {
  // has the helpful error
}
```

This may also eventually be complicated if [optional segments for routes](https://github.com/tildeio/router.js/issues/102) becomes a thing.

For reference, here's a failing test for router.js:

```javascript
test("Handling a transition that is missing required context", function() {
  throws(function() {
    router.transitionTo('showPost');
  }, /Not enough context/);
});
```

I think that's about as helpful as I'm going to be. Humble suggestion:

* Move this issue to router.js, or possibly [route-recognizer](https://github.com/tildeio/route-recognizer)
* Change that repo to throw the error. To avoid the issue noted in the comment, maybe handle this in `link-to` (?)

I'll leave it to someone who knows more than me if the above is a good idea or not.

**Comment by stefanpenner** [comment] 2015-07-26 17:00
@machty can you take a look?

**Comment by rwjblue** [comment] 2015-08-16 21:49
I believe a fix to this landed in https://github.com/emberjs/ember.js/pull/10688 (which will be in 2.1.0), but the JSBin in the issue description isn't runnable (due to Ember Data canary no longer having a fixture adapter).  

@mike-north - Can you update the JSBin and/or test to see if this is fixed?

**Comment by locks** [comment] 2016-04-15 10:44
@mike-north poke, can you check if it's fixed? Appreciated :)

**Comment by pixelhandler** [comment] 2016-05-06 17:01
@mike-north I added the label for "Needs Reproduction" since @rwjblue requested.

**Comment by Serabe** [comment] 2016-05-09 21:31
@mike-north can you check the issue in [this twiddle](https://ember-twiddle.com/80b619c899fc6418b04ebc0712bee9e6) is the one you were talking about? Thank you!

**Comment by pixelhandler** [comment] 2016-05-20 16:46
@mike-north ping. Can you update this issue with a reply regarding https://github.com/emberjs/ember.js/issues/10926#issuecomment-131630380

**Comment by pixelhandler** [comment] 2016-05-27 18:02
@mike-north I'll close this for now, please re-open if the issue is reproducible.

**Closed by pixelhandler** 2016-05-27 18:02 UTC
Labels: Needs Reproduction, Needs Submitter Response
