### ISSUE TITLE
object is not extensible 

### ISSUE THREAD

**Issue by amk221** [emberjs/ember.js#12631] opened 2015-11-20 17:28 UTC
I know we should be using Ember Twiddle in general, but shouldn't these work anyway?

http://jsfiddle.net/amk221/ox9n9r01/
http://emberjs.jsbin.com/veriwaneyi/edit?html,js,output

**Comment by rwjblue** [comment] 2015-11-20 17:31
Duplicate of https://github.com/emberjs/ember.js/issues/12623

You have to load ember before the template compiler.

**Closed** 2015-11-20 17:31 UTC
