### ISSUE TITLE
classNameBindings is removing classes added from outside

### ISSUE THREAD

**Issue by alvarocastro** [emberjs/ember.js#17011] opened 2018-09-26 20:07 UTC
When Ember recomputes the classes for a component through the `classNameBindings` attribute, it overwrittes any class added from outside, for example added by jQuery directly to the element.

I suppose the problem happens because Ember doen't know about the classes added and just ignores them.

I put up a twiddle with a [minimal working example of the problem here](https://ember-twiddle.com/24fe3f55d791e9aa991f68024b90df73?numColumns=2&openFiles=components.x-example.js%2Ctemplates.application.hbs).

I'm using version 3.1.4.

**Comment by rwjblue** [comment] 2018-09-26 20:13
I'm sorry, but I believe that things are working as designed here. Ember is specifically ensuring the classes on the component's root element match what it expects the classes to be. This results in removing classes added by others.

**Comment by pixelhandler** [comment] 2018-10-12 17:44
Perhaps reach out in the #help channel on the Ember Discord app, https://discordapp.com/channels/480462759797063690/483601670685720591 or on the forum, https://discuss.emberjs.com/

I'll close this for now, since it's not an Ember bug.

**Closed by pixelhandler** 2018-10-12 17:44 UTC
