### ISSUE TITLE
Single function getter/setter deprecation warning should show where

### ISSUE THREAD

**Issue by flyswatter** [emberjs/ember.js#11184] opened 2015-05-16 01:58 UTC
Trying to update to ember 1.10, I'm getting a warning:
```
DEPRECATION: Using the same function as getter and setter is deprecated. See http://emberjs.com/deprecations/v1.x/#toc_computed-properties-with-a-shared-getter-and-setter for more details.
```
And it's pretty frustrating, because I don't know where exactly the offending code is!  For all I know, it's in one of the ember-addons I'm depending on.  The call stack isn't any more help.  This would be a great warning to improve.

**Comment by rwjblue** [comment] 2015-05-18 04:52
Closing as a duplicate of https://github.com/emberjs/ember.js/issues/11048.

**Closed by rwjblue** 2015-05-18 04:52 UTC
