### ISSUE TITLE
`{{action preventDefault=preventProperty}}` doesn't work.

### ISSUE THREAD

**Issue by mdebbar** [emberjs/ember.js#13062] opened 2016-03-07 18:46 UTC
We're using Ember 1.13. The action takes a `preventDefault` property but it only works with literal value (`true` and `false`). But if I try to pass another property, it always prevents default.

Here is a [jsfiddle](http://jsfiddle.net/6Evrq/849/) that reproduces the issue.

**Comment by fivetanley** [comment] 2016-03-08 15:34
Hi! Thanks for opening an issue.

The reason this doesn't work is because your template's scope is the controller. Even though you don't have an `IndexController` defined, Ember generates one for you. It doesn't have access to properties in the route. If you add an `IndexController` and move the `prevent` property there, it works. I modified your jsbin [here](http://jsfiddle.net/z0yv757j/), showing this solution as a working one.

Thanks!

**Comment by mdebbar** [comment] 2016-03-08 17:44
I'm sorry but your jsbin still doesn't work. When I click on the second link, it doesn't follow the href.

**Comment by fivetanley** [comment] 2016-03-08 17:51
Ah yup, I misread entirely.

**Comment by jleppert** [comment] 2016-03-08 17:53
I can confirm I've also experienced this issue.

**Comment by fivetanley** [comment] 2016-03-08 18:24
Talking with @mmun in chat, it looks like this needs to be decoded through a `read` function (I'll try to find that in a bit). Right now, the value of `helper.preventDefault` [on this line](https://github.com/emberjs/ember.js/blob/27862a18b8773e57c52dbc7141b1f92a505f16ff/packages/ember-routing-htmlbars/lib/keywords/element-action.js#L53) in is this:

![image showing preventDefault is a KeyStream instead of value](https://dl.dropboxusercontent.com/s/forxrenjawo16j3/2016-03-08%20at%2012.22%20PM.png)

It should be `false` instead of the `KeyStream` object.

**Comment by mdebbar** [comment] 2016-03-08 18:50
Thanks @fivetanley. I was trying to debug this yesterday, and that's exactly what I found out. Ember is not resolving the computed property before comparing to `false`.

**Comment by rwjblue** [comment] 2016-03-08 18:56
All of those hash args should be `read`.

**Comment by fivetanley** [comment] 2016-03-08 18:57
yup, workin' on it :+1:

**Comment by Serabe** [comment] 2016-04-10 22:08
This was fixed and merged in #12764 on January but it was not backported. Should be easy to do, though.

**Comment by rwjblue** [comment] 2016-04-10 22:12
@Serabe - Ya, I believe that https://github.com/emberjs/ember.js/pull/13066 is exactly that.

**Comment by rwjblue** [comment] 2016-04-22 17:02
Closing in favor of https://github.com/emberjs/ember.js/pull/13066

**Closed by rwjblue** 2016-04-22 17:02 UTC
