### ISSUE TITLE
Instance Initializers container lookup yield as undefined (beta 2.0)

### ISSUE THREAD

**Issue by iamjstates** [emberjs/ember.js#11444] opened 2015-06-14 20:24 UTC
/app/instance-initalizer/session.js

<code>
export default{
    name: 'session',
    initialize: function(instance) {

        var container = instance.container,
            registry = instance.registry;

        console.log('service', container.lookup('service:store'));
        console.log('container (5)', container.lookup('controller:sessions'));
</code>

This currently displays all but 'application:main' as undefined - is this as designed? I can not lookup controllers anymore.

If this is as designed how can I lookup controllers in initializers?

**Comment by rwjblue** [comment] 2015-08-20 02:28
Seems to be working properly: 

* 1.13.8 - http://rwjblue.jsbin.com/nogupec/1/edit?html,js,output
* 2.0.0 - http://rwjblue.jsbin.com/henoya/edit?html,js,output
* 2.1.0-beta.1 - http://rwjblue.jsbin.com/cifipa/edit?html,js,output

Closing for now, but I can reopen with a fuller reproduction against current versions.

**Closed by rwjblue** 2015-08-20 02:28 UTC
