### ISSUE TITLE
`<a>` within a `<form>` with an `action` triggers action, ignores `href`

### ISSUE THREAD

**Issue by seanpdoyle** [emberjs/ember.js#10978] opened 2015-04-28 19:40 UTC
http://emberjs.jsbin.com/vobivebiju/1/edit?html,js

In my particular use case, the `href` links elsewhere (i.e. isn't from a `{{link-to}}`.

Clicking the `<a href>` triggers the `<form>`'s action instead of navigating the browser.

**Comment by seanpdoyle** [comment] 2015-04-28 19:40
cc: @rwjblue @stefanpenner

**Comment by clekstro** [comment] 2015-05-04 02:26
@seanpdoyle I think you're simply missing a constraint on the action, namely that the action is only triggered on `submit`:

```html
<form {{action "log" on="submit"}}>
    <ul>
    {{#each model as |item|}}
      <li>
        <a href="{{item.url}}">{{item.name}}</a>
      </li>
    {{/each}}
    </ul>
</form>
```

**Comment by clekstro** [comment] 2015-05-12 23:27
@seanpdoyle Here's a [link](http://emberjs.jsbin.com/cuyubosote/1/edit?html,js,output) to a working JSBin.  I think this can be closed.

**Comment by seanpdoyle** [comment] 2015-05-13 01:26
@clekstro I understand that there needs to be an `on="submit"`.

http://guides.emberjs.com/v1.10.0/components/sending-actions-from-components-to-your-application/ doesn't mention that its required, so the fix might be to make it clearer.

My main concern is that `<a>` tags (without `{{action}}`) are being interfered with by the surrounding form / `{{action}}`

**Comment by clekstro** [comment] 2015-05-13 01:48
I'd be lying if I said this hasn't bit me in the past. I think some clarification in the docs would be great :+1:.

The way I've tried to reason about it is that Ember can't know that you don't want to trigger an event on an element that wraps other elements without triggering that containing element's `{{action}}` unless you specify a scope, or if those elements themselves define actions.  In your example, for instance, aren't you clicking the form as well? 

That said, I'd agree that in this case it isn't necessarily intuitive that an `{{action}}` of a parent element be called by default -- especially when it impacts the native behavior of children tags.  Maybe the disconnect is that we don't typically "click" forms, but "submit" them?

Sorry for suggesting you close this if you're only looking for clarification as to what the expected behavior is in cases like this...

**Comment by acorncom** [comment] 2016-04-15 04:41
@seanpdoyle Based on what I'm seeing here, looks like this is more of a documentation issue than a functionality problem?  If so, the guides have undergone a major revamp since you sent this in. If the guides still aren't clear on this particular issue, would you mind opening a new issue in http://github.com/emberjs/guides ? I'd be happy to work through how we should handle that with you there.

Will close this issue now to help reduce the active issues here.  If I got that wrong, let me know and we can re-open here.

**Closed by acorncom** 2016-04-15 04:41 UTC
