### ISSUE TITLE
Ember.inject.service doesnt respect singleton flag

### ISSUE THREAD

**Issue by Orgil** [emberjs/ember.js#12284] opened 2015-09-03 06:08 UTC
I have a singleton service which is instantiated by initializer with singleton flag. inside component i can't get singleton service instead it gives me new instance when i use Ember.inject.service.

**Comment by rwjblue** [comment] 2015-09-03 11:18
Services in general are singleton by default, so I would expect there to only be a single instance.

Can you share a reproduction JSBin or ember-twiddle?

**Comment by Orgil** [comment] 2015-09-04 01:01
Here is jsbin.

https://emberjs.jsbin.com/josilaguha/edit?html,js,console,output

**Comment by pixelhandler** [comment] 2015-09-04 19:05
@Orgil @rwjblue Yeah this appears problematic I cloned the jsbin example and also logged equality check. https://emberjs.jsbin.com/sevejo/4/edit?js,console

The injected service instance is not the same as the service found via container lookup.

**Comment by Orgil** [comment] 2015-09-07 13:00
it is possible to set array as property without init but due to array nature itself its shared between instance.

**Comment by thriqon** [comment] 2015-09-27 22:10
I'm not sure this is indeed a bug. As far as I can see you are re-registering the service class with a different name in the registry, and then fetching an instance of each, respectively. However, from the point of view of the container these instances (plural) are each singletons in the scope of their *own* name.

See this JSBin: http://emberjs.jsbin.com/lubasu/1/edit?js,console,output

**Comment by Orgil** [comment] 2015-09-28 03:12
@thriqon I don't know if it is intended but it should be documented if it is intended behavior. My whole point is I can't access singleton instance through Ember.inject even i passed registry name to it. It always returns new instance. it works if you pull it from the container by name as same as your jsbin.

**Comment by thriqon** [comment] 2015-09-28 09:01
Well, you can access the singleton instance, but you have to use the correct name: `service:auth` ;-)

By registering the service class with a new name you are effectively giving the constructor two names. Each name has its own singleton instance (which I'd intuitively expect).

**Comment by stefanpenner** [comment] 2015-09-28 18:10
> By registering the service class with a new name you are effectively giving the constructor two names. Each name has its own singleton instance (which I'd intuitively expect).

Yes but registering again, you get a whole new thing. This seems to be working as intended, in theory if people want to "alias" to things, we could explore that feature.

Anyways, closing this as it appears to be working as expected.

**Closed by stefanpenner** 2015-09-28 18:10 UTC
