### ISSUE TITLE
[Bug beta] angle bracket invocation incorrectly shadowed by local variable with different case

### ISSUE THREAD

**Issue by chancancode** [emberjs/ember.js#19334] opened 2021-01-12 02:37 UTC
```hbs
<div class="rentals">
  <ul class="results">
    {{#each @model as |rental|}}
      <li><Rental @rental={{rental}} /></li>
    {{/each}}
  </ul>
</div>
```

This template gives the following error:

```
Expected a dynamic component definition, but received an object or function that did not have a component manager associated with it. The dynamic invocation was `<(result of a `unknown` helper)>` or `{{(result of a `unknown` helper)}}`, and the incorrect definition is the value at the path `(result of a `unknown` helper)`, which was: Object
```

The issue is that `<Rental ...>` got incorrectly compiled into a symbol lookup with the same symbol ID as `|rental|`. In other words, the compiler treated the template as if it was this:

```hbs
<div class="rentals">
  <ul class="results">
    {{#each @model as |rental|}}
      <li><rental @rental={{rental}} /></li>
    {{/each}}
  </ul>
</div>
```

Naming the local variable something else that doesn't "conflict" with a component name inside the block fixes the issue. For example, this works:

```hbs
<div class="rentals">
  <ul class="results">
    {{#each @model as |property|}}
      <li><Rental @rental={{property}} /></li>
    {{/each}}
  </ul>
</div>
```

**Comment by chancancode** [comment] 2021-01-12 08:31
This blocks 3.25.0 release cc @kategengler @rwjblue

**Comment by pzuraq** [comment] 2021-01-12 20:00
Fix in the VM: https://github.com/glimmerjs/glimmer-vm/pull/1253

**Comment by pzuraq** [comment] 2021-01-13 18:14
Reopening until the VM update is merged.

**Closed** 2021-01-22 23:31 UTC
Labels: Bug, Regression, Rendering

**Comment by jurgenwerk** [comment] 2023-05-08 19:54
Looks like this is still an issue.  

Can be reproduced with:

```
{{#each this.buttons as |button|}}
{{/each}}
```
