### ISSUE TITLE
Positional rest params don't work as expected for nested closure components

### ISSUE THREAD

**Issue by zackthehuman** [emberjs/ember.js#13742] opened 2016-06-22 20:45 UTC
Consider the following example:

```handlebars
{{component (component 'link-to' 'index')}}
```

This results in an error:

> You must provide one or more parameters to the link-to component.

If you re-write the declaration so that the outer component passes in positional args, then it works:

```handlebars
{{component (component 'link-to') 'index'}}
```

Which differs in behavior from using curried named parameters. I think the issue is here: https://github.com/emberjs/ember.js/blob/master/packages/ember-htmlbars/lib/utils/extract-positional-params.js#L40

```javascript
  // when no params are used, do not override the specified `attrs.stringParamName` value
  if (params.length === 0 && nameInAttrs) {
    return;
  }
```

I think that what we really want is to bail out early if `params.length` is 0, otherwise the condition could be false, which will result in creating a new stream that ultimately returns an empty array. Later the components see this empty array as "no parameters" and they don't work.

**Comment by mixonic** [comment] 2016-06-26 16:54
@Serabe can you take a look here?

**Comment by Serabe** [comment] 2016-06-26 16:57
Assigning this to myself. Thanks for mentioning, @mixonic!

**Comment by Serabe** [comment] 2016-06-27 06:24
I think the problem is caused by the merging. Looking for a nice way to fix it.

**Closed** 2016-07-21 19:47 UTC
Labels: Bug, Has PR
