### ISSUE TITLE
component with tagName of <img> with "width" / "height" attribute regression

### ISSUE THREAD

**Issue by oriSomething** [emberjs/ember.js#10846] opened 2015-04-08 08:58 UTC
since ember 1.11.1, i have a regression related to `components` with `tagName` of `img`. i cannot assign `width` or `height` with percentage unit. it convert percentage units to `0`.

you can see in the link the problem:
http://codepen.io/oriSomething/pen/LEoqBo

edit:
also doesn't work with canary build

**Comment by oriSomething** [comment] 2015-04-09 06:33
i made this test in `ember-metal-views/tests/attributes_test.js`:
```javascript
QUnit.test('<img> aliased attributeBindings', function() {
  var view = {
    tagName: 'img',
    isView: true,
    attributeBindings: ['width', 'dataWidth:data-width'],
    width: '90',
    dataWidth: '90'
  };

  var el = appendTo(view);

  equal(el.getAttribute('data-width'), '90', "The data attribute alias was set");
  equal(el.getAttribute('width'), '90', "The attribute alias was set");

  subject().removeAndDestroy(view);
});
```
and got this result:
![ember](https://cloud.githubusercontent.com/assets/2685242/7061483/605c07cc-de9b-11e4-8861-94f6567b283e.png)

**Comment by xtian** [comment] 2015-04-17 00:03
I'm not sure whether this is a valid regression since in HTML5 the spec for `<img>` was changed to only allow integer values.

**Comment by oriSomething** [comment] 2015-04-17 06:40
i can't say if it's true, but i only know for sure if you have `<img … width="100%">` non component in your template. everything will work just fine. i've also added this code to work around the regression:
```javascript

    widthDidChanged: on('didInsertElement', observer('width', function() {
      /** @validation <img> is in the DOM */
      if (this.element === null) { return; }

      const width = this.get('width');
      const element = this.element;

      if (width === null) {
        element.removeAttribute('width');
      } else {
        element.setAttribute('width', width);
      }
    }))
```

**Comment by oriSomething** [comment] 2015-04-17 06:46
but interestingly this is looks weird O_O:
```javascript
var i = document.createElement('img');
i.setAttribute('width', '10%');

console.log(i.width); // 10
console.log(i.getAttribute('width')); // "10%"
```

**Comment by xtian** [comment] 2015-04-17 13:33
Yeah, I think this could be the result of stricter parsing from HTMLBars compared to what browsers implement (see also: missing closing tags, etc).

**Comment by xtian** [comment] 2015-04-17 13:58
Note you can keep the same component API with some extra code to convert to a `style` attribute: http://emberjs.jsbin.com/jemewoyequ/2/edit

**Comment by oriSomething** [comment] 2015-04-17 17:46
if percentage unit deprecated to `width` and `height` on `<img>` tag. it my be nice that `HTMLBars` will throw or at least warn when there is a code like this:
```html
<img … width="100%">
```

**Comment by stefanpenner** [comment] 2015-07-08 19:19
Alright. I believe the issue is props and attrs do no correctly reflect the `50%`.

I'll think about what the best solution is (special casing height/width) or detecting string etc.

**Comment by stefanpenner** [comment] 2015-07-08 19:20
Note: this will need to be fixed in HTMLBars, but we can keep this open as a tracking issue.

**Comment by locks** [comment] 2016-09-28 23:11
I am closing this as I believe it no longer applies in the 2.x branch.

**Closed by locks** 2016-09-28 23:11 UTC
Labels: Bug, Ember 1.X, Regression
