### ISSUE TITLE
Unexpected reserved word in strict mode error (for yield) on Android 4.0

### ISSUE THREAD

**Issue by fivetanley** [emberjs/ember.js#12657] opened 2015-11-27 05:44 UTC
The line on HTMLBars here: https://github.com/tildeio/htmlbars/blob/72c7350805e4d7d44e2e88f2377915960cd3513a/packages/htmlbars-runtime/lib/hooks.js#L107

causes an error of `Unexpected reserved word in strict mode` error on Android 4.0. The solution is probably to add 'yield' to https://github.com/stefanpenner/es3-safe-recast.

**Comment by fivetanley** [comment] 2015-11-27 05:54
Another example on another project: https://github.com/angular/angular.js/issues/7969

**Comment by rwjblue** [comment] 2015-11-27 06:20
Dupe of https://github.com/tildeio/htmlbars/issues/420, which would be fixed by https://github.com/tildeio/htmlbars/pull/421.

**Comment by fivetanley** [comment] 2015-11-27 06:22
I was getting Saucelabs set up for Ember Data which made me notice this. Glad it's been fixed! I think we'll need a point release for the changes to apply? I'm also concerned about previous versions of ember.

**Comment by rwjblue** [comment] 2015-11-27 06:23
Ya, we will need to release updated version of HTMLBars for Ember versions 1.13 (kinda like an LTS), 2.2 (release), and 2.3 (beta).

**Comment by mmun** [comment] 2015-11-27 08:21
I am confused. Babel should be handling this?

https://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&code=var%20x%20%3D%20%7B%20'yield'%3A%20true%2C%20yield%3A%20false%20%7D%3B

**Comment by stefanpenner** [comment] 2015-11-27 17:24
@mmun I don't believe old builds always used babel.

**Comment by fivetanley** [comment] 2015-11-27 17:27
FWIW this is now in es3-safe-recast thanks to @stefanpenner, so it may be as simple as bumping the version + doing rebuild.

**Comment by rwjblue** [comment] 2015-11-27 17:32
Nothing is simple with older deps and npm. ;P

**Comment by Serabe** [comment] 2016-05-09 08:23
Closing this since 1.13 is no longer _LTSish_ and the fix was in htmlbars 0.14.11 (the version in Ember 2.3).

Please, reopen it if something is still missing.

**Closed by Serabe** 2016-05-09 08:23 UTC
Labels: Bug
