### ISSUE TITLE
Loading route always entered when using async/await

### ISSUE THREAD

**Issue by bakerac4** [emberjs/ember.js#15240] opened 2017-05-12 14:08 UTC
It looks like if your application has a loading route, the loading route will always be entered if you use async/await in the `model` method (or `beforeModel`/`afterModel`). If you use a normal promise, it doesn't look like the loading route is entered (which is correct, since the promise is resolved immediately)

I created a twiddle to reproduce the issue. https://ember-twiddle.com/d6b3e147867c15987eeedec1b0284979?openFiles=routes.test.js%2C&route=%2Ftest

**Comment by stefanpenner** [comment] 2017-05-12 18:29
Most likely this is because with async/await your getting native promises which don't coalesce with the run-loop (yet). There is some work to address this in the back burner repo. Although it is possible for more tuning to be required

**Comment by spieker** [comment] 2017-05-16 06:29
As a work around you can replace the native promise with Embers `RSVP.Promise`. Just add an initializer setting `window.Promise = Ember.RSVP.Promise`. It's not very nice, I know, but it works.

**Comment by esbanarango** [comment] 2018-09-21 15:28
Based on @rwjblue's comment here: https://github.com/emberjs/ember.js/issues/15556#issuecomment-341941606 I think we could either close this or `Has Reproduction`. 

What do you think @pixelhandler ?

There is also a good _Readers’ Questions_ on discuss about why `async/await` currently has some limitation:
https://discuss.emberjs.com/t/readers-questions-why-does-ember-still-use-rsvp/14736

**Comment by pixelhandler** [comment] 2018-09-21 15:56
@Serabe @bakerac4 @esbanarango @simonihmig @spieker @stefanpenner Gonna close this out for now seems like we have a good work around and this is essentially new Our guides do not indicate that using `async` or `await` with the model hooks just yet.

**Closed by pixelhandler** 2018-09-21 15:56 UTC
Labels: Routing
