### ISSUE TITLE
[Bug] Error thrown when using Ember 5.4 with custom browserlist query in config/target.js

### ISSUE THREAD

**Issue by ndekeister-us** [emberjs/ember.js#20572] opened 2023-11-09 22:52 UTC
### 🐞 Describe the Bug

When we use Ember 5.4 and have custom browserlist query defined in `config/targets.js` (like `last 2 versions and > 0.2%`) then the app will not build correctly and an error will be thrown when trying to access the app after running `ember s`
- `Uncaught TypeError: (0 , _emberBabel.extends) is not a function` 
- exact line -> https://github.com/emberjs/ember.js/blob/main/packages/%40ember/-internals/views/lib/views/states.ts#L33

<img width="1489" alt="Capture d’écran 2023-11-09 à 23 28 46" src="https://github.com/emberjs/ember.js/assets/56396753/666d4a5d-61c7-4d7d-b2b2-ed8ad370c14f">
<img width="907" alt="Capture d’écran 2023-11-09 à 23 28 59" src="https://github.com/emberjs/ember.js/assets/56396753/a55b7cb0-1df2-47a0-b6b2-16f3cece931c">

If we use default query `'last 1 Chrome versions', 'last 1 Firefox versions', 'last 1 Safari versions'` it works fine

### 🔬 Minimal Reproduction

Reproduced here -> https://github.com/ndekeister-us/test-ember-5-4
```
git clone git@github.com:ndekeister-us/test-ember-5-4.git
cd test-ember-5-4
yarn install
ember s
```

### 😕 Actual Behavior

- Considering an application using Ember 5.4 and having custom browsers targets defined in `./config/targets.js`, like `last 2 versions and > 0.2%`
- Then when running `ember s`
  - When reaching http://localhost:4200 an error is thrown and I can't access the app

### 🤔 Expected Behavior

- Considering an application using Ember 5.4 and having custom browsers targets defined in `./config/targets.js`, like `last 2 versions and > 0.2%`
- Then when running `ember s`
  - When reaching http://localhost:4200 no error is thrown and I can access the app

### 🌍 Environment

- Ember: 5.4
- Node.js/npm: 18.16/9.5.1
- OS: Mac
- Browser: N/A (Chrome, Firefox, ...)

### ➕ Additional Context

- Found the error trying upgrade to Ember 5.4 on an application
- Using `const browsers = ['last 2 versions and > 0.4%'];` I don't have the issue anymore
- Exact line where the issue comes from is this one https://github.com/emberjs/ember.js/blob/main/packages/%40ember/-internals/views/lib/views/states.ts#L33
  - Dunno if this issue should be created in this repo or in https://github.com/emberjs/ember-cli-babel, as the error is not obvious to debug I believe it can help peoples doing the upgrade to 5.4 if we have a ticket here, so that they understand why they have this error and have a workaround (updating browserlist query)

**Comment by BarryThePenguin** [comment] 2023-11-13 02:06
I ran into the same problem, my browserslist query is..

[`supports es6-module-dynamic-import and supports fetch`](https://browsersl.ist/#q=supports+es6-module-dynamic-import+and+supports+fetch)

For some reason this still includes iOS 11.0-11.2 and 11.3-11.4

If I include [`not iOS < 12`](https://browsersl.ist/#q=supports+es6-module-dynamic-import+and+supports+fetch%2C+not+iOS+%3C+12) in the query, ember no longer transforms the code to include `_emberBabel.extends`

**Comment by chancancode** [comment] 2023-11-13 02:11
cc @NullVoxPopuli you may have some relevant context (both where to add the missing helper if needed, but also you may know how to figure out why this became an issue in the first place)

**Comment by NullVoxPopuli** [comment] 2023-11-13 13:01
I'm OOO atm, so my focus time is veeery limited. earliest I could take a look is friday, probably

**Comment by kategengler** [comment] 2023-12-11 21:40
This is indeed caused by having an unsupported browser in your browserlist. You'll also see this error if you end up with IE11 in your browserslist. 

@ndekeister-us The query `last 2 versions and > 0.2%` does match IE11 https://browsersl.ist/#q=last+2+versions+and+%3E+0.2%25 If you add `and not dead` to the query, you'll get a more reasonable set of browsers https://browsersl.ist/#q=last+2+versions+and+%3E+0.2%25+and+not+dead

Another possibility for hitting this is failure to update caniuse data. This can be fixed by running `npx browserslist@latest --update-db`

The list of supported browsers by your Ember version can be seen by `require('ember-source').supportedBrowsers` and can be seen in the source code here https://github.com/emberjs/ember.js/blob/main/lib/browsers.js

The current browser support policy is described here https://rfcs.emberjs.com/id/0685-new-browser-support-policy

**Comment by ndekeister-us** [comment] 2023-12-19 10:14
We had `not ie 11` on our config (but did not added in the issue description), indeed adding `not dead` solved the issue 

Seems our `query` was way too old, sorry for the times passed to investigate on this issue, guess it will not happen to many projects

Thanks for the link and for the answer 🙏

**Closed** 2023-12-19 15:11 UTC
