### ISSUE TITLE
[3.17] Regression in observing an array

### ISSUE THREAD

**Issue by boris-petrov** [emberjs/ember.js#18794] opened 2020-03-05 06:59 UTC
```javascript
test('foo', function(assert) {
  assert.expect(1);
  const callback = function() {
    assert.ok(true);
  };
  const x = A([1]);
  x.addObserver(0, x, callback, true);
  x.set(0, 2);
});
```

This works fine on `3.16.3` and breaks on `3.17.0`. I would guess it's because of [this commit](https://github.com/emberjs/ember.js/pull/18741) that fixed [another similar issue](https://github.com/emberjs/ember.js/issues/18739) but can't be sure.

We're stuck on `3.16` because of this issue. Otherwise everything else looks fine with the Glimmer VM update, well done!

P.S. cc @pzuraq

**Comment by pzuraq** [comment] 2020-03-05 16:28
Can you describe what breaks, exactly? Is it the same mandatory setter error?

**Comment by boris-petrov** [comment] 2020-03-05 16:39
No, the test fails, that is, the observer’s callback doesn’t get called. It did on 3.16. There is no error.

**Comment by pzuraq** [comment] 2020-03-05 18:01
Ok. For what it's worth, when we discussed this issue with mandatory setters, most core team members were surprised that observers were being used like this. It was not originally intended behavior, and while we will work to fix it, I really do recommend moving away from this pattern and the use of observers in general. We'll be moving to deprecate sync observers in the near future, and async observers will come soon after that most likely.

If you would like to discuss alternative patterns, let me know, happy to go over the options and figure out a migration path. In the meantime, we'll put a fix for this in the queue, as it is a regression.

**Comment by boris-petrov** [comment] 2020-03-05 20:40
@pzuraq - thanks. I'll ping you tomorrow on Discord on a private message. I have a number of cases (including this one) that I see no way to do without observers. Let's see how it goes. Do you have a (rough) time-frame for deprecating sync and async observers? I'm asking because I want to decide how we proceed from here.

Thanks for looking into this!

**Comment by boris-petrov** [comment] 2021-02-23 13:11
Just a heads-up - this is still broken on 3.25.1. Not that it matters that much, just for the record.

**Comment by locks** [comment] 2023-07-22 22:10
Closing as stale! If there is a follow up please open a fresh issue 🙇

**Closed by locks** 2023-07-22 22:10 UTC
