### ISSUE TITLE
LinkComponent cannot be yielded as a contextual component

### ISSUE THREAD

**Issue by phcoliveira** [emberjs/ember.js#14508] opened 2016-10-23 00:54 UTC
First of all, I did look at StackOverflow before creating this issue. As a matter of fact, I could not find anything about this, and I am pretty sure that I am not the only one who tried this. 

```handlebars
{{!-- components/a-component/template.hbs --}}
{{yield (hash
  contextual-link=(component "link-to" class="a-component__contextual-link")
}}
{{!-- END --}}

{{!-- somewhere else --}}
{{#a-component as |component|}}
  {{#component.contextual-link "some.route"}}
    Unfortunately, this does not work.
  {{/component.contextual-link}}
{{/a-component}}
{{!-- END --}}
```
When used like that, LinkComponent will complain the it needs at least one parameter. When one bogus parameter is supplied in the template of `a-component`, such as "application", it won't be replaced by the time the `contextual-link` is invoked.

Am I missing something?

**Comment by pixelhandler** [comment] 2016-10-23 01:14
@phcoliveira I see a missing closing parenthesis in the a-component.

See this twiddle, this seems to work: https://ember-twiddle.com/9a253ac0acae6fc9d88c7dd6e0ce0e10?openFiles=templates.components.my-link.hbs%2C

**Comment by phcoliveira** [comment] 2016-10-23 01:43
I apologize for not describing the problem as I am exactly seeing. What I am trying to do is something different, but possible when not used as contextual component.
```javascript
Ember.Component.extend({
  linkParams: Ember.computed('route', 'model', function() {
    return [this.get('route'), this.get('model.id')];
  })
});
```


```handlebars
{{#a-component as |component|}}
  {{#component.contextual-link params=linkParams}}
    Does not work here
  {{/component.contextual-link}}
{{/a-component}}


{{#link-to params=linkParams}}
  But it works here
{{/link-to}}
```

**Comment by pixelhandler** [comment] 2016-10-23 07:19
@phcoliveira can you make an ember-twiddle example that reproduces your issue?

**Comment by Serabe** [comment] 2016-10-23 10:03
Investigating.

**Comment by Serabe** [comment] 2016-10-23 10:27
[Reproduction](https://ember-twiddle.com/b6058da6c0a75ad85a3165632b5c2cf1?numColumns=2&openFiles=twiddle.json%2Ccontrollers.application.js).

This only happens in 2.9 since this behaviour is fixed in Glimmer 2 ([reproduction](https://ember-twiddle.com/0549d1e2bcae30bcf6d626be92b71f6b?numColumns=2&openFiles=twiddle.json%2Ccontrollers.application.js)). This used to work in 2.7 but broke in 2.8 ([reproduction in 2.7](https://ember-twiddle.com/fbe17428f0b0b34a9f94fe0c59b89a4f?numColumns=2&openFiles=twiddle.json%2Ccontrollers.application.js)) so I would consider this a regression. I'll try to land a fix this morning though if I don't get it right, I won't be able to fix it until Ember Fest.

**Comment by Serabe** [comment] 2016-10-23 11:38
Thanks to @locks to noticing that reproduction in 2.7 does not transition but renders, but in 2.6 does render and transitions ([reproduction](https://ember-twiddle.com/7cc9337e7394e33ff5b1bc68c4726219?numColumns=2&openFiles=twiddle.json%2Ccontrollers.application.js&route=%2Fsome%2Froute)).

**Comment by Serabe** [comment] 2016-10-23 12:02
## Summary

This bug was introduced partially in 2.7, while fixing another issue with rest positional params. In 2.7 the component would render, but would received an empty `params`.

In 2.8, it stopped rendering given that an assertion was added to check that `link-to` receives at least one parameter.

I submitted a PR for fixing this in 2.9 and I am now checking for LTS. Since this seems to be a regression, I have some hope in getting it there.

Thank you all for this report!

**Comment by phcoliveira** [comment] 2016-10-23 13:49
So much has happened while I slept. I really should have described all the basics and created a twiddle, my bad again.

I am using Ember 2.8.2.

**Comment by Serabe** [comment] 2016-10-28 07:37
Closing since PR was merged. Thank you!

**Closed by Serabe** 2016-10-28 07:37 UTC
Labels: Bug, Has PR, Regression
