### ISSUE TITLE
Ember.run.later is halting under certain circumstances

### ISSUE THREAD

**Issue by rondale-sc** [emberjs/ember.js#12193] opened 2015-08-24 19:01 UTC
Here is a twiddle demoing it for 1.13.6.  I've also tested this for 2.0.0:

http://ember-twiddle.com/d7e78ce7132882773232

The gist can be found here: 

http://ember-twiddle.com/d7e78ce7132882773232

The demonstration has a timer value being updated via `Ember.run.next` continuously.  When it is running calls to `Ember.run.later` will halt the update of the value until the full duration of `Ember.run.later` has expired.

If `Ember.run.later` is replaced with a simple `setTimeout` there is no halting.  I did not experience this problem on 1.12.x.

If I can assist in any way please let me know.  :heart:

**Comment by dtetto** [comment] 2015-08-24 19:09
At a glance, this sounds like a duplicate of https://github.com/emberjs/ember.js/issues/10479 which in turn is an upstream bug at https://github.com/ebryn/backburner.js/issues/135.

**Comment by rwjblue** [comment] 2015-08-24 20:16
@dtetto - Yes, I just came to the same conclusion. Thank you for linking!

**Comment by rondale-sc** [comment] 2015-08-24 20:59
Consolidated some of the related PR's together: https://github.com/ebryn/backburner.js/pull/146

**Comment by rwjblue** [comment] 2015-09-11 19:43
Will be fixed by #12331, but @stefanpenner will have to review to see if this is eligible for backporting.

**Comment by stefanpenner** [comment] 2015-09-11 21:26
I'll take care of the backport

**Comment by workmanw** [comment] 2015-10-06 18:49
Shameless Bump. This was the root cause of an issue a customer reported for us. 

We're still on 1.13.x and would really love to get this fixed.

**Comment by stefanpenner** [comment] 2015-10-06 18:58
> I'll take care of the backport

I haven't had time, @workmanw care to submit a PR backporting backburner?

**Comment by workmanw** [comment] 2015-10-06 19:13
@stefanpenner If you give me a little bit of direction, I'd be more than happy to. It seems to be fixed in backburner and backburner seems to be pulled in via bower (https://github.com/emberjs/ember.js/blob/release-1-13/bower.json#L9). So is the PR just as simple as updating the 'bower.json' or is there more to it?

**Comment by stefanpenner** [comment] 2015-10-06 19:13
> So is the PR just as simple as updating the 'bower.json' or is there more to it?

yup

**Comment by rwjblue** [comment] 2015-10-07 01:06
Fix back ported in #12449

**Closed by rwjblue** 2015-10-07 01:06 UTC
Labels: Needs backport
