### ISSUE TITLE
isArray() returns true for object with length property

### ISSUE THREAD

**Issue by cbroeren** [emberjs/ember.js#17015] opened 2018-09-28 11:45 UTC
Lately we updated our application from Ember 3.1 to 3.3 and with that change we broke part of our application, due to this code in the `isArray` function:
https://github.com/emberjs/ember.js/blob/c2c8171301d2b1a0c499b4a55009ebf428f40e69/packages/%40ember/-internals/runtime/lib/mixins/array.js#L168

We happen to have an object with a length property, but Embers isArray will say it's an array. Mainly breaks on using the `@each` in a computed property on that object. 
```js
@computed('content.@each.anyProperty', 'content.anyProperty')
```
In this case content can be a single object or a multi-edit-object (by using ArrayProxy), so thats why we need to check both. 

For now we fixed it by renaming all our custom `length` properties, but it made us have some questions:
1. Is it expected, and should we be aware of not using `length` in our own objects anymore?
2. Why the `length === length`?

**Comment by jonatahr** [comment] 2018-10-03 18:16
@cbroeren The statement "length === length" is always true, in the code, objects are always considered Array-like if the object has a length property and if length property type is a number.

```
let length = obj.length;
  if (typeof length === 'number' && length === length && 'object' === type) {
    return true;
  }
```
I did the following test:

```
let instance = EmberObject.extend({
        // intentionally returning non-null / non-undefined
        length: 12,
        unknownProperty() {
          return false;
        },
      }).create();

      assert.equal(isArray(instance), true);
```

I would not consider this a bug, let me know your thoughts.

**Comment by jonatahr** [comment] 2018-10-03 18:37
@btecu yeap, my fault, thanks.

**Comment by pixelhandler** [comment] 2018-10-12 17:27
@cbroeren can you create an example reproduction using ember-twiddle?

**Comment by locks** [comment] 2019-05-30 14:46
Thanks for reporting! Closing due to lack of reproduction.

**Closed by locks** 2019-05-30 14:46 UTC
Labels: Needs Reproduction
