### ISSUE TITLE
test skipped in Firefox, we should fix it

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember.js#11698] opened 2015-07-08 20:58 UTC
https://github.com/emberjs/ember.js/blob/8767515d65def291dfbf42b9ad7f48816f425a32/packages/ember-htmlbars/tests/integration/select_in_template_test.js#L156-L188

**Comment by mixonic** [comment] 2015-07-08 21:33
This is a dupe of https://github.com/emberjs/ember.js/issues/10984. I'll move that to the release, it has more context.

**Closed by mixonic** 2015-07-08 21:33 UTC
Labels: Bug

**Comment by stefanpenner** [comment] 2015-07-08 21:44
@mixonic awesome, i tried searching but GH search failed me. Thanks for the correction + link.
