### ISSUE TITLE
Problem with nested outlets & named outlets

### ISSUE THREAD

**Issue by fpauser** [emberjs/ember.js#10652] opened 2015-03-17 14:45 UTC
See http://emberjs.jsbin.com/dosafe/6/edit?html,js,output

Navigate to "admin -> roles-and-users -> user-roles#edit".
The user-roles-edit-template should be rendered into the "dialog" outlet of  "user-roles" but is not.

Bug - or unintended usage of outlets?

**Comment by fpauser** [comment] 2015-03-17 14:56
Changed this version a bit and added {{outlets}} besides the named outlets which seem to work better, but now it behaves strange when navigating into `admin -> roles-and-users -> user-roles#edit` and switch to `admin -> this-and-that`.

See http://emberjs.jsbin.com/dosafe/7/edit?html,js,output

**Comment by fpauser** [comment] 2015-03-18 15:59
Added a failing test, see emberjs/ember.js#10660

**Comment by sandstrom** [comment] 2015-03-18 16:35
This issue may be related: https://github.com/emberjs/ember.js/issues/10658

**Comment by alexdiliberto** [comment] 2015-03-18 19:54
I also believe this is related to https://github.com/emberjs/ember.js/issues/10602

`renderTemplate` hijacking with `this.render()` seems broken now

**Comment by ef4** [comment] 2015-03-20 09:13
Duplicate of #10683.

**Closed by ef4** 2015-03-20 09:13 UTC
