### ISSUE TITLE
Angle bracket components always return hasBlock: true

### ISSUE THREAD

**Issue by tim-evans** [emberjs/ember.js#12597] opened 2015-11-12 19:04 UTC
I was expecting `hasBlock` to return `false` when the block is short-closed, but `true` when it has a closing element. Apparently the only way to have `hasBlock` for an angle bracket component is to use the `{{component}}` helper.

See https://ember-twiddle.com/89b031c3c1f311ca60b7 for a reproduction.

**Comment by rwjblue** [comment] 2015-11-13 01:08
I believe that `<foo-bar />` is intended to be a shortcut for `<foo-bar></foo-bar>`, which means that both technically have a block (since one form expands to the other).

@wycats / @tomdale / @chancancode - Can you confirm the above?

**Comment by tim-evans** [comment] 2015-11-24 15:58
Just a friendly :point_right:  on this

**Comment by chancancode** [comment] 2015-11-24 18:22
Yes, that is the intent for the moment

**Comment by locks** [comment] 2016-04-17 08:45
I am closing this issue since it is working as designed.
Feel free to re-open the issue if you think it's still justified, thank you.

**Closed by locks** 2016-04-17 08:45 UTC
