### ISSUE TITLE
Ember 3.3 has bracket components enabled by default

### ISSUE THREAD

**Issue by staale** [emberjs/ember.js#16880] opened 2018-08-13 12:58 UTC
I had a code block that I could not figure out why broke after 3.3 update, until I noticed that I declared a variable called option in a for each. Here is a minimal reproduction:

Works:

    <select>
      {{#each-in (hash key="value") as |key value|}}
        <option value={{key}}>{{key}}</option>
      {{/each-in}}
    </select>`

Breaks:

    <select>
      {{#each-in (hash key="value") as |key option|}}
        <option value={{key}}>{{key}}</option>
      {{/each-in}}
    </select>

The only change here is declaring the iteration variable called option. This creates the following error message:

> Error: Assertion Failed: You cannot use 'value' as a component name. Component names must contain a hyphen.

So my guess is that here Ember tries to resolve the option variable as a component.

[Working in Ember 3.2.2](https://ember-twiddle.com/64014b86b2065a0d08b63909e6f73aab?openFiles=templates.application.hbs%2C)
[Broken in Ember 3.3.0](https://ember-twiddle.com/02a0bb515b91b1d80a5785c9a04b3f90?openFiles=templates.application.hbs%2C)

One could argue that this is bad naming convention, but it did cause a hard to figure out issue for me.

**Comment by btecu** [comment] 2018-08-13 18:19
Duplicate of #16826

**Closed** 2018-08-14 06:50 UTC
