### ISSUE TITLE
`elementId` issue binding to an immutable computed property

### ISSUE THREAD

**Issue by alexdiliberto** [emberjs/ember.js#10728] opened 2015-03-25 22:31 UTC
The following JSBin is on beta:

http://emberjs.jsbin.com/temiji/2/edit

I would expect something like this to work but the component's final id in the DOM is actually being injected into the as to `toString`'d version of the computed property.

```
id="[object Object]"
```

If I bind  elementId directly to a "String" literal it will work.

**Comment by alexdiliberto** [comment] 2015-03-25 22:50
Also for more context, I updated the example to be v1.9.1 compatible...then it will simply ignore my CP and use the auto-generated id

http://emberjs.jsbin.com/puraqu/1/edit

**Comment by rwjblue** [comment] 2015-03-26 00:18
Seems like this may be a duplicate of https://github.com/emberjs/ember.js/issues/10607 (which should have been fixed by https://github.com/emberjs/ember.js/pull/10613).  Can you confirm/deny?

**Comment by alexdiliberto** [comment] 2015-03-26 01:19
I don't think that one fixes this. I also tested this on beta/canary (first JSBin)

@rwjblue Some weird behavior also when I explicitly pass in the id vs set the elementId on the component  http://emberjs.jsbin.com/temiji/5/edit?html,js,output

Really what I'm trying to achieve is an ID set using a CP though

**Comment by rwjblue** [comment] 2015-03-26 11:51
I'm not seeing where this was ever supported (I could be wrong).  We assume that calling `this.elementId` will return a plain string in many many places.

I believe that this isn't a bug/regression, but simply something that we do not support.  I'd be in favor of documenting that explicitly in the API docs ([around here](https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/views/view.js#L1107)).

The following JSBin shows a way to get a dynamic value for `elementId`: http://emberjs.jsbin.com/wirahi/1/edit?html,js,output

**Comment by rwjblue** [comment] 2015-03-26 11:52
Closing now, as I think my last comment addresses things, but if you can show me where this once worked (which would make this a regression) I'm happy to reopen...

**Closed by rwjblue** 2015-03-26 11:52 UTC
