### ISSUE TITLE
Rubbish!

### ISSUE THREAD

**Issue by NeilAllen** [emberjs/ember.js#12585] opened 2015-11-11 11:10 UTC
npm install -g ember-cli
ember new knob
cd knob
ember serve --port 4201

ENOENT: no such file or directory, open 'd:\ember\knob\tmp\concat_with_maps-input_base_path-7Ru0USRW.tmp\0\d:\ember\knob\tmp\cocat_with_maps-input_base_path-7Ru0USRW.tmp\0\ember-cli-app-version\components\app-version.js'

It's a clean install, new app; nothing extra & ...it's rubbish!

**Comment by rlivsey** [comment] 2015-11-11 11:48
Duplicate of ember-cli/ember-cli#5055

I understand that bugs are frustrating but please be respectful of the people giving up their free time to work on this stuff.

**Comment by NeilAllen** [comment] 2015-11-11 13:04
Plenty of respect for them; for those who 'contribute' as a means of self-publication, and the quality of their input, I have little

**Comment by Arkham** [comment] 2015-11-11 14:11
Nice contribution! Next time you could submit a PR to fix the problem :)

**Comment by rwjblue** [comment] 2015-11-11 14:45
This issue report is unrelated to ember development, it was an issue with a dependency of ember-cli and is being tracked in https://github.com/ember-cli/ember-cli/issues/5055. Please follow that issue for further developments.

**Comment by rwjblue** [comment] 2015-11-11 14:45
> Plenty of respect for them

Indeed.

**Closed by rwjblue** 2015-11-11 14:45 UTC
