### ISSUE TITLE
href property of LinkComponent/LinkView is not recomputed when a promise resolves (link-to)

### ISSUE THREAD

**Issue by aroberts** [emberjs/ember.js#11471] opened 2015-06-15 14:44 UTC
I run into this issue when using `link-to` with an ember-data `async` association, so `link-to` receives a promise that resolves to a model.

Ordinarily, the link is able to render successfully because the unresolved object already has an `id` property, because it's being fetched by id.  However, when `Route#serialize()` is implemented to return some other property, then the href computes before the model is resolved, and `serialize()` can't find the property it's looking for.  

It seems to me that the link's `href` should be recomputed by the model resolving, which I'm really using as a proxy for the output of `serialize()` changing.

Here's a bin that illustrates the issue (Ember 1.13, also present in ember 1.12):

http://emberjs.jsbin.com/duqoqumeco/1/edit?html,js,output

**Comment by rwjblue** [comment] 2015-08-03 03:18
Can you update the JSBin to see if the issue is fixed on canary?

**Comment by aroberts** [comment] 2015-08-03 17:05
Ported to canary, still seeing the issue:

https://jsbin.com/vufeje/edit?html,js,output

**Comment by mydea** [comment] 2016-04-01 17:55
We are also experiencing this problem, together with slugs. I ported the example showing the problem to Ember Twiddle:
https://ember-twiddle.com/f93d7e772cba9159f73e567a4b52a186?openFiles=routes.user.js%2C

with latest canaray ember/ember-data. Basically, this makes it impossible to use slugs in our application. We kind of fixed it by overwriting LinkComponent:

```js
Ember.LinkComponent.reopen({
   _checkForPromise: Ember.observer('models.[]', function() {
     Ember.get(this, 'models').forEach(model => {
     if (Ember.get(model, 'promise') && !Ember.get(model, 'isSettled')) {
       model.then(() => this.notifyPropertyChange('models'));
     }
  });
});
```

But I think this is something that should normally work out of the box?

**Comment by locks** [comment] 2016-04-26 06:27
@mydea your Twiddle is erroring out for me, so I can't check your reproduction.

**Comment by mydea** [comment] 2016-04-26 14:46
Hmm what error do you get? It works for me on Chrome & FF.

**Comment by pixelhandler** [comment] 2016-05-06 18:04
@aroberts the jsbin errors for me, below are the errors I see in my console (Chrome on mac)…

```
Refused to execute script from 'https://raw.githubusercontent.com/jakerella/jquery-mockjax/v2.0.1/dist/jquery.mockjax.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
runner-3.35.12.min.js:1 error ReferenceError: Ember is not defined
    at vufeje.js:1:1181
vufeje.js:1 Uncaught ReferenceError: Ember is not defined
```

@mydea your fiddle does seem to reproduce the issue with the links having an `undefined` path in the `href` and url too. https://ember-twiddle.com/f93d7e772cba9159f73e567a4b52a186?openFiles=routes.user.js%2C

**Comment by pixelhandler** [comment] 2017-09-15 17:26
@aroberts we were not able to verify this issue as bug and the activity has lulled, I'll close this out for now.

If you still have the issue feel free to reopen. Also if you found a work around please post a comment.

**Closed by pixelhandler** 2017-09-15 17:26 UTC
Labels: Has Reproduction

**Comment by aroberts** [comment] 2017-09-15 17:33
is there a fiddle site out there that still supports ember-latest? I am happy to port my reproduction but it's not clear where I should

**Comment by locks** [comment] 2017-09-15 17:35
@aroberts Twiddle does
