### ISSUE TITLE
{{yield}} block haven`t any context variables 

### ISSUE THREAD

**Issue by kingartes** [emberjs/ember.js#10451] opened 2015-02-13 15:25 UTC
Have the following template inside the context of ArrayController called page for example
<code>
  {{!-- code.hbs --}}
  {{#view 'list'}}
        <div>
            <span>{{this.name}}</span>
        </div>
    {{/view}}
</code>

And corresponding template for list view.

<code>
 {{!-- list.hbs --}}
  <div class="scroller">
    <ul class="scroll-list">
    {{#each}}
        {{#view 'listItem' index=id}}
            {{yield}}
        {{/view}}
    {{/each}}
    </ul>
</div>
</code>

The problem is following - the block inside list view helper doesn`t have the name variable in context ( it doesn`t have any context at all) despite of controller content is correct. This code was doing well with 1.9.0 version and bellow.

**Comment by rwjblue** [comment] 2015-02-13 15:29
Duplicate of https://github.com/emberjs/ember.js/issues/10402.

**Closed by rwjblue** 2015-02-13 15:29 UTC
