### ISSUE TITLE
array_proxy.js: cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by srsgores** [emberjs/ember.js#17441] opened 2019-01-06 05:37 UTC
Upon upgrading a legacy ember app, the model is unable to resolve to `ArrayProxy`:

> array_proxy.js:155 Uncaught TypeError: Cannot set property 'length' of undefined
    at Class.objectAt (array_proxy.js:155)
    at objectAt (metal.js:1300)
    at EmberArrayIterator.valueFor (glimmer.js:2333)
    at EmberArrayIterator.next (glimmer.js:2290)
    at ReferenceIterator.next (reference.js:373)
    at Object.APPEND_OPCODES.add [as evaluate] (runtime.js:1288)
    at AppendOpcodes.evaluate (runtime.js:39)
    at LowLevelVM.evaluateSyscall (runtime.js:2179)
    at LowLevelVM.evaluateInner (runtime.js:2153)
    at LowLevelVM.evaluateOuter (runtime.js:2146)

The error occurs on this line:

```
let length = this._objects.length = (0, _metal.get)(arrangedContent, 'length');
```

As [here](https://github.com/emberjs/ember.js/blob/v3.6.1/packages/%40ember/-internals/runtime/lib/system/array_proxy.js#L174).

By the looks of it, some models will not have prepopulated with `this.objects`, so we should check that this array is also `undefined` as opposed to [just `null`](https://github.com/emberjs/ember.js/blob/v3.6.1/packages/%40ember/-internals/runtime/lib/system/array_proxy.js#L167):

```
if (this._objects === null || this._objects === undefined) {
    this._objects = [];
}
```

* Ember: 3.6.1
* Ember data: 3.6.0

**Comment by rwjblue** [comment] 2019-01-06 11:44
Can you provide a demo / reproduction?

**Comment by srsgores** [comment] 2019-01-16 08:13
@rwjblue: I can PM you a link.  Leave your contact details

**Comment by mactenm** [comment] 2019-01-16 08:19
jack skok puertas

ons. 16. jan. 2019 kl. 09.14 skrev Sean Goresht <notifications@github.com>:

**Comment by mactenm** [comment] 2019-01-16 08:22
4542555943 thcjackskok@icloud alternative mail

ons. 16. jan. 2019 kl. 09.19 skrev Tony Montana <thcjackskok@gmail.com>:

**Comment by mactenm** [comment] 2019-01-16 08:22
4542555943 thcjackskok@icloud alternative mail

ons. 16. jan. 2019 kl. 09.21 skrev Tony Montana <thcjackskok@gmail.com>:

**Comment by mactenm** [comment] 2019-01-16 08:35
understand

**Comment by pixelhandler** [comment] 2019-01-25 18:06
@srsgores Often we use https://ember-twiddle.com/ or if that doesn't work for your use case a sample repository and link to it here. The goal with a reproduction of the issue is to demonstrate the bug, and in many cases when trying to create a simple example we find out where the bug is, either in our codebase or in some cases in the framework. 

Also, sharing a simple reproduction in code helps others address a problematic use case. Can you re-create the issue using ember-twiddle?

**Comment by locks** [comment] 2020-04-19 10:43
Closing due to lack of reproduction. If you are able to publish the reproduction, or if you encounter the same bug for newer versions of Ember, please let us know!

**Closed by locks** 2020-04-19 10:43 UTC
Labels: Needs Reproduction
