### ISSUE TITLE
ember is not rendering polymer elements

### ISSUE THREAD

**Issue by matheusdavidson** [emberjs/ember.js#11361] opened 2015-06-06 15:01 UTC
Ember works with polymer 0.5 but not with polymer 1.0.
Elements will only render if placed inside index.html, but inside any route like in application.hbs it does not render very well. The big problem is with <content></content> tags, here is an image to explain whats happening:

Inside index.html, the element is rendered and the content is going to the right place, inside this topBar div there is a <content></content> and this is where the content should go:
![inside-index](https://cloud.githubusercontent.com/assets/2229994/8020074/56bbd11e-0c42-11e5-927d-6681df7c55df.png)

But in application.hbs, the content doens't go to the right place:
![inside-application](https://cloud.githubusercontent.com/assets/2229994/8020082/a734a508-0c42-11e5-983b-c25e7fa303c0.png)

This is somehow related to how ember is rendering templates because if i use the console and just insert the element with jQuery it works:
```
$('.ember-view').html('<paper-toolbar><div>Title</div></paper-toolbar>');
```

I saw this article about ember and web components, it uses the <content></content> tag as an insertion point so this should work:

http://pixelhandler.com/posts/a-bet-on-web-components-and-embercomponent-synchronicity

Would be very good to have ember working with polymer 1.0 the same way it works with 0.5.

**Comment by matheusdavidson** [comment] 2015-06-06 15:50
i tried this with ember 1.12 and 1.13 beta2

**Comment by matheusdavidson** [comment] 2015-06-07 03:52
I was surprised to see that everything works fine in IE and Firefox but not on chrome.

**Comment by stefanpenner** [comment] 2015-06-07 04:33
i believe those other browsers may fall back to polyfils, for things that chrome already implements.

**Comment by matheusdavidson** [comment] 2015-06-07 04:49
Yes, im currently using polymer dom = shadow instead of shady and almost worked, except for a few elements

**Comment by stefanpenner** [comment] 2015-06-07 04:53
the best chance of some-one tackling this is to provide an example that demonstrates the issue.

**Comment by matheusdavidson** [comment] 2015-06-07 04:57
forget my last comment, that config actually makes things more buggy.
There is another guy having same problems:
https://github.com/thijsvdanker/ember-polymer

**Comment by matheusdavidson** [comment] 2015-06-07 05:26
Hey @stefanpenner i have uploaded the demo i was testing to github and gh-pages.
Here is the repository:
https://github.com/matheusdavidson/ember-polymer

and here is gh-pages:
http://matheusdavidson.github.io/ember-polymer/

As you can see, elements in index.html render as expected, but inside application.hbs, content does not goes into the right insertion point.

**Comment by thijsvdanker** [comment] 2015-06-11 15:44
I'm having the same issue. In my repository (https://github.com/thijsvdanker/ember-polymer) there are two routes: 1 with the paper-toolbar component, and one with a wrapped version.
The demo is visible here: http://bitsnbolts.nl/ember-polymer/
 
The first time you click the paper-toolbar version, the Title is rendered outside of the toolbar, but if you go to the poly-toolbar (which works) and than back to the paper-toolbar then it does work.

**Comment by peec** [comment] 2015-06-17 17:09
Same problems - ref. https://github.com/peec/ember-cli-polymer/commits/feature/polymer-support

**Comment by bjornharrtell** [comment] 2015-07-17 09:25
Works for me in Chrome if I:

1. use Polymer global setting window.Polymer.dom = 'shadow';
1. do *not* include webcomponents.js

**Comment by steven-ferguson** [comment] 2015-07-29 21:41
@bjornharrtell Can you provide an example project that has Ember 1.13+ working with Polyer 1.0+?

**Comment by bjornharrtell** [comment] 2015-08-03 07:03
forked the example repo from peec with the needed mods - https://github.com/bjornharrtell/ember-cli-polymer

**Comment by steven-ferguson** [comment] 2015-08-03 17:38
There still seem to be some issues with some of the elements such as paper-radio-button and paper-checkbox, but I think this is an issue on the Polymer side and not Ember (see https://github.com/PolymerElements/paper-radio-button/issues/26).

**Comment by matheusdavidson** [comment] 2015-08-03 18:05
Polymer elements that doesn't use <content> works, paper-radio-button, checkbox, drawer panel and others that use <content> do not work!

**Comment by bjornharrtell** [comment] 2015-08-03 19:41
Can confirm what @matheusdavidson reports in Chrome. However, it seems to work in Firefox. I suspect Ember JS and/or Polymer incompatibilities involving the built in shadow dom in Chrome (un-educated guess though).

**Comment by matheusdavidson** [comment] 2015-08-03 20:00
I've tried in all browsers, none of them works. Depending on your config(shadow or shady dom) it will look like is working, but after you transition into routes you'll see the same bug in all browsers!

I tried to use ember + polymer for a month with no success, i was told that polymer members are trying to create an interop to get things working but it should take some time.

**Comment by dnegstad** [comment] 2015-08-05 00:22
From what I've been able to see, the main issue is related to when Polymer's [ready](https://www.polymer-project.org/1.0/docs/devguide/registering-elements.html#ready-method) callback fires. Basically, if the polymer element is getting generated dynamically (say by glimmer), then ready will fire before the content is available. We've been able to work around the issue by monkey patching the broken components to use the [attached](https://www.polymer-project.org/1.0/docs/devguide/registering-elements.html#initialization-order) callback instead of ready, which fires when the element is actually inserted into the page dom.

**Comment by bjornharrtell** [comment] 2015-08-05 11:40
Thanks for that insight @dnegstad.

**Comment by steffenbrem** [comment] 2015-08-28 15:01
Is there currently a workaround to use for instance the `paper-input` element from Polymer inside Ember? Or are we in the dark here.

**Comment by peec** [comment] 2015-08-28 15:17
I concluded to use ember-paper addon instead which uses css from angular
material (which goes though googles ux team for validation).
28. aug. 2015 17.02 skrev "Steffen Brem" <notifications@github.com>:

**Comment by dunnkers** [comment] 2015-10-24 17:03
It's probably wise to set up some failing tests for this, in order to stimulate development on solving the issue.

**Comment by bjornharrtell** [comment] 2016-02-16 20:16
Revisited this yesterday and with up to date versions of the involved packages I can no longer reproduce any issues in Chrome or Firefox.

**Comment by dunnkers** [comment] 2016-03-05 02:23
Thanks for the heads up @bjornharrtell, I just did some tests with up to date packages as well. Whilst Safari and Firefox worked fine, Chrome only rendered correctly with Shadow DOM. Were you using Shady- or Shadow DOM?

**Comment by bjornharrtell** [comment] 2016-03-05 17:33
I have only tested with Shadow DOM.

**Comment by locks** [comment] 2016-04-17 09:04
I am closing this issue as after reading the discussion it seems more like a Chrome/Polymer issue than an Ember issue, feel free to correct me though.
Feel free to re-open the issue if you think it's still justified, thank you!

**Closed by locks** 2016-04-17 09:04 UTC

**Comment by jaichandra** [comment] 2016-09-09 17:57
The issue still exists with `paper-checkbox` and `paper-radio-button` and this happens only when transitioning between routes. Initially the components render fine, but after transitioning to another route and coming back, the components are broken. Here's the working example where you can see the issue.
[http://codepen.io/jaichandra/pen/jrOpab?editors=1010](url)

**Comment by dunnkers** [comment] 2016-09-09 18:02
Jai, try configuring polymer to use shadow dom. It should resolve some or
all issues.

**Comment by jaichandra** [comment] 2016-09-09 18:04
@dunnkers enabling Shadow DOM fixes the issue. But I don't think anyone is ready to use shadow DOM yet, because of browser compatibility and performance issues with polyfill.

**Comment by github-polymer-user** [comment] 2016-09-13 07:45
Everytone, who intersted, how to work with the Polymer and Ember:

Look, ma, it works: http://codepen.io/github-polymer-user/pen/jrWyrp

**Comment by github-polymer-user** [comment] 2016-09-13 07:46
@jaichandra You even do not need to enable Shadow DOM, really:

 http://codepen.io/github-polymer-user/pen/jrWyrp

**Comment by jaichandra** [comment] 2016-09-13 14:10
Thanks @github-polymer-user. But, I still think there's some work needed. Wrapping a Polymer component as another Polymer component doesn't look right. And other components (`paper-input` and `paper-button`) work without wrapping.

**Comment by matheusdavidson** [comment] 2016-09-13 14:16
Hi guys, i tried to work with ember and polymer in many ways, none of them was 100%. Best advice i have is: don't.

Try to use ember libraries such as ember paper, ember materialize.

I decided to go with angular + angular material and im happy today :)

**Comment by dunnkers** [comment] 2016-09-13 15:35
By the way, for importing Polymer into Ember you guys can use [ember-polymer](https://github.com/dunnkers/ember-polymer).

**Comment by github-polymer-user** [comment] 2016-09-14 09:36
@jailchandra, You really did not understand what is going on:

At first, wrapping Polymer elements into Polymer elements is perfectly 100% correct.
At second, This is not as simple as it seems, because of component initialization.
At third, you are usung Ember in sample which is actually have different handlebars idioms usage, than in Polymer, these mixins of Polymer components an Ember controllers are so much more confusing.

At last, you do not have to use server-side capable, SEO ready (FastBoot), framwork with polymer elements, which is also is client side 100% pure Web components (but Ember aren't).

I'm not wrapping Polymer, I was showing you that DOM manipulation differs of these two framework initialization sequence, because they are conficting for DOM resorces. 

Shadow DOM for Polymer and Ember differs, so you have to choose which pattern is best for you, but not both. You mentioned that other components is still works, but this is just because you didn't put any usage of component's Shadow DOM. 

You will take a 100% trouble every time, since you use transformations in both Ember and Polymer. It still works when used differently: either Ember components (routes, controllers, views, etc.) or Polymer components (routes, controllers, views, etc.) but not both. In such case as you show, yor comonents wirk incorrectly because they work with different shadow DOM respecively and not aware of existence of each other.

So this little code blocks in JS do the trick, and in my opinion the same:

It is better to distinguish between Polymer approach of component creation and Ember approach of declaration and initialization of components.

So, you have to use pure Polymer elements inside compound Polymer components, and create distinguised pure Ember components to utilise those Polymer elements.

**Do not create mixins. Period.**

**Comment by github-polymer-user** [comment] 2016-09-14 09:46
@jaichandra, You have to close this issue. As I already show you, Ember is 100% correctly renders Polymer elements.

Untill you write mixin components with Ember. Be 100% Ember and 100% Polymer, do not try to create monsters.

**Comment by github-polymer-user** [comment] 2016-09-14 09:52
@dunnkers, I saw it (library) and think that it is really too strange for me. Everything I need i can create using either Polymer oe Ember, creation of MVC with partial V- on Polymer seems for me so strange, that I can't say why for the sake of God you have to use this library, that you have mentioned

**Comment by jaichandra** [comment] 2016-09-14 17:09
Thanks @github-polymer-user for the detailed explanation. I get your point that this is an issue with the differences in Shadow DOM. I also see that they were trying to access DOM resources at the same level, which was causing conflicts. 

While, I'm not negating any of your concerns on using Polymer and Ember together, and I agree that I can't leverage complete Ember features when using Web components, I think I figured the root cause of this specific problem, based on your code sample. I am now sure that the problem is with Polymer's `<content></content>` tag rendering.

If we modify your example like below, you'll see the same issue again.

Template:
```
<dom-module id="x-foo">
  <template>
     <paper-checkbox checked="{{checked}}"> <content></content> </paper-checkbox>
  </template>
</dom-module>
```

Usage:
```
<x-foo checked= {{model.isAdministrator}} {{action "updateStatus" on="change"}}>Select</x-foo>
```
Notice the addition of `<content>` tag in the template and how I am trying to pass the content from the `<x-foo>` element.

This is surely a polymer issue to fix. Appreciate your patience.
