### ISSUE TITLE
Html filtered out of select views in ember canary

### ISSUE THREAD

**Issue by gonvaled** [emberjs/ember.js#10445] opened 2015-02-13 02:01 UTC
I have a select2 component with some html in the options / selection. This was working fine up to 1.9.1: the html markup is passed to the select element, and it can be styled using select2 semantics. See
[this jsbin](http://jsbin.com/galon/1). As you can see, the html is displayed as text (in a real select2 component it would be displayed as markup)

Now, in canary, the html markup is filtered out: see [here](http://jsbin.com/yituxu/1/)

What has happened? Why? Where is this documented? Is this intended, or a regression? Can it be activated again?

It takes sooo much effort to track this sudden changes ... (I thought I had introduced a bug into my app until I realized - some 5 hours later - that ember was silently swallowing the html)

**Comment by mixonic** [comment] 2015-02-13 02:05
@gonvaled this was definitely not intended behavior. The strings passed through to `optionLabelPath` should definitely not be considered safe by default.

If you make the `html` strings `Ember.Handlebars.SafeString` instances the will render as you expected:

http://jsbin.com/galon/1/edit?html,js,output

I'm going to close this issue. I consider this more of a bugfix than a regression. Feel free to re-open if I've missed something!

**Closed by mixonic** 2015-02-13 02:05 UTC

**Comment by gonvaled** [comment] 2015-02-13 02:09
@mixonic - Mmmm, ok, makes sense. It is a bit unfortunate that it was working for me by doing it wrong all along. BTW, your example was not linked correctly. If you could add the correct link it will help me to refactor my code.

**Comment by mixonic** [comment] 2015-02-13 02:11
@gonvaled here it is:

http://jsbin.com/ponematoka/1/edit?html,js,output

double-checked the link this time :-)

**Comment by gonvaled** [comment] 2015-02-13 02:20
@mixonic - Thanks, that seems ok! But the escapeMarkup filter in the select2 component must return a plain string. Do you know how to obtain the html string from a safestring?

**Comment by mixonic** [comment] 2015-02-13 02:43
@gonvaled I'm not familiar with the component you're referencing. You can call `toString()` on a `SafeString` object to get back an unescaped value.

**Comment by gonvaled** [comment] 2015-02-13 02:57
I am not able to get this working. I have added a simple select2 component:

I have these two test cases:

- [Good with ember 1.9.1 and no SafeString](http://jsbin.com/galon/2/). You can see here that plain strings work, SafeStrings don't
- [Bad with ember-canary and SafeString](http://jsbin.com/yituxu/2/): you can see that neither plain strings nor SafeStrings produce any html markup in the select2 component.

How can I restore in Ember canary the old behaviour where the select2 component is able to show the html markup?

**Comment by lolmaus** [comment] 2015-02-15 22:00
We're using Select2. This issue prevents us from upgrading to 1.10. Please reopen.

**Comment by gonvaled** [comment] 2015-02-16 12:06
@lolmaus : I have succeeded in upgrading by stopping to use my own Ember.Select derived Select2 view, and moving to the ember-select-2 add-on. The refactoring is not straightforward, though. The plus-side is that you are getting a (probably) more thorough-tested and feature-complete component.

**Comment by lolmaus** [comment] 2015-02-16 13:49
@gonvaled: so this issue does not happen with `ember-select-2`?

**Comment by gonvaled** [comment] 2015-02-16 18:58
I do not know how ember-select-2 is implemented, but the it does not have this issue.
