### ISSUE TITLE
binding variable between template and controller seems to be broken

### ISSUE THREAD

**Issue by jrm2k6** [emberjs/ember.js#12047] opened 2015-08-11 01:33 UTC
Updating from 1.13.6 to 1.13.7 seems to break the binding of variables between template and controller.
For example:

template.hbs:

```
{{input name="email" value=email}}
``` 

and declaring a property email on the controller doesn't update the email property of the controller when typing.

Worked just fine with versions below 1.13.7

**Comment by jcope2013** [comment] 2015-08-11 01:48
can you post a reproduction using http://ember-twiddle.com/ or http://emberjs.jsbin.com/?

**Comment by rwjblue** [comment] 2015-08-11 02:11
Seems to be working here: http://emberjs.jsbin.com/kenoha/edit?html,js,output

**Comment by adam-knights** [comment] 2015-08-11 10:46
Also hit this issue - http://emberjs.jsbin.com/titimu/edit?html,css,js,console,output I believe that shows it - if you toggle back to 1.13.6 the label updates, with 1.13.7 it does not.

**Comment by rwjblue** [comment] 2015-08-11 11:15
Changing  classNames= to class= should fix the issue. 

Likely a duplicate of #12008.

**Comment by rwjblue** [comment] 2015-08-11 11:16
(Still a regression though, I'm not saying that this is good :smile_cat: )

**Comment by blimmer** [comment] 2015-08-11 16:19
I'm able to repro it [twiddle](http://ember-twiddle.com/fc18ff5947a9dc7b940b), and as @rwjblue suggests, changing `classNames` to `class` fixes the problem.

**Closed** 2015-08-13 02:56 UTC
Labels: Needs Submitter Response
