### ISSUE TITLE
[Bug] Initializing a service does not work in ember glimmer components

### ISSUE THREAD

**Issue by rinoldsimon** [emberjs/ember.js#19505] opened 2021-04-23 04:39 UTC
### 🐞 Describe the Bug
Initializing a service does not work in ember glimmer components

### 🔬 Minimal Reproduction
**app/initializers/pandaui.js**

```
export function initialize( application ) {
  application.inject('route', 'pandaui', 'service:pandaui');
  application.inject('component', 'pandaui', 'service:pandaui');
  application.inject('controller', 'pandaui', 'service:pandaui');
}

export default {
  initialize
};
```

**app/pods/pandaui/service.js**
```
import Service from '@ember/service';

export default class PandauiService extends Service {
  block() {
    ...
  }

  unblock() {
    ...
  }
}
```

**app/components/test-form/component.js**

```
import Component from '@glimmer/component';
import { action } from '@ember/object';

export default class TestFormComponent extends Component {
  @action
  testPandaService() {
    this.pandaui.block() **ERROR: Cannot read property 'block' of undefined**
  }
}

```

### 😕 Actual Behavior
The line `this.pandaui.block()` throws `Cannot read property 'block' of undefined`
When I explicitly inject the service like below it works. 

```
import { inject as service } from '@ember/service';
@service pandaui;
```

### 🤔 Expected Behavior
When I initialize a service, I think it is not needed to inject explicitly 

Am i missing something? OR its a bug?

I think according to the doc that is all I need to do 
https://guides.emberjs.com/release/applications/initializers/#toc_application-initializers

### 🌍 Environment

- Ember: - 3.26.0
- Node.js/npm: - 10.16.3
- OS: - MacOS darwin x64
- Browser: - Chrome 89.0.4389.128

**Comment by rinoldsimon** [comment] 2021-04-23 04:39
Bug also reported in ember-cli https://github.com/ember-cli/ember-cli/issues/9508
I'm not sure which is the exact place to report this bug.

**Comment by tehmaestro** [comment] 2021-04-29 05:30
Hi, I faced this issue too, today
https://github.com/emberjs/rfcs/blob/master/text/0416-glimmer-components.md#type-injections
Seems it is on purpose.

**Comment by mcfiredrill** [comment] 2021-04-29 06:02
Hi, 

This is expected behaviour afaik, you only need to inject the service as you said.
```js
import { inject as service } from '@ember/service';
@service pandaui;
```

The initializer is not needed, is there a reason you want to keep using it?

**Comment by pzuraq** [comment] 2021-04-29 16:25
Beyond not being needed, implicit injections like the ones in the example have been _deprecated_ and will be removed in v4.0.0. Explicit injections, using the `@service` decorator, should be used instead.

**Comment by MelSumner** [comment] 2021-05-13 18:32
Here is the documentation you are looking for: https://guides.emberjs.com/release/services/#toc_accessing-services 

Please let us know if you have any other issues! Closing this issue for now.

**Closed by MelSumner** 2021-05-13 18:32 UTC

**Comment by rinoldsimon** [comment] 2021-05-14 11:15
So, there is a wrong example in the guide 
https://guides.emberjs.com/release/applications/initializers/#toc_application-initializers
```
export function initialize(application) {
  application.inject('route', 'cart', 'service:shopping-cart');
};

export default {
  initialize
};
```

Initializing a service(shopping-cart) won't work, since we need to inject it explicitly

**Comment by bertdeblock** [comment] 2021-05-14 11:28
That example is correct and should work. Though implicit injections have now been deprecated in v3.26, so at some point that example will be updated.

**Comment by rinoldsimon** [comment] 2021-05-14 12:38
I'm referring to the guide https://guides.emberjs.com/v3.26.0/applications/initializers/  (3.26.0) - which has implicit injection in the example.

According to the above discussions, implicit injection is not working in 3.26 and it has been deprecated in 3.26?  Correct?
So the guide for 3.26 https://guides.emberjs.com/v3.26.0/applications/initializers/  should not have that example? Correct?

**Comment by bertdeblock** [comment] 2021-05-14 12:44
Implicit injections should work, but not for Glimmer components (which is by design, mentioned [here](https://github.com/emberjs/ember.js/issues/19505#issuecomment-828950018)). The example in the guides shows an implicit injection for routes, so even though deprecated, that example is still correct AFAICT.
