### ISSUE TITLE
Triple braces sometimes render wrong

### ISSUE THREAD

**Issue by luxferresum** [emberjs/ember.js#14978] opened 2017-03-02 22:56 UTC
The following template: 

    <h1>head</h1>
    {{{model}}}
    <div>foot</div>

sometimes results in rendering the content of `model` *after* the `<div>foot</div>`.

Reproduction: https://ember-twiddle.com/2cadbc4061c5444402d3462afd892ce7?openFiles=templates.application.hbs%2C&route=%2Fmy-route%2F2

For reproduction first click "1", then click "2". It works if you directly click on the "2".

**Comment by Serabe** [comment] 2017-03-02 23:02
Thank you for your report!

**Comment by Panman8201** [comment] 2017-03-06 13:34
Is this related/duplicate of #14924 ? Does this also apply to a Component? Or just Controller/View related?

**Comment by luxferresum** [comment] 2017-03-07 09:10
Its not a duplicate, but it might be related. #14924 is double-rendering handlebars content, this here is rendering content at the wrong place. I was not yet able to reproduce for components, however I'm not sure what exactly is triggering it.

**Comment by zackthehuman** [comment] 2017-03-23 05:22
Could this be due to how we track bounds? If we render a bounds for `""` do we somehow get off track? /cc @krisselden @chancancode

**Comment by pixelhandler** [comment] 2018-09-14 19:04
@Panman8201 @Serabe @locks @luxferresum @pixelhandler @zackthehuman is this still an issue, perhaps we should close or create a new reproduction of this, what do you think?

**Comment by chancancode** [comment] 2018-09-25 01:08
Leaving this open until the fix lands in ember and backported into LTS

**Comment by chancancode** [comment] 2018-09-25 21:13
Sorry it took so long, this is fixed in 3.4.3

**Closed** 2018-09-25 21:13 UTC
Labels: Bug, Has Reproduction
