### ISSUE TITLE
Instance initializers, cannot read property register of undefined

### ISSUE THREAD

**Issue by tehmaestro** [emberjs/ember.js#11950] opened 2015-08-02 06:51 UTC
Hello. Trying to update to Ember 1.13 and I'm getting a lot of  `Cannot read property 'register' of undefined` . I've went through the docs, http://emberjs.com/deprecations/v1.x/ , and I read about instance initializers, but I don;t really understand how should I migrate my initializers in an Ember-CLI environment. Isn't `Clock` undefined in the example from the deprecation docs?  

Here's a sample initializer ... how do I migrate this over to using instance initializers so I don't get the errors anymore? Thanks.

```
import Ember from 'ember';

export function initialize( container, application ) {

    var myInit= Ember.Object.extend({
        init: function() {
               //doing something here
            var stuff = container.lookup("something:main").get("stuff");
        }
    });

    application.register('myInit:main', myInit);
    application.inject('route', 'myInit', 'myInit:main');
    application.inject('controller', 'myInit', 'myInit:main');

    application.inject('component', 'myInit', 'myInit:main');
}   
export default {
        name: 'myInit',
        after: ['otherInit'],
        initialize: initialize
    };
```

**Comment by rwjblue** [comment] 2015-08-03 14:23
Can you provide a runnable reproduction of this (ember-twiddle.com might be easier since its closer to a normal Ember CLI structure)?  I'm having trouble spotting the issue off the bat...

**Comment by rwjblue** [comment] 2015-08-03 14:36
Also, a bit of background: instance-initializers are only called with a single argument, not two.  This format is for "initializers" not "instance-initializers".  In general, initializers are good for registering and scheduling injections (what you are doing here), and instance-initializers are good for looking things up after all the registrations/injections are done.

Your example, doesn't really seem like it needs to look things up (it actually is for registering a new thing and setting up injection), so this belongs as a initializer (not an instance-initializer).

---

Can you describe the specific errors you are getting?  Assuming the initializer you pasted is what you are using as an initializer, `application.register` should definitely be a function...

**Comment by rwjblue** [comment] 2015-08-04 13:52
I'm going to go ahead and close this for now, I'm happy to reopen if you can answer the questions in my last comment...

**Closed by rwjblue** 2015-08-04 13:52 UTC
Labels: Needs Submitter Response
