### ISSUE TITLE
`.click()` not triggering in integration tests in Ember 2.8.0

### ISSUE THREAD

**Issue by alexlafroscia** [emberjs/ember.js#13932] opened 2016-07-28 07:04 UTC
I've noticed a [test failing](https://travis-ci.org/ember-cli/ember-ajax/jobs/147952354#L446) in Ember 2.8.0 (as well as the current canary build) in the `ember-ajax` repo.  I've traced it back to [this line here](https://github.com/ember-cli/ember-ajax/blob/badf9983b32a4f81b4e0a51fff3a06e44be76f31/tests/integration/components/async-widget-test.js#L135) where an element should be clicked.  That should trigger the `click()` event on the component in that test, but it doesn't.

Is that an intentional change or a bug?  If it's intentional, how would one define a general click handler instead?

**Comment by rwjblue** [comment] 2016-07-28 07:06
I believe that this is a duplicate of https://github.com/emberjs/ember.js/issues/13888, but haven't had a chance to dig in and confirm.

**Comment by Serabe** [comment] 2016-07-28 14:57
Closing as a duplicate given internally [`click()` calls `trigger`](https://github.com/jquery/jquery/blob/2.2-stable/src/event/alias.js#L8-L19).

```js
jQuery.each( ( "blur focus focusin focusout load resize scroll unload click dblclick " +
	"mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave " +
	"change select submit keydown keypress keyup error contextmenu" ).split( " " ),
	function( i, name ) {

	// Handle event binding
	jQuery.fn[ name ] = function( data, fn ) {
		return arguments.length > 0 ?
			this.on( name, null, data, fn ) :
			this.trigger( name );
	};
} );
```

**Closed by Serabe** 2016-07-28 14:57 UTC

**Comment by alexlafroscia** [comment] 2016-07-28 17:01
Thanks for triaging; I'll keep an eye on that issue for the fix.
