### ISSUE TITLE
[Bug] Inconsistent behavior between native classes and classic inhertiance

### ISSUE THREAD

**Issue by yads** [emberjs/ember.js#19420] opened 2021-02-22 19:39 UTC
### 🐞 Describe the Bug
Specifying a special field like `queryParams` in an inherited Controller class overrides the setting in a base Controller class when using native class syntax, but correctly merges when using classic `EmberObject.extend` syntax. e.g.

```
class BaseController extends Controller {
  queryParams = ['foo'];
}

class NotWorking extends BaseController {
  queryParams = ['fiz']
}

BaseController.extend({
  queryParams: ['fiz']
});
```

What is the idiomatic way to achieve correct queryParams usage using native classes?

### 🔬 Minimal Reproduction
I've created a twiddle here: https://ember-twiddle.com/1f4f55a6a76a5c4911772d89a8db7622

### 😕 Actual Behavior
navigating to `/my-route?foo=bar` displays a blank page, whereas navigating to `/working-route?foo=bar` displays `bar`

### 🤔 Expected Behavior
Both routes should display `bar`

### 🌍 Environment

- Ember: - at least in 3.22

### ➕ Additional Context
This could very well be a documentation issue, but none of the guides mention what the correct way to do this is.

**Comment by pzuraq** [comment] 2021-02-22 19:44
This is expected behavior. Native classes and classic classes have some fundamental differences, such as the behavior of class fields (there are no merged fields, as in classic classes).

If you want to merge the field, you can use the features of native classes to do so. For instance, you could do:

```js
class BaseController extends Controller {
  queryParams = ['foo'];
}

class Working extends BaseController {
  queryParams = this.queryParams.concat(['fiz']);
}
```

**Comment by yads** [comment] 2021-02-22 20:12
That's what I figured that this was likely expected behaviour for native classes and was likely just a documentation issue. (PS, I think you would do `queryParams = super.queryParams.concat(['fiz']);`)

**Comment by pzuraq** [comment] 2021-02-22 20:20
I believe it would be `this.queryParams` because by the time the subclass fields are assigning, the parent class has already assigned all class fields to the instance (e.g. `this`). `super` references the parent _prototype_, which is not applicable to class fields because they're always defined on the instance.

**Comment by yads** [comment] 2021-02-22 20:59
Interesting, I could not get it to work using `this`, but it did work with `super`.

**Comment by pzuraq** [comment] 2021-02-22 21:03
Seems like that could be a transpiler bug, doing it directly in Chrome (which natively supports class fields) yielded this result for me: 

![Screen Shot 2021-02-22 at 1 02 55 PM](https://user-images.githubusercontent.com/685518/108769807-5ae6d000-750e-11eb-870e-5e85d3204242.png)

But it's also possible Chrome is wrong here and it's a bug, new feature after all

**Comment by yads** [comment] 2021-02-22 21:08
Ah yes I believe you're right that it's a transpiler issue. Here's the 2 code fragments.

```
    // original
    queryParams = super.queryParams.concat(['q']);

    // generated
    constructor(...args) {
      super(...args);

      _defineProperty(this, "queryParams", super.queryParams.concat(['q']));
    }
```

So not sure how to address this then, since if the transpiler is ever fixed to use native syntax the original code will fail. Should I open another bug against a different module?

**Comment by pzuraq** [comment] 2021-02-22 21:10
Ok, actually looking at that snippet makes me think this _isn't_ a transpiler bug. Is the super class in this case defined using `Ember.Controller.extend()`? Because if so, what's happening is that `queryParams` _is_ being assigned to the prototype, so it actually is working as expected. In classic classes, properties are assigned to the prototype just like methods/accessors.

**Comment by yads** [comment] 2021-02-22 21:19
Yes that is correct the super class is defined using `Controller.extend(mixin1, mixin2)`. So that makes sense, I guess I should probably put a comment for all of these that when these get refactored to regular classes to switch them to this.

**Comment by locks** [comment] 2023-07-22 22:09
Thanks for the discussion! It sounds like y'all got to the bottom of the problem and the framework is working as intended so I'll be closing the issue.

**Closed by locks** 2023-07-22 22:09 UTC
