### ISSUE TITLE
Using a component inside a route template of the same name

### ISSUE THREAD

**Issue by wanxie** [emberjs/ember.js#14669] opened 2016-12-02 07:23 UTC
When using a component inside a route template where both have the same name, I got the following error in the console.

`jquery.js:3846 jQuery.Deferred exception: Maximum call stack size exceeded RangeError: Maximum call stack size exceeded`

For example using the POD structure:
`ember generate component aaa-bbb --pod` to generate
app/components/aaa-bbb/component.js
app/components/aaa-bbb/template.hbs

`ember generate route aaa-bbb --pod` to generate
app/aaa-bbb/route.js
app/aaa-bbb/template.hbs

Add `{{aaa-bbb}}` component to aaa-bbb route template and navigate to http://localhost:4200/aaa-bbb will cause an error.

**Comment by Serabe** [comment] 2016-12-02 10:33
Cannot reproduce in a [Twiddle](https://ember-twiddle.com/3b73659f4d84326729ad08c69c50c266?openFiles=templates.my-route.hbs%2C&route=%2Fmy-route). Might this be pod-related?

**Comment by rwjblue** [comment] 2016-12-02 13:45
Doesn't seem directly pods-related, but it could be.  The current resolver allows for duplication at various levels (this is true even with out "pods"), and it is possible that `app/aaa-bbb/template.hbs` has a higher priority for component lookup than `app/components/aaa-bbb/*`.  

If that is the case, then its likely not something that we will fix (since we are actively pushing for replacing this resolver for module unification support).

**Comment by Serabe** [comment] 2016-12-02 15:00
I can only reproduce this with a POD project. Should we close this then, @rwjblue ?

Thank you!

**Comment by rwjblue** [comment] 2016-12-02 15:11
Ya, seems unfortunate but unavoidable with the current system of resolution.

**Closed by rwjblue** 2016-12-02 15:11 UTC
Labels: Needs Bug Verification

**Comment by Leooo** [comment] 2016-12-11 14:14
Anyone else having this "Maximum call stack size exceeded" message while trying to destroy a component in Ember 2.9.0, pls let me know thanks.

**Comment by wouterds** [comment] 2017-06-07 13:05
@Leooo Yes, with Ember 2.8.3 though. So that's something that should have been fixed as of 2.9?

**Comment by corrspt** [comment] 2018-09-12 17:35
Just got bit by this (although in a weird way, the app simply didn't work very well - example: the content of my route was duplicated). I understand Module Unification is `right around the corner` but should the documentation say something about this?
