### ISSUE TITLE
Unable to transition to child route with mapped query parameters

### ISSUE THREAD

**Issue by eguitarz** [emberjs/ember.js#13612] opened 2016-06-06 20:37 UTC
Ember Twiddle: https://ember-twiddle.com/165676557d943e5cfa690261c6342c4d?openFiles=twiddle.json%2C

I have a parent and a nested child route, child route is fed with a query parameter. It works fine if I don't alias query parameter in child controller, but it raises exception if I mapped the query parameter into other name.

Which gave me an exception
>VM276 ember.debug.js:28535 Error while processing route: parent.index Assertion Failed: You're not allowed to have more than one controller property map to the same query param key, but both `parent.child:searchQuery` and `parent.child:searchQuery` map to `q`. You can fix this by mapping one of the controller properties to a different query param key via the `as` config option, e.g. `searchQuery: { as: 'other-searchQuery' }` Error: Assertion Failed: You're not allowed to have more than one controller property map to the same query param key, but both `parent.child:searchQuery` and `parent.child:searchQuery` map to `q`. You can fix this by mapping one of the controller properties to a different query param key via the `as` config option, e.g. `searchQuery: { as: 'other-searchQuery' }`

I have only one controller property map to query param key.

**Comment by acorncom** [comment] 2016-06-10 17:20
There have been regressions with query params since Ember 2.4.3 (more details here: https://github.com/emberjs/ember.js/pull/13600).  Would you check to see if your issue is resolved by shifting back to 2.4.3 or moving to 2.4.6 as mentioned here? https://github.com/emberjs/ember.js/issues/13258#issuecomment-224136445

A more permanent fix is in the works here: https://github.com/emberjs/ember.js/pull/13273

**Comment by acorncom** [comment] 2016-06-10 17:21
I'll close this for now, but please ask to re-open if you're running into something different

**Comment by eguitarz** [comment] 2016-06-10 23:02
@acorncom I tried on both 2.4.3 and 2.4.6 both are not working (and same error message). Seems this bug was lurking for a while. It was not working on 2.3.2 as well. This probably not related to the regression. Do you think it worth to re-open?

**Comment by cantsin** [comment] 2016-06-20 17:07
I just ran into this issue! I'm using 2.5.1. It looks like the only fix for this is to remove (or not to use) the mapped query parameter -- is that correct?

**Comment by raytiley** [comment] 2016-06-27 16:37
@eguitarz Can you test against latest. I think https://github.com/emberjs/ember.js/pull/13273 might address this issue. /CC @rwjblue

**Comment by rwjblue** [comment] 2016-06-27 17:36
Thanks @raytiley.  I'm going to close this for now, but I would love to land a new query params test to ensure we do not regress here in the future.  Feel free to ping me if you would like help on how that might look...

**Closed by rwjblue** 2016-06-27 17:36 UTC
Labels: Query Params

**Comment by eguitarz** [comment] 2016-06-27 17:39
@raytiley I tested on canary (2.7.0-canary+8e9ec7dd), and it works! Looking forward to next release!
