### ISSUE TITLE
1.12 instanceInitializer deferReadiness does not work

### ISSUE THREAD

**Issue by ssured** [emberjs/ember.js#11247] opened 2015-05-21 14:37 UTC
See on SO:
http://stackoverflow.com/questions/30276489/ember-1-12-0-instance-initializer-deferreadiness-method-doesnt-exist

The example in http://emberjs.com/blog/2015/05/13/ember-1-12-released.html mentions that deferReadiness is available on the instance, but it is not.
```javascript
// app/instance-initializers/sleep.js

export function initialize(application) {
  application.deferReadiness();
  // Wait 3s before continuing to boot the app
  Ember.run.later(application, 'advanceReadiness', 3000);
}

export default {
  name: 'sleep',
  initialize: initialize
};
```

How can we use deferReadiness in 1.12?

**Comment by mupkoo** [comment] 2015-05-22 13:41
I have the same problem. I was able to reproduce this in a JSBin
http://emberjs.jsbin.com/ninujejovo/3/edit?js,console,output

**Comment by gerry3** [comment] 2015-05-29 21:04
Same issue. Is there a workaround? Or a better way to do app setup before calling `advanceReadiness`?

We `deferReadiness`, then in an initializer: register a setup controller, look it up, and run some setup with a callback to `advanceReadiness`. As expected, this logs the deprecation stating we shouldn't do lookup in an initializer.

However, if we move the setup to an instance initializer, then the app doesn't load because the instance initializer is never called. If we move the `deferReadiness` into the instance initializer, then it's too late (and does nothing), and the app loads before our setup is called.

Where should we look up our setup controller if not in an initializer?

**Comment by arnaldo2792** [comment] 2015-05-30 01:06
@rwjblue could you include this one in the 1.12.1 milestone? :+1:

**Comment by rwjblue** [comment] 2015-05-30 02:07
I'm not 100% sure that it should be possible to defer readiness in an instance-initializer.  Currently, instance initializers are only called during the actual boot process and I believe that is too late to defer readiness.

Instance initializers are definitely where you should put code that needs to lookup various factories and whatnot from the container (so that it is after everything has been registered), but non-instance initializers still have a place as well (they are not completely deprecated).

One solution if you need to defer readiness AND populate things onto a factory in the container you could use both types of initializer (each for their specific purpose), something like the following:

http://emberjs.jsbin.com/rwjblue/563/edit?html,js,console

**Comment by intuitivepixel** [comment] 2015-05-31 09:48
@ssured @mupkoo @gerry3 does this not solve your problem http://emberjs.jsbin.com/madebuz/1/edit?js,output ? You can fetch data in the initializer, wait for the data to come back and register that on the controller? So there is no need for `advanceReadiness()` from inside an `instanceInitializer` right? Just my 2cents

**Comment by chvonrohr** [comment] 2015-06-01 12:45
I  used it to preload data in the initializer and pushed it to the store (store.pushPayload). Since its not possible to access the store in an initializer (container.lookup is forbidden) anymore and I can't deferReadiness in instanceInitializer, preloading data seems a pretty hard job now...  

How is this typically implemented?

**Comment by jakesjews** [comment] 2015-06-01 14:21
We fixed that issue by pulling in our data in the beforeModel hook of the application route

**Comment by gerry3** [comment] 2015-06-01 18:24
@intuitivepixel while a refactor like that would probably work, that requires moving some setup logic out of our setup controller and into the initializer.

big thanks to @jakesjews! we moved the code we had in the initializer to `beforeModel` of the application route and it just worked. now we don't even need to `deferReadiness`

@rwjblue might be worth adding something about using `beforeModel` of the application route to the deprecations here (when deferReadiness was being used) http://emberjs.com/deprecations/v1.x/#toc_access-to-instances-in-initializers

**Comment by steven-ferguson** [comment] 2015-06-16 20:23
The [example](http://emberjs.com/blog/2015/05/13/ember-1-12-released.html#toc_instance-initializers) in the docs for the 1.12 release uses ```app.deferReadiness```. Is the plan to support ```deferReadiness``` in instance initializers or are the docs wrong?

**Comment by typeoneerror** [comment] 2015-06-17 17:43
@intuitivepixel it'd solve the problem if I (personally) didn't need to use `container.lookup('store:main')`. How can we get access to the ember data store in an initializer if the lookup is no longer "available"?

**Comment by sandstrom** [comment] 2015-06-18 14:29
Making initializers promise-aware would solve some of these issues.

If a promise is returned, Ember would wait for it to resolve before running the next initializer in line (according to the DAG).

It would even be an improvement upon `deferReadiness`, because even with it it's not possible to do async things in initializers while retaining the DAG invokation order.

**Comment by OrKoN** [comment] 2015-06-18 14:39
We have a custom piece of code that provides promise-aware initializers https://github.com/n-fuse/ember-initializer-dm/blob/master/main.js. It would be very cool if this functionality were supported by Ember itself

**Comment by mixonic** [comment] 2015-06-18 20:55
I've updated the blog post at https://github.com/emberjs/website/pull/2216

There are three spots in the initial render sequence being discussed here. Each has a specific role:

* Application initializers are responsible for loading app code, and for setting up dependency injection. Because they load code, they require the ability to defer app boot.
* Instance initializers are specifically intended to run after the entire app is present. They are there to set initial configuration and values in prep for the app to handle a first request. In fastboot, this phase is run before each request.
* `beforeModel` and the async hooks in the application route will always run before anything else. This is absolutely where you should be putting things that require async on boot, as this is the phase were you can display a loading state and errors that occur here will result in the error handler being invoked. I strongly suspect most of the things you want to do async during instance initializers should be moved into the async hooks of the application route (the route in turn can access services and other parts of the framework as is appropriate).

I'm going to close this issue, as I'm fairly sure we will not consider this a bug. If I've missed some significant use-case that cannot be handled as described above, please re-open or reach out! Thanks.

**Closed by mixonic** 2015-06-18 20:55 UTC

**Comment by hhff** [comment] 2015-06-23 17:38
Thanks @mixonic!  I've got an addon related use case that doesn't feel quite "solved" by this thread.

I've got this [Spree Ember](https://github.com/hhff/spree-ember) lib.  It's a collection of 4 Ember CLI addons that work together to provide a fully functional Ember storefront for Spree.

There's a package called `spree-ember-checkouts`, that provides `currentOrder` to the `spree` service.  It needs to async load the `currentOrder` before the application is ready.

Moving this code into the `beforeModel` hook on the host application would mean:

1. The `spree-ember-storefront` package (the "parent" addon  to the checkouts package) would have to generate an application route for the developer's host application.
2. That application route would look something like this:
```
import Ember from 'ember';

export default Ember.Route.extend({
  beforeModel() {
    /* Returns a promise */
    return this.spree._setupCurrentOrder();
  }
});
```

The above doesn't feel great because it muddys the concerns of the the `storefront` and `checkouts` packages - storefront shouldn't really need to worry about initialization for its nested package.  

Further to that, I don't believe the developer should be conscious of this code.  As an addon developer, It's harder to provide a consistent experience (and harder to maintain the project in general) for developers if code that should be handled in the background by an addon has to be moved into the host application.

Any thoughts here?  Thanks so much for the hard work!

**Comment by mixonic** [comment] 2015-06-23 17:52
This would be excellent addition to the Engines RFC discussion: https://github.com/emberjs/rfcs/pull/10 /cc @tomdale

**Comment by hhff** [comment] 2015-06-23 18:03
Thanks @mixonic / @tomdale - I've been meaning to dig into that Engines RFC for a while - the Spree Ember lib is as close as I could get to building a fullblown Ember engine with Ember in its current iteration.

Am I right in saying the `generating` the application route option above in the host application is the only way I can move forward to supporting Ember 1.13 for now?

**Comment by mixonic** [comment] 2015-06-23 18:33
@hhff I would suggest making a mixin that can be added to the application controller. Two other thoughts:

* Add an auto-run blueprint that tries to generate an application view upon `ember install`. This would make things easy for devs without an existing view.
* Alternatively, during instanceInitialization you could lookup the factory for the application route then reopen it an add your mixin. This would automatically add your custom functionality, and presuming you use `_super` correctly it would just work.

**Comment by hhff** [comment] 2015-06-23 19:08
Yup - already got an auto-run blueprint happening, just trying to minimize the the surface exposed to the host application, mainly.

Ahh ok applying the mixin to the application route in an `instanceInitializer` sounds like the way to go.  I can do all of that from the `checkouts` package and the parent addon can be none the wiser.

I'll have a go at that and report back - I've tried something similar before without much luck.

**Comment by flyswatter** [comment] 2015-07-02 19:28
I just ran into this, thanks for the `beforeModel` on the `ApplicationRoute` idea.  Now I have it running, and then setting the async value on my old service, because I still need it available throughout the app :P 

I would love to see some kind of support for async, delaying instanceInitializers added back to Ember.

**Comment by tomdale** [comment] 2015-07-02 19:46
@flyswatter I personally think asynchronous instance initializers are a very bad idea (because they don't participate in the router promise chain) but I'd love to have a use case-driven discussion of how we can improve syntactic sugar for adding promises to the chain. 

FWIW in my apps that have asynchronous setup, I just give them a method that does it and returns a promise, then RSVP.all them:

```js
export default Route.extend({
  auth: service(),
  webSocket: service(),
  beforeModel() {
    let auth = this.get('auth');
    let webSocket = this.get('webSocket');

    return RSVP.all([ auth.setup(), webSocket.setup() ]);
  }
});
```

This has the same effects as async instance initializers without carving an entirely different path through the system.

**Comment by rwjblue** [comment] 2015-07-02 20:15
@tomdale's suggestion also has the benefit of not presenting a completely blank screen until the async is done (since you can use the loading templates).

**Comment by flyswatter** [comment] 2015-07-02 20:57
Hi @tomdale, zot zot.

That works fine.  I didn't realize initializers prevented even loading templates from taking place, so that's a good argument to continue this way and not look back, I think I was mostly holding to the semantics of "initialization".  I don't think I have a use case left that requires otherwise, short of *maybe* a note in the `initializers` docs on async transactions and this recommended approach.

**Comment by tomdale** [comment] 2015-07-02 22:33
![zotfingers](https://cloud.githubusercontent.com/assets/90888/8489371/b431481e-20cf-11e5-912b-b18c8310b8b5.png)

**Comment by hussfelt** [comment] 2015-08-05 11:25
@tomdale You told me about the above solution before, fair to say I never really understood how to get that working the same way as deferReadiness until now! :-)

I really think this deserves a separate blogpost or at least shed some light on the proper way of doing this!

Thanks for a short but awesome description on how to solve this! :+1:

**Comment by hussfelt** [comment] 2015-08-06 18:47
@tomdale I threw one together here, if someone has the same issue again - would you mind correcting me if something is wrong? Feel free to reuse anything if it makes sense and put it in an Ember context, I could take the post down :)

http://hussfelt.net/2015/08/06/how-to-stop-using-deferreadiness-and-advancereadiness-in-ember/

**Comment by hhff** [comment] 2015-08-06 18:56
In my Spree Ember lib I just have an array of promises that other spree-ember addons can push promises to in their initializers.  When the host app initializes it just waits for all of those promises to resolve in the application beforeModel hook with an RSVP all.  Super clean!

**Comment by hussfelt** [comment] 2015-08-06 19:28
@hhff sounds promising, could you extrapolate on that with some code? :)

**Comment by hhff** [comment] 2015-08-09 10:34
I'm actually still working on it in a local branch.  Will post it here when it's ready!

**Comment by tharrington1** [comment] 2016-03-27 08:11
I came across a use-case that seems to need async instance initializers to work. 

I'm helping build an ember app in the finance sector that has admin users and normal users (our customers). There are routes, controllers, etc that are admin only. Even if a normal user somehow manages to discover the admin stuff, our backend will block any attempted admin operation. However, this isn't enough. For our app to pass the security review, we need to not even send the admin parts of the app to the user until after authentication has happened. This means putting some of the define calls in the build's javascript output into a separate file that's served only after authentication occurs.

The solution I came up with was to override ember-cli's EmberApp.javascript function to split the broccoli tree so that it produces a main app file and a separate admin app file. Then when the user authenticates I do an Ember.$.loadScript call at the right time (in our ember-simple-auth authenticator). This call occurs at the beginning of the lookup('route:application').beforeModel promise chain.

This works for most cases. By the time a route from the admin script is needed, it's already been defined and therefore the resolver finds it and the right factory gets registered, instantiated and cached in the container.

The one case where it doesn't work is when a signed-in admin refreshes the page while at one of the admin-only routes. When the page loads again, ember looks up the admin route, doesn't find it, and auto-generates one to put in the container. This happens before the beforeModel hook is called on the application route. Since the admin app file is loaded in the beforeModel chain, the target admin route is defined too late. The resolver never looks it up again because the generated one is already registered.

Perhaps there's another solution, but one that I think would work is doing the session restore in an an instance initializer, and loading the extra admin js file at that point. That way, when the transition is constructed, the admin routes will all be defined and therefore properly put into the container by the resolver. Unfortunately, this would require async support in instance initializers, so it doesn't work. 

Another solution that might work is unregistering the target admin route in the beforeModel, but I think this would be messy because then I would have to maintain a separate list of routes that come from the admin app file.

I can also explore generating the index.html dynamically, so that for users with an authenticated  session and an admin role would get the extra script link, but I'm not sure this would be race-condition free since the ember app presumably starts as soon as the main app file loads. On slow connections the extra admin js file might not load in time for the resolve call.

I'd love to hear ideas about how to support this requirement. I'd rather not build a separate admin app because so much of the code is shared and I think it would be painful to manage this. Hacky ideas that work are okay for the short term. We're under a tight deadline to check the box on our review.

cc: @tomdale @rwjblue

**Comment by tharrington1** [comment] 2016-03-28 21:12
The solution I found was to keep the admin routes in the main app file. It's not ideal for us, so I'm still looking for a way to not load them until user authentication occurs. 

Just to update/clarify my original comment above: ember-simple-auth does session restore at the beginning of the applicationRoute.beforeModel() promise chain. Only after session restore are we able to know if the user is allowed to access the admin parts of the app, at which point we load them as a separate javascript file. But this separate javascript file cannot contain any of the admin routes because one or more of them may have already been resolved, not found, and auto-generated by ember.

What I'd like to be able to do is resolve the session in an instance initializer so that we can load the admin part of the app before the app finishes initializing. This would solve our problem nicely. However, we'd need the instance initializers to support deferReadiness and advanceReadiness. 

Is this enough of a use-case to reopen the discussion about whether ember should support async instance initializers?
