### ISSUE TITLE
Regular expression [regex] defined in config converts into empty POJO.

### ISSUE THREAD

**Issue by batjaa** [emberjs/ember.js#13593] opened 2016-06-03 14:58 UTC
Here's a repro https://github.com/batjaa/test-config-regex

As the title says, any regular expression [regex] that's defined in the config file gets converted into a POJO and is not possible to use from the application.

**Comment by Serabe** [comment] 2016-06-09 22:40
Thank you @batjaa for this report (and thank you for your PR #13609 too!). App configuration is serialized in JSON format, so you cannot add a regexp to it as is. If you are not using flags, you can just use the string and then build a RegExp. If you are using flags, you can serialize it as an object like:

```
myRegExp: {
  pattern: 'my pattern as a string',
  flags: 'collection of flags'
}
```

And then create the RegExp.

I am closing this since it is not a bug.

Thank you for the report!

**Closed by Serabe** 2016-06-09 22:40 UTC
