### ISSUE TITLE
Getting "Uncaught Error: infinite rendering invalidation detected" with 2.9-beta3

### ISSUE THREAD

**Issue by jrjohnson** [emberjs/ember.js#14351] opened 2016-09-25 23:10 UTC
In attempting to test compatibility with ember-beta I'm seeing an issue.  With 2.9-beta2 I was getting a white screen with no ember container and no content rendered.  With beta3 I'm getting a flash of the content followed by a white screen, but now I'm seeing the error "infinite rendering invalidation detected" in the console.

Code (with updated ember) is here: 
https://github.com/ilios/frontend/tree/ember-beta-test

Demo which shows error can be seen here: 
https://ember-beta-test--ilios-frontend.netlify.com

It does not show up on the login page, only post-authentication so you have to login.  You can do so with:
username: `demo_faculty1`
password: `demofaculty1`

The error seems to be present on every route.

I also tried a build with #master but it has the same error.  I'm not sure how to track down where the issues is occurring because the stack trace is just full of ember-debug lines, but I'm happy to provide any info or help.  I think my next step is to start pulling out individual addons to see if I can find a culprit unless someone else has seen this error or knows about it already.  It seems strange that the /login is not affected, but every other route is.

**Comment by fivetanley** [comment] 2016-09-28 20:54
this seems to happen with class based helpers (e.g. `Ember.Helper.extend` based helpers), our pages using https://github.com/fivetanley/ember-promise-helpers experience this error also. I'll see if I can dig in a bit more.

**Comment by fivetanley** [comment] 2016-09-28 21:01
I can reproduce locally on ember-promise-helpers with `ember try ember-beta test --server`

**Comment by snewcomer** [comment] 2016-10-10 15:40
This is something I am encountering quite often in my test suite.  Seems related to `run` wrapping an expression.  When removed, error goes away.

**Comment by adam-knights** [comment] 2016-10-12 11:43
@fivetanley I originally opened https://github.com/emberjs/ember.js/issues/14456, but I think it may be a dupe of this (although I see this in Ember 2.8, not just 2.9)

This is the twiddle: https://ember-twiddle.com/18b75f7761ba740567c1829660ce28e1?openFiles=templates.application.hbs%2C

To reproduce simply goto the application.hbs, and add the final {{/if}} **(warning this will cause your browser and computer to cry)**

**Comment by jrjohnson** [comment] 2016-10-24 22:33
I'm no longer seeing this error in my application with the release of 2.9.0. I'm inclined to close this as having been resolved elsewhere.  @fivetanley or @snewcomer - are you still seeing this issue in 2.9.0?

**Comment by fivetanley** [comment] 2016-10-24 22:35
@jrjohnson That's because 2.9.0 is basically 2.8.3. It does not use the new glimmer 2 rendering engine. @chancancode and I tracked this one down and I owe him some failing tests 😄

**Comment by jrjohnson** [comment] 2016-10-24 22:38
Ah!  I didn't know that.  I thought 2.9.0 included glimmer2 - I obviously missed that critical announcement.  I will leave this open then.  Thanks.

**Closed** 2016-10-26 22:36 UTC
Labels: Bug, Glimmer2, Has Reproduction, Regression

**Comment by chancancode** [comment] 2016-10-27 01:16
I believe this is fixed in #14520. I verified that it at least fixed @adam-knights' gist. @fivetanley @jrjohnson can you confirm? (The fix is available in `ember#beta` or `ember#2.10.0-beta.2` – I am in the middle of releasing the latter, but it'll probably be up by the time you see this.)

**Comment by chancancode** [comment] 2016-10-27 01:16
The actual fix (and tests) are in https://github.com/tildeio/glimmer/pull/337

**Comment by jrjohnson** [comment] 2016-10-27 03:05
@chancancode quick click around in my app and this appears to be fixed in `ember#2.10.0-beta.2`.  Thanks!

**Comment by Turbo87** [comment] 2016-11-11 15:24
@chancancode I'm running `2.10.0-beta.3` at the moment and some of my users still seem to be hitting this error. Can't reproduce locally unfortunately.

**Comment by acburdine** [comment] 2016-11-23 21:53
I am getting this error now when testing [Ghost-Admin](https://github.com/TryGhost/Ghost-Admin) on 2.10.0-beta.3. Tried going to 2.10.0-beta.2 as well, with the same result.

**Comment by Turbo87** [comment] 2016-11-23 22:03
@acburdine are you able to reproduce this consistently? could you write down some instruction on how to reproduce it?

**Comment by acburdine** [comment] 2016-11-23 22:06
yup - happens every time I render the page.

Repro steps:
- get Ghost itself set up
- update Ghost-Admin to 2.10.0-beta.3
- visit index page when you have >= 1 post

Currently I'm drilling down as to the cause of this. I think I've got it narrowed down to a specific component that's doing a `{{yield this}}` in its template

**Comment by acburdine** [comment] 2016-11-23 22:19
@Turbo87 I think I figured it out - the component I mentioned above was using some old code borrowed from ember-cli-active-link-wrapper and I'm assuming that's what broke it. Updating to use the actual ember-cli-active-link-wrapper fixed the issue

**Comment by Turbo87** [comment] 2016-11-23 22:38
hmm, I'm using `ember-cli-active-link-wrapper` in my app too. Some of my users are still hitting that error, but I haven't been able to reproduce it. It's possible that this addon is still doing some funky stuff...

**Comment by rwwagner90** [comment] 2016-12-02 15:37
Does anyone know some specific lines of code that are causing this issue? We have this error in a bunch of our tests, and I am not sure what is causing it.

**Comment by srvance** [comment] 2017-03-14 01:29
Similar issues in the above ember-bootstrap issue in the code that manages the same kind of behavior as `ember-cli-active-link-wrapper`.

**Comment by knownasilya** [comment] 2017-04-27 15:56
Also seeing this error after I updated to the latest cli version using ember-source. Seeing it in my app.
