### ISSUE TITLE
getOwner(this): inconsistent behavior for dev/prod

### ISSUE THREAD

**Issue by jamesarosen** [emberjs/ember.js#15507] opened 2017-07-14 15:51 UTC
I have a factory for typesafe enumerations:

```js
export default function typesafeEnum(ids, klass) {
  ids = array(ids);
  assert('ids must be an array of length > 0', ids.length > 0);
  klass = klass || Ember.Object;

  return ArrayProxy.extend({
    container: null, // <-- note this line

    content: computed(function() {
      const owner = getOwner(this);
      return ids.map((id) => {
        const result = klass.create({ id });
        setOwner(result, owner);
        return result;
      });
    })
  });
}
```

The `container: null` was originally there just to remind consumers that they had to provide one. Before Ember 1.13, when I created one of those things and passed in a `container`, everything worked fine. On Ember 1.13 in development and test mode, everything continued to work fine and emitted no warnings.

But when we hit production, this blew up [here](https://github.com/emberjs/ember.js/blob/v2.13.4/packages/container/lib/container.js#L551) because `getOwner(this)` was `undefined` on the `ArrayProxy` instance. Removing `container: null` fixed the problem.

It concerns me that Ember's core object classes have differing behavior in dev/test vs prod, especially since there aren't even any warnings for this in dev/test. (I'm not concerned with the change in behavior from 1.12 to 1.13. We were doing something weird. But our dev/test environments should have caught the problem during the upgrade.)

**Comment by stefanpenner** [comment] 2017-07-14 15:54
Thanks for reporting, good news it should be fixed!

duplicate of: 

* https://github.com/emberjs/ember.js/issues/15492
* https://github.com/emberjs/ember.js/issues/15468

Fixed by:

* https://github.com/emberjs/ember.js/pull/15502 (master branch)
* https://github.com/emberjs/ember.js/pull/15504 (backport to beta)
* https://github.com/emberjs/ember.js/pull/15505 (backport to release)

2.14.1 was deployed just (moments ago)

**Closed by stefanpenner** 2017-07-14 15:54 UTC

**Comment by stefanpenner** [comment] 2017-07-14 15:56
@jamesarosen the issue was a JSC JIT bug, so its hard to tell if your exact scenario was addressed by the work-around. Please give 2.14.1 a go, if it doesn't resolve it, comment here \w reproduction (if possible) and we can reopen.

**Comment by jamesarosen** [comment] 2017-07-14 16:36
> Please give 2.14.1 a go

We'll be doing that over the next few days I hope :)

**Comment by stefanpenner** [comment] 2017-07-14 16:41
@jamesarosen keep us posted
