### ISSUE TITLE
Add assertion that "classNames" property in components is an array, not a string

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember.js#15605] opened 2017-08-28 08:21 UTC
We've found several cases already where developers unknowingly used something like `classNames: 'foobar'` instead of `classNames: ['foobar']`, and the resulting error message only showed `TypeError: Object foobar has no method 'forEach'`. It would be great to add an assertion to the component constructor that asserts that `classNames` is actually an array.

**Comment by rwjblue** [comment] 2017-08-28 14:02
As I dug around for where that is being handled, I did find an assertion doing exactly what you were suggesting ([see here](https://github.com/emberjs/ember.js/blob/299c1ab3d804fd92b0ec9b9c2e7a1fa100335753/packages/ember-views/lib/mixins/class_names_support.js#L23)). Unfortunately, that assertion _never fires_ due to how `concatenatedProperties` [are constructed](https://github.com/emberjs/ember.js/blob/9057741de71a7b261ef13a09920fe472919dd68b/packages/ember-metal/lib/mixin.js#L137-L163) for `Ember.Component`. We initialize `classNames` and `classNameBindings` eagerly [here](https://github.com/emberjs/ember.js/blob/299c1ab3d804fd92b0ec9b9c2e7a1fa100335753/packages/ember-views/lib/mixins/class_names_support.js#L36) (so the base class always has an array) which means that when we extend to create our component [this line is executed](https://github.com/emberjs/ember.js/blob/9057741de71a7b261ef13a09920fe472919dd68b/packages/ember-metal/lib/mixin.js#L147) which means that this "just works"...

> We've found several cases already where developers unknowingly used something like classNames: 'foobar' instead of classNames: ['foobar'], and the resulting error message only showed TypeError: Object foobar has no method 'forEach'.

I'd love to see the full stack trace, [a quick reproduction twiddle](https://ember-twiddle.com/58deb667d90f1ea319d2b3df5bf74c2e?openFiles=components.foo-bar.js%2Ctemplates.components.foo-bar.hbs) does not emit an error when `classNames` is a string.

**Comment by Turbo87** [comment] 2017-08-28 14:28
> I'd love to see the full stack trace, a quick reproduction twiddle does not emit an error when classNames is a string.

funny enough I was not able to reproduce this either. in dev builds everything seems to work fine, but I've seen several bug reports from Sentry indicating that this was not working properly for everybody in production.

**Comment by Serabe** [comment] 2017-09-03 18:09
I test this and the production build does not show any error either.

**Comment by alvincrespo** [comment] 2017-09-08 22:23
I was just recently on a project where classNames is set to a string instead of an Array in the components respective `component.js`. Based on the conversation above, I'm assuming the assert thats in place should be causing a failure correctly?

**Comment by rwjblue** [comment] 2017-09-09 01:24
I believe that actually coerces `Component.extend({ classNames: 'lol' })` into an array (based on my findings that I tried to link and document in the comment above).

**Comment by Serabe** [comment] 2017-09-29 15:10
Has anybody been able to reproduce this?

**Comment by rwjblue** [comment] 2017-09-30 13:16
Closing for now. I’m happy to work on the messaging and/or identification of the failure scenario if we do end up with a reproduction...

**Closed by rwjblue** 2017-09-30 13:16 UTC
Labels: Needs Reproduction, Needs Submitter Response
