### ISSUE TITLE
TypeError: Cannot read property 'template' of null

### ISSUE THREAD

**Issue by jcbvm** [emberjs/ember.js#11703] opened 2015-07-09 07:27 UTC
Since 1.13.3 I get the following error which seems to be thrown somewhere deep in htmlbars `TypeError: Cannot read property 'template' of null`. Is this a known problem? If not, I have to investigate further where this is coming from.

Stacktrace:

    TypeError: Cannot read property 'template' of null
        at Ember.Object.extend._nodeTemplateName (<anonymous>:4122:43)
        at Ember.Object.extend._shouldShowNode (<anonymous>:3978:17)
        at <anonymous>:3949:18
        at Array.forEach (native)
        at Ember.Object.extend._appendNodeChildren (<anonymous>:3948:18)
        at <anonymous>:3954:16
        at Array.forEach (native)
        at Ember.Object.extend._appendNodeChildren (<anonymous>:3948:18)
        at Ember.Object.extend.viewTree (<anonymous>:3597:14)
        at <anonymous>:3553:25

**Comment by btecu** [comment] 2015-07-09 12:24
I've been randomly getting this. Can't find what the issue is.

**Comment by rwjblue** [comment] 2015-07-09 12:46
I don't recall another issue for this, thank you for reporting.

> I have to investigate further where this is coming from.

:+1: - To track this down we will need a reproduction.

**Comment by jcbvm** [comment] 2015-07-09 14:51
Will look further into it.

**Comment by btecu** [comment] 2015-07-09 18:32
Looks like when in Firefox the error is `renderNode.lastResult is null`.
Still, I don't know yet what's causing it.

**Comment by jcbvm** [comment] 2015-07-09 19:00
It seems like a timing issue, because the error pops up randomly, looks to me if it's trying to update the DOM which isn't existing anymore.

**Comment by btecu** [comment] 2015-07-09 19:24
That's what my guess was too, but it looks like the cause of my problem is `ember inspector`.
The issue seems to happen if I go at least once to the `ember inspector` tab. I'll get the errors immediately and every time I refresh or navigate until I close that page (doesn't matter if I change the tab in development tools). I never get this issue in IE - and now I understand why - because there is no `ember inspector` for IE.

@jcbvm can you check if this is the problem for you too?

**Comment by jcbvm** [comment] 2015-07-09 19:31
@btecu Ah, that's interesting, will look at it tomorrow when I have access to the code. Will let you know.

**Comment by rwjblue** [comment] 2015-07-09 19:34
@teddyzeenny - Is this something you have seen before?

**Comment by teddyzeenny** [comment] 2015-07-09 19:58
Yes. The error is now guarded against in https://github.com/emberjs/ember-inspector/pull/417. Not yet released.

**Comment by rwjblue** [comment] 2015-07-09 20:05
@teddyzeenny - Awesome, thank you!

@jcbvm - I'm going to close this issue, as this is fixed upstream...

**Closed by rwjblue** 2015-07-09 20:05 UTC

**Comment by jcbvm** [comment] 2015-07-09 20:10
Glad to know the cause of the problem, thanks all for helping.
