### ISSUE TITLE
Sticky query params broken with loading substate

### ISSUE THREAD

**Issue by tobymarsden** [emberjs/ember.js#12107] opened 2015-08-14 23:08 UTC
Related to #11857:

If a route has a dynamic segment, a query parameter, a child route with a slow-loading model and a loading template, the query parameter is no longer sticky.
#12037 fixed the JS error that was occurring in #11857, but didn't fix the underlying problem.

As far as I can trace back, [`transition` inside `setup` on Route](https://github.com/emberjs/ember.js/blob/v1.13.8/packages/ember-routing/lib/system/route.js#L1117) is null, when it shouldn't be.

Here's a fiddle (Ember Canary) with no loading substate, which has the correct sticky query params: 
http://jsfiddle.net/tobymarsden/x0rngqL2/

And here's a fiddle with a loading substate added, where the query params are no longer sticky:
http://jsfiddle.net/tobymarsden/963qt5p9/

**Comment by tobymarsden** [comment] 2015-11-22 22:59
Fiddles moved to Ember-Twiddle and updated to Ember 2.1.0:

**Here sticky query params are working:**
https://ember-twiddle.com/91e7b67f87afc0836c4f

**A loading template is added, and now query params are not sticky:**
https://ember-twiddle.com/5b5a761bf8ea50365d80

**Comment by workmanw** [comment] 2015-11-23 02:53
It's possible that #10945 is also related. It's kind of similar in that a transition inside of an existing transition usually (always?) results in an `abort` call. Though because this is complicated, I can't say for sure.

**Comment by thijsvdanker** [comment] 2016-04-20 12:37
I'm having the same problem and created these twiddles:

**Both a dynamic segment and a loading template => bug**
https://ember-twiddle.com/63153573fe0150b655613b0ce5e83771?openFiles=templates.main-route.hbs%2C

**Only dynamic segment, no loading template => works**
https://ember-twiddle.com/c8a25c0d17cd05119360fc470eba6d3c?openFiles=templates.main-route.hbs%2C&route=%2Fparent%2Fsub-route

**Only loading template, no dynamic segment => works**
https://ember-twiddle.com/5571992920996228f84bbe06cf7cdb26?openFiles=templates.main-route.hbs%2C&route=%2Fparent%2Fsub-route

**Comment by sunsetlincoln** [comment] 2016-04-20 12:53
@thijsvdanker Should `//this.transitionTo({ queryParams: { two: 'two' }});` be uncommented in `main-route.js` to demonstrate the issue?

**Comment by thijsvdanker** [comment] 2016-04-20 13:04
@sunsetlincoln the second transition is done in the main-route controller at this moment (reflecting my own code-base). I'll refactor it to the route to better demonstrate the issue.

**Comment by thijsvdanker** [comment] 2016-04-20 13:07
@sunsetlincoln refactor is done, both transitions now take place in `routes/main-route.js`

**Comment by akashdsouza** [comment] 2017-06-07 04:22
I'm having the same issue as well. From what I can tell, `values` being null in [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-routing/lib/system/route.js#L226) is what's causing the incorrect cache key to be set. While transitioning to a slow model with loading template, the `transition` object is undefined in the parent route's setup method and [this condition](https://github.com/emberjs/ember.js/blob/master/packages/ember-routing/lib/system/route.js#L1301) is never fulfilled.

**Comment by rwjblue** [comment] 2020-11-06 14:04
The reproduction test from @rlivsey (in #16986) was landed in https://github.com/emberjs/ember.js/pull/19249.

**Closed by rwjblue** 2020-11-06 14:04 UTC
Labels: Needs Bug Verification, Query Params
