### ISSUE TITLE
Ember 2.11 double forward slash causes application to break

### ISSUE THREAD

**Issue by sergproua** [emberjs/ember.js#14925] opened 2017-02-10 18:14 UTC
accidently entered double forward slash in path breaks the application

```http://localhost:4200//```
or 
```http://localhost:4200//some-route```

route error handler never gets called to recover

**Comment by locks** [comment] 2017-02-10 18:25
Duplicate of https://github.com/emberjs/ember.js/pull/11801-

**Comment by pixelhandler** [comment] 2017-02-10 21:49
@sergproua can you update your description to indicate what version of Ember you are using. If this you're using a current version of Ember then we may need to create a working example to reproduce the issue. As @locks indicated this seems to duplicate #10937.

**Comment by sergproua** [comment] 2017-02-13 18:28
Hi @pixelhandler, I've updated description and will play with Ember-twiddle to build a working example and will attach. There's an easier way to recreate a problem.
```
ember new test
cd test
ember s
```
just open a browser to http://localhost:4200://

**Comment by sergproua** [comment] 2017-02-13 18:35
#11801 is in fact a duplicate however is already closed, please advise what next steps are.

**Comment by stefanpenner** [comment] 2017-02-25 07:33
This seems legit!

Error message:

<img width="1483" alt="screen shot 2017-02-24 at 11 32 53 pm" src="https://cloud.githubusercontent.com/assets/1377/23329241/a4612120-fae9-11e6-85d8-f0023813d1b0.png">

**Comment by stefanpenner** [comment] 2017-02-25 08:05
potential fix: https://github.com/emberjs/ember.js/pull/14961

**Closed** 2017-04-05 17:53 UTC
Labels: Needs Bug Verification, Routing

**Comment by Exelord** [comment] 2019-08-02 18:42
This issue is still appearing in `v3.11.1`
