### ISSUE TITLE
TypeError: Cannot read property 'unchain' of undefined

### ISSUE THREAD

**Issue by ryanrishi** [emberjs/ember.js#15098] opened 2017-03-30 17:28 UTC
It looks like this error occurs when there is an observer on an aliased property.

[Here is a twiddle](https://ember-twiddle.com/1cb5cea91c573dcf535b76162bf1752d?openFiles=controllers.application.js%2C) that reproduces the issue in 2.12.0. I'm using 2.9.0 in my project, and it's happening there as well. Filter using the search box and sort using the table headers to reproduce the error.

There are no properties that start with a capital letter in that twiddle, which rules out a duplicate of #9851. There might be some internal property that is not calling `removeObserver`, so it may be related to #10717.

**Comment by pixelhandler** [comment] 2017-04-07 15:04
@ryanrishi it seems to be beaking on some logic around using this computed property in the filter mixing, `filterFunction: computed('filterProperties.[]',` the `unchain` method can't seem to find a node using the args for `filterProperties`, `[]`. Not sure about what is actually being done under the hood but that seems to be the troublesome part.

**Comment by pixelhandler** [comment] 2017-11-03 16:46
@ryanrishi any luck with using a current version of Ember, e.g. 2.16.x ?

**Comment by rwjblue** [comment] 2017-11-05 16:51
Seems to have the same issue on 2.16.2.  

@krisselden - If you have time, would you mind poking at this one?  🤕

**Comment by Allariel** [comment] 2017-12-15 07:06
Hi guys. Do you have any fix for this bug?

**Comment by pixelhandler** [comment] 2018-09-28 17:49
@Allariel @rwjblue @ryanrishi is this still an issue, perhaps we should close or create a new reproduction of this, what do you think?

**Comment by ryanrishi** [comment] 2018-10-24 18:53
@pixelhandler I believe this is still an issue—[here](https://ember-twiddle.com/8d533ef878f5020c665887cfb635d415?openFiles=twiddle.json%2C) is a twiddle reproducing the issue on Ember 2.18.

Haven't been able to figure out a fix. @VitaliyShevchenko what were you trying to develop when you encountered this? I was trying to have some sort of filterable and sortable list, so I'm thinking that this issue comes up when there is a computed property whose dependent key is another computed property.

**Comment by VitaliyShevchenko** [comment] 2018-10-25 12:18
@ryanrishi I just checked your twiddle. Please, take a look below code from your example:
`playlist: reads('sortedContent'),`
I changed it to **Ember.computed** :
``playlist: Ember.computed('sortedContent', function() {
               return this.get('sortedContent');
}),
``
And it's working now. 
Why are you using **read** alias for this things?
Except that, I saw, that you defined  **playlist** property in several mixins and in the application.js file. It can be some issues with that.

**Comment by pixelhandler** [comment] 2018-10-26 19:19
Closing for now, I don't believe this is a bug in Ember.

**Closed by pixelhandler** 2018-10-26 19:19 UTC
Labels: Has Reproduction, Needs Bug Verification

**Comment by ryanrishi** [comment] 2018-10-26 20:46
Thanks @VitaliyShevchenko for taking a look. I'm using `reads` so that the controller doesn't overwrite the `sortedContent` from the sortable mixin (which has `sortedContent: sort('sortableContent', 'sortKeys')`). This particular example doesn't do that, but in a larger application it may help to have `reads` in there so that code that uses the sortable mixin doesn't overwrite `sortedContent`. FWIW, using `computed.alias` instead of `reads` still results in the same error.

I believe this is a bug in Ember internals ([ember-metal chains](https://github.com/emberjs/ember.js/blob/f73d8440d19cf86a10c61ddb89d45881acfcf974/packages/%40ember/-internals/metal/lib/chains.ts#L273))

**Comment by kboucher** [comment] 2020-06-26 17:19
I recently encountered this issue in Ember 3.1.4. I have a lazy rendering mixin that references the data via a `records` property. Depending on where the mixin is used, a developer may need to alias the `records` property (for example to `filteredRecords`. This aliasing is working fine in several places, but in one particular location, it is throwing the `TypeError: Cannot read property 'unchain' of undefined ` error.

Simply changing the `alias` to a `computed` that simply returns `this.get('filteredRecords)` solves the issue.
