### ISSUE TITLE
{{#each}} helper does not update on Array Mixin

### ISSUE THREAD

**Issue by ssured** [emberjs/ember.js#10650] opened 2015-03-17 11:11 UTC
It seems the {{#each}} helper does not update on changes to objects implementing the Array or MutableArray mixin.

See http://emberjs.jsbin.com/gawiquhate/1/edit?html,js,output

**Comment by lolmaus** [comment] 2015-03-17 12:04
That's a duplicate of #10405, though the solution suggested there does not work in your JSBin, so the issue is legit.

@MiguelMadero, any suggestions?

**Comment by stefanpenner** [comment] 2015-07-08 05:25
@wycats although we want to kill this, we do likely need a way to broadcast this arbitrary enumerable/iterable has changed re-render me.

**Comment by rwjblue** [comment] 2016-04-18 04:37
My suggestion in "post glimmer" here would be to use a helper that properly subscribes to the array change events and recomputes:

```hbs
{{#each (rerender-on-array-change model) as |item|}}
{{/each}}
```

A class based helper (aka `Ember.Helper.extend()`) that subscribed to its first argument could always recompute and return a newly built array (forcing an intelligent rerender).  This is roughly what we did for reduced computed type things, and it has worked pretty well.

I'm going to close this for now, in favor of the solution I outlined above.

**Closed by rwjblue** 2016-04-18 04:37 UTC
Labels: Bug

**Comment by adamreisnz** [comment] 2017-06-20 01:48
@rwjblue has a solution for this been implemented yet somehow? Custom helpers still do not act on arrays that have been mutated without passing in another property like the array length in Ember 2.13.
