### ISSUE TITLE
Every Ember JS Bin example on the internet broken

### ISSUE THREAD

**Issue by christophermlne** [emberjs/ember.js#10930] opened 2015-04-22 12:26 UTC
... because the link to the latest Ember build is broken: http://builds.emberjs.com/ember-latest.js

I haven't seen a working Ember JS Bin example on the internet in about a week.

Possible to fix the Ember builds link?

**Comment by stefanpenner** [comment] 2015-04-22 12:32
> I haven't seen a working Ember JS Bin example on the internet in about a week.

http://emberjs.jsbin.com/?html,css,js,output seems to be working.

> Possible to fix the Ember builds link?

yup – @fivetanley / @rwjblue you two are likely most familiar with this part of the build, care to take a look?

**Comment by rwjblue** [comment] 2015-04-22 12:59
Duplicate of https://github.com/emberjs/ember.js/issues/10641.  `ember-latest.js` was not being updated (and had not been for quite a long time), and if we updated it again the JSBin/JSFiddles would still be broken (because they would need `ember-template-compiler.js` to be added).

**Comment by stefanpenner** [comment] 2015-04-22 14:05
so TL;DR ping to an exact version or deal with breakages over time.

**Closed by stefanpenner** 2015-04-22 14:05 UTC
