### ISSUE TITLE
2.8.0 causing loop when using contains within Ember.Debug.registerDeprecationHandler

### ISSUE THREAD

**Issue by jcbvm** [emberjs/ember.js#14249] opened 2016-09-09 17:06 UTC
When using `Enumerable.contains` within `Ember.Debug.registerDeprecationHandler`, a loop will happen causing a maximum callstack exceeded.

For exmaple:
```javascript
 const IGNORED_DEPRECATION_IDS = [
      'ember-views.render-double-modify',
      'ember-views.dispatching-modify-property'
 ];
 Ember.Debug.registerDeprecationHandler((message, options, next) => {
      if (options && IGNORED_DEPRECATION_IDS.contains(options.id)) return;
      next(message, options);
 });
```

Thing here is that contains will throw a warning, causing to enter the deprecation handler again and again and again...
This can easily be fixed by changing `contains` with `includes`.

Not a really big issue, but though it might be helpful to mention for people running into the same issue.

**Comment by pixelhandler** [comment] 2016-09-09 18:17
@jcbvm good point using `includes` instead of `contains` is the work around.

Not sure yet if contains will be deprecated in the future, but that is my assumption. So not sure that this will get priority for solving the issue with "contains throwing a warning".

**Comment by rwjblue** [comment] 2016-09-09 18:25
Yeah, the issue is that `contains` is deprecated so using a deprecated thing from inside a deprecation handler will be a recursive loop.  

I definitely appreciate this issue being opened (hopefully it shows up when folks search), but I don't think there is much we can do here to prevent a recursive loop so I'm going to go ahead and close this...

**Closed by rwjblue** 2016-09-09 18:25 UTC
Labels: Needs Bug Verification
