### ISSUE TITLE
Canary - generated controller using id not model.id

### ISSUE THREAD

**Issue by zyllorion** [emberjs/ember.js#10144] opened 2015-01-05 15:55 UTC
```
DEPRECATION: You attempted to access `id` from `(generated container.detail controller)`, but object proxying is deprecated. Please use `model.id` instead.
        at __exports__.default.Mixin.create.unknownProperty (http://localhost:4200/assets/vendor.js:43071:17)
        at get (http://localhost:4200/assets/vendor.js:30251:22)
        at Object.merge.valueFn (http://localhost:4200/assets/vendor.js:53367:18)
```
Obviously there's no controller.js, but there is a view.js with computed model.

**Comment by stefanpenner** [comment] 2015-01-05 15:56
can you provide a JSBIN

**Comment by zyllorion** [comment] 2015-01-05 16:05
Not easily, would have to try and recreate from scratch, too much company logic and complex models :(  Will see if I can recreate when I get a mo.  It's only a warning at the moment so not a show stopper.  Suspect it's just a case of adding model. in the generator code somewhere.
Happy to inspect and debug if you point me at what to look for :)

**Comment by stefanpenner** [comment] 2015-01-05 16:13
Without steps to reproduce and clarity of which versions you are using this issue isn't very actionable.

**Comment by zyllorion** [comment] 2015-01-05 16:42
Sorry, thought canary would be enough :)

DEBUG: Ember      : 1.11.0-beta.1+canary.111861f0
DEBUG: Ember Data : 1.0.0-beta.14.1
DEBUG: jQuery     : 1.11.2

Will take a quick look in the source to try and find the generator code then try and mock something up to reproduce.

**Comment by rwjblue** [comment] 2015-01-05 21:07
Duplicate of https://github.com/emberjs/ember.js/issues/10143.

**Closed by rwjblue** 2015-01-05 21:07 UTC

**Comment by rwjblue** [comment] 2015-01-05 21:13
Your `container.detail` template is using `id` instead of `model.id` (as the message indicates).

**Comment by zyllorion** [comment] 2015-01-06 09:23
Aha, it was a nested component.  Could the error message be enhanced to name the view/component with error?  Currently it says it's the controller which is a bit misleading.
Thanks for the help!
