### ISSUE TITLE
[REGRESSION]: Ember 1.11.0-beta.5 test hangs when element does not exist and trying to use the fillIn helper

### ISSUE THREAD

**Issue by williamsbdev** [emberjs/ember.js#10676] opened 2015-03-19 15:50 UTC
@jcttrll and I noticed that we are using the beta version of Ember 1.11.0-beta.5 and we have a test that is attempting to fillIn an element that does not exist on the page, the test hangs and will not run any other tests. In previous versions, the `fillIn` helper would alert you and let you know that the element does not exist and fail the test. This is only an issue when you have the `andThen` in the test. If there is no `andThen`, it will alert you that the element does not exist and fail the test.

```
test('do something', function(assert) {
    visit('/');
    fillIn('input.element-does-not-exist-on-page', 'wat');
    andThen(function() {
        assert.equal(1, 1);
    });
});
```

Thanks for all your work on this awesome project!

**Comment by camthompson** [comment] 2015-03-20 18:51
I've experience this issue as well, but it seems to be fixed in canary already.

**Comment by rwjblue** [comment] 2015-03-22 01:32
Confirmed.  Looking into this now...

Beta (fails): http://emberjs.jsbin.com/rwjblue/344/edit
Canary (doesn't stall): http://emberjs.jsbin.com/rwjblue/346/edit

**Comment by rwjblue** [comment] 2015-03-22 01:46
https://github.com/emberjs/ember.js/pull/10463 fixes the hanging test (which is why it is fixed on master).  I'm pulling that commit into beta, and marking this as closed.

**Closed by rwjblue** 2015-03-22 01:46 UTC
Labels: Bug, Regression

**Comment by williamsbdev** [comment] 2015-03-22 01:48
@rwjblue Thank you!
