### ISSUE TITLE
Template Compiler crashes on invalid template

### ISSUE THREAD

**Issue by Gaelan** [emberjs/ember.js#18817] opened 2020-03-13 23:47 UTC
# Steps to reproduce

In any ember project, paste the following into a template file: 
```
<div style={{html-safe concat ("background-color: " color.hex)}}></div>
```
[Twiddle](https://ember-twiddle.com/5a588221fdc55d0febd93650eae3a156?openFiles=templates.application%5C.hbs%2C)

# Expected behavior
Ember tells me that my syntax is invalid, in a proper error message with a line number.

# Actual behavior
Ember CLI gives the following output:
```
(node:97567) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at isAttrs (/Users/gaelan/src/maps/node_modules/ember-source/dist/ember-template-compiler.js:7104:26)
    at PathExpression (/Users/gaelan/src/maps/node_modules/ember-source/dist/ember-template-compiler.js:7092:15)
    at visitNode (/Users/gaelan/src/maps/node_modules/ember-source/dist/ember-template-compiler.js:5159:16)
    at visitKey (/Users/gaelan/src/maps/node_modules/ember-source/dist/ember-template-compiler.js:5217:20)
    at visitNode (/Users/gaelan/src/maps/node_modules/ember-source/dist/ember-template-compiler.js:5178:9)
    at visitArray (/Users/gaelan/src/maps/node_modules/ember-source/dist/ember-template-compiler.js:5233:20)
    at visitKey (/Users/gaelan/src/maps/node_modules/ember-source/dist/ember-template-compiler.js:5215:7)
    at visitNode (/Users/gaelan/src/maps/node_modules/ember-source/dist/ember-template-compiler.js:5178:9)
    at visitKey (/Users/gaelan/src/maps/node_modules/ember-source/dist/ember-template-compiler.js:5217:20)
    at visitNode (/Users/gaelan/src/maps/node_modules/ember-source/dist/ember-template-compiler.js:5178:9)
(node:97567) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:97567) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
A similar message appears in the browser console on Ember Twiddle.

**Comment by rwjblue** [comment] 2020-05-23 21:01
Ya, we should definitely fix. The issue is caused by this line:


https://github.com/emberjs/ember.js/blob/d96d9aad52e010da977d813f479494397ee53ec6/packages/ember-template-compiler/lib/plugins/transform-attrs-into-args.ts#L59

You can't assume that `.parts[0]` is a thing there (in this case you are passed a `StringLiteral` I think).

**Comment by locks** [comment] 2023-07-22 21:30
Fixed by linked PR.

**Closed by locks** 2023-07-22 21:30 UTC
Labels: Bug, Help Wanted
