### ISSUE TITLE
[Beta regression] attributeBindings bound to booleans act as properties instead of attributes

### ISSUE THREAD

**Issue by cibernox** [emberjs/ember.js#13628] opened 2016-06-09 14:58 UTC
In a component that binds the `disabled` attribute to an `aria-disabled` attribute like this

```
export default Component.extend({
  attributeBindings: [
    'disabled:aria-disabled'
  ]
});
```

In 2.6 it generated `<div aria-disabled="true / false"></div>` and in 2.7-beta.1 generates `<div aria-disabled></div>` (or just `<div></div>` when false).

Wether or not this is a fix of wrong behaviour or a not, I'm not sure, but is certainly different.

**Comment by rwjblue** [comment] 2016-06-09 15:01
Thank you for reporting. 

@krisselden / @mixonic - Thoughts?

**Comment by krisselden** [comment] 2016-06-09 15:02
This is a bugfix, it makes it align to the props first behavior when the fallback is taken.  When it takes the prop first route it does not generate the above.

**Comment by krisselden** [comment] 2016-06-09 15:07
@rwblue this was motivated by the fact that when you actually test the output which was not tested before you cannot get the test to pass in IE and in Edge + plus all other browsers when the prop is there. Also SSR won't match prop first output.

**Comment by cibernox** [comment] 2016-06-09 15:08
In the case of `aria-*`, I'm not sure if they are properties or attributes. 
In the case that they are properties that would be the right approach? Create N computed properties that basically do (`function() { return String(this.get('required')) }`)? Very verbose.

Given that the feature is named `attributeBindings` i'd expect those to be treated as attributes, and maybe have a `propertiesBinding` that are treated like properties.

**Comment by pixelhandler** [comment] 2016-06-09 17:14
@cibernox @krisselden this may be related too #13537

**Comment by cibernox** [comment] 2016-06-09 22:18
Just some insights extracted from a loooooong discussion about this topic in slack.

While in properties, the distinction between attribute and property is irrelevant. p.e. `<iinput required="true">` and `<input required>` and even `<input required="false" >` both all required fields because the sole presence of the property is an indicator, in attributes that is not the case.

The only examples I can think about where is maters is  `aria-*` attributes, where `<div aria-required>` is not the same than `<div aria-required="true">` (the first is the first is not required, the second is).

In those cases, the boolean value has to be converted to the string `"true"` in order to generate `aria-*="true"`. While this is a bit verbose, a computed property macro and dry it.


```js
function trueStringOrNull(path) {
  return computed(path, function() {
    return this.get(path) ? 'true' : null;
  });
}

export default Component.extend({
  attributeBindings: [
    'aria-required',
    'aria-expanded',
    'aria-invalid'
  ],
  // CPs
  'aria-required': trueStringOrNull('required'),
  'aria-expanded': trueStringOrNull('dropdown.isOpen'),
  'aria-invalid': trueStringOrNull('ariaInvalid')
});
```

**Comment by rwjblue** [comment] 2016-06-10 00:11
Thanks for the summary @cibernox. I discussed a solution for aria-* attributes with @krisselden this afternoon and will take a stab at a solution tonight/tomorrow morning.

**Comment by rwjblue** [comment] 2016-09-13 03:44
I believe that it is still something we should make easier, but it isn't affecting many folks. I'm going to close this for now.

**Comment by nathanhammond** [comment] 2016-10-09 18:38
So this should still be addressed. Given Glimmer:

- [Provide messaging in dev to get people to do the right thing.](https://github.com/emberjs/ember.js/blob/master/packages/ember-glimmer/lib/environment.js#L396)
- _Possibly_ add in an `aria-*` coercion opcode if we can detect it at build time.
- Never add it into the `attributeBindings` hot path because that would be sad. (edited)

/cc @cibernox @rwjblue @les2

**Comment by pixelhandler** [comment] 2018-09-14 17:04
@cibernox @rwjblue @nathanhammond @krisselden is this still an issue, perhaps we should close or create a new reproduction of this, what do you think?

**Comment by cibernox** [comment] 2018-09-14 17:07
I believe it was never fixed, but by now reverting to the old behavior would be MUCH worse than leave things as they are. I vote cose it.

**Comment by pixelhandler** [comment] 2018-09-14 18:50
@cibernox thanks, closing

**Closed by pixelhandler** 2018-09-14 18:50 UTC
Labels: Regression
