### ISSUE TITLE
[Bug] `@model` and `this.model` have different values

### ISSUE THREAD

**Issue by kaermorchen** [emberjs/ember.js#19290] opened 2020-12-01 08:57 UTC
### 🐞 Describe the Bug
`@model` and `this.model` have different values if a route has a `setupController` hook

### 🔬 Minimal Reproduction
https://ember-twiddle.com/ba66bc82501bdc851a5041e466ffc94d

### 🤔 Expected Behavior
`@model` and `this.model` should have a same value

### 🌍 Environment
- Ember: - 3.22.0
- Node.js/npm: - 14.11.0/6.14.8
- OS: - linux x64
- Browser: - Firefox

**Comment by lolmaus** [comment] 2020-12-01 09:06
My finding is that `@model` is an alias for `this.attrs.model`.

PS I believe that the introduction of `@` in classic components (and controllers?!) was a mistake. It creates ambiguity that is hard to teach and have frustrated even experienced developers at least once.

**Comment by pzuraq** [comment] 2020-12-01 18:00
@lolmaus this is correct. FWIW, it would be more difficult to _disable_ these features in classic templates than it is to allow them to work, even if they have different meanings, which I imagine played into the decision to allow them. Either way, the feature exists, so I think the best thing to do is move forward and get to deprecating classic components and controllers sooner rather than later 😄 

@kaermorchen I'm not 100% sure, but I don't believe this is a bug, for the reason @lolmaus stated. `@model` refers directly to the model value that the route was loaded with, e.g. the one returned from the `model()` hook on the route, which cannot be changed. `this.model` refers the the value on the controller, which can be changed, for instance via `setupController`. While somewhat confusing, I think this is the correct behavior, and in general if you are moving toward using `@model` I would recommend removing usage of `setupController`.

**Comment by lolmaus** [comment] 2020-12-02 08:00
@pzuraq Though you have explained why it works as it works, I believe this does not resolve the problem.

I'm absolutely certain that no newbie developer will be aware the difference in the behavior between `this.model` and `@model`. The ones to reach `setupController` documentation are just unlucky because it only makes things worse for them.

In fact, in our local Ember chatroom, this issue was a surprise for everyone, including all matured Ember devs present.

Sure, deprecating controllers would resolve this issue as `@model` will be removed from the guides (or replaced with `@model` on a Glimmer component where no ambiguity exists). But realistically, controllers aren't going anywhere anytime soon.

I believe, the right vector of attacking this issue is addressing the ambiguity of `@` in controllers and Classic components.

**Comment by pzuraq** [comment] 2020-12-04 00:39
@lolmaus I actually believe controllers may be deprecatable sooner rather than later. The only real blocker is query parameters, and the recent discussions on the core team have been about how we can bridge this gap. It shouldn't be too difficult, in the end.

> I believe, the right vector of attacking this issue is addressing the ambiguity of @ in controllers and Classic components.

Can you say more here? The current behavior is spec'd public API, so unfortunately even if we did decided we would like to change it, it's not going to be possible to do so. Do you mean addressing this in documentation?

**Comment by lolmaus** [comment] 2020-12-04 06:57
> I actually believe controllers may be deprecatable sooner rather than later. 

Woah! That's exciting news.

I personally love controllers and don't share the urge to deprecate them. But I can totally see how removing controllers from the equation makes it easier for newbies to wrap their heads around the framework. It also stops guiding newbies towards incorrectly treating Ember as an MVC framework.

***

> The only real blocker is query parameters

I think that there should be some coupling between routes and root components. `setupController` is a notorious footgun (and this issue is a surprising new way), but some tricky cases still require it. I personally use `setupController` in a custom route subclass that enables `setup` and `teardown` hooks on controllers. I  wonder what the alternative will be, modifiers? Will they receive route arguments such as transition?

***

> Can you say more here? The current behavior is spec'd public API, so unfortunately even if we did decided we would like to change it, it's not going to be possible to do so. Do you mean addressing this in documentation?

Yes. It must be made very clearly that there is a conflict between `this.foo` and `this.attrs.foo` in Classic components, and even controllers as it turns out. It must be explained what the exact mechanism there is: is one property shadowing the other, or is it overwriting and in what direction, etc. To this point I still don't fully understand the mechanism, and naturally I resolved my frustration by not using `@` in Classic components.

Additionally, I think one of the following recommendations must be made, for the sake of avoiding potential frustration:

* either to never have the same property name in both `this.X` and `this.attrs.X`;
* or to never use `@` in the templates of Classic components and controllers.

Since I love the ability to set a default value on a Classic component with a simple property, my preference is strongly with the latter approach. That is, in all legacy projects that still use Classic components.

PS Sadly, Glimmer components don't offer a handy way of specifying default values for arguments, and a boilerplatey getter must be used instead (four lines of code, including a linebreak!). @simonihmig has made a handy decorator to resolve this. Should we extract it into an addon?

**Comment by locks** [comment] 2020-12-04 08:56
As explained in the thread, this behavior is by design and [is mentioned in the RFC](https://github.com/emberjs/rfcs/blob/master/text/0523-model-argument-for-route-templates.md#drawbacks). Thanks for reporting, and I hope the explanation is clear!

**Closed by locks** 2020-12-04 08:56 UTC
