### ISSUE TITLE
Current route name not easily accessible within Router#didTransition hook

### ISSUE THREAD

**Issue by diazruy** [emberjs/ember.js#10180] opened 2015-01-09 22:35 UTC
## The Problem
Under certain circumstances, it is desirable to have some logic in the `Router#didTransition` hook based on what the previous/current route is. Currently, the only way to obtain this is through the container 
```javascript
App.__container__.lookup("controller:application").get("currentRouteName")`
```

## The Request
Would it be possible to get this info as an argument to the callback hook? Maybe even a Transition object indicating the from/to routes?

## The Back Story
The use case that led me to this scenario was trying to get Google Analytics tracking on my app and doing something like the [Ember Guides suggest](http://emberjs.com/guides/cookbook/helpers_and_components/adding_google_analytics_tracking/). The problem I was running into was that I was getting events doubled up whenever a slow transition occured. This is because `didTransition` is firing once for the `loading` substate and a second time once the model promise has resolved, which is desirable and correct behaviour. However, I need to ignore any transition to a route that matches `/\.loading$/` for page view tracking purposes:

```javascript
App.Router.reopen({
  notifyGoogleAnalytics: function() {
    // Get current route name the "hacky" way
    currentRoute = App.__container__.lookup('controller:application').get('currentRouteName');

    if (!currentRoute.match(/\.loading$/)) {
      // Track pageview only if not a `loading` substate
      return ga('send', 'pageview', {
          'page': this.get('url'),
          'title': this.get('url')
        });
    }
  }.on('didTransition')
});
```

Ideally, this could be a little nicer with something like:
```javascript
App.Router.reopen({
  notifyGoogleAnalytics: function(transition) { // Assuming transition = {from: 'original.route', to: 'target.route'}
    // Obtain the current route from the arguments, or from some property on the Router
    currentRoute = transition.to;

    if (!currentRoute.match(/\.loading$/)) {
      return ga('send', 'pageview', {
          'page': this.get('url'),
          'title': this.get('url')
        });
    }
  }.on('didTransition')
});
```

**Comment by ahacking** [comment] 2015-01-10 06:38
Is there a reason you can't observe ``currentRouteName`` or ``currentPath`` on ApplicationController ?

Guide: http://emberjs.com/guides/understanding-ember/debugging/

**Comment by asakusuma** [comment] 2015-01-16 00:18
+1. I'm doing the same thing with the container lookup. It works, but it'd be nice to not have to do that.

Also I'd be nice to have access to the actual Ember.Route object.

**Comment by mmun** [comment] 2015-07-08 04:56
1. In theory you could use `Ember.Route#didTransition` but it seems to be called before the transition is complete (specifically currentRouteName on the application controller hasn't updated: http://emberjs.jsbin.com/yafocejime/edit?html,css,js,output)
2. In the future you'll be able to inject a routing service instead of having to go through the application controller.

**Comment by rafael-paiva** [comment] 2016-01-11 16:38
I'm facing the same problem as @mmun mentioned.

For my specific case I need to show a modal after every transition, except for one route (checkout). My solution is to cover this modal appearance on Application's didTransition hook. The problem is that `currentPath` returns the previous path at the time `didTransition` is called (also URL is not updated yet, so checking `ocation.pathname` is not an option either), and I also don't want to hack this with `run.next`.

**Comment by acorncom** [comment] 2016-04-29 23:30
We (the ember triage team) have started asking folks to either comment on existing RFCs related to their issue or to open a new issue about the desired feature in the RFC repo: https://github.com/emberjs/rfcs/issues  As this seems to fit better there, I'll go ahead and close this for now.  Please comment here if you disagree! 👍

**Closed by acorncom** 2016-04-29 23:30 UTC
Labels: Feature, Needs Label Review

**Comment by tschoartschi** [comment] 2017-03-16 11:38
I'm also experiencing the same problem as @mmun described. 
> 1. In theory you could use Ember.Route#didTransition but it seems to be called before the transition is complete (specifically currentRouteName on the application controller hasn't updated: http://emberjs.jsbin.com/yafocejime/edit?html,css,js,output)
> 2. In the future you'll be able to inject a routing service instead of having to go through the application controller.

@acorncom is this a bug or intended behavior? After ```didTransition``` I would expect the ```currentPath``` to be the actual ```currentPath``` and not one behind.
