### ISSUE TITLE
Ember.assert is not logging to console when thrown in Ember-2.8.0

### ISSUE THREAD

**Issue by tdyer-aio** [emberjs/ember.js#14328] opened 2016-09-21 16:24 UTC
When throwing an Ember.assert from within a component's `init` method nothing will be logged to the console, but rendering of that component is stopped.

Expected: logged exception with message from Ember.assert is logged to console

Actual: no message is logged to console, and rendering is stopped due to exception handling.

**Comment by rwjblue** [comment] 2016-09-21 17:00
I believe this is a duplicate of https://github.com/emberjs/ember.js/issues/14309.  As I mentioned in that issue, we need a reproduction to be able to track it down and fix.

Closing this issue to track in the other one...

**Closed by rwjblue** 2016-09-21 17:00 UTC

**Comment by tdyer-aio** [comment] 2016-09-21 17:23
sounds good. I have been working on reproducing at https://ember-twiddle.com/c42e29e87484ad4e153d8b0b5f659ecf but i can't... one thing i know is we are getting some warnings about modifying fields twice in a single render. I'm not sure if that may be related.

**Comment by rwjblue** [comment] 2016-09-21 17:24
TBH, since we don't know what is actually the culprit here, I would try to reproduce in an environment closer to your app (i.e. an actual ember-cli app).  Many other things could be happening on twiddle to make it ever so slightly different and harder to track down...

**Comment by tdyer-aio** [comment] 2016-09-26 12:15
looks like it may have been caused by https://github.com/emberjs/data/pull/4537
