### ISSUE TITLE
[3.13-beta] CP not recomputing when dependent key is not read from

### ISSUE THREAD

**Issue by simonihmig** [emberjs/ember.js#18264] opened 2019-08-14 07:37 UTC
It seems the changes for tracked properties (I assume) have caused an edge case to fail, which could be seen as a regression!? 

I have a CP that declares a dependency on a key but does not read from it. It still recomputed whenever the dependency changed, until the latest 3.12-beta/canary. 

The use case here was that I wanted the CP to return the value of `router.isActive()`, which obviously is an imperative API, so I declared a dependency on `router.currentURL` to make sure it gets properly recomputed. As said before this worked until now. 

Here is the current (now failing) code: https://github.com/kaliber5/ember-bootstrap/blob/10c7bb9597bfa1381e08572bb9f0a100deb7320c/addon/components/base/bs-nav/item.js#L88-L109, and this is a fix/workaround by making sure that `router.currentURL` is read from (although the value is not needed): https://github.com/kaliber5/ember-bootstrap/pull/871

/cc @pzuraq

**Comment by pzuraq** [comment] 2019-08-14 15:16
Hey! So we are absolutely aware of this case, and we worked really hard to try to match the original semantics as closely as possible. I believe we even have tests for this behavior in general. It seems like you may be encountering an edge case of the edge case, can you try to make a reproduction/test case for us to take a look at? I can try to dig in once I’ve landed a few other PRs, but a repro/test would really help speed things up 😄

**Comment by simonihmig** [comment] 2019-08-14 20:15
> can you try to make a reproduction/test case for us to take a look at

I hope so and would love to, but I cannot promise due to lack of time currently. There is a reproduction available in form of `ember-bootstrap` - though far from being "minimal" :wink:, where this bug is making [this test](https://github.com/kaliber5/ember-bootstrap/blob/master/tests/acceptance/bs-nav-link-test.js#L19) fail. (see also the above links)

**Comment by anehx** [comment] 2019-10-21 13:13
I also ran into this issue. In my case I'm computing to an intermediary property (which is suggested [here](https://github.com/emberjs/ember.js/blob/338cfa6db1d29de4f17611709340591e68fb6cb9/packages/%40ember/-internals/metal/lib/computed.ts#L463)) but I'm not reading it. The intermediary property is a `reads` solely used for the computation and is never directly used.

**Comment by rwjblue** [comment] 2019-10-23 14:39
I think the path forward here is for someone to create a reproduction so we can dig into it.

**Comment by sandstrom** [comment] 2023-06-27 18:46
Closing since tracked properties is the way forward.

**Closed** 2023-06-27 18:45 UTC
