### ISSUE TITLE
[Bug] Imported `LinkTo` component is not a component class

### ISSUE THREAD

**Issue by kaermorchen** [emberjs/ember.js#20182] opened 2022-09-04 07:54 UTC
### 🐞 Describe the Bug
Imported `LinkTo` component is not a component class

### 🔬 Minimal Reproduction
[Link](https://limber.glimdown.com/edit?format=glimdown&t=%23%20Reproduction%20maybe%20LinkTo%20bug%0A%0A%60%60%60gjs%20live%20preview%0Aimport%20%7B%20LinkTo%20%7D%20from%20%27%40ember%2Frouting%27%3B%0A%0Aexport%20default%20class%20LinkToButton%20extends%20LinkTo%20%7B%0A%20%20get%20class()%20%7B%0A%20%20%20%20%20let%20classes%20%3D%20this.super()%3B%0A%0A%20%20%20%20%20classes%20%2B%3D%20%60%20button%60%3B%0A%0A%20%20%20%20%20return%20classes%3B%0A%20%20%7D%0A%7D%0A%60%60%60%0A)
```js
import { LinkTo } from '@ember/routing';

export default class LinkToButton extends LinkTo {
  get class() {
    let classes = this.super();

    classes += ` button`;

    return classes;
  }
}
```

### 😕 Actual Behavior
When I import `LinkTo` from `@ember/routing` and extend it, I get an error `LinkTo is not a constructor`. `LinkTo` looks like a component and works well in [strict mode](https://github.com/emberjs/ember.js/blob/master/packages/@ember/-internals/glimmer/tests/integration/components/strict-mode-test.js), but it is internal component. This can lead to confusions.

### 🤔 Expected Behavior
I think all developers will expect that `LinkTo` and other internal components should work as a component.

### 🌍 Environment

- Ember: 4.6

### ➕ Additional Context
May be it is not a bug, more like unexpected behavior.

**Comment by bertdeblock** [comment] 2022-09-05 10:10
Reading the [RFC](https://rfcs.emberjs.com/id/0671-modernize-built-in-components-1/#detailed-design), this seems to be by design:

```
Note that in accordance with RFC #496, the following import paths will be made available
for use in strict mode:

- Input (import { Input } from '@ember/component)
- LinkTo (import { LinkTo } from '@ember/routing)
- Textarea (import { Textarea } from '@ember/component')

However, unlike the deprecated import paths in group 1, these modules provide opaque
values that are intended for use in templates only. Since they do not expose the implementation
details of the built-in components, these new import paths do not have the same issue described
in this RFC.
```

I.e. sub-classing is not possible / allowed.

**Comment by chriskrycho** [comment] 2022-09-12 13:12
@bertdeblock is correct! Closing accordingly.

**Closed by chriskrycho** 2022-09-12 13:12 UTC
