### ISSUE TITLE
Component.replaceIn regression

### ISSUE THREAD

**Issue by rohmann** [emberjs/ember.js#14779] opened 2017-01-03 17:18 UTC
`Component.replaceIn` calls a similar function on the Glimmer Renderer, but that function doesn't exist.
https://github.com/emberjs/ember.js/blob/9b11b2153d2a35422b66c09ddb0bccfb0f5f2b74/packages/ember-views/lib/mixins/view_support.js#L242-L265

When `this.renderer.replaceIn` is called, I get this:

`Uncaught TypeError: this.renderer.replaceIn is not a function`

I understand `replaceIn` is private, and it would seem it's not being used internally anymore. It's likely that it was meant to be removed from the component as well.

Regardless of how this gets addressed as a bug/regression, I could really use a way to call `replaceIn` like I was able to before updating. It's a very specific use case where I can't have a wrapping element. Open to any suggestions.

**Comment by rwjblue** [comment] 2017-01-03 17:58
It looks like `replaceIn` is just not under test at all.  I'd suggest adding a test to [this file](https://github.com/emberjs/ember.js/blob/master/packages/ember-glimmer/tests/integration/components/append-test.js) for `Component.prototype.replaceIn`.  The fix is likely to just manually empty the element then call `.appendTo` (which is roughly what was being done before).

---

RE: a work around for now, just clear the element and then call `appendTo` instead of `.replaceIn`

**Comment by pixelhandler** [comment] 2017-01-06 16:43
@rohmann is the work around mentioned by @rwjblue good enough? if so perhaps close this out for now. Also, the work around seems like a good way to avoid using a private method.

> RE: a work around for now, just clear the element and then call `appendTo` instead of `.replaceIn`

**Comment by pixelhandler** [comment] 2017-01-06 16:44
@locks @chadhietala did you think this is issue can be address with Documentation ? if so perhaps we can label it as `Documentation`

**Comment by mixonic** [comment] 2017-03-26 06:22
@rohmann thank you for raising this.

I'm going to suggest the outcome here is that we drop the `replaceIn` API entirely. It is [not used in any addons](https://emberobserver.com/code-search?codeQuery=replaceIn) once you look at the usage, is marked as private, and it does not seem like a very large number of users noticed when it broke. It doesn't seem to rise to the level of "intimate" where we might consider it a regression. Especially since the workaround is pretty straight ahead.

**Comment by mixonic** [comment] 2017-03-30 00:21
Closed by https://github.com/emberjs/ember.js/pull/15077

**Closed by mixonic** 2017-03-30 00:21 UTC
