### ISSUE TITLE
After update ember-source from 3.5.1 to 3.6.0 I've got index.js:91 RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by bedrosenator** [emberjs/ember.js#17373] opened 2018-12-14 15:27 UTC
```
    index.js:91 RangeError: Maximum call stack size exceeded
    at Function.toString (<anonymous>)
    at Function.isPlainObject (jquery.js:315)
    at Function.jQuery.extend.jQuery.fn.extend (jquery.js:270)
    at Function.jQuery.extend.jQuery.fn.extend (jquery.js:282)
    at Function.jQuery.extend.jQuery.fn.extend (jquery.js:282)
    at Function.jQuery.extend.jQuery.fn.extend (jquery.js:282)
    at Function.jQuery.extend.jQuery.fn.extend (jquery.js:282)
    at Function.jQuery.extend.jQuery.fn.extend (jquery.js:282)
    at Function.jQuery.extend.jQuery.fn.extend (jquery.js:282)
    at Function.jQuery.extend.jQuery.fn.extend (jquery.js:282)
```

**Comment by avdept** [comment] 2018-12-14 15:33
Getting same issue while updating 3.4 -> 3.6

**Comment by pieter-v** [comment] 2018-12-14 15:41
Probably a duplicate of #17190

**Comment by rwjblue** [comment] 2018-12-14 15:41
Will definitely need reproduction steps to be able to help with this...

**Comment by bedrosenator** [comment] 2018-12-14 15:44
It happens when I load app. So I can't see even index page loaded

**Comment by rwjblue** [comment] 2018-12-14 15:49
Awesome, thanks for connecting the dots on that for me @pieter-v!

**Comment by rwjblue** [comment] 2018-12-14 15:50
I’m going to close this in favor of 
https://github.com/emberjs/ember.js/issues/17190

**Closed by rwjblue** 2018-12-14 15:50 UTC

**Comment by bedrosenator** [comment] 2018-12-14 15:53
Thanks, seems to me this is the same as it was described in #17190
