### ISSUE TITLE
Re-rendering based on layoutName is broken in 1.13.9

### ISSUE THREAD

**Issue by elwayman02** [emberjs/ember.js#12216] opened 2015-08-26 21:04 UTC
We have a component that renders a number of different layouts based on certain conditions and flows.  In Ember 1.12.1, we were accomplishing this by updating the `layoutName` and then calling `rerender`.  When I updated our app to 1.13, the old template was still rendered, even though the layoutName had been updated.

I've created JSbins illustrating the approximate issue we're seeing.  The only difference is that in these examples, both the `layout` and `layoutName` attributes seem to be updating properly, whereas in our app, I'm not seeing `layout` update correctly when `layoutName` is changed.  In either case, both the examples and our app fail to render properly in 1.13, so I'm hoping the solution will be the same for each.

Working 1.12 Example: http://emberjs.jsbin.com/payuqe/3/edit?html,js,output

Broken 1.13 Example: http://emberjs.jsbin.com/xufezo/2/edit?html,js,output

**Comment by elwayman02** [comment] 2015-08-26 21:08
I'm fully willing to admit that we may not be taking the best approach here, so if there is some other method I should be using other than `rerender`, I would love to find out about a better way.

**Comment by rwjblue** [comment] 2015-08-26 21:14
This is a duplicate of https://github.com/emberjs/ember.js/pull/11315, can you comment over there?

**Closed** 2015-08-26 21:17 UTC

**Comment by rwjblue** [comment] 2015-08-26 21:24
I did a small mockup using the provided 1.13 JSBin showing how you might do this with the `{{component` helper: http://emberjs.jsbin.com/yexizi/1/edit?html,js,output.
