### ISSUE TITLE
Beta: Active async route bug

### ISSUE THREAD

**Issue by topaxi** [emberjs/ember.js#10421] opened 2015-02-11 13:14 UTC
It seems like the link-to active state on async routes updates a bit late / weird.

Try to switch between foo and bar on this jsbin:
http://emberjs.jsbin.com/wonovalara/1/edit?js,output

**Comment by elwayman02** [comment] 2015-03-06 23:45
I just noticed this as well.

**Comment by mixonic** [comment] 2015-03-22 23:19
@topaxi @elwayman02 I believe this is a dupe of https://github.com/emberjs/ember.js/issues/10366. Please re-open if I am incorrect!

**Closed by mixonic** 2015-03-22 23:19 UTC
Labels: Bug, Needs Bug Verification
