### ISSUE TITLE
transition.isActive is undefined in Ember 2.8

### ISSUE THREAD

**Issue by blimmer** [emberjs/ember.js#14268] opened 2016-09-12 17:02 UTC
Testing my LTS app against the current pre-LTS Ember 2.8 version, I noticed that some of my routes started breaking because I was checking `transition.isActive` in route hooks.

For instance, consider this block in a mixin to block mobile devices from accessing certain routes:

```javascript
  beforeModel(transition) {
    this._super(...arguments);

    if (!transition.isActive) { return; }

    if (this.get('browserDetectService.isMobileDevice')) {
      this.transitionTo('mobile-not-supported');
    }
  }
```

In Ember 2.4.x LTS `transition.isActive` is defined to be a boolean. In Ember 2.8.0, `transition.isActive` is `undefined`.

To be honest, I can't remember why we were originally checking this, as it is an app that has been upgraded from early 1.x days. I also realize that this is likely caused by a router.js change, not something directly handled by Ember.

I think it will be safe for us to remove our check for that flag, but I wanted to call it out to make sure it's not an unintended change.

**Comment by rwjblue** [comment] 2016-09-12 17:43
Seems like a regression to me.

**Comment by rwjblue** [comment] 2016-09-12 17:45
Looks like https://github.com/tildeio/router.js/commit/1db19a4f511bfc9cb9aedb1e1a9d21ab258156f8 added `this.isActive = undefined` [in the constructor](https://github.com/tildeio/router.js/blob/master/lib/router/transition.js#L35) to ensure the `Transition` object was properly shaped, but unfortunately that overrides the `Transition.prototype.isActive = true;` that is done [here](https://github.com/tildeio/router.js/blob/master/lib/router/transition.js#L92).

The fix is to remove `isActive` from the prototype and set the default value to `true` (instead of `undefined`) in the constructor.  We should also add a test confirming it is `true` by default.

**Comment by rwjblue** [comment] 2016-09-12 21:39
Should be fixed by https://github.com/tildeio/router.js/pull/192 once it lands and is updated here.

**Closed** 2016-09-12 23:42 UTC
Labels: Regression

**Comment by blimmer** [comment] 2016-09-13 03:51
Thanks @rwjblue - I really appreciate your quick turnaround on this! 🍻
