### ISSUE TITLE
Assertion Failed: Attempted to register a view with an id already in use

### ISSUE THREAD

**Issue by NullVoxPopuli** [emberjs/ember.js#13026] opened 2016-02-29 03:20 UTC
I'm having this problem when I render a wrapping component twice in two different places on the page

```
Ember             : 2.3.1
Ember Data        : 2.3.3
jQuery            : 2.2.1
Ember Simple Auth : 1.1.0-beta.1
```

Here is the component that apparently can't be used twice on the same page:
https://github.com/NullVoxPopuli/aeonvera-ui/blob/master/app/components/foundation-modal.js
https://github.com/NullVoxPopuli/aeonvera-ui/blob/master/app/templates/components/foundation-modal.emblem

Here is how the above component is used in templates:
https://github.com/NullVoxPopuli/aeonvera-ui/blob/master/app/templates/components/donate-to-aeonvera.emblem#L1
and the other:
https://github.com/NullVoxPopuli/aeonvera-ui/blob/master/app/templates/components/event-at-the-door/a-la-carte.emblem#L62

What does this error message mean? 
I've tried completly commenting out the foundation-modal content and the exception still happens.

**Comment by NullVoxPopuli** [comment] 2016-02-29 03:29
I just tried running the latest ember (2.4.0-beta.3) and the problem persists.

**Comment by Serabe** [comment] 2016-02-29 05:44
That error means that you are trying to use to different components with the same id. You can see in the `elementId` declaration that [it only declares](https://github.com/NullVoxPopuli/aeonvera-ui/blob/master/app/components/foundation-modal.js#L31-L38) `modalName` as a dependency and that is probably avoiding the property to recompute with the proper value of `overrideId`.

I would suggest the component not to use any custom id unless you can guarantee it is unique.

**Comment by NullVoxPopuli** [comment] 2016-02-29 12:03
If I comment out elementId and the attributeBindings it appears to work -- so I guess elementId is a bit of a keyword?

the modal requires that the id of the modal be a data attribute of the button that launches the modal.

So then, I guess it would be better to have the button and the modal in the same component. Is there a way to get the ember-generated id as a property so that the modal id and the button's `data-reveal-id` can be the same value?

**Comment by Serabe** [comment] 2016-02-29 12:09
`elementId` is not any kind of a keyword AFAIK. The problem is that that code can produce two modals with the very same id, and that is what is making the app crash.

**Comment by NullVoxPopuli** [comment] 2016-02-29 12:11
is there a way to get the ember-generated id?

**Comment by Serabe** [comment] 2016-02-29 12:22
Not sure there is an official API, but [this twiddle's approach](https://ember-twiddle.com/bfb6ba922498b6c7cafb?openFiles=my-component.template.hbs%2Cmy-component.component.js) seems to work.

**Comment by btecu** [comment] 2016-02-29 13:48
If the answers weren't clear enough the problem is you're ending up with:
`<div id="abc">..</div><div id="abc">...</div>`

This is *illegal* html syntax as you can't have the same id more than once.
It's not a problem that you're setting `elementId`, although I'd suggest not to, but that you're passing the same id value to multiple instances of your component.

And yes, you can generate a unique id: `Ember.generateGuid()`.

**Comment by NullVoxPopuli** [comment] 2016-02-29 13:51
I guess the biggest confusion is where the same ID is getting passed. Because of the two rendered modals, they have different Ids. The only situation which I can see that multiple components would use the same ID is if something else is rendering the component more than once.

**Comment by btecu** [comment] 2016-02-29 13:57
Does your parent component needs to know the id of the child component? If so, it seems like doing something that doesn't really align with Ember best practices.

If you can provide a repo demoing the issue it could be helpful.

**Comment by NullVoxPopuli** [comment] 2016-02-29 13:59
Possibly, but just for more information, here is what I'm dealing with:

```html
<a href="#" data-reveal-id="myModal">Click Me For A Modal</a>

<div id="myModal" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
  <h2 id="modalTitle">Awesome. I have it.</h2>
  <p class="lead">Your couch.  It is mine.</p>
  <p>I'm a cool paragraph that lives inside of an even cooler modal. Wins!</p>
  <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>
```

I've previously had the `#myModal` part in its own component, and the `a` would be outside. Currently, I'm trying to see if I can use @Serabe's idea and make them use the component's generated id (and tacking on -modal at the end).

**Comment by NullVoxPopuli** [comment] 2016-02-29 14:11
Ok, I sort of have it working now.

This is my new foundation-modal component:

```
a class=buttonClasses data-reveal-id=modalId
  = buttonText

div.reveal-modal.medium data-reveal=reveal aria-labeledby=titleId aria-hidden=hidden role=role id=modalId data-options="root_element: 'body'"
  h2.text-center = title
  p
    = yield
    a.close-reveal-modal aria-label="Close" &#215;
```

however, now I have a dom / css issue, as the the actual modal part is hidden by its containing element.

I need the modal to like.. be at the top level of the dom or something.

Is there a recommended way to do modals in ember? this seems like it should already have a solution.

**Comment by btecu** [comment] 2016-02-29 15:15
If it's not a `z-index` issue, it's most likely that you're nesting the modal under a `fixed` or `absolute` positioned parent. In that case you will need to insert the modal in a different place. `ember-wormhole` will allow you to do this.

**Comment by NullVoxPopuli** [comment] 2016-02-29 15:32
thanks, I'll give this a go.

**Comment by NullVoxPopuli** [comment] 2016-02-29 16:08
@btecu that seems to mostly do exactly what I want - it appears that the wormhole'd content doesn't retain its actions/bindings though. :-\

**Comment by NullVoxPopuli** [comment] 2016-02-29 16:09
I need a afterWormhole hook to call `this.$(document).foundation('reflow');` I think

**Comment by btecu** [comment] 2016-02-29 16:22
See https://github.com/yapplabs/ember-wormhole/issues/31.

**Comment by NullVoxPopuli** [comment] 2016-02-29 16:31
hey, that worked -- here is my code, in case someone else finds this:

ember g component foundation/foundation-reflow

in the js: 
```js
import Ember from 'ember';

export default Ember.Component.extend({
  initFoundation: function() {
    this.$(document).foundation('reflow');
  }.on('didInsertElement')

});
```

in the template (emblem):

```
= yield
```

now my foundation-modal.emblem template looks like this:

```
a class=buttonClasses data-reveal-id=modalId
  = buttonText

= ember-wormhole to="foundation-modals"
  = foundation/foundation-reflow
    div.reveal-modal.medium data-reveal=reveal aria-labeledby=titleId aria-hidden=hidden role=role id=modalId
      h2.text-center = title
      p
        = yield
        a.close-reveal-modal aria-label="Close" &#215;
```

thanks!

**Comment by locks** [comment] 2016-04-17 09:02
I am closing this issue because the issue was resolved, from what I understand after reading the thread.
Feel free to re-open the issue if you think it's still justified, thank you.

**Closed by locks** 2016-04-17 09:02 UTC
