### ISSUE TITLE
Objects/arrays defined on classes are a vector for state leakage in tests

### ISSUE THREAD

**Issue by aquamme** [emberjs/ember.js#13558] opened 2016-05-25 20:19 UTC
[Twiddle](https://ember-twiddle.com/0daf214d0a9a0a30f2584f54f369d153?openFiles=tests.unit.dummy-test.js%2C)

I was seeing some intermittent test failures and tracked it down to this. Fortunately for me, none of the objects or arrays defined on any of our classes actually needed to be shared across instances. Users who need this behavior are left with these options:
* Ignore the intermittent test failures that may be caused by cross contamination between tests
* Manually reset class state between tests
* Switch to a different mechanism for sharing state between instances of a class
* Some other option I'm not thinking of offhand

The guides advertise the [behavior of objects/arrays defined on classes](https://guides.emberjs.com/v2.5.0/object-model/classes-and-instances/#toc_initializing-instances), but nowhere do I see it documented that this can cause state leakage between tests.

While this may not strictly speaking be a bug, it can definitely be a painful gotcha. At the least, I think some documentation should be added, but perhaps some other action is warranted.

**Comment by Serabe** [comment] 2016-05-25 21:46
Thank you for your report. In this case, this is not a bug and is documented in the [guides](https://guides.emberjs.com/v2.5.0/object-model/classes-and-instances/#toc_initializing-instances).

I am closing this. Reopen it if I am mistaken.

Thank you so much for your report!

**Closed by Serabe** 2016-05-25 21:46 UTC

**Comment by aquamme** [comment] 2016-05-25 22:11
Yes, I did actually link to that guide. What I want to point out though is that this feature can cause unpredictable behavior with tests, because the class state doesn't get reset between tests. That caveat isn't documented, but even if it were, it would be tedious and error prone to deal with. The test writer would have to be aware that the state isn't automatically reset between tests (unlike other app state), and write code to reset it manually between every test. You can take a peek at the [twiddle](https://ember-twiddle.com/0daf214d0a9a0a30f2584f54f369d153?openFiles=tests.unit.dummy-test.js%2C) for an example of test cross contamination.

@Serabe -- I don't have permission to reopen this issue.

**Comment by Serabe** [comment] 2016-05-25 22:25
This is a expected behaviour, not only in Ember but in Javascript. You can check in [this jsbin](http://jsbin.com/gojizogeca/edit?html,js,console,output).

This is clearly not expected coming from other language semantics.

This will be solved once the Ember Object model has been migrated to ES6 classes, but it depends on a couple of proposals for TC39 (I am thinking about [Class Fields and Static Properties](https://github.com/jeffmo/es-class-fields-and-static-properties) and [Decorators](https://github.com/wycats/javascript-decorators/blob/master/README.md)).

This was originally discussed in #10341. There is no RFC open for that yet but you can see more discussion about ES5 getters/setters in [this one](https://github.com/emberjs/rfcs/issues/108)

**Comment by aquamme** [comment] 2016-06-01 20:58
I understand it's a feature/quirk of the language, however, it seems asymmetric to me that the guides would point out the feature/quirk but not also warn of the potential complications in a test environment.
