### ISSUE TITLE
documentation on http://guides.emberjs.com/ is not easy to understand

### ISSUE THREAD

**Issue by reemasaluja** [emberjs/ember.js#11601] opened 2015-06-30 15:39 UTC
Hardly can find proper documentation online. As compared to angular , no proper structure for ember has been provided

**Comment by bradcypert** [comment] 2015-07-01 01:12
Can you elaborate more on proper structure?

If you mean app structure, using Ember CLI will help illustrate a "standard-ish" app structure. Of course, you can use pods, to deviate from it, provided your app makes more sense to follow that structure.

**Comment by stefanpenner** [comment] 2015-07-03 16:16
Im going to close this.

Please feel to reopen at the appropriate repo: https://github.com/emberjs/guides
When the issue is reopened, please try to include more some extra detail. I believe @bradcypert's comment is great, and a future issue to attempt to elaborate on those points.

**Closed by stefanpenner** 2015-07-03 16:16 UTC
