### ISSUE TITLE
`didRender` not triggered when class/attribute bindings change

### ISSUE THREAD

**Issue by Herriau** [emberjs/ember.js#12723] opened 2015-12-17 22:21 UTC
https://gist.github.com/Herriau/fbcd391e75a14930912b
https://ember-twiddle.com/fbcd391e75a14930912b?numColumns=1

```handlebars
{{foo-bar bar=whatever}}
```

```javascript
var FooBarComponent = Ember.Component.extend({
  foo: false,
  bar: false,
  
  classNameBindings: ['foo'],
  
  onRerendered: function() {
        // triggered when `bar` changes
        // not triggered when `foo` changes
  }.on('didRender'),
});
```

* In the above example, I expected the `didRender` hook to be triggered whenever `foo` changes since it ultimately causes the DOM to mutate. 
* Conversely since `bar` is not bound to anything I expected the `didRender` hook not to be triggered when its value changes

**Comment by sohara** [comment] 2015-12-18 13:36
I'm pretty sure it's not supposed to render if nothing in the template has changed (i.e. there is no reason for the template to render if the rendered output DOM will be identical). Put `{{foo}}` in the template and you will see that `didRender` is called.

**Comment by acorncom** [comment] 2016-05-07 02:14
@Herriau appreciate your reproduction of your issue. Like @sohara said though, I'm not sure this is an actual bug. Are you still having this problem or can we close this issue?

**Comment by pixelhandler** [comment] 2016-05-13 17:00
@Herriau See this fork of your twiddle example, https://ember-twiddle.com/67c6f45034fab29e81873bd354a8792f?openFiles=application.template.hbs%2C

since I added `foo` and passed in a value `whatever` like you did with `bar` now the template re-renders. The change of an internal property `foo` doesn't cause the component template to re-render, only the bound value to change the css class, not a complete template re-render since no values that were passed in changed. I do not think this is an Ember bug.

I'll close this issue out for now.

**Closed by pixelhandler** 2016-05-13 17:00 UTC
Labels: Needs Submitter Response

**Comment by Herriau** [comment] 2016-05-13 18:28
@pixelhandler It may not be a bug per se, but I still believe that the notion of rerender as conveyed by the `didRender` hook is flawed. I would expect any event that leads to a mutation of the DOM (including change in attributes of the component's element itself) to trigger the `didRender` hook. It just seems reasonable. 

Rather, the current situation is such that we can potentially get a lot of false positives (e.g. with the `bar` attribute from my initial example that is not wired to anything inside the template or any attribute bindings yet cause the `didRender` hook to be triggered), and a lot of false negatives (e.g. with the internal `foo` property that is wired to an attribute, hence causing the DOM to be mutated, yet doesn't trigger the `didRender` hook).

If you guys are happy with this design then great this is not a bug.

**Comment by Tev-work** [comment] 2018-04-06 13:15
This is definitely confusing, especially as documentation makes no effort of mentioning this.

https://www.emberjs.com/api/ember/2.15/classes/Ember.Component/methods/didRender?anchor=didRender:

> Called after a component has been rendered, both on initial render and in subsequent rerenders.

So changing class is not rerender, fine, but that is not at all obvious and seems like a bug on first encounter.
