### ISSUE TITLE
Big memory leak when destroying templates that contain iframe

### ISSUE THREAD

**Issue by BryanCrotaz** [emberjs/ember.js#15872] opened 2017-11-27 23:13 UTC
create and destroy components that include an iframe and we get an enormous memory leak each time.

Twiddle:
https://ember-twiddle.com/b1ce25d3c3fd4a1db41750ca37b316c3?openFiles=components.iframe-display.js%2Ctemplates.components.iframe-display.hbs

The content of the iframe isn't mopped up.

**Comment by stefanpenner** [comment] 2017-11-27 23:29
> The content of the iframe isn't mopped up.

Can you share more details? What specifically indicates the iframes are not getting cleaned up? How can I be sure I am able to reproduce what you are seeing.

Can you also provide a more reduced example, as ember-twiddle is a series of iframes. It may conflate this problem.

**Comment by stefanpenner** [comment] 2017-11-27 23:31
Interesting in the example provided, I seem to not have an unbounded number of iframes in the heap inspector.

**Comment by stefanpenner** [comment] 2017-11-27 23:34
Ya, in the given example the heap seems to maintain a stable size. I tested for 10 iterations and 100 iterations, both scenarios had the same number of frames and the same heap size.

If you are experiencing a leak and I am not, then likely some reproduction steps are missing?

**Comment by BryanCrotaz** [comment] 2017-11-27 23:48
Look at the number of HTMLDocument nodes on the heap - it looks as though the entire framed DOM is leaked.

**Comment by BryanCrotaz** [comment] 2017-11-27 23:54
These heap snapshots were taken in the twiddle with a forced garbage collect immediately before each one, a few minutes apart.

 
<img width="149" alt="screen shot 2017-11-27 at 23 53 14" src="https://user-images.githubusercontent.com/2016523/33295620-49ab610a-d3ce-11e7-805b-fcf70e907da0.png">

**Comment by stefanpenner** [comment] 2017-11-28 03:02
@BryanCrotaz hmm ya I do see the number of `HTMLDocument` instances grow (next time it would be really great if you could provide this information in your issue, that would really make this issues actionable)

Interestingly though, I so far can't see anything ember related retaining them.

In each case it appears to be one of:

* `slow_template_instantiations_cache in system`
* `fast_template_instantiations_cache in system `

Both of which are v8 internals ember shouldn't be able to affect. So either, the heapsnapshot tool is broken (hiding a bug in ember) or something is funky in v8/browser land.

**Comment by stefanpenner** [comment] 2017-11-28 03:05
Relevant V8 code: https://github.com/v8/v8/blob/da0af28545459800f99665bfe8cccfe80cb6f52e/src/api-natives.cc#L300-L344

**Comment by stefanpenner** [comment] 2017-11-28 03:14
Also for context, I believe ember here is merely literally toggling `iframe.src = <some value>`

**Comment by stefanpenner** [comment] 2017-11-28 03:15
Pinging our v8 friends, maybe they can sanity check my hypothesis ... if so, I'll open a crbug.

**Comment by stefanpenner** [comment] 2017-11-28 03:48
potential minimal reproduction: http://static.iamstef.net/iframe-leak-1.html (running it now to see)

**Comment by BryanCrotaz** [comment] 2017-11-28 06:20
Sorry for confusion. That’s what I meant by saying the content of the iframe wasn’t mopped up. I didn’t know what the root retainer was as it’s all a big island of references.

**Comment by stefanpenner** [comment] 2017-11-28 07:04
No prob. It’s good to bubble these issues up, that way we can get them solved (regardless of where the root cause lies)

**Comment by BryanCrotaz** [comment] 2017-11-28 07:19
I've looked at the V8 code and it's a bit beyond my knowledge of JS engines, but it looks as though they're caching the DOM by url? In which case in my example I'd expect to only ever see 4-6 cached copies, but I was seeing as high as 90.

**Comment by hashseed** [comment] 2017-11-28 13:14
@BryanCrotaz where in the code do you see this?

**Comment by BryanCrotaz** [comment] 2017-11-28 13:24
@hashseed - I'm guessing a lot - this is my first look at engine code - this is what Stefan suggested
https://github.com/v8/v8/blob/da0af28545459800f99665bfe8cccfe80cb6f52e/src/api-natives.cc#L300-L344

**Comment by hashseed** [comment] 2017-11-28 13:55
I see. We indeed cache instantiating objects from object templates. What's not entirely clear to me is that how that's related to components. Just by guessing, this may actually cause a leak, if we cache JSObjects, since those have references to the context.

@verwaest should have more insights here though.

**Comment by BryanCrotaz** [comment] 2017-11-28 14:11
@hashseed @verwaest I don't think it's the component that's at fault - it's disposing of the iFrame correctly, but the framed document and its resources are staying in the cache by the sound of it, causing a mem leak (or an overly long caching strategy causing problems on constrained devices)

**Comment by verwaest** [comment] 2017-11-28 22:47
The actual root you're looking at is the thing marked as (Document DOM
trees) which basically means Blink's Oilpan thinks those DOM trees are
still rooted. Typically once a single (non-primitive) object from a native
context leaks, the context itself (including instantiations caches) will
stay alive.

The particular path you're seeing is because HTMLDocument has an
ObjectTemplate that's marked as a cacheable template. The HTMLDocument
instance you're seeing is in the instantiations cache for that reason. That
cache is held on by the native context, which is held on by the
HTMLDocument constructor (which as "context" pointer points to the native
context). The constructor is installed on the __proto__ of another
HTMLDocument from the same native context. (I'm not sure why there are
multiple HTMLDocument instances in the same native context, this is out of
my expertise.) That second HTMLDocument is the rooted one.

@hashseed, since I'm OOO, perhaps you can ping someone from the Blink
bindings / GC teams to have a look at this?

**Comment by Serabe** [comment] 2017-12-22 16:50
@stefanpenner shall we close this issue or is there any actionable to do?

**Comment by Serabe** [comment] 2018-01-05 20:34
@stefanpenner ping

**Comment by stefanpenner** [comment] 2018-01-10 17:38
@serabe is the problem resolved? I suspect if we want to close this, we must ensure the v8/blink folks are carrying the torch.

**Comment by stefanpenner** [comment] 2018-01-10 17:42
I have filed a CRBug:  https://bugs.chromium.org/p/chromium/issues/detail?id=800830

**Comment by stefanpenner** [comment] 2018-02-13 07:33
I think we can close, I believe the V8/Chrome folks are aware / working on the issue.

**Closed by stefanpenner** 2018-02-13 07:33 UTC

**Comment by stefanpenner** [comment] 2018-03-01 19:07
@BryanCrotaz I believe chrome canary has this fixed now: https://bugs.chromium.org/p/chromium/issues/detail?id=800830#c12

If you could double check from your side? That way if something is still sideways he can work with our chrome/v8 friends to get this addressed asap.
