### ISSUE TITLE
IE8 & IE9 fail on input type="search"

### ISSUE THREAD

**Issue by MichaelVdheeren** [emberjs/ember.js#10603] opened 2015-03-10 21:50 UTC
Issue:
when using the input helper setting the type to search this results in an error in the metamorph code.

```
{{input type="search" classNames="form-control js-noPlaceholder" placeholder="Search" value=searchValue}}
```

What I expected it to do:
fallback to normal input element for IE8 and IE9 if possible.

Failing test:
need to add this.

**Comment by MichaelVdheeren** [comment] 2015-03-10 22:09
Failing jsbin: http://jsbin.com/wacihaqake/1/

**Comment by MichaelVdheeren** [comment] 2015-03-10 22:28
Related to #10458

**Comment by mixonic** [comment] 2015-03-10 23:04
Sounds like a dupe of #10458

**Closed by mixonic** 2015-03-10 23:04 UTC
Labels: Bug, Regression

**Comment by MichaelVdheeren** [comment] 2015-03-11 07:49
@mixonic but this one provides you with a failing test ;-)
