### ISSUE TITLE
Component lifecycle hooks documentation is missing

### ISSUE THREAD

**Issue by t-sauer** [emberjs/ember.js#12637] opened 2015-11-21 17:28 UTC
Until 2.1 the lifecycle hooks/events of a component were listed in the API documentation of components but since 2.2 they seem to be missing.

**Comment by rwjblue** [comment] 2015-11-21 19:31
This is ultimately a duplicate of https://github.com/emberjs/ember.js/issues/12601 (same root cause).  I added a note to the end of that one to point out what needs to be done.

**Closed by rwjblue** 2015-11-21 19:31 UTC
