### ISSUE TITLE
Controller's init method is called before model method of application route 

### ISSUE THREAD

**Issue by mani-mishra** [emberjs/ember.js#15495] opened 2017-07-12 09:27 UTC
**Issue on Ember 2.14**

So our app is breaking on upgrading to 2.14, as the  ```init``` method of controller for a particular route is executed before the ```model``` method of ```application``` route. 

We have bunch of features/flags check in ```init``` methods, and all those are being set in application model. 

This is working as expected (```model``` => ```afterModel``` => ```init``` of controller of the route being loaded) till ember 2.13.3

**Comment by mani-mishra** [comment] 2017-07-12 14:36
As ember twiddle doesn't support newer versions of ember, created a demo app. Below are the screenshots and links for the same.

For 2.13.3: https://github.com/mani-mishra/ember-15495-demo/tree/2.13.3

![2 13-3](https://user-images.githubusercontent.com/3315240/28122996-7801f6fc-673d-11e7-8eba-082681348b4b.png)

For 2.14.0: https://github.com/mani-mishra/ember-15495-demo/tree/2.14.0
![2 14 0](https://user-images.githubusercontent.com/3315240/28123016-86423006-673d-11e7-9cf1-b013bf070359.png)

**Comment by rwjblue** [comment] 2017-07-14 20:52
I am not 100% sure without more details or a reproduction, but I believe that this is due to the change I made in https://github.com/emberjs/ember.js/pull/15178 (I tried to ensure that PR description explains the rationale for the change). In general, there has never been a guarantee that controllers would be created in any specific order related to the route structure.

That PR was definitely fixing a number of bugs and edge cases with the prior behaviors, but its also one of those situations where a good fix happened to accidentally break a subtle behavior your app was relying on and I apologize for that.

Sadly, I believe that you will need to refactor your logic in this case.

**Comment by Serabe** [comment] 2017-07-15 00:37
As commented before and in the PR text, this won't be fixed for the reasons there specified. I am afraid this is one of the rare cases where we cannot fix all the edge cases. We can offer some support through Slack to help through this refactor. If you are not there yet, [you can use the Slackin app to sign in](https://ember-community-slackin.herokuapp.com/).

Thank you and we are sorry.

**Closed by Serabe** 2017-07-15 00:37 UTC
Labels: wontfix

**Comment by mani-mishra** [comment] 2017-07-17 06:42
Thanks @rwjblue and @Serabe for the explanation. Appreciate it. 👍

**Comment by mani-mishra** [comment] 2017-09-19 13:40
@rwjblue and @Serabe, for fixing the above I was doing the same changes in our app and the potential fix is following the below assumption.

Application's route model hook will finish before any individual route's lifecycle(except ```init```) hook is run. 
Example: ```application route model => route A's beforeModel => route A's activate => route A's model ```

I didn't find any documentation for such, so please correct me if the above assumption is wrong.
