### ISSUE TITLE
link-to transitioningIn and transitioningOut not valid if a transition is aborted

### ISSUE THREAD

**Issue by dnachev** [emberjs/ember.js#14083] opened 2016-08-18 07:19 UTC
I'm using link-to transitioningIn and transitioningOut to determine which link will be the active instead of which is the active. Everything works correctly unless the active transition is aborted.

In this case, router targetState remains set and different then the router currentState and link-to component considers that the application is still transitioning and causes the states of the links to be wrong.

You can see a demo of the problem here:
https://ember-twiddle.com/3430f1e33c4e96a2563c3d89fea7dbaf

Click on page1 and then click on page2 and observe how the transitioning classes are left behind.

**Comment by pixelhandler** [comment] 2016-08-19 19:26
@dnachev thanks for the reproduction of the issue. Yeah I would expect that after the transition is aborted and the current route remains active, but instead the current route (that aborted transition is still in 'transitioning-out' and the other route is in 'transitioning-in' which it is not since the transition cancelled.

**Comment by pixelhandler** [comment] 2016-08-19 19:40
@emberjs/issues-team @emberjs/learning-team-managers are you aware of any documented behavior for these classes (`ember-transitioning-in` and `ember-transitioning-out`) when a transition is aborted?

**Comment by GavinJoyce** [comment] 2016-11-26 07:42
Related issue: https://github.com/emberjs/ember.js/issues/13164

**Comment by rwjblue** [comment] 2016-11-26 13:38
Closing in favor of #13164

**Closed by rwjblue** 2016-11-26 13:38 UTC
Labels: Needs Team Discussion
