### ISSUE TITLE
[routeName].index undefined has no properties

### ISSUE THREAD

**Issue by MohamadAtieh** [emberjs/ember.js#12568] opened 2015-11-06 20:11 UTC
Hey all,

I'm trying to set up a model for my route, and although returning a simple array makes it work, calling findAll(modelName) throws the following error:

`Error while processing route: advisors.index undefined has no properties @http://localhost:4200/assets/poc.js:28:4`

My router looks like this:

    Router.map(function() {
      this.route('authentication', {}, function() {
       this.route('login', {});
       this.route('logout', {});
       });
      this.route('advisors', function() {
          this.route('advisor', { path : ':id' });
       });
    });

What is `undefined` exactly?

**Comment by stefanpenner** [comment] 2015-11-06 20:51
Can you share the various versions of stuff. (atleast the version of ember)

**Comment by MohamadAtieh** [comment] 2015-11-06 21:29
- ember-cli: 1.13.8
- node: 4.1.2
- npm: 2.13.4

**Comment by MohamadAtieh** [comment] 2015-11-06 21:59
I don't have `routes/advisors/index.js`, I have seen other examples and they don't usually provide it. However, when I try `return this.store.findAll('advisors'); //GET -> /advisor/list` in my `routes/advisors.js` , I receive that error.

I have defined two models: 
- `advisor` for the nested route
- `advisors` for the one I am having an issue with. 

What happens when I call  `return this.store.findAll('advisors'); ` and `pathType: /advisor/list`?

The reason is that I can't use one model for `advisor` since GET `advisor/list` has a different response or structure (array object) than `/advisor/{id}` in the API.

**Comment by pixelhandler** [comment] 2015-11-13 18:39
@MohamadAtieh it is a good idea to create a jsbin, jsfiddle or ember-twiddle example of the code that is broken. Sometimes just the effort of isolating an error in a simple example can show either a mistake or even expose a bug (which then can be worked on).

**Comment by MohamadAtieh** [comment] 2015-11-13 18:57
Changing the serializer to JSONAPISerializer made the error disappear. Now that I look at my code, I have an adapter that extends from RESTAPI and a serializer that extends from JSONAPI, and it is working. 

Can I understand why?

**Comment by Serabe** [comment] 2016-04-18 00:05
@MohamadAtieh can you try to recreate in a [twiddle](https://ember-twiddle.com) so we can make sure it was not a bug and help you? Thank you!

**Comment by pixelhandler** [comment] 2016-04-29 21:36
@MohamadAtieh It sounds like you have worked out your issue. I'll close this out for now. 

If you'd like to discuss further perhaps reach out in the http://embercommunity.slack.com #-help channel to chat regarding the specific version your app is using.

**Closed** 2016-04-29 21:36 UTC
Labels: Ember 1.13, Needs Bug Verification, Needs Submitter Response
