### ISSUE TITLE
Cannot read property 'eventName' of undefined

### ISSUE THREAD

**Issue by noslouch** [emberjs/ember.js#14888] opened 2017-01-30 20:36 UTC
I've got a component which is conditionally rendered based on the value of a boolean. If that boolean value is changed by an action from within that component, the above error is thrown when the component is removed from the view.

Seems like it was introduced with canary and is happening from `2.13.0-alpha.1-canary+96c0bb79` onward.

Here's a simple twiddle demonstrating: https://ember-twiddle.com/b86adfba657f450a4d264e01a3fb0d37?openFiles=templates.application.hbs%2Ctemplates.components.my-component.hbs

Seems related to #1643. The stack trace points to the same block patched by pivotal-topher-bullock@74e0d58.

Stack trace:
```
Uncaught TypeError: Cannot read property 'eventName' of undefined
    at HTMLButtonElement.<anonymous> (ember.debug.js:43826)
    at HTMLDivElement.dispatch (VM229 jquery.js:4670)
    at HTMLDivElement.elemData.handle (VM229 jquery.js:4338)
    at Object.trigger (VM229 jquery.js:4579)
    at Object.simulate (VM229 jquery.js:4906)
    at HTMLDocument.handler (VM229 jquery.js:5169)
    at clear (ember.debug.js:916)
    at UpdatableBlockTracker.reset (ember.debug.js:916)
    at TryOpcode.handleException (ember.debug.js:1070)
    at UpdatingVMFrame.handleException (ember.debug.js:1071)

// disclosed
(anonymous) @ ember.debug.js:43826
dispatch @ VM229 jquery.js:4670
elemData.handle @ VM229 jquery.js:4338
trigger @ VM229 jquery.js:4579
simulate @ VM229 jquery.js:4906
handler @ VM229 jquery.js:5169
clear @ ember.debug.js:916
reset @ ember.debug.js:916
handleException @ ember.debug.js:1070
handleException @ ember.debug.js:1071
_throw @ ember.debug.js:1070
evaluate @ ember.debug.js:862
execute @ ember.debug.js:1070
rerender @ ember.debug.js:1057
_this.render @ ember.debug.js:13523
runInTransaction @ ember.debug.js:24861
_renderRoots @ ember.debug.js:13784
_renderRootsTransaction @ ember.debug.js:13822
_revalidate @ ember.debug.js:13861
invoke @ ember.debug.js:1902
flush @ ember.debug.js:1970
flush @ ember.debug.js:2094
end @ ember.debug.js:2164
run @ ember.debug.js:2287
run @ ember.debug.js:24085
handler @ ember.debug.js:13301
(anonymous) @ ember.debug.js:43827
dispatch @ VM229 jquery.js:4670
elemData.handle @ VM229 jquery.js:4338

```

**Comment by rwjblue** [comment] 2017-01-30 20:42
Thank you for reporting!!!

@GavinJoyce - This is related to the event dispatcher refactors, mind taking a look?

**Comment by noslouch** [comment] 2017-01-30 20:44
you're welcome! :D 

small addition, the same error is thrown when that component is added back to the view. also demonstrated in that twiddle.

**Comment by GavinJoyce** [comment] 2017-01-30 20:46
Sure, I'll take a look

**Comment by GavinJoyce** [comment] 2017-01-30 21:31
It looks like [this guard](https://github.com/intercom/ember.js/blob/7166d886887670e441a9612743af8114d6a965af/packages/ember-views/lib/system/event_dispatcher.js#L244-L249) is needed:

<img width="748" alt="screen shot 2017-01-30 at 21 30 11" src="https://cloud.githubusercontent.com/assets/2526/22442437/4ef2b45c-e733-11e6-921f-82d684aad247.png">

I'm working on a test now

**Comment by rwjblue** [comment] 2017-01-30 22:00
Oh no! There was even a comment explaining why it was needed.  If only we had a test too...

**Comment by GavinJoyce** [comment] 2017-01-30 22:02
I'm having trouble creating a failing test. I believe that this should fail, but it doesn't:

https://github.com/emberjs/ember.js/pull/14889

**Comment by GavinJoyce** [comment] 2017-01-30 22:07
I could manually unregister the action and ensure that an exception isn't thrown, but I'd much rather use the high level API to drive the test. Suggestions welcome

**Comment by noslouch** [comment] 2017-01-30 22:10
Looks like Firefox doesn't throw, but Chrome does. Can you run your travis build in Chrome?

**Comment by GavinJoyce** [comment] 2017-01-30 22:10
> Can you run your travis build in Chrome?

I haven't yet managed to create a failing test in Chrome

**Comment by GavinJoyce** [comment] 2017-01-30 22:15
@noslouch thanks, can you point me to the source of a failing test?

**Comment by noslouch** [comment] 2017-01-30 22:16
ah, it's an acceptance test: https://github.com/nypublicradio/nypr-account-settings/blob/master/tests/acceptance/server-error-test.js

**Comment by GavinJoyce** [comment] 2017-01-30 22:27
oh, I see. I need to trigger a `focusout` after the `click` has been handled

**Comment by GavinJoyce** [comment] 2017-01-30 23:01
The fix is here: https://github.com/emberjs/ember.js/pull/14890

It's late here are creating a failing test is proving tricky. I think we should merge the fix and leave this issue open until I follow up with a test later this week

**Comment by GavinJoyce** [comment] 2017-01-30 23:02
@rwjblue thanks for merging. Can you reopen this issue and assign to me?

**Comment by GavinJoyce** [comment] 2017-02-04 20:48
Here's a (non-ideal IMO) test which will prevent a regression: https://github.com/emberjs/ember.js/pull/14889

**Comment by mixonic** [comment] 2017-03-30 00:29
Fixed in https://github.com/emberjs/ember.js/pull/15080

**Closed by mixonic** 2017-03-30 00:29 UTC
Labels: Bug
