### ISSUE TITLE
Components with with names of native elements throw compilation error

### ISSUE THREAD

**Issue by Exelord** [emberjs/ember.js#18530] opened 2019-10-29 12:08 UTC
Creating components with names of some native elements like `Script`, `Title` etc results with an error :
```Unclosed element `Title` - glimmer-engine```
when using them as a block:
```hbs
<Title>
  It is closed
</Title>
```

Is it expected behavior? 

Tested in Ember 3.13

**Comment by Exelord** [comment] 2019-10-30 14:03
> Not sure what you mean here. Script and title both require closing tags (e.g. are not “self closing”).
My mistake sorry

> Hmm, no I don’t think this is expected. Is it limited to title/script/noscript/style though? Does (for example) <Span>Foo</Span> have an issue?

Not all of them. Im not sure about `Span` but `Div` works fine.

also you can use title as `<Title />`. It just doesn't work as block.

**Comment by rwjblue** [comment] 2019-11-01 17:13
I suspect the issue is with the changes from https://github.com/tildeio/simple-html-tokenizer/pull/69. Since (in the spec) element tag names are case insensitive, this patch does `tagName.toLowerCase()` to normalize. Unfortunately, this means that we treat `<Title>` and `<Style>` the exact same way that we treat `<title>` and `<style>`. 

In addition, that PR lowercases the tag name and looks for a closing tag that is also lowercase (IOW it will match `<Title>` but _not_ match `</Title>`). I think this is the reason for the specific error you see here.

**Comment by rwjblue** [comment] 2019-11-01 17:14
The fix is most likely to fix that PR over in simple-html-tokenizer to specifically _only_ look for the lowercase variants (removing that `.toLowerCase()` call).

**Comment by rwjblue** [comment] 2019-11-01 17:15
@CvX - Do you think you might have any time to poke at this? To confirm my suspicion and/or send in a patch?

**Comment by dcyriller** [comment] 2020-01-29 16:32
@rwjblue I gave it at try here: https://github.com/tildeio/simple-html-tokenizer/pull/81

**Closed** 2020-01-31 01:55 UTC
Labels: Bug, Help Wanted
