### ISSUE TITLE
Deprecate Ember.merge in favor of Object.assign

### ISSUE THREAD

**Issue by mateuspv** [emberjs/ember.js#12320] opened 2015-09-10 13:32 UTC
Ember.merge has similar purpose of Object.assign(es6), I think it is a good idea deprecate it and create/use a polyfill. I opened this Issue since I'm not sure about ember policy about polyfills.

Differences:
-  Ember.merge: Merge the contents of two objects together into the first object.
- Object.assign: copy the values of all *enumerable own* properties from *one or more* source objects to a target object.

Plan:
- [ ] Deprecate Ember.merge.
- [ ] Create/add a polyfill for Object.assign.
- [ ] Update ember code base.

Suggestions/Opinions? Thanks.

**Comment by rwjblue** [comment] 2015-09-10 13:44
I agree with all of your points.

Closing as a duplicate of https://github.com/emberjs/ember.js/pull/12303 which @tricknotes is working on...

**Closed by rwjblue** 2015-09-10 13:44 UTC

**Comment by mateuspv** [comment] 2015-09-10 23:22
I was searching for Ember.merge/Object.assign in the issues, so Ember.assign no caught my attention, 
^-^ Thanks.

**Comment by Caltor** [comment] 2018-07-18 09:34
There isn't a deprecation warning in the API documents for Ember.merge. Should there be?

**Comment by locks** [comment] 2018-07-18 10:37
@Caltor `merge` is not deprecated. If you are interested in proposing that is becomes deprecated, you can propose a new RFC at https://github.com/emberjs/rfcs!

**Comment by Caltor** [comment] 2018-07-18 10:40
@locks No I'm not proposing that at all. I was considering using it then came across this thread which I must have misunderstood as I thought that is what this issue was doing. Can you explain how this issue is different from what I understand it to be please?

**Comment by locks** [comment] 2018-07-18 10:45
The issue was proposing to deprecate `merge` (it might have been prior to RFCs?). https://github.com/emberjs/ember.js/pull/12303 introduced `assign` as mentioned, but a deprecation for `merge` was never introduced.

**Comment by Caltor** [comment] 2018-07-18 10:47
@locks Ah I see! So I did understand the purpose of the thread properly but not the outcome. Thanks for the clarification.

**Comment by locks** [comment] 2018-07-18 10:51
No problem :)
