### ISSUE TITLE
Support Model Unwrapping in Action Helper

### ISSUE THREAD

**Issue by sandstrom** [emberjs/ember.js#11645] opened 2015-07-03 12:34 UTC
Ember has a nifty feature allowing decorators (e.g. `ObjectController`) to be unwrapped by the action helper[1].

I find decoration useful in Ember, and we've used it for a bunch of things throughout the app. With item-controllers gone (I'm in favour of moving from controllers to components!) this has gotten harder.

One solution could be to use duck typing, e.g. if a `unwrapModel` function exist, call it. It's up to the decorator to unwrap itself.

Thoughts?

***

Related, I'm also curious why `Ember.ObjectProxy` is private. We've found it very useful for various things, e.g. for our decorators.

[1] https://github.com/emberjs/ember.js/blob/4200641b9142/packages/ember-views/lib/streams/utils.js#L40

**Comment by stefanpenner** [comment] 2015-07-03 15:26
likely something that should be openned as a RFC or an issue to the RFC repo. As this is not a bug.

**Comment by mixonic** [comment] 2015-07-03 20:02
@sandstrom in general, I suggest one of three:

* Using a component (and possibly block params) to handle decoration.
* Creating a decorator class, but *not* one with default proxy behavior. It will perform better and be compatible with the removal of `this.get` at a later time.
* Using the [new Ember.Helper API](http://emberjs.com/blog/2015/06/12/ember-1-13-0-released.html#toc_new-ember-js-helper-api) to create formatting helpers instead of using a decoration object.

A general solution for decoration may be welcome, but it definitely requires design and likely an RFC.

I'm going to close this for now, but please let me know if I've missed anything of note!

**Closed by mixonic** 2015-07-03 20:02 UTC
Labels: Needs Submitter Response

**Comment by sandstrom** [comment] 2015-07-06 08:54
Fair point stefan, you're right that this isn't a bug!

@mixonic Thanks, that's more or less what I've done (I've wired it using a component and decorator classes). I'll write up an RFC instead.

**Comment by mixonic** [comment] 2015-07-06 14:11
@sandstrom FWIW, you also do not need to go straight into an RFC. We have done a poor job of suggesting it, but you can also open an issue on the RFC repo to gather other use-cases an organize the thoughts of everyone at large before trying to design an API. It might be better to start there, since lots of people are experimenting with different ideas still.

**Comment by sandstrom** [comment] 2015-07-06 17:44
@mixonic Thanks, I didn't know that was an option! I've opened an issue https://github.com/emberjs/rfcs/issues/74

**Comment by workmanw** [comment] 2015-07-06 18:19
Hmm. That is kind of troubling to see `Ember.ObjectProxy` marked as private given that many things rely on it (eg ember-data and ember-buffered-proxy). I sure hope this isn't going away anytime soon.

**Comment by stefanpenner** [comment] 2015-07-06 18:23
> . We have done a poor job of suggesting it, but you can also open an issue on the RFC repo to gather other use-cases an organize the thoughts of everyone at large before trying to design an API.

we should add this to the RFC repo

**Comment by stefanpenner** [comment] 2015-07-06 18:24
@sandstrom got a sec to add that option readme?
