### ISSUE TITLE
Assertion Failed: Ember Views require jQuery between 1.7 and 2.1

### ISSUE THREAD

**Issue by arifhussain353** [emberjs/ember.js#12794] opened 2016-01-09 19:05 UTC
I installed ember-cli by following in "Rock and Roll with Emberjs" book but i am facing this error in console and can't see "Welcome to Ember. Js" text after navigate to  http://localhost:4200.
I did same what was written in book.
![image](https://cloud.githubusercontent.com/assets/12670763/12217767/2bc574a2-b72c-11e5-903b-c0ec0c77e382.png)

**Comment by pixelhandler** [comment] 2016-01-09 19:23
In hour bower.json you may need to use a compatible version for now

**Comment by pixelhandler** [comment] 2016-01-09 19:29
See https://github.com/ember-cli/ember-cli/issues/5316

**Comment by arifhussain353** [comment] 2016-01-09 19:29
after changing to 1.9.0 in bower.json file now i have 1.9.0 version but  it give error " no such file or directory  bower_components\jquery\dist\jquery.js'" ...etc  after navigate to http://localhost:4200.

**Comment by stefanpenner** [comment] 2016-01-09 19:30
@arifhussain353 instruction in that issue are to pin to `jQuery 1.11`, following that run `bower install` again

**Comment by stefanpenner** [comment] 2016-01-09 19:30
This issue is a dupe of several others, going to continue to track them their

**Closed by stefanpenner** 2016-01-09 19:30 UTC
