### ISSUE TITLE
Debug statements in production

### ISSUE THREAD

**Issue by jcbvm** [emberjs/ember.js#13597] opened 2016-06-04 16:05 UTC
I'm having an issue with debug statements coming from an ember addon in my production build. 

I'm really sure my `environment` ran with `production`. The debug statements are coming from the ember addon `ember-simple-auth` and are declared like `Ember.Logger.debug`. 

Are there any cases where debug statements are getting enabled again in production?

**Comment by Serabe** [comment] 2016-06-06 12:33
Confirmed. It does not only happens with messages from addons, but coming from the app as well.

In the bower component, ember.prod.js has actual methods in `Logger` instead of no-ops.

**Comment by rwjblue** [comment] 2016-06-06 12:59
Logger statements are not intended to be stripped or noops. If you want that you would need to use Ember.debug / Ember.warn / Ember.info. Ember.Logger is largely a polyfill from the dark ages when we couldn't rely on console methods to exist or function properly.

**Comment by herom** [comment] 2016-06-06 14:08
Perhaps you could use `ember-cli-groundskeeper` to be sure that your `Logger` statements are stripped out of production code?

**Comment by mixonic** [comment] 2016-06-06 14:56
As this is not a bug, I'm closing it. Please feel free to re-open if we have missed something!

I am going to follow up on @Serabe's ticket and try to get a direction for normalizing the logging API options. They are indeed a mess (Logger should be deprecated, `info` and friends are private and it is unclear if they should become public).

**Closed** 2016-06-06 14:56 UTC
Labels: Bug

**Comment by jcbvm** [comment] 2016-06-06 17:49
Thanks all, missed the thing that `Ember.Logger.debug` is something different than Ember.debug. Will ask the author of `ember-simple-auth` to replace it with `Ember.debug`.

**Comment by rwjblue** [comment] 2016-06-06 18:15
There is still some discussion here though, since Ember.debug / Ember.info / etc are currently marked as private.
