### ISSUE TITLE
Enumerable.filterBy(key, value) should support an array of values to match against

### ISSUE THREAD

**Issue by f3ndot** [emberjs/ember.js#13740] opened 2016-06-22 20:18 UTC
[Enumerable.filterBy(key, value)](http://emberjs.com/api/classes/Ember.Enumerable.html#method_filterBy) could benefit from optionally supported an array of values to test against:

```js
// Available today
this.get('dogs').filterBy('breed', 'corgi');
 => [class, class, class]

// What this issue proposes to support
this.get('dogs').filterBy('breed', ['corgi', 'shiba']);
 => [class, class, class, class, class]
```

This is useful because sometimes you want to filter an array by more than just one value and saves us from writing the long-form callback:

```js
this.get('dogs').filter(function(dog) {
  return ['corgi', 'shiba'].contains(dog.get('breed'));
});
 => [class, class, class, class, class]
```

**Comment by rishi-freshbooks** [comment] 2016-06-22 20:20
👍

**Comment by joelthecoder** [comment] 2016-06-22 20:33
👍

**Comment by btecu** [comment] 2016-06-23 01:32
@rishi-freshbooks & @joelthecoder you know there's a button reaction, right?

@f3ndot it's unlikely that the core team will want to extend the `filterBy`. It seems more appropriate for an addon.

**Comment by f3ndot** [comment] 2016-06-24 18:25
@btecu it feels like a natural extension to the intended `filterBy` method. It feels like a fairly common occurrence and is simply convenient. The very nature of placing it into an addon for such a small tweak feels counter to that goal.

I'm positive I've encountered other frameworks that offer the same nothing of `value` or `[value, value, value]` support.

I might take a stab at putting up a PR myself, to see how the core team feels.

**Comment by Serabe** [comment] 2016-06-24 18:52
I don't know about the core team's feeling about this particular enhancement, though in the past they have expressed they are hesitant to extend the current CPM (see the part of Ember.computed.uniqBy in the [2.6 and 2.7 beta announcement post](http://emberjs.com/blog/2016/06/08/ember-2-6-and-2-7-beta-released.html)).

In any case, you should follow the RFC flow stablished in the [Contributing](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md) file.

Since this is not a bug in Ember but a feature request, I encourage you to follow up in emberjs/rfcs and I am closing this issue.

Thank you!

**Closed by Serabe** 2016-06-24 18:52 UTC

**Comment by f3ndot** [comment] 2016-06-24 19:01
Whoops! I didn't realize there's a new RFC process. Apologies.

**Comment by Serabe** [comment] 2016-06-24 19:17
Don't worry!
