### ISSUE TITLE
cacheFor returns the wrong value for aliased properties

### ISSUE THREAD

**Issue by dwickern** [emberjs/ember.js#15545] opened 2017-07-24 23:13 UTC
Aliased properties (`computed.alias`, `computed.readOnly`, etc) return the [CONSUMED](https://github.com/emberjs/ember.js/blob/2232478367c36f911c7dc3425e3fba478e266358/packages/ember-metal/lib/alias.js#L16) object when you try to get their cached value.

[ember-twiddle](https://ember-twiddle.com/e1f0129649ef8be7d84379cbea776884?openFiles=controllers.application.js%2C)
```js
export default Ember.Controller.extend({
  appName: 'Ember Twiddle',
  aliased: Ember.computed.alias('appName'),
  
  init() {
    this._super(...arguments);
    console.log('before:', this.cacheFor('aliased'));
    console.log('get:', this.get('aliased'));
    console.log('after:', this.cacheFor('aliased'));
  }
});
```

Expected output:
```
before: undefined
get: Ember Twiddle
after: Ember Twiddle
```

Actual output:
```
before: undefined
get: Ember Twiddle
after: Object {}
```

**Comment by krisselden** [comment] 2017-07-25 20:24
I was surprised that `cacheFor` is marked a `@public` to be honest, but cacheFor is only for computed props not aliases, aliases are just using the cache meta for a flag, they don't actually cache values.

**Comment by bekzod** [comment] 2017-07-25 20:33
I think expected behavior should be `alias` should default to `aliased value cache` done so in pr #15548

**Comment by dwickern** [comment] 2017-07-25 20:39
Does public API ever distinguish between computed properties and aliases? They're both created by `Ember.computed`. I assumed aliases are a special-case implementation for performance, but they should outwardly behave the same as computed properties

**Comment by krisselden** [comment] 2017-07-25 20:43
`alias` just uses `Ember.computed` as a namespace, internally they are different.

**Comment by pixelhandler** [comment] 2017-08-25 17:58
@krisselden is this mainly a documentation issue? cc\ @locks

**Comment by pixelhandler** [comment] 2017-11-03 16:42
@locks should this be closed in favor of a documention issue elsewhere?

**Comment by pixelhandler** [comment] 2018-09-28 17:37
@bekzod @dwickern @krisselden @rwjblue is this still an issue, perhaps we should close or create a new reproduction of this, what do you think?

**Comment by pixelhandler** [comment] 2018-10-12 17:06
I updated the twiddle to a current version of Ember, https://ember-twiddle.com/791c87e01d7492046a5978e1aafae197?openFiles=controllers.application.js%2C

**Comment by locks** [comment] 2019-05-30 15:56
Closing as this issue is a weird intersection of APIs and it is not likely to get fixed as the impact could be wide ranging.

**Closed by locks** 2019-05-30 15:56 UTC
Labels: Documentation, Has Reproduction, wontfix

**Comment by lolmaus** [comment] 2019-05-31 06:26
@locks But the description of the issue sounds like a legit bug.

Do you mean by *"the impact [of fixing it] could be wide ranging"* that Ember internalsdepend on the buggy behavior?

**Comment by locks** [comment] 2019-05-31 08:32
@lolmaus according to https://github.com/emberjs/ember.js/issues/15545#issuecomment-317861212 it is working as expected and the issue is a misalignment of expectations.
I mean that changing the behaviour of the API this late into the game can bring unexpected surprises.
