### ISSUE TITLE
When calling `disconnectOutlet`, `render` stops working (ember-2.6)

### ISSUE THREAD

**Issue by ppcano** [emberjs/ember.js#13698] opened 2016-06-17 14:00 UTC
When calling `disconnectOutlet`, the `render` method stops working. The following [ember-twiddle](https://ember-twiddle.com/318a4146d5d18494f0f8aac760ae03c5) reproduces the behaviour.

1. Click render 1  
2. Click Disconnect outlet 
3. Click render 2 

This behaviour has been introduced in `ember-2.6`, but it was working in previous versions.

**Comment by Serabe** [comment] 2016-06-17 14:05
Closing this as a duplicate of #13670 and addressed in #13672 as `[BUGFIX release]` (it should get out there in 2.6.1).

You can check [here](https://ember-twiddle.com/a9747863ec68b9048f5d2632b141bfa3?openFiles=twiddle.json%2C) that your twiddle is working in canary (master).

Thank you for reporting this!

**Closed by Serabe** 2016-06-17 14:05 UTC
