### ISSUE TITLE
[1.13+ Regression] Attempted to register a view with an id already in use 

### ISSUE THREAD

**Issue by OrKoN** [emberjs/ember.js#11925] opened 2015-07-30 07:31 UTC
See the following [jsbin](http://emberjs.jsbin.com/disevavudi/1/edit?html,js,output). Click "Up" several times and you will get an error: Uncaught Error: Assertion Failed: Attempted to register a view with an id already in use: labelId. 

The component having id=labelId is rendered twice in the template but there is a condition that ensures that there should be one element with this id at any moment:

```
{{#if show}}
  {{#x-label id="labelId"}}
    {{x-checkbox id="checkboxId"}}
  {{/x-label}}
{{else}}
  {{#each model as |item index|}}
    {{x-li tagName="li" item=item}}
    {{#if (eq index 0)}}
      <li>{{#x-label id="labelId"}}
        {{x-checkbox id="checkboxId"}}
      {{/x-label}}</li>
    {{/if}}
  {{/each}}
{{/if}}
```

Here is a [working jsbin for Ember 1.12.1](http://emberjs.jsbin.com/yunukimaca/1/edit?html,js,output).

P.S. the condition inside the `#each` loop seems to be important to reproduce the issue.
P.S.S. Tried to test with Ember 2.0.0-beta.4 but could not make it work because Ember could not find the `eq` helper

**Comment by mixonic** [comment] 2015-07-30 13:40
@OrKoN this message seems to be catching a bug, no? Non-unique ids introduce a variety of unexpected behaviors.

**Comment by OrKoN** [comment] 2015-07-30 13:55
@mixonic Can't I remove an element with an id and create it again in a different place with the same id? The non-unique id should never be rendered twice because of the boolean `show` condition but Ember thinks it is. Plus if rewritten like this it works: http://emberjs.jsbin.com/tejezavomu/1/edit?html,js,output but that's not my use case. In my app I render the component either separately or after the first item of the list. Of course, I can find a workaround but looks like some kind of bug to me.

**Comment by pixelhandler** [comment] 2015-07-31 19:14
@OrKoN Since v1.13.6 was released today I tested your jsbin example with 1.13.6 and I still see the same issue.

**Comment by OrKoN** [comment] 2015-07-31 20:05
@pixelhandler Thanks! I have tried to test with Ember 2.0.0-beta.4 but could not make the `eq` helper work...

**Comment by noslouch** [comment] 2015-08-13 19:50
Hi, I have a similar issue with a reduced test case here: 
http://emberjs.jsbin.com/ladenej/edit?js,output

There is a set of radio input components rendered by an each loop. Their IDs are determined by the index and values are computed from an inventory on the controller. If the value of the enumerable used in the loop changes, the components are re-rendered.

The issue comes in when values are shared between rendered outputs. My hunch is that Glimmer is optimizing re-renders by looking at what is coming out, and keeps items in the DOM if they overlap.

This is happening on 1.13.8.

**Comment by noslouch** [comment] 2015-08-13 20:11
FWIW: there are no error messages for ember 2.0.0: http://emberjs.jsbin.com/begoso/edit?js,output

but there are many deprecation notices.

**Comment by runspired** [comment] 2015-08-13 20:25
@mixonic inputs needing known IDs is a problem for ember right now.  I bump into lots of scenarios like this where the input is unique, has an explicit ID (needed for labels), but throws this error when an `if` block changes or a `model` transition occurs (usually but not always with liquid-fire involved).

It's never that there is actually 2 instanced of an ID present, it's that one instance is being torn down but isn't removed yet, and another is being activated.

Something I've thought about is trying to build template helpers for generating unique IDs for form inputs.  Something like this.

```
<label for={{(useInputId "foo-input-"}}>Foo</label>
<input type="text" id={{getInputId "foo-input="}}>
```

Where a given ID can only be consumed once before it's assigned a new `uid`, but this just feels to heavy a solution for avoiding teardown during animation/if block switching cases.

**Comment by devinus** [comment] 2015-09-12 09:54
I am also experiencing this issue.

If I do `this.set('items', [])` and then do the render in an `Ember.run.later` it will work fine because it forces Glimmer to re-render *after* the old elements are removed. This is obviously bad.

**Comment by devinus** [comment] 2015-09-12 10:31
This should also definitely be labeled as *Glimmer* and *Regression*.

**Comment by devinus** [comment] 2015-09-12 10:33
Additionally, this is present even if I use `Ember.run.scheduleOnce('afterRender')`

**Comment by rwjblue** [comment] 2015-09-12 12:01
I suspect that the initially reported issue is related to one of the memory leak bugs fixed in 1.13.10 that was causing an {{each}} in an if/else to not be torn down properly when traversing from the truthy to falsey blocks.

**Comment by rwjblue** [comment] 2015-09-12 12:47
Upstream fixing PR with description of the issue: https://github.com/emberjs/ember.js/pull/12272.

Confirmed that the reported issue JSBin is working http://rwjblue.jsbin.com/noyuvib/edit?html,js under 1.13.10.

**Comment by rwjblue** [comment] 2015-09-12 13:47
Looks like there is another scenario reported by @noslouch that I need to dig into also. 

Reopening for now.

**Comment by devinus** [comment] 2015-09-12 14:40
@rwjblue this is definitely happening on 1.13.10 for me.

**Comment by devinus** [comment] 2015-09-12 14:58
@rwjblue For more information, it seems like I'm passing an index to a component within an each like @noslouch's example as well.

**Comment by rwjblue** [comment] 2015-09-12 21:37
In the [JSBin](http://rwjblue.jsbin.com/doyaja/edit?js,output) an array of numbers is iterated over via `{{each}}` and a component is created for each using the iteration index as the components `elementId`.

When you click a button, the underlying array of numbers is swapped out with another array of numbers triggering a rerender.  During the rerender an assertion is triggered because two items exist with the same `elementId`.  The following is a walk through of what is happening:

1. When initially rendered we create components for `[12000, 24000, 144000, 216000, 288000, 360000]` with their array positions being the `index` in the template (which is used for the component's `elementId`'s).
2. Click on "change frequency"
3. The templating layer begins processing the new list of items `[1000, 2000, 12000, 18000, 24000, 30000]`
  * A new entry is added for `1000` (`elementId` of `0` is used)
  * A new entry is added for `2000` (`elementId` of `1` is used)
  * The previously rendered item for `12000` is reused because the item being iterated is the same as the prior iteration (it has already been rendered with `elementId` of `0`).
  * A new entry is added for `18000` (`elementId` of `3` is used)
  * The previously rendered item for `24000` is reused because the item being iterated is the same as the prior iteration (it has already been rendered with `elementId` of `1`).
  * A new entry is added for `30000` (`elementId` of `5` is used)

As you can see you have actually told Ember to create two elements with an ID of `0`, this is what the assertion is correctly telling you.

---

After doing the digging and tracking down what is actually happening here, this isn't something that we can fix unless we completely throw away any rerender optimizations that were added.

**Comment by rwjblue** [comment] 2015-09-12 21:37
@stefanpenner - I'd like to close this, but your call.

**Comment by noslouch** [comment] 2015-09-12 21:50
Thank you for the clear explanation of the Ember internals on this. 

What about the use case @runspired brings up [his comment](https://github.com/emberjs/ember.js/issues/11925#issuecomment-130829852)? These are form elements with labels taking advantage of HTML's native click-label-and-focus-input behavior on labels and inputs with matching `for` and `id` attributes?

In my situation I ended up resolving this by rendering each "frequency" and displaying based on another property:
```
{{#if isMoreFrequent}}
    {{#each moreFrequentLevels as |level index|}}
        {{x-label for=index}}
        {{x-input id=index}}

**Comment by rwjblue** [comment] 2015-09-12 22:21
You need to avoid using `id` as an `index` by itself because once an element is created we **never** update its `elementId` (and I believe there is a warning/assertion somewhere if you try to change it), so when an item is reused it is likely to cause an issue because the `index` is used similarly to my walk through above.

However, if you use something from the object being yielded you are roughly guaranteed to avoid this type of conflict, because if the underlying object is reused it will still need/have the same value for `id`.

---

The point of the technique you are asking about is just that the `for` attribute has the same value as `id` on the input.  The technique works perfectly well if you use something based on the object that is being yielded (because that the the basis of reuse by the rendering engine).

For example, you could do something like (assuming the thing yielded is an object and not a primitive):

```handlebars
{{! in the template }}
{{#each items as |item|}}
  <label for={{identity-for item}}>Foo</label>
  <input type="text" id={{identity-for item}}>
{{/each}}
```

```javascript
// app/helpers/identity-for.js
import Ember from 'ember';

export default Ember.Helper.helper(function([object]) {
  return Ember.guidFor(object);
});
```

**Comment by stefanpenner** [comment] 2015-09-12 22:46
@rwjblue I agreed with you.

Although I suspect this may cause some upgrade pains. This feels like a big :footprints: :gun:, relying on dynamically toggling ID's settling correctly, is an unintended hazard. I apologies we in the past exposed such a hazard.

**Closed by stefanpenner** 2015-09-12 22:46 UTC

**Comment by devinus** [comment] 2015-09-13 03:44
@noslouch's example is exactly what I'm doing. `label for` and `input id`. What I'm wondering is why isn't the element just being reused? Why is it trying to create an element with the same ID?

**Comment by devinus** [comment] 2015-09-13 04:19
Also, can this be solved by using e.g. `key="@item"`?

**Comment by devinus** [comment] 2015-09-13 06:36
**UPDATE:** My hunch was correct. Using `key='@index'` solves this problem, I'm guessing because it no longer tries to tie the element to previous elements in the array? @rwjblue

**Comment by devinus** [comment] 2015-09-13 06:38
Also, using key='@index' seems MUCH faster in this case.

**Comment by alvinvogelzang** [comment] 2015-09-29 11:57
`key='@index'` works for me as well in Ember 1.13.0
