### ISSUE TITLE
Regression from 2.8 onward (Glimmer2?) textarea unusable in ie11

### ISSUE THREAD

**Issue by adam-knights** [emberjs/ember.js#14539] opened 2016-10-28 08:15 UTC
1) Take any `{{textarea value=testing rows=3}}` in an Ember app with 2.8 or 2.9.

2) Type a few words "hello its me"

3) Click somewhere in the middle and try to add a new word, after the first key stroke it moves you to the end of the textarea. This makes the control unusable for our users.

Reproduction here: http://jsbin.com/vodaxipeda/1/edit?html,js,output

Click run with js, takes a while on ie, but then try out the textarea as above.

This does not appear on chrome - it appears that Ember is now causing this: http://stackoverflow.com/questions/6899047/why-does-ie-8-make-the-cursor-jump-to-the-end-of-the-textarea-for-this-js - in particular `"In IE, whenever the <textarea> gets modified, the cursor will jump to the end."`

This also appears in 2.9. This is a big regression for us and we've had to roll production back to 2.7.

Possibly related to glimmer 2?

**Comment by Serabe** [comment] 2016-10-28 08:29
Ember 2.8 and 2.9 does not ship Glimmer 2.

I'm adding the Needs Bug Verification to check if someone can get a windows machine and replicate it.

Thank you!

**Comment by adam-knights** [comment] 2016-10-28 08:51
Thanks @Serabe . I also tried 2.10.0-beta.2 and that appears to resolve the issue, perhaps some of the prep for glimmer 2 caused the issue, but then it itself fixes it?

I guess (once someone else verifys) its a question of whether its worth having this fixed on 2.8 LTS, and would be good to know so we can plan our versioning.

**Comment by rwjblue** [comment] 2016-10-28 11:27
2.8 is an LTS so it's definitely important to figure this out and fix there. Just needs digging to figure out what changed to break it.

**Comment by gregdillon** [comment] 2016-11-10 19:16
We just noticed this regression in our production app as well. I tried moving to 2.9.1 from 2.9.0 and the error is still there. I'm looking at IE11 right now.

**Comment by adam-knights** [comment] 2016-12-02 13:57
This may even be specific to ie11 on Windows 7. ie11 on windows 10 does not do this with 2.8 or 2.9 for me.

@adamlawson if you up the versions in the js bin to 2.10 is it resolved in that version?

**Comment by adamlawson** [comment] 2016-12-05 11:22
@adam-knights Just tested the jsbin in IE11 (Windows 7) and yes it's resolved in ember 2.10

**Comment by RobIsHere** [comment] 2016-12-13 12:26
Should we keep the older LTS and skip 2.8.3 LTS until the next one because of this? What is the recommended way to go?

**Comment by adam-knights** [comment] 2016-12-13 20:03
@RobIsHere My gut feel is a platform specific bug that is fixed by glimmer in 2.10 is unlikely to have that much priority.

If you answer yes to: Could any of your users be on win7 + ie11 and does your app/site have textareas? Then I would at least wait to see what comes first, either a fix or the next LTS.

**Comment by Vishwaas** [comment] 2017-02-20 21:55
We are facing this issue in IE9 with Ember lts-2-8. Any solution figured?

**Comment by adamlawson** [comment] 2017-02-21 08:07
@Vishwaas no solution for that version as far as I know for that version. I reverted to 2.7 until 2.10 was released. In 2.10 the issue is resolved.

**Comment by locks** [comment] 2017-02-21 10:14
Closing as the issue seems confirmed to be fixed in 2.10. Thanks everyone!

**Closed by locks** 2017-02-21 10:14 UTC
Labels: Needs Bug Verification

**Comment by RobIsHere** [comment] 2017-02-21 13:41
I do not think this should be closed! It is an LTS issue. Until the next LTS is out, this issue is valid! Perhaps Tag it with something like "LTS 2.8"

I even knew this issue existed BEFORE doing the upgrade to 2.8 because I looked here! So we are still on 2.5 with our video editor. Waiting for the next LTS. And everything is just fine. No one wants to spend hours on debugging known things.

**Comment by rwjblue** [comment] 2017-02-21 13:57
> I do not think this should be closed! It is an LTS issue. Until the next LTS is out, this issue is valid! Perhaps Tag it with something like "LTS 2.8"

IMO, it is extremely unlikely that someone would have found this issue without searching, and as such it is just as findable now as it was when you found it. 😺 

As it stands now, having issues like this open hinders our ability to triage actual ongoing and new issues, and has little (or no) benefits to keeping it open.

---

Regardless of keeping this open, this issue doesn't rise to the standard of requiring an LTS bug fix release anyways (only 5 folks have commented as affected since 2.8 which was > 18 weeks ago). However, if you care deeply please bisect and identify what caused the issue and we would be happy to review a targetted patch for `lts-2-8` branch.

**Comment by Vishwaas** [comment] 2017-02-21 20:04
I would love to see it fixed, I will see if I can dwell more into it.

In the meantime if somebody is looking for an alternate solution, this is what I did for now.

```
export default Ember.Component.extend({
  tagName: 'textarea',

// add more attributes if needed.
  attributeBindings: ['value', 'maxlength'],

  focusOut() {
    this.set('value', this.$().val().trim());
  }
});
```

**Comment by zombeerose** [comment] 2017-03-14 15:56
This issue is affecting all of our sites.  A LTS patch would be ideal.
