### ISSUE TITLE
When a route doesn't have a model property defined and the route is hit, it throws an ambiguous error

### ISSUE THREAD

**Issue by ckl1989** [emberjs/ember.js#14940] opened 2017-02-18 23:45 UTC
It should likely say something about how a the model property is missing but instead it just shows:

```
Error message: Assertion Failed: Expected route:companies to resolve to an Ember.Route but instead it was function () {
      var Class = makeCtor();
      var proto;
      Class.ClassMixin = _emberMetal.Mixin.create(this.ClassMixin);
      Class.PrototypeMixin = _emberMetal.Mixin.create(this.PrototypeMixin);

      Class.ClassMixin.ownerConstructor = Class;
      Class.PrototypeMixin.ownerConstructor = Class;

      reopen.apply(Class.PrototypeMixin, arguments);

      Class.superclass = this;
      Class.__super__ = this.prototype;

      proto = Class.prototype = Object.create(this.prototype);
      proto.constructor = Class;
      _emberUtils.generateGuid(proto);
      _emberMetal.meta(proto).proto = proto; // this will disable observers on prototype

      Class.ClassMixin.apply(Class);
      return Class;
    }.
```

Saying that it 'expected to resolve to a route but instead...etc', sounds like it couldn't find the route at all. For beginning users, this is really confusing.

**Comment by rwjblue** [comment] 2017-02-19 01:34
I'm not quite sure how this is cropping up, can you share a reproduction (either ember-twiddle or full demo app) so we can try to figure this out?

**Comment by ckl1989** [comment] 2017-02-20 01:12
I tried it on ember twiddle with es6 and it seems to work!

I wonder if this is caused by coffeescript's translation (sorry I forgot to mention that I'm using coffeescript). I found the translated source code to be something like in the ember twiddle below. 

https://ember-twiddle.com/0b078a277a3af91b9cd6adb12a4aae6b?fileTreeShown=false&openFiles=routes.my-route.js%2C

You can see the following error in the console when you go to the my-route url:

Assertion Failed: Expected route:my-route to resolve to an Ember.Route but instead it was [object Object].
Error
    at assert (https://cdnjs.cloudflare.com/ajax/libs/ember.js/2.10.2/ember.debug.js:5715:13)
    at Object.assert (https://cdnjs.cloudflare.com/ajax/libs/ember.js/2.10.2/ember.debug.js:16643:34)
    at Object.validateType [as default] (https://cdnjs.cloudflare.com/ajax/libs/ember.js/2.10.2/ember.debug.js:5351:19)
    at Class.resolve (https://cdnjs.cloudflare.com/ajax/libs/ember.js/2.10.2/ember.debug.js:5057:51)
    at resolve (https://cdnjs.cloudflare.com/ajax/libs/ember.js/2.10.2/ember.debug.js:2445:36)
    at Registry.resolve (https://cdnjs.cloudflare.com/ajax/libs/ember.js/2.10.2/ember.debug.js:1904:21)
    at Registry.resolve (https://cdnjs.cloudflare.com/ajax/libs/ember.js/2.10.2/ember.debug.js:1908:55)
    at factoryFor (https://cdnjs.cloudflare.com/ajax/libs/ember.js/2.10.2/ember.debug.js:1455:28)
    at instantiate (https://cdnjs.cloudflare.com/ajax/libs/ember.js/2.10.2/ember.debug.js:1520:19)
    at lookup (https://cdnjs.cloudflare.com/ajax/libs/ember.js/2.10.2/ember.debug.js:1388:17)


If it doesn't look familiar perhaps I should Xpost this to ember-cli-coffeescript. 

Thank you for looking at this with me!

**Comment by ckl1989** [comment] 2017-02-20 01:44
Actually I wonder if this is a ember-cli-coffeescript issue. I tried repo-ing this on ember twiddle with es6 and it works fine! 

This is what the coffeescript code looks like:

```
import Ember from 'ember'
CompaniesRoute = Ember.Route.extend
  # model: -> []

export default CompaniesRoute
```

This is what the translated code looks like:

```
define('relationship/routes/companies', ['exports', 'ember'], function (exports, _ember) {
  var CompaniesRoute;

  CompaniesRoute = _ember['default'].Route.extend;

  exports['default'] = CompaniesRoute;
});
```

I will repost this to ember-cli-coffeescript!

**Comment by alexspeller** [comment] 2017-02-20 01:56
@ckl1989 you have made a coffeescript error - `foo.extend` is not the same as `foo.extend()`

**Comment by ckl1989** [comment] 2017-02-20 02:02
@alexspeller wow that was it! Thank you! 

Can you point me to some documentation on this? Is the extend() implicitly set when there is content in the router?

**Comment by locks** [comment] 2017-02-20 02:03
I'm closing as the issue was in the source code, but feel free to finish the conversation :)

**Comment by alexspeller** [comment] 2017-02-20 02:04
@ckl1989 you can read all about the coffeescript syntax on http://coffeescript.org/ - you have to be careful with coffeescript, because it is so terse there are quite a few ways it can be ambiguous to write

**Closed by locks** 2017-02-20 02:03 UTC

**Comment by ckl1989** [comment] 2017-02-20 02:07
@alexspeller got it. Thank you for your help!
