### ISSUE TITLE
attributeBinding for booleans broken in 2.7

### ISSUE THREAD

**Issue by vcipriani** [emberjs/ember.js#14024] opened 2016-08-04 15:36 UTC
In earlier versions, view attribute binding for boolean properties would have generated a tag similar to below:

 `<div id="ember444" bindingval="true" class="ember-view">`

Now it is not displaying the attribute at all if false and doing the following if true

 `<div id="ember444" bindingval class="ember-view">`

This can be verified by creating a brand new app and rendering a simple component setup like below.  

```
import Ember from 'ember';

export default Ember.Component.extend({
    bindingVal: true,
    attributeBindings: ['bindingVal']
});

```

**Comment by pixelhandler** [comment] 2016-08-04 16:54
@vcipriani  I believe that is the desired behavior for boolean attributes in HTML, See http://www.w3.org/TR/html5/infrastructure.html#boolean-attributes

I do not believe this is a bug.

**Comment by rwjblue** [comment] 2016-08-04 17:04
I agree with @pixelhandler. If you do want `bindingval="true"` you should use the string `"true"` or `"false"`.

**Comment by Serabe** [comment] 2016-08-04 17:57
Given the answers by @pixelhandler and @rwjblue, I'm closing this as not a bug. Thank you everybody!

**Comment by vcipriani** [comment] 2016-08-04 20:32
I should have referenced this earlier, but the [Ember documentation](http://emberjs.com/api/classes/Ember.View.html) specifies the behavior we expected.  

> If the return value of an attributeBindings monitored property is a boolean the property's value will be set as a coerced string:

`<input id="ember1" class="ember-view" disabled="false" />`

Its easy enough to use a string, so I don't mind, but it seems like the docs should be updated and this should be noted as a change.

**Comment by dfreeman** [comment] 2016-08-05 03:28
This broke a few of our tests that were using `data-` attributes as testing hooks — the behavior similarly changed for cases like `data-foo={{booleanValue}}`.

The new behavior is definitely preferable (and, as @pixelhandler mentioned, correct), but it was surprising to discover, particularly since there was no mention in the changelog or release announcement.

**Comment by Serabe** [comment] 2016-08-05 16:26
Reopening for tracking the documentation change. Thank you!

**Closed** 2016-08-06 21:55 UTC
Labels: Documentation, Has PR

**Comment by benjaminbalazs** [comment] 2016-08-15 15:11
Was wondering if anyone has built a patch for this to behave as it used to?

**Comment by Serabe** [comment] 2016-08-15 15:18
No, but you can do so easily casting the boolean to a string in your function.
