### ISSUE TITLE
Lost bindings & silent deprecations

### ISSUE THREAD

**Issue by ksnyde** [emberjs/ember.js#11927] opened 2015-07-30 10:38 UTC
I was running into VERY hard to explain behaviour with CP's (w/ getter and setters). I have, however, been able to recreate with Twiddle and I'm pretty sure this is defect in at least 1.x. I suspect in 2.x the best answer may be instead to change the behaviour of CP's setters but for 1.x I feel it must stay true to how its been documented.

- [bad juju](http://ember-twiddle.com/6c1d3f88fbdcb597f36e) -- the twiddle has fully commentary on how to run the test

> warning: this is VERY odd, please wear your safety belts

The problem should be thought of as consisting of two "stages". In both stages the problem is represented by a component which exposes a CP as part of it's API. And in both stages we have two sets of buttons:

-  one set of butttons which passes a value to the API only to be returned *the same value* (this is what you'd expect in a JS setter)
- the second set of buttons pass a value to the API and get a different value back. This seems to be allowed functionality in the Ember CP and is backed unit up tests such as: [computed_test](https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/tests/computed_test.js#L691-L693)

Stages:

- Stage 1

    - In stage one when we use buttons which return "different" values it works in the way that Ember seems to be specified (even if changing the value in the setter may be considered a bad practice in JS).
    - this *does* issue a deprecation warning which is good and starts anyone heading down this path wondering what they should do about it

- Stage 2

    - If you don't have the property displayed in the template that the value is set on the first button press but then the binding to the component breaks down
   - the deprecation warning from stage 1 never shows up so things just silently go dark
   - also worth noting that "stage 2" may in fact be where the coder *starts* (which was the case for me) and therefore I was fumbling around for a long time until i got the deprecation message.

**Comment by ksnyde** [comment] 2015-07-30 10:40
In a London slack conversation this has been discussed quite thoroughly and I believe there is a growing consensus that in 2.x we should change CP syntax to not have a return value to make it consistent with the JS setter. I think the remaining issue is to preserve caching the of a *undefined* value.

**Comment by ksnyde** [comment] 2015-07-30 10:41
In either case I think there is clearly a defect here currently on 1.13.x (where x = 5 for me currently).

**Comment by rwjblue** [comment] 2015-07-30 13:58
Is this a duplicate of https://github.com/emberjs/ember.js/pull/11225?

**Comment by ksnyde** [comment] 2015-07-31 07:18
Looks similar on first blush but hard to be 100%. IMO the detail here is greater though so maybe close this but link to it in #11225?

**Comment by rwjblue** [comment] 2015-08-01 00:16
@ksnyde - Oh, totally agree that this is wonderful detail! I was mostly asking if you thought they were similar / the same issue. When I reviewed it struck me that they may be the same underlying issue...

**Comment by ksnyde** [comment] 2015-08-01 18:01
I suspect they are. Feel free to close if you'd rather track with the other ID ... just as long as it has a place on the radar. :)

**Comment by locks** [comment] 2016-04-19 00:34
I am closing this issue because the linked bug report is closed.
Feel free to re-open the issue if you think it's still justified, thank you!

**Closed by locks** 2016-04-19 00:34 UTC
