### ISSUE TITLE
[3.4.0-beta.2] Cannot update watchers for `isVisible` on component teardown

### ISSUE THREAD

**Issue by Dhaulagiri** [emberjs/ember.js#16871] opened 2018-08-08 14:01 UTC
I'm not sure if I will be able to come up with a concrete, independent reproduction but in the latest 3.4.0 beta I am seeing an error in code that has worked in previous versions of Ember.

The code in question is a computed property on a component where `chart.graphs` is an array of components.

`visibleSiblingGraphs: filterBy('chart.graphs', 'isVisible'),`

This triggers this error when, I think, this component is being torn down.

```
Error: Assertion Failed: Cannot update watchers for `isVisible` on `<my-app@component:my-component::ember1016>` after it has been destroyed.
    at new EmberError (index.js:37)
    at assert (index.js:125)
    at Meta.writeWatching (meta.js:279)
    at unwatchKey (ember-metal.js:1010)
    at unwatch (ember-metal.js:2010)
    at removeObserver (ember-metal.js:1511)
    at removeObserverForContentKey (ember-metal.js:1619)
    at EachProxy.stopObservingContentKey (ember-metal.js:1594)
    at EachProxy.didUnwatchProperty (ember-metal.js:1571)
    at unwatchKey (ember-metal.js:978)
```

For reasons that aren't clear to me, if I switch to using `filter` I no longer get the error:

```
visibleSiblingGraphs: filter('chart.graphs', function(graph) {
    return graph.get('isVisible');
  }),
```

I'm sure we have many other instances of `filterBy` in use so something odd must be happening for this case that I can't quite ascertain just yet, but I thought it would helpful to open something in case anybody has any ideas.

**Comment by sdhull** [comment] 2018-08-18 06:53
We actually had issues with `sortBy` that were fixed by switching to `sort` macro. IIRC it was that they weren't updating in certain circumstances...

**Comment by sdhull** [comment] 2018-08-18 06:57
But at any rate, I got here because we recently upgraded to ember 3.2.2 and I just noticed this error cropping up:
```
"Assertion Failed: Cannot update watchers for `cssString` on `<my-app@component:my-component::ember619>` after it has been destroyed."
```
In my case, I noticed it happens when I am on a page with `{{component 'my-component'}}`, I navigate away then I navigate back. The error happens when I navigate back.

**Comment by Dhaulagiri** [comment] 2018-09-04 21:03
In the interest of time I had moved past this since we had a bunch of other small things to fix in our app and I had a workaround, but I'll see if I can put something together.

**Comment by sdhull** [comment] 2018-09-06 06:46
I tried to build a repro in ember-twiddle for quite some time but failed. I think should should close this issue pending a repro @rwjblue

**Comment by danielspaniel** [comment] 2018-10-08 23:10
This is definitely an issue .. don't close this .. i will try to reproduce somehow

**Comment by rwjblue** [comment] 2018-10-09 02:00
That would be awesome, thank you for trying! FWIW, I'm totally happy to clone a GH repo to reproduce if that is easier...

**Comment by danielspaniel** [comment] 2018-10-09 13:19
interesting .. i found the problem but it might not be a bug bug in ember. 

case 1] 
  for ember simple auth  after signing up i assign the user to a service  ( let's call it  auth )

  ```js
export default class Auth extends Service {
   @reads('currentUser.company') currentCompany
    
   // after sign up do this 
    async loadCurrentUser(userId) {
        const user = await this.store.findRecord('user', userId);
        this.set('currentUser', user);
     }
}
```
so, lets say that other components are binding to   auth.currentUser  
 with the usual 
  
```js
 @reads('auth.currentUser') currentUser 
```

 or maybe a 

```js  
@reads('auth.currentUser.email') currentUserEmail 
```
  
 and then later you sign out with your basic 

```js
   async signOut() {
      await this.session.invalidate();
      this.transitionTo('sign-in');
}
```

then its fine, and then you sign in again and blam, you get the error 
it's like that old user model is still attatched to the auth service ( obviously ) but is now in destroyed state 
and before the new user model ( that is loaded ) can replace it, blah .. ember barfs trying to setup watchers on the old user 

the solution is to be more mouse like and tip toe around the problem. 

```js
 async signOut() {
    this.auth.unloadUser(); // in auth service this method does:  this.set('currentUser, null); 
    await this.session.invalidate();
    this.transitionTo('sign-in');
}
```

and voila .. problem solved. 

this is also issue when i have an array of models in a weakMap and a component is using that array, and later those models are destroyed. the component freaks out.  the answer there is to be more mouselike and before i destroy those array of models to tip toe over to that weakmap and clear them from the array.

**Comment by locks** [comment] 2020-12-04 09:03
`isVisible` is now deprecated, and not present in Glimmer components, so I'm closing this issue. Thanks!

**Closed by locks** 2020-12-04 09:03 UTC
Labels: Needs Reproduction
