### ISSUE TITLE
Bug.ember.js

### ISSUE THREAD

**Issue by AriesTriputranto9** [emberjs/ember.js#20083] opened 2022-05-05 08:45 UTC
### 📙 Describe the Issue
A clear and concise description of what the issue is.

### 🔬 Minimal Reproduction
Please, share a link to the page with the documentation and share steps to reproduce.

### 😕 Actual Behavior
A clear and concise description of what is happening.

**Comment by MelSumner** [comment] 2022-05-19 22:54
Unsure what the issue is, please re-open with more details if this is a problem. For now, I'm closing the issue since it is essentially blank. Thank you!

**Closed by MelSumner** 2022-05-19 22:54 UTC
