### ISSUE TITLE
Cannot pass hash helper to link-to (EmptyObject lacking hasOwnProperty)

### ISSUE THREAD

**Issue by mhluska** [emberjs/ember.js#17018] opened 2018-09-29 12:26 UTC
Sometimes a route can resolve with multiple records like so:

```js
model() {
  const profile = ...;
  const user = ...;

  return RSVP.hash({
    profile,
    user,
  });
},
```

So then you'd think you could use `link-to` like so:

```hbs
{{link-to 'My Profile' 'profiles.show' (hash user=user profile=profile)}}
```

This doesn't work because the `hash` helper returns `EmptyObject` and `extractQueryParams` tries to call `.hasOwnProperty()` on it, resulting in an error.

There's a workaround to this which involves using an action with `transitionTo` but it feels like a poor experience.

This is an issue I've had with Ember for years. What's the correct way to pass multiple records to `link-to` if not this?

I'm using ember-cli 3.0.2.

---

Edit: I've started using the following helper in place of `hash` as a workaround:

```js
import { helper } from '@ember/component/helper';

export function plainObject(params, hash) {
  const object = {};
  // NOTE: `hash` is an `EmptyObject` so we convert to a POJO so that it can be
  // used with `link-to`.
  Object.keys(hash).forEach(k => object[k] = hash[k]);
  return object;
}

export default helper(plainObject);
```

**Comment by rwjblue** [comment] 2018-09-29 12:51
> This doesn't work because the hash helper returns EmptyObject and extractQueryParams tries to call .hasOwnProperty() on it, resulting in an error.

This is a bug, we can (and should) totally fix this (swapping to `’queryParams’ in obj` instead of `obj.hasOwnProperty(‘queryParams')`). Would you mind taking a crack at a PR?

**Comment by mhluska** [comment] 2018-09-29 15:16
Yep, I can take a look tomorrow.

**Comment by mhluska** [comment] 2018-10-01 08:19
@rwjblue it might be a few days before I can get to this.

**Comment by Parrryy** [comment] 2018-10-01 12:55
I wouldn't mind giving this a go, Hacktoberfest and all that :) That's if you can't @mhluska.

**Comment by mhluska** [comment] 2018-10-01 13:54
@Parrryy go for it 😄

**Comment by ctcpip** [comment] 2018-10-02 23:34
> > This doesn't work because the hash helper returns EmptyObject and extractQueryParams tries to call .hasOwnProperty() on it, resulting in an error.
> 
> This is a bug, we can (and should) totally fix this (swapping to `’queryParams’ in obj` instead of `obj.hasOwnProperty(‘queryParams')`). Would you mind taking a crack at a PR?

where is this code?

**Comment by rwjblue** [comment] 2018-10-02 23:55
```
packages/@ember/-internals/routing/lib/system/route.ts:2207:48:      if (!combinedQueryParameterConfiguration.hasOwnProperty(propName)) {
  packages/@ember/-internals/routing/lib/utils.ts:16:50:  if (possibleQueryParams && possibleQueryParams.hasOwnProperty('queryParams')) {
> packages/@ember/-internals/routing/lib/system/router.ts:1668:22:    if (!queryParams.hasOwnProperty(key)) {
```

**Comment by rwjblue** [comment] 2018-10-03 12:55
@mhluska - I'm actually unable to reproduce the original issue, I wrote a test that _should_ have failed but didn't:

```js
    ['@test [GH#17018] using `hash` helper for model']() {
      this.addTemplate('index', `{{link-to 'Post' 'post' (hash id="bar")}}`);
      this.addTemplate('post', 'Post: {{model.id}}');

      this.router.map(function() {
        this.route('post', { path: '/posts/:post_id' });
      });

      return this.visit('/')
        .then(() => {
          this.assertComponentElement(this.firstChild, {
            tagName: 'a',
            attrs: { href: '/posts/bar' },
            content: 'Post',
          });

          return this.click('a');
        })
        .then(() => {
          this.assertText('Post: bar');
        });
    }
```

**Comment by btecu** [comment] 2018-10-03 13:05
@rwjblue maybe the issue here is that in `(hash user=user profile=profile)`, `user` and `profile` are not ids but models. I'm not sure that should be supported, since passing models to `link-to` is already controversial.

**Comment by rwjblue** [comment] 2018-10-03 13:07
The whole `(hash ....)` invocation is seen as a "model" from the `{{link-to`'s perspective.

**Comment by mhluska** [comment] 2018-10-03 16:29
Isn't passing a record to link-to pretty standard? It should prevent the route from reloading data. That's the reason I want to pass two records via hash - to prevent reloading data.

**Comment by btecu** [comment] 2018-10-03 17:02
Define standard.
It works right now but it's been decided that in general it's not a good pattern and in the future it might be no longer supported.

There was at least one RFC related to this, maybe more:
https://github.com/emberjs/rfcs/pull/283

@mhluska Are you able to create a test replicating the issue?

**Comment by shawnren** [comment] 2019-03-18 18:28
I am also not able to reproduce the issue and have written a test that replicates the scenario originally reported. The test passes — there are no issues retrieving the record passed to route via link-to hash. 

https://github.com/emberjs/ember.js/pull/17769

If everything looks good with the test, I guess we can close this issue?

**Comment by rwjblue** [comment] 2019-03-18 18:55
Yep, thank you @shawnren!

**Closed by rwjblue** 2019-03-18 18:55 UTC
Labels: Bug, Good for New Contributors
