### ISSUE TITLE
Query Parameters break with Manually Rendered Route

### ISSUE THREAD

**Issue by cmkornell** [emberjs/ember.js#10562] opened 2015-03-02 21:45 UTC
When using `renderTemplate` and specifying it's controller with query parameters defined (Object or Array), any attempt to `{{link-to}}`, `set` , or manually entering query parameters in address bar for the route fails. They never get to the route or controller. I'm not sure if this is intended behavior, but if it is, it should be documented. Here's a quick jsbin to show the issue: http://emberjs.jsbin.com/cupijipowe

**Comment by pixelhandler** [comment] 2016-06-17 19:13
@cmkornell can you provide an updated example (reproduction of the issue) using a current release of Ember.js or the LTS release (2.4.6) ?

**Comment by rwjblue** [comment] 2016-11-10 17:01
I don't think this should work (though I do understand the confusion about it). 

We look up the controller for the specific route (which in the JSBins case would be `App.TestController`), to determine its query param values. This is a very separate concern from what templates to render.

I'm going to go ahead and close this (because I do not think its a bug), but we can still continue the conversation if you'd like...

**Closed by rwjblue** 2016-11-10 17:01 UTC
Labels: Ember 1.X, Needs Bug Verification, Query Params
