### ISSUE TITLE
Handlebars Helpers Regressions

### ISSUE THREAD

**Issue by realityendshere** [emberjs/ember.js#10812] opened 2015-04-02 19:33 UTC
We use Handlebars helpers to determine if users should see certain parts of the UI. Unfortunately, creating custom if/else style block helpers has gotten more challenging with each Ember release since v1.9.1. I am seeing significant breaking changes and no documentation for updating Handlebars helpers to work with newer Ember releases.

Here are jsbins to illustrate how helpers are breaking:

Ember v1.9.1 (Works as expected)
=======================
http://jsbin.com/hocuro/1/

Ember v1.10.0 (Breaking change: inverse)
=======================
http://emberjs.jsbin.com/xoyulihize/1/

Ember v1.11.0 (White screen of doom)
=======================
http://emberjs.jsbin.com/xibire/2/

Ember v1.11.0 (Block helpers disabled)
=======================
http://emberjs.jsbin.com/xibire/1/

=======================

I've tried to find documentation regarding the evolution of Handlebars/HTMLBars. I understand there is adapter code to make Handlebars and HTMLBars play together and the context (what `this` is) in which helpers run has changed from `controller` to `view` to `undefined`.

In any case, I see this as a breaking change. Or at least an opportunity for someone to document how I should adjust my registered helpers to operate as expected in the newer Ember versions.

Thanks.

**Comment by pixelhandler** [comment] 2015-04-02 19:38
+1 this breaks more that one app I've worked on, really don't want to be stuck on ember 1.9.1

**Comment by rwjblue** [comment] 2015-04-02 21:05
Fixed by https://github.com/emberjs/ember.js/pull/10813.

Working JSBins:

http://jsbin.com/sigoqa/1/edit
http://jsbin.com/cewaha/1/edit

**Comment by rwjblue** [comment] 2015-04-02 21:09
I wish someone had raised an issue in the 1.10 timeframe. At this point, I can likely get these fixes into 1.11.1 (which hopefully will release in a day or so), but I don't see an easy path to getting these fixes into 1.10.x because we have already branched 1.11 into stable.

**Closed** 2015-04-02 21:15 UTC

**Comment by realityendshere** [comment] 2015-04-02 21:34
@rwjblue Thanks for the fix. That was super fast!

**Comment by rwjblue** [comment] 2015-04-02 21:39
@realityendshere - Thanks for reporting.  This compat stuff is pretty important to us, I am sorry this fell through the cracks so long. :disappointed:

**Comment by pixelhandler** [comment] 2015-07-20 21:22
@rwjblue FYI our apps are back to the 'white screen of doom' again. Today we updated to 1.13; not sure yet if this will be a similar regression but with all the changes we can't run beta anymore at least not in the timeframe of the ember release cycles.

**Comment by rwjblue** [comment] 2015-07-20 21:25
@pixelhandler - Sounds bad, please open issues when you track down the cause.  We'll happily fix anything we can for bugs on the Ember side.
