### ISSUE TITLE
sinon.useFakeTimers in acceptance tests break if run.later is used

### ISSUE THREAD

**Issue by Gaurav0** [emberjs/ember.js#14722] opened 2016-12-15 16:13 UTC
You can use sinon.useFakeTimers in an acceptance test, or you can use run.later in your application, but doing both causes the acceptance test to time out.

Reproduction: https://ember-twiddle.com/d5f34d97be1e75b8258e654f6a482d70?openFiles=tests.acceptance.my-acceptance-test.js%2C

**Comment by Gaurav0** [comment] 2016-12-15 17:26
I think the issue is in Backburner.

**Comment by morhook** [comment] 2016-12-15 18:56
I think the problem is that sinon.useFakeTimers() is modifying the environment (the timers of the VM JS, as kind-of-everything depends on setTimeout). 

You can put a lot of `clock.tick(0);` to let run the normal async mechanisms of the acceptance utilities (like `visit(xx)`, `andThen()`, etc).

**Comment by morhook** [comment] 2016-12-15 19:29
p.s.2: I've fixed your twiddle, taking out the 'Date' parameter in `sinon.useFakeTimers()` https://ember-twiddle.com/f2c762d2bdcb25e7329827bf92c91c68?openFiles=tests.acceptance.my-acceptance-test.js%2C

**Comment by stefanpenner** [comment] 2016-12-15 19:29
believe this has been addressed: https://github.com/ebryn/backburner.js/pull/179 (although that was merged yesterday) and it still needs to make its way into ember.

**Comment by Gaurav0** [comment] 2016-12-15 21:22
@morhook Not putting a Date in sinon.useFakeTimers() kind of defeats the point, I am using it so that Date.now() returns a predictable value.

**Comment by pixelhandler** [comment] 2016-12-16 16:55
@stefanpenner so does this need a PR for the Backburner update?

**Comment by robbiepitts** [comment] 2016-12-17 20:16
@pixelhandler I'd be happy to make a follow-up PR in Ember if necessary. Thinking Backburner just needs to cut a new release though.

**Comment by morhook** [comment] 2016-12-19 21:31
@Gaurav0 sounds fair! Thanks for explaining it to me.

**Comment by rwjblue** [comment] 2017-07-04 13:25
Discussed with @turbo87 and we believe this is resolved.

**Closed by rwjblue** 2017-07-04 13:25 UTC
Labels: Bug, Has Reproduction

**Comment by Turbo87** [comment] 2017-07-04 13:30
yes, https://github.com/BackburnerJS/backburner.js/pull/179/files resolved it and has found its way into one of the recent Ember releases, though I can't say which one specifically fixed it.

**Comment by vcipriani** [comment] 2017-08-18 20:59
Just fyi for anyone running into this problem, it looks like the Backburner fix is not included in Ember 2.14.  It looks like it is shipping in 2.15.
