### ISSUE TITLE
5.10: test waiters broken?

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember.js#20724] opened 2024-07-23 09:01 UTC
### 🐞 Describe the Bug

After upgrading the crates.io codebase from 5.9 to 5.10 several tests started failing for no apparent reason. It looks like the test waiters are not working as intended and are causing the tests to be flaky. When I run the test suite locally the subset of failing tests is different from CI, which indicates that race conditions might be responsible.

### 🔬 Minimal Reproduction

see https://github.com/rust-lang/crates.io/pull/9035

### 😕 Actual Behavior

Previously succeeding tests are failing.

### 🤔 Expected Behavior

Previously succeeding tests should keep passing, if the test waiter system is used correctly.

### 🌍 Environment

- Ember: 5.10.1
- Ember-CLI: 5.10.0
- Node.js/npm: 20.15.1
- OS: Linux & MacOS
- Browser: Chrome & Firefox

**Comment by NullVoxPopuli** [comment] 2024-07-23 10:57
This matches what i've been seeing in open source repos, too

**Comment by jelhan** [comment] 2024-07-29 09:25
I noticed the same in one app. The `click` test helper resolves before a network request triggered by that click has settled. The network request is done with `fetch`. The project uses `ember-fetch@8.1.2`. `fetch` is imported from `fetch` package in the file doing the network request.

The tests are working as expected with `ember-source@5.9.0`. They are starting to fail if upgrading `ember-source` to `5.10.1`. I don't see any entry in the changelog for `5.10.0` and `5.10.1`, which may be related.

**Comment by NullVoxPopuli** [comment] 2024-07-29 14:29
Looks like it may have been the legacy waiters that broke: 
![image](https://github.com/user-attachments/assets/c0e050fb-cb61-4f4b-b62e-2a98fd5f3e9b)
 (this is from the `@ember/test-helpers` test suite)
 
 @jelhan do you have a minimal repro of the click resolving too early?

**Comment by jelhan** [comment] 2024-07-29 14:44
> @jelhan do you have a minimal repro of the click resolving too early?

Sadly not. I expect reproducing is not that easy. Only 2 out of many tests in the app are affected.

Aren't the failing tests in `@ember/ember-test-helpers` enough to reproduce and debug?

**Comment by ef4** [comment] 2024-08-05 19:18
#20726 should be a complete fix for this.

**Comment by kategengler** [comment] 2024-08-06 20:12
This should be fixed in v5.10.2 and in v5.11.0-beta.2

**Closed by kategengler** 2024-08-06 20:12 UTC

**Comment by jelhan** [comment] 2024-08-06 22:21
> This should be fixed in v5.10.2 and in v5.11.0-beta.2

I can confirm that v5.10.2 is working as expected in the app which was affected by the bug before.
