### ISSUE TITLE
Newly generated ember-cli@0.2.7 app issuing reduce computed depreciation warning

### ISSUE THREAD

**Issue by Ghostavio** [emberjs/ember.js#11435] opened 2015-06-13 19:21 UTC
I've created a demo repo with this issue [here](https://github.com/Ghostavio/demo-repo).

Just did `ember new demo-repo`, went to `bower.json` and updated both ember and ember data.
`"ember": "1.13.0"` and `"ember-data": "1.0.0-beta.19.1"`.
Then did `bower install` and `ember server` and nothing else, got the following deprecation warning:

```
DEPRECATION: Ember.reduceComputed is deprecated. Replace it with plain array methods
        at Descriptor.ReduceComputedProperty (http://localhost:4200/assets/vendor.js:40073:31)
        at Object.reduceComputed (http://localhost:4200/assets/vendor.js:40459:14)
        at http://localhost:4200/assets/vendor.js:75870:36
        at http://localhost:4200/assets/vendor.js:81831:4
```

cc @rwjblue

**Comment by stefanpenner** [comment] 2015-06-13 19:21
this doesn't seem like an ember-cli issue.

**Comment by stefanpenner** [comment] 2015-06-13 19:23
> "ember": "1.13.0" and "ember": "1.13.0".

this looks like a typo?

**Comment by Ghostavio** [comment] 2015-06-13 19:27
@stefanpenner fixed :)

**Comment by stefanpenner** [comment] 2015-06-13 19:29
this is a bug in ember-data. I have opened an issue: https://github.com/emberjs/data/issues/3327

**Comment by Ghostavio** [comment] 2015-06-13 19:30
awesome, that was fast :p

**Comment by rwjblue** [comment] 2015-06-13 19:35
@ghostavio - Can you remove ember data from the package.json of your test app (then stop and restart the server), and see if that clears the deprecation? If it does, this issue can be closed in favor of the ED one above.

**Comment by stefanpenner** [comment] 2015-06-13 19:38
> @ghostavio - Can you remove ember data from the package.json of your test app (then stop and restart the server), and see if that clears the deprecation? If it does, this issue can be closed in favor of the ED one above.

it totally is ember-data. 100% confirmed

**Closed by stefanpenner** 2015-06-13 19:38 UTC
Labels: pending 3rd party fix

**Comment by yonida** [comment] 2015-06-22 19:24
how can i get this fix ? @stefanpenner

**Comment by pangratz** [comment] 2015-06-22 20:34
@yonida you need to update `ember-data` to at least `v1.13.0` ...

**Comment by yonida** [comment] 2015-06-23 07:03
This is what I'm using:
DEBUG: Ember      : 1.13.0
Ember Data : 1.0.0-beta.19

What's ember-data 1.13.0 ?

**Comment by pangratz** [comment] 2015-06-23 07:58
ember-data v1.13 has been released a few days ago: http://twitter.com/fivetanley/status/610929008872587264 ...

**Comment by yonida** [comment] 2015-06-23 08:24
Great, thanks !
