### ISSUE TITLE
v3.6.0-beta.2 -assert-implicit-component-helper-argument error

### ISSUE THREAD

**Issue by bekzod** [emberjs/ember.js#17172] opened 2018-11-01 20:52 UTC
in production builds this lines are not being striped https://github.com/emberjs/ember.js/blob/master/packages/ember-template-compiler/lib/plugins/transform-component-invocation.ts#L214-L231 

here is screenshot of `ember-template-compiler.js` file from ember-source@v3.6.0-beta.2 
https://cl.ly/5a41e4cae417/Screen%20Shot%202018-11-02%20at%201.47.48%20AM.png
not sure if `ember-template-compiler` has notion of debug mode

here is error when app is run in production mode `ember s --prod`
https://cl.ly/4bcb2c1853a8/Screen%20Shot%202018-11-02%20at%201.51.47%20AM.png

**Comment by bekzod** [comment] 2018-11-01 20:55
cc @chancancode

**Comment by mariowilde** [comment] 2018-11-20 15:40
The error still happens in ember-source 3.6.0-beta.4.

**Comment by buschtoens** [comment] 2018-11-20 16:09
Dupe of / related to https://github.com/emberjs/ember.js/issues/17154

**Comment by devinus** [comment] 2018-11-24 07:32
After hours of debugging, I gave up and added a helper that takes care of the problem in production. It's obvious there's some compilation issue, but I couldn't track down where.

* app/helpers/-assert-implicit-component-helper-argument.js

```js
import { warn } from '@ember/debug';
import { helper } from '@ember/component/helper';

const name = '-assert-implicit-component-helper-argument';

const helperFn = {
  [name](params) {
    const [node, error] = params;
    warn(error);
    return node;
  },
}[name];

export default helper(helperFn);
```js

**Closed** 2018-12-05 12:04 UTC
