### ISSUE TITLE
Ambiguity between curly component invocation and local properties

### ISSUE THREAD

**Issue by 22a** [emberjs/ember.js#18094] opened 2019-06-13 19:12 UTC
Recent versions of ember have dropped the validation that component names must contain a dash which can lead to undesired behaviour when creating new angle bracket components whose names clash with existing local property lookups.

Say for example I create a `<Text>` component and have an existing classic component, `my-banner`, which uses a local `text` property in its template, like so:

```hbs
{{text}}
```

 Historically, relying on implicit `this` allowed the property lookup to behave as expected but, now that we have a `<Text>` component, the `{{text}}` expression is being interpreted as curly invocation of the `text` component.

I understand that the solution for this is to stop relying on implicit this contexts so we should enable [template-lint rules](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-implicit-this.md) and/or strict mode to prevent this causing issues but I wonder was this intended for the Octane upgrade path?

Minimal reproduction app on 3.10: [22a/ember-curly-component-invocation-repro](https://github.com/22a/ember-curly-component-invocation-repro)

**Comment by rwjblue** [comment] 2019-06-13 21:20
Yes, newly generated octane apps should absolutely be failing linting when falling back to the implicit `this`.

**Comment by 22a** [comment] 2019-06-14 09:27
Yes, this is the case for new octane apps:

```
octane-app/templates/components/my-banner.hbs
  5:6  error  Ambiguous path 'text' is not allowed. Use '@text' if it is a named argument or 'this.text' if it is a property on 'this'. If it is a helper or component that has no arguments you must manually add it to the 'no-implicit-this' rule configuration, e.g. 'no-implicit-this': { allow: ['text'] }.  no-implicit-this
```

Is this something we have considered warning or erroring on in a pre-Octane app?

**Comment by rwjblue** [comment] 2019-06-14 15:44
Yep, you can absolutely enable the ember-template-lint rule yourself in `.template-lintrc.js` and we are planning to enable it by default for all apps once we can ensure the codemod is straightforward enough for people to be able to easily silence the warnings/errors.

**Comment by mupkoo** [comment] 2019-08-03 20:51
This feels like a regression to me.  Since Ember 3.11, you do not have a component that matches a name of a local property of any of the addons that you have.

**Comment by locks** [comment] 2020-04-19 11:30
Closing as the linting is now enabled by default!

**Closed by locks** 2020-04-19 11:30 UTC
