### ISSUE TITLE
Yield hash can not be used as 2-way binding

### ISSUE THREAD

**Issue by nightire** [emberjs/ember.js#14481] opened 2016-10-16 16:55 UTC
According to PR:  #13177, yield hash in contextual component should be able to use as 2-way binding from v2.4.4, but today in v2.8.2 I still found this problem, here is a twiddle to reproduce it:

https://canary.ember-twiddle.com/23760ac65b7703a730748c29e862cff5?openFiles=templates.application.hbs%2C

I also include a work-around in this twiddle, it could solve my problem right now but still could be a pain point for future usage.

**Comment by Serabe** [comment] 2016-10-16 19:23
Sorry if I did not explain the issue correctly in that PR. The problem there is that `value` in `{{component (component "change-button" val=value)}}` was not being double bound but that has nothing to do with the `hash` helper. A value passed to the `hash` helper is never double bound.

There is more to this, a helper is only recomputed when an argument is changed (a function helper, a class helper has more control over this), and the value returned from the helper is not linked in any way to the input parameters. You can check this in [this twiddle](https://canary.ember-twiddle.com/eb6a0be9d3c9d754f2a7ba61ea637012?openFiles=helpers.my-id.js%2C). Please, notice that given I am using `with` the _inner_ part is not being shown unless you type something.

You can ping me in the Slack channel if you need more help on this subject!

Closing this since it is not a bug.

**Closed by Serabe** 2016-10-16 19:23 UTC

**Comment by nightire** [comment] 2016-10-16 20:17
@Serabe thank you for the explanation, now I understand better with how `hash` helper works.
