### ISSUE TITLE
Testing a Component using _ProxyMixin produces autorun error.

### ISSUE THREAD

**Issue by bdiz** [emberjs/ember.js#13216] opened 2016-03-30 17:43 UTC
Trying to use a component that mixes in _ProxyMixin (ember v2.4.1). I get the autorun error during integration testing.

```
import Ember from 'ember';

export default Ember.Component.extend(Ember._ProxyMixin, {
});
```

Then in my test:
```
moduleForComponent('my-component', 'Integration | Component | my component', {
  integration: true
});

test('it responds to changes in content object', function(assert) {
  this.set('myContent', Ember.Object.create({myProperty: true}));
  this.render(hbs`{{my-component content=myContent }}`);
  this.get('myContent').set('myProperty', false); // Autorun error happens when setting a property on content
  assert.ok(...);
});
```

This results in the autorun error: `Error: Assertion Failed: You have turned on testing mode, which disabled the run-loop's autorun. You will need to wrap any code with asynchronous side-effects in a run`

I found when I add a run-loop to `lib/mixins/-proxy.js` the error goes away:

```
import run from 'ember-metal/run_loop';

function contentPropertyDidChange(content, contentKey) {
  var key = contentKey.slice(8); // remove "content."
  if (key in this) { return; } // if shadowed in proxy
  run(() => propertyDidChange(this, key)); // Added run-loop here.
}
```

I don't know enough about the run-loop and ember internals to know if this has any implications beyond being an annoyance in testing, but I thought I'd report it just in case.

I can wrap setting of `content` properties in a run-loop as a workaround.

```
Ember.run(() => this.get('myContent').set('myProperty', false));
```

Can close if this is small fry. I know it's a bit obscure. :) Thanks.

**Comment by pixelhandler** [comment] 2016-04-09 01:27
@bdiz I'm curious have you discussed this in the testing channel of the embercommunity.slack.com chatroom ?

Usually added an Ember.run solves the testing error.

However I'm a bit hesitant when relying on private APIs, see https://github.com/emberjs/ember.js/blob/v2.4.4/packages/ember-runtime/lib/mixins/-proxy.js#L36-L44 

Would using ArrayProxy or ObjectProxy solve the issue?

**Comment by bdiz** [comment] 2016-04-09 01:36
Hi @pixelhandler, no I didn't know about the slack channel, but thanks for letting me know about it. 

Unfortunately ArrayProxy and ObjectProxy won't help me as I need a "ComponentProxy" as it were.  

There doesn't seem to be an explanation as to why _ProxyMixin was made private when it was originally public.

**Comment by rwjblue** [comment] 2016-04-09 14:22
> There doesn't seem to be an explanation as to why _ProxyMixin was made private when it was originally public.

`_ProxyMixin` was never public, (`Ember.ObjectProxy` is and has always been public).  https://github.com/emberjs/ember.js/pull/5156 introduced the the idea of exposing it as a mixin in the `ember-runtime-proxy-mixin` feature, but was never enabled and the feature was subsequently removed in https://github.com/emberjs/ember.js/pull/5392.

---

The error you are receiving is telling you that your tests `set` must be wrapped in run loop (as you described).  Either of the following would work to resolve the issue:

```
Ember.run(() => { this.get('myContent').set('myProperty', false); })

// or
this.set('myContent.myProperty', false); // `this.set` in unit/integration tests is always run wrapped
```

---

I'm going to close this, as it is not a bug in the framework.

**Closed by rwjblue** 2016-04-09 14:22 UTC
