### ISSUE TITLE
IE8: {{input type=""}} returns an error

### ISSUE THREAD

**Issue by MichaelVdheeren** [emberjs/ember.js#11553] opened 2015-06-25 10:32 UTC
Using IE8 and Ember.js 1.13.2

When using `{{input type="checkbox"}}` IE8 shows a "this command is not supported" error. I guess this is the result of the type being set after the input element is rendered which is not possible in IE8.

http://stackoverflow.com/questions/18240063/ie8-throws-this-command-is-not-supported-error-when-using-knockout-for-data-bi

**Comment by MichaelVdheeren** [comment] 2015-06-25 10:34
Using <input type="checkbox" checked={{value}}> works but {{input type="checkbox" checked=value}} not

**Comment by stefanpenner** [comment] 2015-06-25 13:48
In the < case, consider using an action to be notified of the DOM change

**Comment by MichaelVdheeren** [comment] 2015-06-25 13:51
A temporary solution would be:
`<input placeholder="Search" value="{{search}}" onchange={{action (mut search) value="target.value"}} />`

But @rwjblue said he will look into this for 1.13.3

**Comment by stefanpenner** [comment] 2015-06-25 14:52
> A temporary solution would be:
> <input placeholder="Search" value="{{search}}" onchange={{action (mut search) value="target.value"}} />

this is actually likely the best solution moving forward, although the original should also continue to work.

**Comment by MichaelVdheeren** [comment] 2015-06-29 13:55
Any idea if 1.13.3 would land this week?

**Comment by rwjblue** [comment] 2015-06-29 14:50
@MichaelVdheeren - 1.13.3 should be out this week, but it hasn't fixed this issue yet.

**Comment by XrXr** [comment] 2015-07-06 17:38
I ran into this also. `{{input type="text"}}` also breaks, and I think it breaks if you type is set at all.

I looked into it a bit, and the cause seems to be ember trying to the the type of the input element after it has been inserted into the DOM tree. IE 8 does not allow this.

**Comment by stefanpenner** [comment] 2015-07-06 18:09
@XrXr have you tried 1.13.3 ?

**Comment by XrXr** [comment] 2015-07-06 18:33
@stefanpenner yes

**Comment by stefanpenner** [comment] 2015-07-06 18:46
> I looked into it a bit, and the cause seems to be Ember trying to set the type of the input element after it has been inserted into the DOM tree

into a fragment, it shouldn't be trying to insert it after its been inserted into the regular tree.

**Comment by XrXr** [comment] 2015-07-06 19:59
@stefanpenner It turns out I was half correct. :P

I did a quick search and found that setting `type` on an element in the regular tree would cause this error, and I assumed that is what caused the error here. I was too quick to judge.

It happens that the same error happens if the element is a part of a document fragment.

Below is a small test case
```html
<!DOCTYPE html>
<html>
  <body>
    <script>
      var input = document.createElement('input');
      var docFragment = document.createDocumentFragment();
      docFragment.appendChild(input);

      input.setAttribute('type', 'text');  // throws

      alert('not reached');
    </script>
  </body>
</html>
```

So the type of an input element must be set before it is inserted into *any* tree.

**Comment by stefanpenner** [comment] 2015-07-06 20:36
> So the type of an input element must be set before it is inserted into any tree.

This sounds reasonable, thanks for digging into this further. Are there other attributes like this?

**Comment by XrXr** [comment] 2015-07-06 20:49
I don't know if there are any other attribute that have this behaviour. If there are any, we can be sure that there will be bug reports :)

**Comment by stefanpenner** [comment] 2015-07-06 20:56
I have opened another issue on HTMLBars to track this.

We will have to fix this for 1.13.x, which is a shame since it wont be needed for 2.x at all.

**Comment by XrXr** [comment] 2015-07-06 21:18
By the way just, `{{input}}` is enough to break it

**Comment by stefanpenner** [comment] 2015-07-06 21:57
@XrXr ya, I would imagine.

**Comment by zanemayo** [comment] 2015-07-10 11:07
Is there any update on this bug? 
Here is a simple page showing the problem: http://zanemayo.github.io/ie8-textbox.html

**Comment by stefanpenner** [comment] 2015-07-10 14:49
> Is there any update on this bug?

I plan to look at it soon. Sorry for the delay, my queue has been full.

**Comment by stefanpenner** [comment] 2015-07-10 14:49
tracking issue: https://github.com/tildeio/htmlbars/issues/380

**Comment by btecu** [comment] 2015-07-20 19:29
`{{textarea}}` is also affected.

**Comment by rwjblue** [comment] 2015-11-12 18:13
Fixed by https://github.com/emberjs/ember.js/pull/12596.

**Closed by rwjblue** 2015-11-12 18:13 UTC
Labels: Bug
