### ISSUE TITLE
Can't pass component to controller

### ISSUE THREAD

**Issue by oskarrough** [emberjs/ember.js#11192] opened 2015-05-17 15:17 UTC
To get access a component in a controller, I set the component as a property on itself which exposes it to the controller([link](http://www.samselikoff.com/blog/getting-ember-components-to-respond-to-actions/)).

- Works in Ember 1.12: http://emberjs.jsbin.com/wokelikice/1/edit
- Fails in 1.13.0-beta.1: http://jsbin.com/gohovifedi/2/edit
- Also tried using ember-cli: http://vast-plate.surge.sh

Not sure what I need to change to make it work again?

**Comment by mixonic** [comment] 2015-05-17 15:40
@wycats this is failing (silently) because `set` is called on the proxy during rendering. IMO this should either blow up or just work. Blowing up is fine, but silently failing seems really weird.

@oskarrough a work around (and better in 1.12 as well) is to wrap the `set` in an `Ember.run.schedule('afterRender'`. See http://jsbin.com/jifevugesu/1/edit?html,js,output

**Comment by oskarrough** [comment] 2015-05-17 15:59
@mixonic thank you! Is there a way to enable two-way binding as well? E.g. changing the input should change the value in the component.

**Comment by mixonic** [comment] 2015-05-17 16:11
@oskarrough there is two way binding, but you are changing a parent component during rendering. That is the currently unsupported behavior. We might be changing it to raise instead of fail silently, or may consider it t a regression. Unsure at this point.

**Comment by oskarrough** [comment] 2015-05-17 16:26
Alright, thanks for looking in to it. In your jsbin, changing the input doesn't change the component title. What is needed to make sure the component updates as well?

**Comment by mixonic** [comment] 2015-05-17 16:40
@oskarrough that looks like another regression.

**Comment by mitchlloyd** [comment] 2015-05-18 00:19
@mixonic It's interesting to note that issue #11188 may be related to this issue. During render using `viewName`, a property is set on a parentView and that change is not causing a rerender.

**Comment by locks** [comment] 2016-04-15 09:57
@mixonic is this still relevant?

**Comment by mixonic** [comment] 2016-04-15 14:48
The `Fails in 1.13.0-beta.1` jsbin is for Canary. This still fails without warning or error on master today.

**Comment by mixonic** [comment] 2016-04-15 14:49
The correct "fix" here is just that there should be an error, not a silent failure.

**Comment by rwjblue** [comment] 2016-04-17 14:52
@mixonic - TBH, I'm not sure that is correct either.  Two way binding isn't just a thing that can be done during rendering.

**Comment by rwjblue** [comment] 2016-04-17 15:37
Will be fixed by https://github.com/emberjs/ember.js/pull/13351

**Comment by rwjblue** [comment] 2016-04-19 11:40
Going to close this in favor of #13351, but there is some discussion there about whether we should add support back for this...

**Comment by locks** [comment] 2016-04-20 00:57
@rwjblue I'm gonna go ahead and close it. That discussion can happen in the issue that supercedes this one, too.

**Closed by locks** 2016-04-20 00:57 UTC
Labels: Ember 1.13, Ember 2.X
