### ISSUE TITLE
Tagless component defined with ES Class causes error

### ISSUE THREAD

**Issue by peabnuts123** [emberjs/ember.js#16177] opened 2018-01-26 02:48 UTC
I am trying to use ES class syntax (this is because I am actually using ember-typescript, but this issue is not related to that project). As I understand the RFC for this was merged some time last year and some work has been done in this space to support projects _like_ ember-cli-typescript and ember-decorators. I have read the RFC and am using the class syntax correctly from what I understand but perhaps I am still doing something wrong.
I am trying to have a tagless element through `tagName = ''` but the way ES classes are implemented seems to have a problem with this. 

See the following example, which I've created in [this ember twiddle](https://ember-twiddle.com/6b95090de2f49db44438b78f2f8a721d?openFiles=components.my-component.js%2Ctemplates.components.my-component.hbs): 
```javascript
import Ember from 'ember';

export default class MyComponent extends Ember.Component {
  constructor() {
    super();
    
    // Empty string causes runtime error
    // "Assertion Failed: You cannot use `elementId` on a tag-less component"
    // Comment this line to fix
    this.tagName = '';
    this.debug = "Lorem ipsum dolor sit amet";
  }
}
```

This compiles fine, but when I visit the page I get a strange Error:
```
Assertion Failed: You cannot use `elementId` on a tag-less component: <component name>
```

I am unsure if I'm doing things wrong, if i've uncovered a legitimate bug, or if this is just something that is not yet implemented. Any ideas?

**Comment by Serabe** [comment] 2018-01-27 23:46
The problem here is that for `tagName = ''` to work, it needs to be set before `super` is called.

In this case, using fields might fix it:

```js
class MyComponent extends Ember.Component {
  tagName = '';

  constructor() {}
}
```

Though this does not fix the problem when the tagName needs to be conditional (as an example, Ember Power Select).

**Comment by peabnuts123** [comment] 2018-01-28 19:31
Love your work with the PR there. Using fields does not seem to fix it as it seems that transpilation tends to spit out the `this.tagName = ''` after `super()`, especially in an `ember-cli-typescript` context. As you say, it's something that really should be supported anyway and so, again, good job making that PR 🙂

**Comment by pixelhandler** [comment] 2018-09-28 18:08
@peabnuts123 is this still an issue, perhaps we should close or create a new reproduction of this, what do you think?

**Comment by peabnuts123** [comment] 2018-10-02 23:57
I have not worked on this project in a while, so I cannot confirm how it is going with newer versions of ember. If I run my twiddle above against Ember 3.2 it still seems to be happening – you also cannot set `this.tagName` before calling super, as it results in the error:

```
Must call super constructor in derived class before accessing 'this' or returning from derived constructor
```

**Comment by dguettler** [comment] 2018-10-11 14:39
I can confirm that this still seems to be an issue in Ember 3.4 and ember-cli-babel < 7.0
I didn't see this issue with the latest ember-cli-babel, but this caused an issue with ember-decorators. So I had to go back to 6.17 and now I get above mentioned error for a components with `tagName = ''`

**Comment by locks** [comment] 2019-03-26 20:08
cc @pzuraq

**Comment by pzuraq** [comment] 2019-03-27 01:15
We do not support using classic components with native classes directly in Ember. In order to customize the element, you should use [ember-decorators](https://github.com/ember-decorators/ember-decorators), specifically the `@tagName` class decorator.

**Comment by rwjblue** [comment] 2019-04-09 19:51
Sorry for the run around here, @pzuraq's last reply is spot on.

I'm going to go ahead and close this as a (very polite and apologetic) "wont fix".

**Closed by rwjblue** 2019-04-09 19:51 UTC
