### ISSUE TITLE
New computed property syntax breaks _super on set

### ISSUE THREAD

**Issue by davewasmer** [emberjs/ember.js#11177] opened 2015-05-15 20:02 UTC
[jsbin with old arity syntax (works)](http://jsbin.com/rajiqaqiwi/1/edit?js,console)

[jsbin with new object syntax (broken)](http://jsbin.com/qihexemuni/2/edit?js,console)

The new computed property object syntax seems to break if invoked via `_super` calls on set. The setter method is called, but afterwards seems to override the entire property value.

*Edit: improved the jsbin output to make things a bit clearer*

**Comment by rwjblue** [comment] 2015-05-15 20:09
Welp. That is not good.

**Comment by rwjblue** [comment] 2015-05-18 04:55
@cibernox - Do you happen to have any time to poke around at this one?

**Comment by cibernox** [comment] 2015-05-18 06:23
I'll have time today

**Comment by cibernox** [comment] 2015-05-18 07:56
Ok, @davewasmer I've looking into this and it's not a bug. The code in the new CP was not equivalent to the code using the old syntax. 

In the example using the old syntax, you always return `this.get('foo')` both in the getter and setter. That is the correct way of doing things.
In the example with the new syntax your are calling `set` and returning it. The call to `set` returns the property itself, not the value being set, and anything you return from the setter function gets cached as the new value of the property.

If in the JSBin with the new syntax you do this change you will have the desired behaviour:
```diff
let Parent = Ember.Object.extend({
  
  _foo: 'some starting value',
  
  foo: Ember.computed({
    get() {
      console.log('parent is getting _foo');
      return this.get('_foo');
    },
    set(key, value) {
      console.log('parent is setting _foo to ' + value);
-      return this.set('_foo', value);
+      this.set('_foo', value);
+      return this.get('_foo');
    }
  })
});
```

Alternatively, if you change the JSBin with the old syntax to match the behavior in the new one:

```diff
let Parent = Ember.Object.extend({
 
  _foo: 'some starting value',
  
  foo: Ember.computed(function(key, value) {
    if (arguments.length > 1) {
-      this.set('_foo', value);
+      return this.set('_foo', value);
    }
    return this.get('_foo');
  })
  
});
```

you'll have the wrong behaviour too

**Comment by rwjblue** [comment] 2015-05-18 11:05
@cibernox - Thank you for digging into it, sorry I didn't catch that when I reviewed the JSBin.

@davewasmer - I'm going to close this, but I am happy to reopen if the above explanation doesn't fix/help...

**Closed by rwjblue** 2015-05-18 11:05 UTC

**Comment by davewasmer** [comment] 2015-05-18 14:03
@cibernox ah, okay, that makes sense. Thanks for the help :+1: 

@rwjblue I think that does it - probably should have RTFM a bit more closely :wink:

**Comment by stefanpenner** [comment] 2015-05-18 14:29
It's really to bad that ember .set doesn't return the value. Then super would just work

**Comment by rwjblue** [comment] 2015-05-18 14:34
Yeah, I'm not even really sure why we return the CP instance from `set` anyways. Is it "fixable" or would that be a SemVer breakage?

**Comment by cibernox** [comment] 2015-05-18 14:41
I surprised me too when I was refactoring CPs. Maybe the initial intention was to allow some kind of chaining?

**Comment by rwjblue** [comment] 2015-05-18 14:43
I'd be open to changing (or at least seeing what breaks if we do)...

**Comment by cibernox** [comment] 2015-05-18 14:57
I'll schedule that for today, given that I'm going to investigate how to give a better hint of where the problem lies on deprecated setter.

**Comment by stefanpenner** [comment] 2015-05-18 16:16
I would prefer that we mimic `foo.prop = val` behavior. This would be semver break, but likely we have 2.0 coming out soon.

@rwjblue we have 3 weeks to change this, c/d ?. I am not 100% sure how to deprecate though..

**Comment by cibernox** [comment] 2015-05-18 16:40
@stefanpenner I think that we can check in [this area](https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/computed.js#L463-L465) if the return value of the setter is a descriptor and raise a warning.

But could cause gazillions of deprecation warning, we need to set a flag in the object or something.

**Comment by cibernox** [comment] 2015-05-18 22:32
@stefanpenner @rwjblue I've found where this happens: https://github.com/emberjs/ember.js/blob/master/packages/ember-runtime/lib/mixins/observable.js#L198-L215

Apparently it's intentional, although I don't see any utility on this chaining. 

It was introduced in [this commit](https://github.com/emberjs/ember.js/commit/2b28b204d5ea49cb2a132bbe58b9767492e1892e) **exactly** *4 years ago*.

This is the last opportunity to change this until Ember 3.0, so it's now or never. But on the other hand, its *****g scary to modify something that internal. 

I quick grep shows that chaining it's not used by ember.js internally, and the only tests that fail are those actually testing for this feature.

**Comment by stefanpenner** [comment] 2015-05-18 23:10
> This is the last opportunity to change this until Ember 3.0, so it's now or never. But on the other hand, its *****g scary to modify something that internal.

I would love to kill this. My vote would be + 1

**Comment by spruce** [comment] 2015-07-23 13:45
Just found this discussion after trying to update to use new cp syntax. Why can ember not automatically call this.get when this.set returns undefined? Now I have to include the ugly getters at the end of all setters.
```javascript
set: function(key, value) {
  this.set('salary', parseFloat(value.replace(',', '.')).toFixed(2)); // german input
  this.get('salary');
}
```

Would be nice to only write this:
```javascript
set: function(key, value) {
  this.set('salary', parseFloat(value.replace(',', '.')).toFixed(2)); // german input
// auto get the new value
}
```

**Comment by cibernox** [comment] 2015-07-23 20:00
@spruce To be aligned with regular javascript getters/setters you must return a value from your setter function.

However, I have good news. In ember 2.0 `this.get` changes it's behavior and now returns the setted value instead of `this` (again, to be aligned with JS getters/setters). That means that you will be able to write:

```js
set: function() {
  return this.set('salary', parseFloat(value.replace(',', '.')).toFixed(2));
}
```

You still have to explicitly return, but it's a nice one-liner.

**Comment by spruce** [comment] 2015-07-24 12:55
nice thanks :+1:

**Comment by spruce** [comment] 2015-07-24 20:02
how would one solve this one?
```javascript
street_complete: Ember.computed('street', 'streetnr', {
    get: function() {

      if(this.get('street') === '' && this.get('streetnr') === '') {
        return '';
      }
      return this.get('street') + ' ' + this.get('streetnr');
    },
    set: function(key, value) {
      this.set('street', value.substr(0, value.indexOf(' ')));
      this.set('streetnr', value.substr(value.indexOf(' ') + 1));
      return this.get('street_complete'); //always returns ""
    }
  })
```
