### ISSUE TITLE
isEmpty({'length': 0}) returns true

### ISSUE THREAD

**Issue by mangatinanda** [emberjs/ember.js#18875] opened 2020-04-15 13:56 UTC
Please check the [Twiddle](https://ember-twiddle.com/cac3fd2a9045495195256f2e7f0da8c1)

This is because of the [function code](https://github.com/emberjs/ember.js/blob/8b273eb04023a876dbf968a05929d8a21a8fd27b/packages/%40ember/-internals/metal/lib/is_empty.ts#L61)

Is this the expected behaviour? 
If yes, at least the documentation should be updated with this example.

**Comment by locks** [comment] 2020-04-19 16:43
Thanks for reporting, duplicate of https://github.com/emberjs/ember.js/issues/18745.

**Closed by locks** 2020-04-19 16:43 UTC
