### ISSUE TITLE
Using `instanceof Ember.Handlebars.SafeString` is broken on beta and canary

### ISSUE THREAD

**Issue by workmanw** [emberjs/ember.js#13354] opened 2016-04-18 12:29 UTC
In our app we have a few occasions where we do `if (str instanceof Ember.Handlebars.SafeString)` when handling string values, this capability is broken with the recent deprecation of `new  Ember.Handlebars.SafeString("")` because of the way in which this deprecation was introduced. 

See: https://github.com/emberjs/ember.js/commit/0e95d7cc1325efa03d19732ebb89034279b5deeb

The problem is that the function `SafeString` is no longer publically accessible. What was `Ember.Handlebars.SafeString` is now a wrapper function around `htmlSafe`.

It isn't just our app either. While submitting a PR to Ember-i18n I discovered their tests are broken because they too do not have access to this function. See: https://github.com/jamesarosen/ember-i18n/blob/master/tests/unit/utils/i18n/default-compiler-test.js#L56-L59

I'm not sure what the best course of action is to prevent breaking backwards compatibility and keep the deprecation warning.

**Comment by rwjblue** [comment] 2016-04-18 13:16
Duplicate of https://github.com/emberjs/ember.js/issues/13318, would you mind moving the description above into a comment on that issue?

**Closed by rwjblue** 2016-04-18 13:16 UTC

**Comment by workmanw** [comment] 2016-04-18 13:30
Oops. Sorry about that. Monday fail. :(

**Comment by rwjblue** [comment] 2016-04-18 13:33
No worries!  We definitely need to understand and address the underlying issue...
