### ISSUE TITLE
<input> is not updated when value is set to a substring of typed in value

### ISSUE THREAD

**Issue by martndemus** [emberjs/ember.js#12125] opened 2015-08-17 09:46 UTC
[JS Bin](http://emberjs.jsbin.com/fabafesufu/1/edit?html,css,js,output)

Just type in the input and see what happens. It should cut off at 4 characters.
Possibly because glimmer sees the same value of 4 chars, so it doesn't think it needs to update the input.

**Comment by rwjblue** [comment] 2015-08-17 14:21
The issue is that the morph cache gets out of sync with the currently displayed value in the input box.  

For example, if you always reset to a unique value the input text is updated properly: http://rwjblue.jsbin.com/labema/edit?html,js,output.

**Comment by rwjblue** [comment] 2015-08-17 14:24
I need to dig around a bit more with this to see if we have a solution for the bare `<input>` case.  If you use a component we have a mechanism for this built-in (it is how `Ember.TextField` does it) via `this.readDOMAttr`).

You can take a look at [this](https://github.com/aptible/dashboard.aptible.com/blob/master/app/components/one-way-input/component.js) one-way-input component that I have been using (also supports sanitization which seems somewhat related to what you are trying to do).

**Comment by rwjblue** [comment] 2015-08-22 13:03
FYI - This is what I use for one-way-input: http://ember-twiddle.com/2d7246875098d0dbb4a4.

**Comment by martndemus** [comment] 2015-08-25 08:16
@rwjblue Thanks! We came up with something that looks the same as that.

**Comment by rwjblue** [comment] 2016-04-18 04:57
You could use the `event.target` to force the DOM elements value back to what you expect.  This is the only way AFAIK to keep the internal and external state of the `<input>` in sync.

http://emberjs.jsbin.com/nutidab/edit?html,js,output

I'm going to close this, as it is unlikely that we can fix the internal state representation issue mentioned above.  You would need to drop down to the lower level DOM API's to handle these sorts of things...

**Closed by rwjblue** 2016-04-18 04:57 UTC
