### ISSUE TITLE
select issue on hover when pressing modifier key (Chrome only)

### ISSUE THREAD

**Issue by eben-roux** [emberjs/ember.js#11865] opened 2015-07-23 05:50 UTC
It seems that the following behaviour presents itself only on Chrome (Firefox, IE work fine):

With any `select` element (so not only `Ember.Select` but plain html `select` tag) when the list is dropped and the mouse pointer is hovered over an option that is *not* selected and you press, say, the **shift** key it *appears* as though the option is selected.  However, when then clicking on another application (outside the browser) the item stays in the semi-selected in such a ways that the item is displayed in the `select` box but when dropping the list you can see that the value is still on the previous one.  The `change` event is also not fired.

Our testers picked this up while performing screen prints and, since the option isn't actually selected, but *appears* to be, incorrect data is submitted.

**Comment by mixonic** [comment] 2015-07-23 15:19
@eben-roux I'm a little confused after trying to parse this, but it seems like it may be an issue with Chrome?

**Comment by eben-roux** [comment] 2015-07-23 17:42
From what I can tell it is an Ember/Chrome combination.  A plain 'select' tag within no Ember loaded works fine.  With an Ember application even the plain select tag has this strange behaviour;  I have a sneaky suspicion that it has something to do with the way Chrome fires its events but that is just speculation :)

Anyhow.  It isn't a big deal but there it is.

**Comment by stefanpenner** [comment] 2015-07-23 17:44
@eben-roux can you provide a [jsbin](https://emberjs.jsbin.com/?html,js,output) that accurately demonstrates this? That way we can with 100% confidence look at the exact code you are looking at.

**Comment by mixonic** [comment] 2015-07-23 17:48
@eben-roux a JSBin would definitely help. I ask if it is a Chrome issue, because if it is you should definitely open an issue upstream on their tracker. We can work around it maybe, but they won't be able to fix the issue if they don't know about it.

**Comment by eben-roux** [comment] 2015-07-23 19:12
Here is a jsfiddle: http://jsfiddle.net/EbenRoux/6j5Louq0/

I can never get JSBin to run.

Here are the steps (Chrome):
- the drop down displays 'red'
- drop down the combo box and hover over 'blue'
- press the shift key
- click on *another* application (not in the browser)
- the drop down will display blue but when you drop it down it will still have 'red' selected

You can easily bind the to 'change' to show that it doesn't fire.

**Comment by pixelhandler** [comment] 2015-07-24 23:00
@eben-roux I am not able to reproduce this on my mac in Chrome. Perhaps recoding a video with quicktime and posting the link to a location on dropbox would help to demonstrate the issue. 

Also the steps to reproduce do seem like an edge case. (press shift and click another app)

**Comment by eben-roux** [comment] 2015-07-27 08:43
I have created a short video to demonstrate this (Windows 8.1, Chrome Version 44.0.2403.89 m):

https://www.dropbox.com/s/whe8cyg78adol5a/chrome-ember-select.mp4?dl=0

Keep your one eye on the select and the other on the captions; else try pausing every-so-often :)

**Comment by rwjblue** [comment] 2015-08-16 20:38
This really feels like a browser bug to me. I am not sure what we can do here....

**Comment by locks** [comment] 2016-04-15 10:45
I am closing this issue as it seems it's not an Ember.js bug.
Feel free to re-open the issue if you think it's still justified, thank you.

**Closed by locks** 2016-04-15 10:45 UTC
Labels: wontfix
