### ISSUE TITLE
[Glimmer2] Ember.binding support

### ISSUE THREAD

**Issue by chadhietala** [emberjs/ember.js#13902] opened 2016-07-26 18:37 UTC
__Failing Test__ : [should accept bindings as a string or an Ember.binding](https://github.com/emberjs/ember.js/blob/3cfc9614bbd92ee8e80b6c4894b024f2e14bffae/packages/ember-glimmer/tests/integration/binding_integration_test.js#L8)
__Knowledge__: Requires knowledge of reference/tagging system

This appears to be an "off by one" bug where the previous expectation becomes the current assertion.

**Comment by chancancode** [comment] 2016-07-27 06:35
@krisselden I figured out why this is not working, but I don't know enough about the bindings/runloop system to fix it.

### What _is_ working

* the bindings are propagated correctly
* the references are pulling the right thing
* setting the binding correctly dirty both objects

### What is _not_ working

* timing issue causing the bindings to be synced too late

### Details

The current strategy is that we will capture the revision in Backburner.begin, then decide if we have any rendering work to do in the render queue. This is not working, because the bindings are being synced *after* the render queue in practice, causing us to not notice the change.

### Timline of events (synchronous/chronological)

1. This line is reached:  https://github.com/emberjs/ember.js/blob/798ba8a1c82b9d041ed25f1e914d69643d40d41e/packages/ember-glimmer/tests/integration/binding_integration_test.js#L37
2. `Backburner.begin`: we captured CURRENT_TAG.value()
3. `set(this.context, 'direction', 'up');`
4. `Backburner.flush`:
    1. sync (nothing)
    2. actions (nothing)
    3. routerTransitions (nothing)
    4. render
        1. CURRENT_TAG.validate(capturedValue) => false
        2. rerender
            1. UPDATE-COMPONENT
                1. component.setProperties(namedArgs.value())
                2. endPropertyChanges
                3. ObserverSet.flush
                4. fromDidChange
                5. this._scheduleSync
    5. sync (bumped back to the front)
        1. set(component, ...)
        2. dirty(component)
    6. sync (again? not sure why; might be a bug?)
    7. actions (nothing)
    8. routerTransitions (nothing)
    9. render (**nothing this time – since we already drained it previously**)
    10. afterRender
    11. destroy
    12. rsvpAfter

Soo... the problem is that binding sync is.. async, and we didn't schedule a second re-render in response to that. But otherwise, tags, etc are working just fine here.

**Comment by chancancode** [comment] 2016-07-27 06:40
@krisselden can you triage this tomorrow? by that I mean do you think this is only a problem for `Binding`s or if it's a deeper problem that is likely to affect apps that don't use that feature. If it's the former, I think it's pretty low-priority.

**Comment by chancancode** [comment] 2016-07-29 10:37
Closed by #13935 and #13937

**Closed by chancancode** 2016-07-29 10:37 UTC
Labels: Glimmer2
