### ISSUE TITLE
Failed to find a valid digest in the 'integrity' attribute for resource for the css file

### ISSUE THREAD

**Issue by alxistn** [emberjs/ember.js#14877] opened 2017-01-25 21:25 UTC
Hello everybody,

I'm having an issue with ember. When I build my app with the command line: **ember build --environnement=production** and upload my website online, I have a problem with the sh256 integrity for my css ressource file.

I have identified what caused this to happen and it's very unclear why.

When I do this modification in my .scss file, I get the integrity error.

<img width="991" alt="screen shot 2017-01-25 at 22 21 33" src="https://cloud.githubusercontent.com/assets/9989863/22309797/17fef9b8-e34d-11e6-8294-2453b207e6a6.png">

When I cancel the modification, everything's back to normal.

**EDIT:**
Here is my package.json just in case:

<img width="396" alt="screen shot 2017-01-25 at 22 32 49" src="https://cloud.githubusercontent.com/assets/9989863/22310096/41f6ec70-e34e-11e6-8176-aa402b90bb65.png">

**Comment by nathanhammond** [comment] 2017-01-26 01:57
@alxistn The integrity check is a hash of the file which gets generated. If you _only_ upload the CSS file the integrity constraint which appears in `index.html` will not be satisfied and it will block loading of the CSS. I believe your issue is that you need to publish all of the assets.

Please stop by [#-help](https://embercommunity.slack.com/messages/-help/) in the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/) in the future and seek help from the wonderful people in our community!

I'm closing this issue as likely not a bug but _please feel encouraged to keep commenting here_ if upon further investigation on your side you discover that it may in fact be a bug. We will still continue to receive notifications from any followup comments on this issue; being closed doesn't mean that we're ignoring the thread.

**Closed** 2017-01-26 01:58 UTC
