### ISSUE TITLE
[LEADERSHIP] ember-cli Should Provide the Ember Documentation

### ISSUE THREAD

**Issue by lazaridis-com** [emberjs/ember.js#15052] opened 2017-03-22 03:50 UTC
(This addresses the Project Leadership, so please, leave the issue open, until it is addressed or at least seen by the relevant people.)

Having lost excessive amounts of time with the documentation provided on "guides.emberjs.com" (e.g. tutorial), I've finally dropped Ember from my evaluation list.

But Ember is now back on my eval list, in the form of "ember-cli" (which has nice real-life docs, without "TDD fixation", straight to the business result, which is a working application)

The suggestion to the Ember leadership is: let ember-cli provide the (primary) documentation within guides.emberjs.com. This would **greatly** enhance things.

Or at **minimum**, please have the decency (yes: **decency**) to provide a link to the ember-cli tutorials, which have simply  **far** better quality that the ones on "guides.emberjs.com".

https://ember-cli.com/user-guide/#tutorials

I don't know if there are any "political" issues here with the 2 teams (ember core and ember-cli). But one thing I know: The Ember documentation is a **major weakness**, and the ember-cli documentation is a **strength**.

So, please act.

(This affects emberjs/guides#1851 and lazaridis-com/js-eval#7)

**Comment by Serabe** [comment] 2017-03-22 09:34
Hello, @lazaridis-com,

as stated in our [Contributing guide](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md) this issue tracker is reserved to bugs in the framework.

Please, also observe that suggesting that people act with a lack of moral or respectability for not having done or not doing what you think it would be best is against our [Code of Conduct](http://emberjs.com/guidelines/). We ask people to be respectful and empathetic and suggesting a lack of decency is none of them.

Closing this as is not a bug.

Thank you!

**Closed by Serabe** 2017-03-22 09:34 UTC

**Comment by lazaridis-com** [comment] 2017-03-22 09:51
Guess I have to use email, to bypass those strange "Issue-Guard-Bots" which do not even know what the word "bug", "defect", "decency" and mostly "Empathy" means. So sad all this...

**Comment by locks** [comment] 2017-03-22 09:56
You addressed the project leadership, and that's who's handling your issue.

As for the actionable portion of your post, both the "User Guide" and "Extending" sections of the Ember CLI documentation are linked to from http://emberjs.com/learn/, which serves as the hub for the current and future documentation efforts.

**Comment by lazaridis-com** [comment] 2017-03-22 10:12
Note to readers: As a workaround, ignore **any** documentation on the emberjs.com domain, and use the https://ember-cli.com/user-guide/#tutorials. Don't miss this one: http://yoember.com/, which will most possibly make you like Ember again, after loosing your faith in it.

@locks , time to eat!

**Comment by pixelhandler** [comment] 2017-03-22 14:59
@lazaridis-com the issue trackers for the various Ember code repositories are not the place for a `meta` discussion. I invite you to open a discussion in the forums. That would be the proper place to reach out to leadership and formulate a positive discussion and share your ideas about how to improve the documentation and learning experience. 

I'm sure you're aware that this framework and associated libraries, learning resources, etc. are provided by volunteers and not a commercially backed project. Which means if you want to change things you need to get involved in a positive way. This means finding a way to serve the existing leadership among the various teams, by helping lift the weight of say, "improving the learning experience".  

Your tone in this post does not come across as considerate of the sweat and labor of the individuals whom you are calling to "take action". I don't think you'll get far with that, not in this community. 

My opinion is… if you can find a way to roll up your sleeves and help solve "shared problems", as a community, you will benefit greatly. And if not, perhaps consider purchasing a commercial product with the level of support you expect.

Some info on the Ember discussion forums…

- https://discuss.emberjs.com/faq

> Meta is where all leadership and governance forms, a place for debate and evaluating direction.

- https://discuss.emberjs.com/t/what-is-meta/746

**Comment by lazaridis-com** [comment] 2017-03-23 04:27
@pixelhandler , I'm done here. Tell this stuff to your goldfish. Will have more effect.

**Comment by lazaridis-com** [comment] 2017-03-23 05:07
Note to readers:

### Positive Attitude
If you really think that a "more positive attitude" would help, then look at the quality comments of @mike-north :

https://github.com/emberjs/guides/issues/1718#issuecomment-274283176

The people discussing with North do not even realize that he plays in one or two leagues above them. They simply do not grasp the essence of what he's talking about. And because they are volunteers, no one intervenes to say "hey, cool down. You're out of your league here.".

Who pays? The users, who hit on this terrible docs and loose time. Cause this is volunteer work, but it's on the "emberjs.com" domain (a commercially backed framework).

### Contributing

Usual "open-source-whiners" do not grasp the concept of "analysis is contribution". You think, you file an issue, you invest time. But look what happens when a direct contribution is suggested:

me: "May I send you a reworked version of a page, so you can see how it should/could look?"
Result: @locks locks the issue (this is actually fun, "@locks locks" - this project has a dedicated locks role).
https://github.com/emberjs/guides/issues/1718#issuecomment-288283548

## final result:

As you've seen, its impossible to even try to make the docs better within this project.

Not perfect, but much better docu (both, for beginner & expert)

https://ember-cli.com/user-guide/#tutorials
http://yoember.com/

Just go with it, and try to contribute there. Possibly it works better.
