### ISSUE TITLE
Build error in ember js, that occurs while adding route with with ajax call.

### ISSUE THREAD

**Issue by flynsequeira** [emberjs/ember.js#15570] opened 2017-08-05 08:51 UTC
This occurs only after i shut down and restart server after creating new route with some ajax call (that calls another ember app). Tried deleting npm package and doing npm install again, removing tmp folder, and so on. Details given in [stackoverflow this link](https://stackoverflow.com/questions/45500112/ember-build-error-that-is-happening-on-adding-a-route-that-has-an-ajax-request/45500490#45500490)

**Comment by pixelhandler** [comment] 2017-08-25 17:34
@flynsequeira this doesn't seem to be a bug report. Have you reached out for help in the embercommunity.slack.com #-help chatroom?

**Comment by pixelhandler** [comment] 2017-11-03 16:36
Closing this for now, its not a bug in the Ember framework

**Closed by pixelhandler** 2017-11-03 16:36 UTC
