### ISSUE TITLE
ember 2.10 + jquery 3 issue

### ISSUE THREAD

**Issue by kellyselden** [emberjs/ember.js#14655] opened 2016-11-29 18:07 UTC
I tried tracking it down to somewhere in my code, but I think it leads me to an issue with 2.10 using jquery 3.

ember 2.9 + jquery 2: [success](https://travis-ci.org/kellyselden/ember-datetimepicker/jobs/179623233)
ember 2.9 + jquery 3: [success](https://travis-ci.org/kellyselden/ember-datetimepicker/jobs/179623234)
ember 2.10 + jquery 2: [success](https://travis-ci.org/kellyselden/ember-datetimepicker/jobs/179624749)
ember 2.10 + jquery 3: [fail](https://travis-ci.org/kellyselden/ember-datetimepicker/jobs/179624750)

When running the addon's dummy locally, there are no console errors. The addon, as you might guess, wraps a jquery datepicker plugin. I inspected, and I'm sending the right options hash to the plugin init, but the options are not taking effect in the datepicker.

Normally, I would point the finger at the datepicker, but it works fine with jquery 3. I just have to rollback to ember 2.9. It also works fine with ember 2.10 if I use jquery 2. So the combo of ember 2.10 and jquery 3 seems to be culprit.

I tried updating the jquery plugin to most recent version, no change.

Here is one of the success cases:
<img width="563" alt="screen shot 2016-11-29 at 10 05 10 am" src="https://cloud.githubusercontent.com/assets/602423/20722312/ec72f4ca-b61a-11e6-87b9-6078d5eb27d9.png">

Here is the failure case:
<img width="395" alt="screen shot 2016-11-29 at 10 06 36 am" src="https://cloud.githubusercontent.com/assets/602423/20722317/f38901c8-b61a-11e6-8062-54b5c8738bec.png">

Here is the branch to see it failing: https://github.com/kellyselden/ember-datetimepicker/tree/ember-bug-report

**Comment by sandstrom** [comment] 2016-11-30 22:29
A good place to start would be the jQuery changes between 2 -> 3.

This page has a list of breaking changes:
https://jquery.com/upgrade-guide/3.0/

Also, it's a bit unclear in what way it isn't working. I ran your branch and although the failure case looked like the image above it opens just fine when I click the input. I.e. the only thing I see is a small difference in the default state of the input. Perhaps you can explain in more detail?

![image](https://cloud.githubusercontent.com/assets/122287/20774015/c162cf68-b754-11e6-8903-d973de152ffe.png)

*image is from the ember-bug-report branch*

**Comment by kellyselden** [comment] 2016-11-30 22:38
> I.e. the only thing I see is a small difference in the default state of the input. Perhaps you can explain in more detail?

Correct. The difference is the options aren't working.

> A good place to start would be the jQuery changes between 2 -> 3.

I don't know if that's true. The addon works perfectly with ember 2.9 and jquery 3. So I don't know if the jquery 3 changelog would give me any answers. It seems to me that ember 2.10 is using jquery 3 a bit differently, leading me to believe intimate knowledge of the ember inner workings is where to start. Please correct me if I am wrong.

**Comment by pixelhandler** [comment] 2016-12-02 19:57
@kellyselden is there a way to reproduce the issue with an input + Ember 2.10 + jQuery 3.0 aside from the complete addon? Trying to boil down the root cause may help with a solution; and also identity whether there is a bug in Ember.

**Comment by kellyselden** [comment] 2016-12-02 20:44
@pixelhandler That's the next step. I was hoping something would jump out at someone with my high level debugging.

**Comment by kellyselden** [comment] 2016-12-04 22:27
I figured it out. It has to do with the object the `hash` template helper makes, and how `$.isPlainObject()` handles it.

Here is the success case: https://ember-twiddle.com/a6f37f20e21f638cc2f6f221875eef9d/d48d86ad523a7ae8511a786717e0407625df000f
Here is the fail case: https://ember-twiddle.com/a6f37f20e21f638cc2f6f221875eef9d

This appears to be a mild breaking change in 2.10.

**Comment by rwjblue** [comment] 2016-12-05 01:03
The hash argument passed into helpers is the result of the [`EmptyObject` pattern](https://github.com/emberjs/ember.js/blob/master/packages/ember-utils/lib/empty-object.js) (meant to emulate `Object.create(null)` but avoid some bad performance characteristics on certain platforms).  FWIW, the object is also frozen after creation.

`jQuery.isPlainObject` has a specific check for objects without a prototype ([see here](https://github.com/jquery/jquery/blob/1b9575b9d14399e9426b9eacdd92b3717846c3f2/src/core.js#L247-L250)), but our `new EmptyObject()` instances do not qualify there (but a true `Object.create(null)` object would pass this check).

Ultimately, I'd suggest just working around the issue in the specific addon via something like:

```js
export default Ember.Helper.helper(function(params, _hash) {
  let hash = {};
  Ember.merge(hash, _hash);
  // pass `hash` out to whomever is using it
});
```

**Comment by stefanpenner** [comment] 2016-12-05 01:06
> ut avoid some bad performance characteristics on certain platforms

on new v8 this should be fixed, old ones (non upgrading mobile, or others) may not though...

**Comment by kellyselden** [comment] 2016-12-05 01:15
Once I narrowed down the problem, I was able to quickly work around using
```
let options = Ember.copy(this.get('options'));
```

Now I guess the question is, is this treated as a bug, or a wontfix?

**Comment by rwjblue** [comment] 2016-12-05 01:31
Likely a very sympathetic wontfix, but I'll run it by others first before closing or anything.

**Comment by stefanpenner** [comment] 2016-12-05 03:06
i think this may be a "maybe fix": -> https://github.com/emberjs/ember.js/pull/14677#issuecomment-264758055

**Comment by kellyselden** [comment] 2016-12-14 01:18
@rwjblue @stefanpenner Anything I can do to get this resolved?

**Comment by Asherlc** [comment] 2017-01-23 22:40
This is an issue for me as well. Barring a fix for this, is there a way to turn the EmptyObject into a regular object?

**Comment by dubbs** [comment] 2017-02-07 15:44
@Asherlc Use `Object.assign`.
```js
const hash = Object.assign({}, _hash);
```

**Comment by Serabe** [comment] 2017-07-13 14:49
@kellyselden is this still an issue?

**Comment by kellyselden** [comment] 2017-07-14 05:08
I have a longstanding PR for this bug [here](https://github.com/kellyselden/ember-datetimepicker/pull/85). I just rebased it, and it is still broken.

**Comment by mmun** [comment] 2018-02-23 20:57
Glimmer is using `Object.create(null)` directly now, so this should no longer be an issue.

**Closed by mmun** 2018-02-23 20:57 UTC
Labels: Ember 2.10, Needs Bug Verification
