### ISSUE TITLE
project with custom rootURL builds with errors on production server

### ISSUE THREAD

**Issue by LilyLauben** [emberjs/ember.js#17815] opened 2019-03-28 16:57 UTC
Hello,

I've got an extremely simple project (just a hello world), and I wanted it to be located on a non-root url (`/survey/`). When I test locally using `ember s` the app works perfectly, but when I deploy to heroku, the project builds without error but then shows the following behavior upon visiting the site:

![image](https://user-images.githubusercontent.com/31350278/55176778-29b1c980-5158-11e9-8aff-0b0de8f9ba90.png)

My example project can be found on Github here: https://github.com/LilyLauben/test-roast-hubspot
The deployed project can be viewed here: https://test-roast-hubspot.herokuapp.com/survey/

I am deploying to heroku throught Github, and using this buildpack: https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/emberjs.tgz

This is what displays in heroku's logs when I attempt to view the project:
```
2019-03-28T16:54:48.482183+00:00 heroku[web.1]: Unidling
2019-03-28T16:54:49.221093+00:00 heroku[web.1]: State changed from down to starting
2019-03-28T16:54:55.283152+00:00 heroku[web.1]: Starting process with command `bin/boot`
2019-03-28T16:54:56.991239+00:00 app[web.1]: Starting log redirection...
2019-03-28T16:54:56.991490+00:00 app[web.1]: Starting nginx...
2019-03-28T16:54:57.669492+00:00 heroku[web.1]: State changed from starting to up
2019-03-28T16:54:58.302026+00:00 heroku[router]: at=info method=GET path="/survey/" host=test-roast-hubspot.herokuapp.com request_id=32203606-4d0d-41bd-a4b3-69356a4c585b fwd="73.141.79.175" dyno=web.1 connect=1ms service=2ms status=304 bytes=168 protocol=https
2019-03-28T16:54:58.301297+00:00 app[web.1]: 10.113.237.99 - - [28/Mar/2019:16:54:58 +0000] "GET /survey/ HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36"
2019-03-28T16:54:58.341742+00:00 app[web.1]: 10.113.237.99 - - [28/Mar/2019:16:54:58 +0000] "GET /survey/assets/vendor-d41d8cd98f00b204e9800998ecf8427e.css HTTP/1.1" 304 0 "https://test-roast-hubspot.herokuapp.com/survey/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36"
2019-03-28T16:54:58.370276+00:00 app[web.1]: 10.113.237.99 - - [28/Mar/2019:16:54:58 +0000] "GET /survey/assets/vendor-bb2ac102108e1b75f2128d912e66edd5.js HTTP/1.1" 304 0 "https://test-roast-hubspot.herokuapp.com/survey/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36"
2019-03-28T16:54:58.391138+00:00 app[web.1]: 10.5.182.140 - - [28/Mar/2019:16:54:58 +0000] "GET /survey/assets/test-roast-hubspot-3df545f823012abffa06af7c1b4f9c0b.js HTTP/1.1" 304 0 "https://test-roast-hubspot.herokuapp.com/survey/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36"
2019-03-28T16:54:58.371243+00:00 heroku[router]: at=info method=GET path="/survey/assets/vendor-bb2ac102108e1b75f2128d912e66edd5.js" host=test-roast-hubspot.herokuapp.com request_id=6a9e1427-d5d9-41cc-87df-11e17dc188c2 fwd="73.141.79.175" dyno=web.1 connect=1ms service=4ms status=304 bytes=168 protocol=https
2019-03-28T16:54:58.342526+00:00 heroku[router]: at=info method=GET path="/survey/assets/vendor-d41d8cd98f00b204e9800998ecf8427e.css" host=test-roast-hubspot.herokuapp.com request_id=26e5747c-76d8-4266-b841-a4bf6ee2c55c fwd="73.141.79.175" dyno=web.1 connect=1ms service=2ms status=304 bytes=168 protocol=https
2019-03-28T16:54:58.391147+00:00 heroku[router]: at=info method=GET path="/survey/assets/test-roast-hubspot-3df545f823012abffa06af7c1b4f9c0b.js" host=test-roast-hubspot.herokuapp.com request_id=d6327b15-2264-4689-9702-8c7538b76bc3 fwd="73.141.79.175" dyno=web.1 connect=1ms service=2ms status=304 bytes=168 protocol=https
2019-03-28T16:54:59.347665+00:00 heroku[router]: at=info method=GET path="/survey/assets/test-roast-hubspot-d41d8cd98f00b204e9800998ecf8427e.css" host=test-roast-hubspot.herokuapp.com request_id=c33d3089-05e5-45f9-b274-2ddaf8ea11d3 fwd="73.141.79.175" dyno=web.1 connect=0ms service=2ms status=304 bytes=168 protocol=https
2019-03-28T16:54:59.380658+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=test-roast-hubspot.herokuapp.com request_id=37f05165-e080-4e3a-b30b-294882822740 fwd="73.141.79.175" dyno=web.1 connect=0ms service=2ms status=200 bytes=861 protocol=https
2019-03-28T16:54:59.346823+00:00 app[web.1]: 10.65.253.27 - - [28/Mar/2019:16:54:59 +0000] "GET /survey/assets/test-roast-hubspot-d41d8cd98f00b204e9800998ecf8427e.css HTTP/1.1" 304 0 "https://test-roast-hubspot.herokuapp.com/survey/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36"
2019-03-28T16:54:59.379853+00:00 app[web.1]: 10.65.253.27 - - [28/Mar/2019:16:54:59 +0000] "GET /favicon.ico HTTP/1.1" 200 586 "https://test-roast-hubspot.herokuapp.com/survey/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36"
```

**Comment by Masyaka** [comment] 2021-08-11 10:50
@LilyLauben Any updates here? I have the same problem.

**Comment by bertdeblock** [comment] 2021-08-11 11:52
This seems more like a server config issue instead of an issue with Ember itself? The `index.html` file seems to be returned when the browser expects a JS file?

**Comment by sandstrom** [comment] 2023-06-30 20:11
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. 

This seem like more of a question than a bug report/issue, and therefore better suited for the forums: https://discuss.emberjs.com/

Also, the reality for any open-source framework, relying on individuals to put in the work, is that there isn't always time to answer all questions.

If you want to pay back to the community, one easy thing is to ask one question in the forum (your current one), and also try to answer 2 questions from other people.

If you think this is an error, a reproduction of the bug and a more extensive explanation would be a good start. Then, if others agree it's a bug, the second step is often to dig in and write a patch to fix the bug.

I'll be closing this for now though, to keep the list of open issues manageable. I hope you understand.

**Closed by sandstrom** 2023-06-30 20:11 UTC
