### ISSUE TITLE
Ember.copy ignores GraphQL's meta fields and introspection fields

### ISSUE THREAD

**Issue by viniciussbs** [emberjs/ember.js#15431] opened 2017-06-28 17:46 UTC
GraphQL can return [meta fields](http://graphql.org/learn/queries/#meta-fields) or [introspection fields](http://graphql.org/learn/introspection/). They are prefixed with `__` and hence [they are not copied by `Ember.copy`](https://github.com/emberjs/ember.js/blob/v2.12.0/packages/ember-runtime/lib/copy.js#L48-L52). Right now my option is implement my own copy function.

If we extract `key.substring(0, 2) === '__'` to a function, I could overwrite it with a implementation that does not ignore GraphQL specific fields.

**Comment by stefanpenner** [comment] 2017-06-28 19:24
@viniciussbs I believe this is by design, changing it would likely result in some breakage.

I could see us changing this when symbols are fully supported across our target environment. But in the mean-time, you may need to rely on an alternatively copy function.

**Comment by viniciussbs** [comment] 2017-06-29 20:33
I was thinking about extracting the current behavior to a function as a default implementation. And then any dev could overwrite this new function with their on implementation but only if needed.

```javascript
function isEmberInternalKey(key) {
  return key.substring(0, 2) === '__';
}
```

I would change it to something  like

```javascript
function isGraphQLKey(key) {
  let keys = [
    '__typename',
    // ...
  ];

  return keys.indexOf(key) !== -1;
}

function isEmberInternalKey(key) {
  return key.substring(0, 2) === '__' && !isGraphQLKey(key);
}
```

And `Ember.copy` would rely on `isEmberInternalKey` instead of checking it by itself.

I'll implement my own copy function, though.

**Comment by locks** [comment] 2017-07-06 10:50
I'm closing this as Ember seems to be working as expected, and OP had an alternative resolution.
Feel free to reopen otherwise!

**Closed by locks** 2017-07-06 10:50 UTC
