### ISSUE TITLE
transition.abort() does not work for query param only transitions

### ISSUE THREAD

**Issue by normanhaze** [emberjs/ember.js#18568] opened 2019-11-22 11:02 UTC
When calling transition.abort() on a transition which only changes the query params, the transition goes ahead anyway.  I am using the ‘routeWillChange’ event in the router service to intercept the transition. transition.abort() is called but does not prevent the params change.

Perhaps a slightly different issue, but transition.abort() also triggers the ‘routeWIllChange’ event again, with some confusing properties. ‘isAborted’ is true, ‘isCausedByAbortingTransition’ is false, and the ‘to’ and ‘from’ objects both point to the original ‘from’ query params, not the new  query params. If nothing else, surely an aborted transition shouldn’t be triggering the ‘routeWillChange’ event?

**Comment by jelhan** [comment] 2019-11-25 17:49
I'm seeing a similar issue. Didn't noticed this one exists before I had written it down. Maybe my long explanation will be helpful.

---

I'm seeing two weird bugs if doing a redirect to the same route with different queryParams in `beforeModel` hook:

1. If the route is entered via `<LinkTo>` or `transitionTo()`, the query param is not reflected in the URL.
2. If the route is entered directly on application start, ember throws an error.

The error thrown is this one:

```
TypeError: Cannot read property 'name' of undefined
    at Class._queryParamsFor (https://t95pf.sse.codesandbox.io/assets/vendor.js:35740:59)
    at Class.finalizeQueryParamChange (https://t95pf.sse.codesandbox.io/assets/vendor.js:34759:29)
    at Class.triggerEvent (https://t95pf.sse.codesandbox.io/assets/vendor.js:36198:27)
    at PrivateRouter.triggerEvent (https://t95pf.sse.codesandbox.io/assets/vendor.js:35078:43)
    at PrivateRouter.finalizeQueryParamChange (https://t95pf.sse.codesandbox.io/assets/vendor.js:72248:12)
    at PrivateRouter.queryParamsTransition (https://t95pf.sse.codesandbox.io/assets/vendor.js:71741:37)
    at PrivateRouter.getTransitionByIntent (https://t95pf.sse.codesandbox.io/assets/vendor.js:71810:37)
    at PrivateRouter.transitionByIntent (https://t95pf.sse.codesandbox.io/assets/vendor.js:71759:21)
    at PrivateRouter.doTransition (https://t95pf.sse.codesandbox.io/assets/vendor.js:71894:19)
    at PrivateRouter.transitionTo (https://t95pf.sse.codesandbox.io/assets/vendor.js:72372:19) 
```

It's caused by `routeInfos` of `transition` being an empty array here: https://github.com/emberjs/ember.js/blob/v3.14.1/packages/%40ember/-internals/routing/lib/system/route.ts#L2523 `_queryParamsFor` can't handle that case and throws at this line: https://github.com/emberjs/ember.js/blob/v3.14.1/packages/%40ember/-internals/routing/lib/system/router.ts#L926

For a minimal reproduction use this code:

```javascript
// app/routes/foo.js

import Route from '@ember/routing/route';

export default Route.extend({
  async beforeModel(transition) {
    if (!transition.to.queryParams.bar) {
      await this.transitionTo('foo', { queryParams: { bar: "1" }});
    }
  }
});
```

```javascript
// app/controllers/foo.js

import Controller from '@ember/controller';
import { inject as service } from '@ember/service';

export default Controller.extend({
  router: service(),

  queryParams: ['bar'],
});
```

```hbs
// app/templates/foo.hbs

{{log router.currentRoute}}
```

The current route is logged in template to verify that the query params are available on `RouteInfo` object for scenario 1. And they are indeed. They are just not represented in URL.

Both bugs could be fixed by explicitly aborting the transition before doing the redirect:

```javascript
// app/routes/foo.js

import Route from '@ember/routing/route';

export default Route.extend({
  async beforeModel(transition) {
    if (!transition.to.queryParams.bar) {
      transition.abort();

      await this.transitionTo('foo', { queryParams: { bar: "1" }});
    }
  }
});
```

But accordingly to documentation `transitionTo()` should implicitly abort the transition. It should not be required to do it manually. Also if this is the recommended solution, there should be an assertion if the transition is not aborted before. It should not end with a broken state (URL not reflecting query parameters in URL) neither with throwing a `TypeError`.

**Comment by acorncom** [comment] 2020-01-18 15:44
@normanhaze what version of Ember are you seeing this in? And are you able to send in a reproduction to make it easier to track this down?

**Comment by normanhaze** [comment] 2020-01-20 12:04
Hi @acorncom - I'm using 3.13, but I've created a demo app using 3.15 and the issue is still there. Take a look: https://github.com/normanhaze/transition-issue-demo

A 'routeWillChange' event is set in the component's constructor, which triggers when the queryParams change (when you click the button). 

The first transition has the correct 'from' and 'to' query params, and appears to be aborted, and the event triggers again with a new transition. The 'from' and 'to' query params are both for the current route. This is not aborted due to the check for the 'isAborted' property. However, the query params change to the original target anyway.

**Comment by omairvaiyani** [comment] 2020-02-10 14:58
Hi guys, this issue should have `Needs reproduction` label removed as it is reproducable using that repo posted by @normanhaze

**Comment by acorncom** [comment] 2020-02-11 04:40
thanks @normanhaze / @omairvaiyani, updated

**Comment by rwjblue** [comment] 2020-07-20 22:42
Fixed by https://github.com/emberjs/ember.js/pull/19048 (thanks @richgt!).

**Closed by rwjblue** 2020-07-20 22:42 UTC
Labels: Has Reproduction, Router Bugs

**Comment by patrickberkeley** [comment] 2021-05-21 18:11
I'm seeing this issue again after upgrading to ember 3.26.1
