### ISSUE TITLE
Error: parentNode is null when using queryParam, each and else

### ISSUE THREAD

**Issue by lucas-clemente** [emberjs/ember.js#11210] opened 2015-05-18 17:56 UTC
Demo at http://output.jsbin.com/sapuzoxaka/1/

The stack trace in Safari (8.0.6) and Chrome (dev) is:

```
Uncaught TypeError: Cannot read property 'insertBefore' of nullinsertBefore @ ember-template-compiler.js16687
MorphList$insertBeforeMorph                                                 @ ember-template-compiler.js16599
(anonymous function)                                                        @ ember-template-compiler.js12301
(anonymous function)                                                        @ ember.debug.js6702
forEach                                                                     @ ember.debug.js13599
eachHelper                                                                  @ ember.debug.js6694
invokeHelper                                                                @ ember.debug.js7416
(anonymous function)                                                        @ ember-template-compiler.js12441
renderAndCleanup                                                            @ ember-template-compiler.js16198
hostBlock                                                                   @ ember-template-compiler.js12447
continueBlock                                                               @ ember-template-compiler.js12439
block                                                                       @ ember-template-compiler.js12435
object_utils.merge.block                                                    @ ember-template-compiler.js11935
(anonymous function)                                                        @ ember-template-compiler.js12013
dirtyCheck                                                                  @ ember-template-compiler.js12061
exports.default.object_utils.merge.block                                    @ ember-template-compiler.js12012
RenderResult.populateNodes                                                  @ ember-template-compiler.js13082
RenderResult.revalidateWith                                                 @ ember-template-compiler.js13056
validateChildMorphs                                                         @ ember-template-compiler.js15947
handleKeyword                                                               @ ember-template-compiler.js12531
keyword                                                                     @ ember-template-compiler.js12582
exports.default                                                             @ ember.debug.js8231
handleKeyword                                                               @ ember-template-compiler.js12480
handleRedirect                                                              @ ember-template-compiler.js12466
inline                                                                      @ ember-template-compiler.js12563
object_utils.merge.content                                                  @ ember-template-compiler.js11956
(anonymous function)                                                        @ ember-template-compiler.js12027
dirtyCheck                                                                  @ ember-template-compiler.js12061
exports.default.object_utils.merge.content                                  @ ember-template-compiler.js12026
RenderResult.populateNodes                                                  @ ember-template-compiler.js13086
RenderResult.revalidateWith                                                 @ ember-template-compiler.js13056
validateChildMorphs                                                         @ ember-template-compiler.js15947
dirtyCheck                                                                  @ ember-template-compiler.js12066
exports.default.object_utils.merge.content                                  @ ember-template-compiler.js12026
RenderResult.populateNodes                                                  @ ember-template-compiler.js13086
RenderResult.revalidateWith                                                 @ ember-template-compiler.js13056
validateChildMorphs                                                         @ ember-template-compiler.js15947
handleKeyword                                                               @ ember-template-compiler.js12531
keyword                                                                     @ ember-template-compiler.js12582
exports.default                                                             @ ember.debug.js8231
handleKeyword                                                               @ ember-template-compiler.js12480
handleRedirect                                                              @ ember-template-compiler.js12466
inline                                                                      @ ember-template-compiler.js12563
object_utils.merge.content                                                  @ ember-template-compiler.js11956
(anonymous function)                                                        @ ember-template-compiler.js12027
dirtyCheck                                                                  @ ember-template-compiler.js12061
exports.default.object_utils.merge.content                                  @ ember-template-compiler.js12026
RenderResult.populateNodes                                                  @ ember-template-compiler.js13086
RenderResult.revalidateWith                                                 @ ember-template-compiler.js13056
RenderResult.revalidate                                                     @ ember-template-compiler.js13033
Renderer_revalidateTopLevelView                                             @ ember.debug.js10721
CoreView.default.extend.revalidate                                          @ ember.debug.js43284
Queue.invoke                                                                @ ember.debug.js878
Queue.flush                                                                 @ ember.debug.js943
DeferredActionQueues.flush                                                  @ ember.debug.js748
Backburner.end                                                              @ ember.debug.js173
Backburner.run                                                              @ ember.debug.js228
Backburner.join                                                             @ ember.debug.js247
run.join                                                                    @ ember.debug.js17558
exports.default.EmberObject.default.extend._bubbleEvent                     @ ember.debug.js39654
(anonymous function)                                                        @ ember.debug.js39604
n.event.dispatch                                                            @ jquery-2.1.4.min.js3
r.handle                                                                    @ jquery-2.1.4.min.js3
```

**Comment by rwjblue** [comment] 2015-05-18 18:00
Thanks for reporting!  Closing this as a duplicate of https://github.com/emberjs/ember.js/issues/11140.

**Closed by rwjblue** 2015-05-18 18:00 UTC

**Comment by lucas-clemente** [comment] 2015-05-18 18:02
Sorry, overlooked that one while searching for similar bugs :( Thanks!

**Comment by rwjblue** [comment] 2015-05-18 18:03
No worries!! Thanks for taking the time to submit the issue with a reproduction.
