### ISSUE TITLE
Calling _super in a CP has the wrong context when retrieved from an action

### ISSUE THREAD

**Issue by offirgolan** [emberjs/ember.js#13230] opened 2016-04-01 22:06 UTC
In an Ember.Object, when you call `this._super` in a CP, it will retrieve the parent's value of that same property. What was found is that when you fetch a CP that has a `_super` call in an action handler, the `_super` context is that of the parent's action and not of the parent's CP.

[Ember Twiddle](https://ember-twiddle.com/b972368d3a07da5dba8986c39462168f?openFiles=components.my-component.js%2Ctemplates.components.my-component.hbs) - Tested on Ember 1.13.13 to Canary

When you click the save button, the following should happen:

1. Grab validations object which also grabs inherited validations if possible
2. the `my-component` action should be called which at the end calls `_super` (defined in CRUD mixin)
3. The CRUD save action should then be called

What is actually happening:

1. Grab validations object
2. `_super` in validations objects calls the CRUD mixin save action instead of inherited validations cp
3. Do stuff in my-component save action as intended and then call `_super` (defined in CRUD mixin)
4. The CRUD save action should then be called

**Comment by offirgolan** [comment] 2016-04-01 22:11
cc @stefanpenner @rwjblue

**Comment by stefanpenner** [comment] 2016-04-01 22:23
Yup, seems like a bug.

@offirgolan if you have cycles a failing test would be sweet, im going to skim the code and see what may be going sideways.

**Comment by stefanpenner** [comment] 2016-04-01 22:39
I believe the issue is, the cp has no super so it doesn't bother super wrapping it. But if it does not super wrap it, it doesn't reset the actions `_super`.

https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/mixin.js#L105-L107

**Comment by offirgolan** [comment] 2016-04-01 22:54
:+1: Sweet will do. I dont have too much free time unfortunately, but if I find a spare moment, ill whip up a test. Thanks for taking this on!

**Comment by rwjblue** [comment] 2016-04-04 00:08
Submitted https://github.com/emberjs/ember.js/pull/13242 with a couple tests and fix.  Needs review.

**Comment by offirgolan** [comment] 2016-04-04 01:12
👌 thanks Rob

On Sunday, April 3, 2016, Robert Jackson <notifications@github.com> wrote:

> Submitted #13242 <https://github.com/emberjs/ember.js/pull/13242> with a
> couple tests and fix. Needs review.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/emberjs/ember.js/issues/13230#issuecomment-205080046>
>


-- 
Thanks,
Offir Golan

**Comment by rwjblue** [comment] 2016-04-10 21:20
See https://github.com/emberjs/ember.js/pull/13242#issuecomment-208076203 for an update.  I'm going to close this for now, and track the underlying issue in https://github.com/emberjs/ember.js/pull/13242 instead.

Thank you for reporting, hopefully we can get *something* in place to help prevent this sort of trollage in the near future.

**Closed** 2016-04-10 21:20 UTC
Labels: Bug
