### ISSUE TITLE
[Ember 1.13 Regression] link-to regression when using query-params and no route name

### ISSUE THREAD

**Issue by chbonser** [emberjs/ember.js#11769] opened 2015-07-16 15:58 UTC
With the change from LinkView to LinkComponent the link-to behavior has changed.  Specifically the behavior changed when using link-to with query-params and no route. For example:
`{{#link-to (query-params filter=filter)}}Some Link{{/link-to}}`

Previously an app could have a long lived link in a parent route and the link would respect the route changes in child outlets.  This is no longer the case.  Instead the link-to causes a route transition to whatever the route happened to be when the link was rendered.

Having done a bit of digging, it appears the `targetRouteName` property of the LinkComponent is set in `willRender` and doesn't change when the route changes.  Therefore clicking on the link will cause a route transition to match whatever the `currentRouteName` on the `controller:application` happened to be when the link was rendered.

Here is a jsbin to help illustrate the issue: http://jsbin.com/gedene/edit?html,js,console,output

Steps to reproduce the issue using the jsbin:
* Click on the 'Authenticated' link
* Click on the "Open 'Drawer 1'" link (this is a link-to with query-params and no route name)
* A drawer should open on the right. Clicking 'Close Drawer' will close the drawer and not change the current route
* Now click on 'Child'. This will transition to authenticated/child.
* Click on 'Open Drawer'. The drawer will open and the app will transition to the authenticated route. It should have stayed on 'authenticated/child'

**Comment by chbonser** [comment] 2015-07-16 16:32
Note I believe this is a different issue than https://github.com/emberjs/ember.js/issues/11654 (or at least the behavior and steps to recreate it are different)

**Comment by cbazza** [comment] 2015-08-21 13:52
I came across the same problem in 1.13, trace the problem and found exactly what you did. 
The problem for us was that the 'active' class wasn't being applied correctly to the reused template link-to helper (LinkComponent). The solution for us could be used for you and it is as follows:

In:
https://github.com/emberjs/ember.js/blob/master/packages/ember-routing-views/lib/views/link.js (or you can just search Ember.js or Ember.debug.js). We replaced the line that reads "targetRouteName" with their wrapper that fixes the problem (commented out line and line below it). You might need to do this elsewhere in there.

  function computeActive(view, routerState) {
    if (_emberMetalProperty_get.get(view, 'loading')) {
      return false;
    }

    var currentWhen = _emberMetalProperty_get.get(view, 'currentWhen');
    var isCurrentWhenSpecified = !!currentWhen;
//    currentWhen = currentWhen || _emberMetalProperty_get.get(view, 'targetRouteName');
    currentWhen = currentWhen || view._handleOnlyQueryParamsSupplied(_emberMetalProperty_get.get(view, 'targetRouteName'));
    currentWhen = currentWhen.split(' ');
    for (var i = 0, len = currentWhen.length; i < len; i++) {
      if (isActiveForRoute(view, currentWhen[i], isCurrentWhenSpecified, routerState)) {
        return _emberMetalProperty_get.get(view, 'activeClass');
      }
    }

    return false;
  }

**Comment by sergetab** [comment] 2015-08-21 16:04
Any update on this? It seems that the bug is still there.

**Comment by mmun** [comment] 2016-04-14 01:58
Can someone verify that this bug is still present?

**Comment by Serabe** [comment] 2016-05-11 21:49
It seems to be gone in 2.5. I [forked the jsbin](http://jsbin.com/sacahi/edit?html,js,console,output), changed versions and included the instructions to be followed. 

I am closing this. Please, reopen if you can still reproduce.

Thank you!

**Closed by Serabe** 2016-05-11 21:49 UTC
Labels: Needs Bug Verification, Query Params
