### ISSUE TITLE
[Module Unification] Addon tests are hoisted into the host application

### ISSUE THREAD

**Issue by buschtoens** [emberjs/ember.js#17224] opened 2018-11-22 09:21 UTC
Quest: https://github.com/emberjs/ember.js/issues/16373

`*-test.js` files from an addon are hoisted into the consuming host application, just like regular files, e.g. `component.js`. This means that running `ember test` in the host application will also attempt to run the addon's tests.

I don't think that this is intended / desired behavior. It's also causing errors, if the addon tests import dev dependencies, which are not available in the host application.

**Comment by NullVoxPopuli** [comment] 2018-11-26 10:12
with a recent build of https://emberclear.io,
I'm witnessing this behavior as well -- not any errors, but just tests being included in the bundle.

Here is my "current" bundle: https://nullvoxpopuli.gitlab.io/emberclear/master/bundle.html
![image](https://user-images.githubusercontent.com/199018/49007579-d2640400-f139-11e8-9d67-a5c064c5c466.png)
![image](https://user-images.githubusercontent.com/199018/49007615-e3ad1080-f139-11e8-955f-f3433b0415ab.png)

**Comment by buschtoens** [comment] 2018-11-26 10:40
> not any errors

Sorry for being unclear here. I was referring to the the wrongfully included tests failing or failing to load, because they are importing dev dependencies (of the addon they belong to), which are not available in the host application.

**Comment by pixelhandler** [comment] 2018-11-30 17:03
@buschtoens would this be an issue for https://github.com/ember-cli/ember-cli/issues ? seems that the **expected behavior** is when I visit http://localhost:4200/tests that only my application tests should be run, and no (addon/dependency) tests should be included. And running `ember test` or `ember test -s` should also only execute application tests?

But, it sounds like the **actual behavior** you see is that in all of the above scenarios addon (dependency) tests are included and executed?

Can you provide an example repo?

**Comment by NullVoxPopuli** [comment] 2018-11-30 17:16
> But, it sounds like the actual behavior you see is that in all of the above scenarios addon (dependency) tests are included and executed?

For me, it's the application tests that are being included in the production repo.

Here is my repo:
https://github.com/NullVoxPopuli/emberclear/

**Comment by buschtoens** [comment] 2018-11-30 17:17
> would this be an issue for ember-cli/ember-cli/issues?

I was not sure at what level the filtering happens. But it'd make sense to filter addon tests at the build level, yes.

**Comment by ppcano** [comment] 2018-12-21 01:49
I will look at this issue soon and try to implement a fix.

> would this be an issue for ember-cli/ember-cli/issues?

I think so.

**Comment by ppcano** [comment] 2018-12-21 23:31
> t's the application tests that are being included in the production repo

It should be fixed by ember-cli/ember-cli#8314 

@buschtoens I am not sure if 👆 fixes the addon issue.

**Comment by ppcano** [comment] 2018-12-23 22:08
https://github.com/ember-cli/ember-cli/pull/8314 has been merged.

@buschtoens please, would you mind to test again the addon issue and inform if the problem has been fixed.

**Comment by NullVoxPopuli** [comment] 2019-01-08 13:18
@ppcano @buschtoens my bundle: https://emberclear.io/bundle.html

in my app bundle it looks like tests that I generically named `-acceptance-test.ts` are included.
so, maybe the filter pattern needs updating?

**Comment by locks** [comment] 2019-05-30 17:11
Closing this issue as we are rethinking the MU approach.

**Closed by locks** 2019-05-30 17:11 UTC
Labels: Module Unification, Needs Reproduction

**Comment by NullVoxPopuli** [comment] 2019-05-30 17:32
According to: https://emberclear.io/bundle.html
I think this was actually resolved and forgetten haha :tada:
