### ISSUE TITLE
Uncaught TypeError: t[m] is not a function

### ISSUE THREAD

**Issue by GiovanniL19** [emberjs/ember.js#15053] opened 2017-03-22 10:41 UTC
Hi, 
I am geting the following error:

> Uncaught TypeError: t[m] is not a function
>     at Object.applyStr (ember.debug.js:24978)
>     at Object.sendEvent (ember.debug.js:19411)
>     at notifyObservers (ember.debug.js:23343)
>     at propertyDidChange (ember.debug.js:23160)
>     at ChainWatchers.notify (ember.debug.js:17975)
>     at chainsDidChange (ember.debug.js:23258)
>     at Object.propertyDidChange (ember.debug.js:23159)
>     at Object.set (ember.debug.js:23553)
>     at Class.set (ember.debug.js:36509)

It occurs all around my project in different locations. For example inside my application controller I have a `isLoggedIn` property:

```
isLoggedIn: function(){
    if(this.get('session.isAuthenticated')){
      let controller = this;
      return this.store.find("user", this.get('session.session.authenticated.user')).then(function (user) {
        controller.set("user", user);
        return true;
      });
    }else{
      this.set("user", null);
      return false;
    }
  }.property('session.isAuthenticated', "session.session.authenticated.user")

```
`this.set("user", null);` and `controller.set("user", user);` are both causing the error

Does anyone have any ideas? Thanks

EDIT:

It also errors the following:
```
TypeError: object is not a function
    at Object.applyStr (ember.debug.js:24978)
    at Object.sendEvent (ember.debug.js:19411)
    at notifyObservers (ember.debug.js:23343)
    at propertyDidChange (ember.debug.js:23160)
    at ChainWatchers.notify (ember.debug.js:17975)
    at chainsDidChange (ember.debug.js:23258)
    at Object.propertyDidChange (ember.debug.js:23159)
    at Object.set (ember.debug.js:23553)
    at Class.set (ember.debug.js:36509)
    at application.js:19
```

**Comment by pixelhandler** [comment] 2017-03-24 15:56
@GiovanniL19 is there any way you can reproduce this error in a working example? https://ember-twiddle.com is a great way to share working or failing code examples for others to run and help troubleshoot the issue.

Check the error.trace for what line of code in your app is causing the issue. `object is not a function` seems to indicate that the app code or maybe framework code is trying to invoke a function but doing so on an object, resulting in the `TypeError`.  ( Helps to pause on any error using Chrome debugger tools, https://developers.google.com/web/updates/2015/05/automatically-pause-on-any-exception )

**Comment by Serabe** [comment] 2017-04-02 23:19
@GiovanniL19 ping!

**Comment by GiovanniL19** [comment] 2017-04-03 08:43
Thank you for your reply @pixelhandler, for some reason it is all okay now! Not a clue why? I didn't change anything. I am unable to reproduce this issue :/

**Comment by locks** [comment] 2017-04-03 09:09
Thanks for the update @GiovanniL19, I'm closing this issue due to lack of reproduction. Let us know if you manage to reproduce it again!

**Closed by locks** 2017-04-03 09:09 UTC
Labels: Needs Bug Verification, Needs Reproduction, Needs Submitter Response
