### ISSUE TITLE
Ember 1.13.x binding errors on iPhone 6

### ISSUE THREAD

**Issue by fernandodrumond** [emberjs/ember.js#13275] opened 2016-04-07 08:59 UTC
Hello guys,

I'm experiencing a lot of binding errors on an Ember project when viewing it on an iPhone 6 (Arm64) iOS 9.2. I seems to be something general and multiple things fail, likes aliases, class bindings. The are just ignored.

Have anyone experienced something similar?

I'm currently using Ember 1.13.6, updating to 1.13.13 didn't solve the issue.

It can easily be reproduced on http://staging.movistarmasquefans.com/login

- Go to the login form and tap "Entrar" (Enter). 
- You should get a red alert asking for e-mail and password, but nothing happens.

It works fine on iPhone 5, 5c, 6s and on the simulator for iPhone 6, but not on a real device.

Has anyone experienced something similar?

Thank you in advance,

**Comment by fernandodrumond** [comment] 2016-04-07 10:03
Just some more info: I tried updating to iOS 9.3.1 and I still get the same.

**Comment by pixelhandler** [comment] 2016-04-08 16:26
@fernandodrumond this looks like an error in your app code, not in Ember.

`_error.message` is undefined.

```js
// user feedback
      error: function error(_error /*, transition*/) {
        var defaultMessage = 'errors.default';
        var message = null;

        if (_error) {
          console.error(this.get('locales').t(_error && _error.message));


```

**Comment by fernandodrumond** [comment] 2016-04-09 01:40
Sorry @pixelhandler I had just introduced this bug unrelated to the issue. I fixed it, now you can verify how it works on desktop and iPhones, but not on iPhone 6.

**Comment by Serabe** [comment] 2016-04-10 23:13
@fernandodrumond: can you add a `transform: translate3d(0,0,0)` to the element CSS and check if that fixes it?

**Comment by fernandodrumond** [comment] 2016-04-12 06:21
Hi @Serabe , thanks for your suggestion, but in this case it's not a matter of css. The class `visible` that was supposed to be assigned to the element is not assigned, and that's were I believe the binding error is. There are a few `classBindings` or `Ember.computed.alias` that are jus ignored.

As I said, it works properly on desktop and other iPhone version, but the 6.

**Comment by Serabe** [comment] 2016-04-12 12:47
Have some similar problems with Safari Mobile in the past and they were rendering problems solved using that CSS rule.

If that

**Comment by fernandodrumond** [comment] 2016-04-13 17:02
Sorry @Serabe the project was released and we had to protect the staging (this will only last a couple of weeks).

It's available on
www.movistarmasquefans.com/

I'll try to recreate the problem on a twiddle and post here.

Thanks a lot!

**Comment by Serabe** [comment] 2016-04-22 16:01
Hi, @fernandodrumond, did you have some time to reproduce the bug?

**Comment by pixelhandler** [comment] 2016-04-22 17:49
@fernandodrumond are you able to upgrade your app to a current release of Ember? 

It's very unlikely that any patches will be made to the Ember 1.13.x release, especially since we now have an LTS release.

I'll close this for now, to solve this issue using Ember 1.13 it would be best to find a work around.

Once you have a repo or https://ember-twiddle.com example that reproduces the bug perhaps reach out in the embercommunity.slack.com #-help channel for some assistance, thanks!

**Closed by pixelhandler** 2016-04-22 17:49 UTC
Labels: Ember 1.13, Needs Bug Verification, Needs Submitter Response

**Comment by fernandodrumond** [comment] 2016-04-25 10:04
Hi guys,

I was not able to reproduce the bug separately.

@pixelhandler I couldn't update this app to the most recent Ember version, because it was nearly over, going to be in production for a short amount of time.

I agree with you, next time I'll just start the project using its current release. It doesn't make sense to keep supporting this version.

Thank you anyway for your help!

**Comment by knownasilya** [comment] 2016-04-28 21:19
I'm also experiencing this issue. Was the workaround to add the transform to the button?
