### ISSUE TITLE
[Bug] Unicode Emojis Break Build

### ISSUE THREAD

**Issue by srsgores** [emberjs/ember.js#19251] opened 2020-11-06 05:31 UTC
Using any unicode emojis in `.hbs` files will cause a build error with `3.22` or later:

> Build Error (broccoli-persistent-filter:Babel > [Babel: ember-wp-blog]) in ember-wp-blog/components/page.js
> C:\Users\user\github\ember-wp-blog\ember-wp-blog\components\page.js: Can't reference '{"id":"PY3xMdMK","block":"{\"symbols\":[\"@page\",\"&default\"],\"statements\":[[10,\"article\"],[14,0,\"page\"],[12],[2,\"\\n\"],[6,[37,0],[[32,1,[\"title\"]]],null,[[\"default\"],[{\"statements\":[[2,\"\\t\\t\"],[10,\"header\"],[14,0,\"page-header\"],[12],[2,\"\\n\\t\\
t\\t\"],[10,\"h2\"],[14,0,\"page-title\"],[12],[2,[32,1,[\"title\"]]],[13],[2,\"\\n\\t\\t\"],[13],[2,\"\\n\"]],\"parameters\":[]}]]],[6,[37,0],[[32,1,[\"content\",\"length\"]]],null,[[\"default\",\"else\"],[{\"statements\":[[2,\"\\t\\t\"],[10,\"section\"],[14,0,\"page-content\"],[12],[2,\"\\n\\t\\t\\t\"],[2,[32,1,[\"content\"]]],[2,\"\\n\\t\\t\"],[13],[2,
\"\\n\"]],\"parameters\":[]},{\"statements\":[[2,\"\\t\\t\"],[10,\"dialog\"],[14,\"role\",\"alertdialog\"],[14,\"aria-label\",\"No content found for this page �\"],[12],[2,\"\\n\\t\\t\\t\"],[10,\"h3\"],[12],[2,\"No content found here\"],[13],[2,\"\\n\\t\\t\\t\"],[10,\"p\"],[12],[2,\"Head back \"],[8,\"link-to\",[],[[\"@route\"],[\"index\"]],[[\"default\"
],[{\"statements\":[[2,\"home\"]],\"parameters\":[]}]]],[13],[2,\"\\n\\t\\t\"],[13],[2,\"\\n\"]],\"parameters\":[]}]]],[13],[2,\"\\n\\n\"],[18,2,null]],\"hasEval\":false,\"upvars\":[\"if\"]}","meta":{"moduleName":"ember-wp-blog/components/page.hbs"}}' as a bare identifier (This is an error on an internal node. Probably an internal error.)

Likely due to [using `babel-preset-env` as a `dependency`](https://github.com/storybookjs/storybook/issues/11853).

### 🔬 Minimal Reproduction

`app/components/page.hbs`

```hbs
<article class="page">
	{{#if @page.title}}
		<header class="page-header">
			<h2 class="page-title">{{{@page.title}}}</h2>
		</header>
	{{/if}}
	{{#if @page.content.length}}
		<section class="page-content">
			{{{@page.content}}}
		</section>
	{{else}}
		<dialog role="alertdialog" aria-label="No content found for this page 🐸">
			<h3>No content found here 🦗🦗</h3>
			<p>Head back <LinkTo @route="index">home 🏠</LinkTo></p>
		</dialog>
	{{/if}}
</article>

{{yield}}
```

### 🌍 Environment

Encountered when upgrading from `3.17` ➡ `3.22`.

- Ember: - `3.22`
- Node.js/npm: - `15.1.0`
- OS: - Windows 10
- Browser: - Chrome

**Comment by rwjblue** [comment] 2020-11-06 15:18
Also reported here -> https://github.com/babel/ember-cli-babel/issues/356, I did try to reproduce but was unable to. I created https://github.com/rwjblue/__emberjs19251 and it builds without issue. What else is in play here?

**Comment by rwjblue** [comment] 2020-11-06 15:21
Aha, the problem only happens when transpiling for IE11 (e.g. `ember build --environment=production` or `CI=true ember b`).

**Comment by rwjblue** [comment] 2020-11-06 15:23
Looks like the error comes from `@babel/plugin-transform-unicode-escapes`:

https://github.com/babel/babel/blob/v7.12.6/packages/babel-plugin-transform-unicode-escapes/src/index.js#L77-L79

Which was released as part of `@babel/preset-env@7.10.0`.

**Comment by rwjblue** [comment] 2020-11-06 15:25
Also only happens when using colocated templates, moving `app/components/page.hbs` to `app/templates/components/page.hbs` (from the demo) avoids the error.

**Comment by rwjblue** [comment] 2020-11-06 15:34
The transpiled template (when targeting only modern browsers) is:

```js
;define("--emberjs19251/components/page", ["exports"], function (_exports) {
  "use strict";

  Object.defineProperty(_exports, "__esModule", {
    value: true
  });
  _exports.default = void 0;

  const __COLOCATED_TEMPLATE__ = Ember.HTMLBars.template(
  /*
    <article class="page">
  	{{#if @page.title}}
  		<header class="page-header">
  			<h2 class="page-title">{{{@page.title}}}</h2>
  		</header>
  	{{/if}}
  	{{#if @page.content.length}}
  		<section class="page-content">
  			{{{@page.content}}}
  		</section>
  	{{else}}
  		<dialog role="alertdialog" aria-label="No content found for this page 🐸">
  			<h3>No content found here 🦗🦗</h3>
  			<p>Head back <LinkTo @route="index">home 🏠</LinkTo></p>
  		</dialog>
  	{{/if}}
  </article>
  
  {{yield}}
  
  */
  {"id":"CLVUYBYy","block":"{\"symbols\":[\"@page\",\"&default\"],\"statements\":[[10,\"article\"],[14,0,\"page\"],[12],[2,\"\\n\"],[6,[37,0],[[32,1,[\"title\"]]],null,[[\"default\"],[{\"statements\":[[2,\"\\t\\t\"],[10,\"header\"],[14,0,\"page-header\"],[12],[2,\"\\n\\t\\t\\t\"],[10,\"h2\"],[14,0,\"page-title\"],[12],[2,[32,1,[\"title\"]]],[13],[2,\"\\n\\t\\t\"],[13],[2,\"\\n\"]],\"parameters\":[]}]]],[6,[37,0],[[32,1,[\"content\",\"length\"]]],null,[[\"default\",\"else\"],[{\"statements\":[[2,\"\\t\\t\"],[10,\"section\"],[14,0,\"page-content\"],[12],[2,\"\\n\\t\\t\\t\"],[2,[32,1,[\"content\"]]],[2,\"\\n\\t\\t\"],[13],[2,\"\\n\"]],\"parameters\":[]},{\"statements\":[[2,\"\\t\\t\"],[10,\"dialog\"],[14,\"role\",\"alertdialog\"],[14,\"aria-label\",\"No content found for this page 🐸\"],[12],[2,\"\\n\\t\\t\\t\"],[10,\"h3\"],[12],[2,\"No content found here 🦗🦗\"],[13],[2,\"\\n\\t\\t\\t\"],[10,\"p\"],[12],[2,\"Head back \"],[8,\"link-to\",[],[[\"@route\"],[\"index\"]],[[\"default\"],[{\"statements\":[[2,\"home 🏠\"]],\"parameters\":[]}]]],[13],[2,\"\\n\\t\\t\"],[13],[2,\"\\n\"]],\"parameters\":[]}]]],[13],[2,\"\\n\\n\"],[18,2,null],[2,\"\\n\"]],\"hasEval\":false,\"upvars\":[\"if\"]}","meta":{"moduleName":"--emberjs19251/components/page.hbs"}});

  var _default = Ember._setComponentTemplate(__COLOCATED_TEMPLATE__, Ember._templateOnlyComponent());

  _exports.default = _default;
});
```

Which (when passed into the babel repl with IE11 transpilation enabled) doesn't seem to error on its own 🤔...

**Comment by rwjblue** [comment] 2020-11-06 15:56
This is a reasonable work around for now:

```diff
diff --git a/ember-cli-build.js b/ember-cli-build.js
index d690a25..b4d982b 100644
--- a/ember-cli-build.js
+++ b/ember-cli-build.js
@@ -5,6 +5,9 @@ const EmberApp = require('ember-cli/lib/broccoli/ember-app');
 module.exports = function(defaults) {
   let app = new EmberApp(defaults, {
     // Add options here
+    babel: {
+      exclude: ['@babel/plugin-transform-unicode-escapes']
+    }
   });
 
   // Use `app.import` to add additional libraries to the generated
```

**Comment by rwjblue** [comment] 2020-11-06 17:28
Created a failing test case over in https://github.com/ember-cli/babel-plugin-htmlbars-inline-precompile/pull/297, trying to see who is at fault over there though...

**Comment by gossi** [comment] 2020-11-07 15:18
Oh wow, I was hunting this bug for a while. Thanks @srsgores for right direction here. I can confirm the following:

I had ie11 enabled for CI (in targets). Which why it was working #onmymachine but not on CI. I removed ie11 and it now works quite fine. The assumption with the transform when ie11 is a compile target seems correct.

**Comment by rwjblue** [comment] 2020-11-07 15:43
@gossi excludes work around I mentioned above will avoid the error even if you have to transpile to IE11.

**Comment by gossi** [comment] 2020-11-07 15:49
I am in the happy position to drop ie11 😂 Actually, it was transpiling to ie11 by mistake - I'm more than good now.

For the devs less lucky than me, I'm happy you can provide them an alternative 👍

**Comment by rwjblue** [comment] 2020-11-09 22:46
OK, should be fixed now with `babel-plugin-htmlbars-inline-precompile@4.2.1` (see https://github.com/ember-cli/babel-plugin-htmlbars-inline-precompile/pull/297 for details).

**Closed by rwjblue** 2020-11-09 22:46 UTC

**Comment by abhilashlr** [comment] 2020-11-27 17:27
Thank you for the detailed explaination and the fix @rwjblue 👍
