### ISSUE TITLE
Error when using same template as partial and in outlet

### ISSUE THREAD

**Issue by viccatoff** [emberjs/ember.js#17611] opened 2019-02-12 14:41 UTC
I have two different pages that renders same sub-template but in two different way:
1) one page render it using `partial` helper
2) second page render it using `outlet` (from sub-page)

Basically first page renders this block on page directly, and second page renders it inside a tab content.
When you navigate from first page to second - there is an error:

```
runtime.js:246 Uncaught TypeError: Cannot read property 'someVar' of null
    at Object.evaluate (runtime.js:246)
    at AppendOpcodes.evaluate (runtime.js:46)
    at LowLevelVM.evaluateSyscall (runtime.js:2889)
    at LowLevelVM.evaluateInner (runtime.js:2861)
    at LowLevelVM.evaluateOuter (runtime.js:2853)
    at VM.next (runtime.js:4781)
    at VM.execute (runtime.js:4766)
    at TryOpcode.handleException (runtime.js:3746)
    at UpdatingVMFrame.handleException (runtime.js:3916)
    at UpdatingVM._throw [as throw] (runtime.js:3651)
```

According to stack trace the error inside this method:

```
APPEND_OPCODES.add(96 /* ResolveMaybeLocal */, function (vm, _ref5) {
        var _name = _ref5.op1;

        var name = vm.constants.getString(_name);
        var locals = vm.scope().getPartialMap();
        var ref = locals[name];
        if (ref === undefined) {
            ref = vm.getSelf().get(name);
        }
        vm.stack.push(ref);
    });
```

`locals` variable is null.

There is no such error when you navigate from second page to first one.

I've created project in twiddle that reproduce this bug: [project](https://ember-twiddle.com/80041d0c35dbd0821df3d4f0adfe658a)

Not sure that it's a bug (maybe `locals` should be an empty object `{}` at least or add additional condition before `locals[name]`). I've found some work around for me that fixes this bug by using two additional sub-template - one for first page and one for second. And these two templates renders my general sub-template.

**Comment by Alonski** [comment] 2019-02-13 15:17
I am also running into this issue exactly as @viccatoff described :)
The partial is rendered initially and then when routing to the page with the same template as the partial the error is thrown.

**Comment by Alonski** [comment] 2019-02-17 10:15
Reproduction for my error that is related:
https://ember-twiddle.com/0571fff7b5464e2bac66cb8d874c19d5?openFiles=templates.application.hbs%2C

**Comment by GavinJoyce** [comment] 2019-02-17 20:52
@viccatoff a workaround for your issue is to convert the partial to a component. It's likely that partials will be deprecated soon, using components is always preferred to using partials.

**Comment by GavinJoyce** [comment] 2019-02-17 21:14
This looks like the same issue as https://github.com/emberjs/ember.js/issues/16915

**Comment by GavinJoyce** [comment] 2019-02-18 11:48
@Alonski and I paired on creating this failing test: https://github.com/emberjs/ember.js/pull/17633

**Comment by pixelhandler** [comment] 2019-02-22 16:52
@viccatoff yeah it would be a good idea to replace the use of `partial` with a component (as Gavin pointed out)

**Comment by chancancode** [comment] 2019-03-21 08:01
Hm. When we discover (at runtime) that a template is being used as a partial, it must be compiled specially. Basically, every reference, e.g. `{{foo}}`, can suddenly be referring to a local variable (block param) from an outer scope, in addition to the usual possibilities. This is why they get turned into the `ResolveMaybeLocal` opcode, which checks the outer scope (the `locals` dictionary here) first before the normal steps.

We also cache template compilation. Normally each template only need to be compiled once, so each template factory has a single slot to store the result of the compilation, so subsequent invocations of the same template can reuse its result.

I don’t think we accounted for the case where the same template is used in both modes.

This causes the partial-mode compilation to be used in non-partial invocations, which is why the locals map is unexpectedly missing here. 

While the other direction doesn’t cause an error, it essentially causes the partial to not work properly: if there are local variables in the outer scope, it will fail to pick them up. (You should be able to reproduce that with a failing test.)

The more correct fix here is to make sure we cache the compilation result for the two modes separately. Alternatively, I suppose it is also possible to just keep a single cache slot, but remember if it was compiled in partial mode. When invoked as a partial, and the existing compilation result was compiled for the wrong mode, just clear the result and permanently “deopt” the template into partial mode. This, when paired with the undefined guard you tried to add, should work fine as well.

**Comment by locks** [comment] 2020-04-19 00:55
Thank you for the discussion! Partials have been deprecated so I'm closing this as no longer relevant.

**Closed by locks** 2020-04-19 00:55 UTC
Labels: Has PR
