### ISSUE TITLE
Ember 2.9: HTMLElementInput renders undefined attrs

### ISSUE THREAD

**Issue by jamesdixon** [emberjs/ember.js#14243] opened 2016-09-09 03:45 UTC
Not sure if this intentional, but it appears that `undefined`/invalid attributes on html elements are being rendered. Here's what I posted in the Ember Paper repo (https://github.com/miguelcobain/ember-paper/issues/489):

> I just installed Ember 2.9 beta w/ Glimmer 2 and am receiving the following error:
> 
> ```
> ember.debug.js:10648 Uncaught IndexSizeError: Failed to set the 'size' property on 'HTMLInputElement': The value provided is 0, which is an invalid size.
> ```
> 
> The rendered input looks like this:
> 
> ```html
> <input id="input-ember1275" placeholder="Search by Name, Email, or Phone" type="text" accept="undefined" autocomplete="undefined" height="0" min="undefined" max="undefined" name="undefined" pattern="undefined" size="0" spellcheck="false" step="undefined" width="0" class="md-input   ">
> ```
> I tracked it down to the `size` pass-thru in `paper-input`: https://github.com/miguelcobain/ember-paper/blob/master/app/templates/components/paper-input.hbs#L67
> 
> Here's how it renders on 2.4:
> 
> ```html
> <input class="md-input   " id="input-ember1323" placeholder="Search by Name, Email, or Phone" type="text">
> ```
> 
> It appears that Glimmer 2 or something else doesn't ignore undefined attributes.

**Comment by rwjblue** [comment] 2016-09-09 14:27
The error is being thrown due to setting the `size` property on the underlying element to `0` (which is an invalid value per the [whatwg spec](https://html.spec.whatwg.org/multipage/forms.html#the-size-attribute)).

![screenshot of error setting size property](https://monosnap.com/file/QpwVf0HoZxYzQUsDZzpjpWRrMnj98L.png)

Setting as an attribute does not error, but it also does not use the value specified for `element.size`:

![screenshot of non-erroring setting of size attribute](https://monosnap.com/file/ZrAM2hSR3USulLYr9VjVgRLm11Dfpl.png)

**Comment by rwjblue** [comment] 2016-09-09 14:28
@jamesdixon - Can you provide a general reproduction twiddle/JSBin (preferably without using ember-paper)?  That may help us understanding better what is going on...

**Comment by rwjblue** [comment] 2016-09-09 14:51
After discussing with @miguelcobain I realized that `size=0` was not being passed to the component, the value for the attributeBinding was `undefined` which triggers the same error:

![undefined input size causes error regarding 0](https://monosnap.com/file/HMRdELhUQzdv8F3cPNKioCtbnMUTZ9.png)

Simple repro (thanks to @miguelcobain) is:

```hbs
<input size={{someUndefinedProperty}}>
```

Twiddle: https://ember-twiddle.com/4d5d971172012351aeb22965371bfd5c?openFiles=templates.application.hbs%2C

**Comment by jamesdixon** [comment] 2016-09-09 15:00
Thanks and sorry for the delayed reply, @rwjblue.

Although the `size` error was the trigger to post the issue, it does appear that there are differences in the way `undefined` attributes are rendered. On 2.4 (version I'm using), `undefined` attributes are not rendered, whereas now they are. I'm assuming that change is not intentional?

Appreciate your help!

**Comment by rwjblue** [comment] 2016-09-09 15:04
@jamesdixon - Yep, you are absolutely correct! `null` or `undefined` values should not be triggering a `setAttribute` or property set (and should remove attributes previously set).

**Comment by rwjblue** [comment] 2016-09-12 20:35
Fixed by https://github.com/emberjs/ember.js/pull/14271.

**Closed by rwjblue** 2016-09-12 20:35 UTC
Labels: Glimmer2
