### ISSUE TITLE
[BUG] Nested components in Ember 2.10.0-beta.2 

### ISSUE THREAD

**Issue by mhadaily** [emberjs/ember.js#14541] opened 2016-10-28 10:13 UTC
Before I report this bug I have searched but apparently there was no report similar to this issue so I am writing to report a bug that I have found in Ember 2.10-beta-2.  when I create a child for my component Ember recognize it as `undefined`, while it's working perfectly in Ember 2.9 and below. 

--components
---parent-component 
------child-component 

{{parent-component.child-component}} -> undefined 

[Here is an example ](https://ember-twiddle.com/8cba4805c6ac5555d5f6bc7c7937ed4d?openFiles=templates.application.hbs%2Ctemplates.components.parent-component.child-component.hbs)

**Comment by Serabe** [comment] 2016-10-28 10:16
Closing as a duplicate of #14224

Please, let me know if you are referring to a different issue (using `{{parent-component/child-component}}` does render in your twiddle.

Thank you!

**Closed by Serabe** 2016-10-28 10:16 UTC
