### ISSUE TITLE
Property order on a component makes a difference if one property is a computed property with a setter

### ISSUE THREAD

**Issue by t-sauer** [emberjs/ember.js#13598] opened 2016-06-04 16:52 UTC
When passing a property to a component that is a computed property, it seems to make a difference if one of the depending properties is passed to the component before or after in the template.

Here is a small reproduction of the problem: https://ember-twiddle.com/faa771fc0cdccac9ee217fea6a85c587?openFiles=templates.application.hbs%2Ctemplates.components.my-component.hbs

I actually don't know what the proper handling should be (and I am pretty sure that this is bad design on my side). On one hand I always assumed that the order of properties I pass to a component doesn't matter (I haven't found something in the documentation that says something else) but on the other hand I don't know how this case should be handled. Maybe computed properties should only be set after all normal properties have been set on the component, or it should be noted in the docs that the order of properties makes a difference.

**Comment by Serabe** [comment] 2016-06-04 18:50
The setting of `foo` depends on the value of `bar`. That makes the component behave differently in both cases. I would not count this as a bug: you are relying on the order the parameters are passed to the components and that is bad design in my opinion.

If you want more help on the matter, I suggest trying the `#-help` channel in Slack.

**Comment by Serabe** [comment] 2016-06-04 18:50
I am closing this since it is not a bug in Ember. Please, add more information if you consider this is actually a bug.

**Closed by Serabe** 2016-06-04 18:50 UTC

**Comment by t-sauer** [comment] 2016-06-05 09:42
> you are relying on the order the parameters are passed to the components and that is bad design in my opinion
Well that's the point: is it intended that parameter order can make a difference (as long as they are not positional parameters)?
If yes than it should go into the docs and if not than it should be handled in Ember in my opinion.

**Comment by rwjblue** [comment] 2016-06-05 13:07
This isn't really an Ember issue though, if you do the same setup without Ember via JS accessors you would have the same order dependence issue.
