### ISSUE TITLE
Ember 3.17 - helper re-computation in {{each}}

### ISSUE THREAD

**Issue by 22a** [emberjs/ember.js#18990] opened 2020-05-22 15:42 UTC
Since ember-source `3.17.0-beta.1`, helpers rendered inside an `{{each}}` block are re-computed/re-rendered when the passed list changes by reference. In these scenarios, the existing helper content is removed from the DOM and re-appended.

This has led to a few issues in our app with event targets not being present in the DOM by the time the event has propagated to any global event listeners (on the document/window).

### Minimal reproduction

I’ve put together an reproduction of this in a component by invoking `ember-inline-svg` inside an `{{each}}` block in a fresh app: https://github.com/22a/ember-helper-re-render-repro

- [my-component.hbs](https://github.com/22a/ember-helper-re-render-repro/blob/master/app/templates/components/my-component.hbs)
- [my-component.js](https://github.com/22a/ember-helper-re-render-repro/blob/master/app/components/my-component.js)

The example is a little contrived in how it induces the `{{each}}` re-evaluation, but it does illustrate that, since 3.17.0 (through present: 3.18.1), helpers are being torn down and re-appended to the DOM where components / elements don’t.

### <=`3.16.8`
<img width="726" alt="Screenshot 2020-05-22 at 15 44 52" src="https://user-images.githubusercontent.com/7144173/82679725-39854a80-9c43-11ea-8652-6ff009e2a22b.png">

### >= `3.17.0-beta.1`
<img width="703" alt="Screenshot 2020-05-22 at 15 01 25" src="https://user-images.githubusercontent.com/7144173/82679212-af3ce680-9c42-11ea-8ee7-eb1f9ff948be.png">

While I show a click on a `path` in both screenshots above it happens equally to the `svg` node - I can simplify this reproduction further to a helper that simply inserts a `div` if that would be helpful.

**Comment by rwjblue** [comment] 2020-05-22 16:30
I believe this is a duplicate of an issue that was fixed in 3.18.1. Can you update and confirm?

**Comment by rwjblue** [comment] 2020-05-22 16:31
Hmm, sorry, I see now that you mentioned that the demo still shows the described behavior on 3.18.1.

**Comment by rwjblue** [comment] 2020-06-16 21:13
This was fixed in https://github.com/glimmerjs/glimmer-vm/pull/1100, which is released in 3.19.0. I confirmed in the reproduction you provided.

**Closed** 2020-06-16 21:15 UTC
