### ISSUE TITLE
dynamic namespaced attributes

### ISSUE THREAD

**Issue by luxferresum** [emberjs/ember.js#18007] opened 2019-05-04 22:47 UTC
When doing something like `xlink:href={{data}}` it is not working.

[twiddle with reproduction](https://ember-twiddle.com/c786d81c4e970e245878bd87287b5845?openFiles=templates.application.hbs%2C)

This is a duplicate from #14752. However we *still have the problem on 3.8!*

The workaround works but is flawed. It only works when changing the attribute. If originally the value is empty and then gets set it does not work ([demonstation here](https://ember-twiddle.com/aa0a180e0c31d930114d3310004bfd6f?openFiles=templates.application.hbs%2C))

Also we currently *lint against the workaround* with `ember-cli-template-lint`.

We should at least fix the lint and lint against the not working behaviour, but better fix it.

**Comment by rwjblue** [comment] 2019-05-21 16:26
Also a duplicate of https://github.com/emberjs/ember.js/issues/16968. The fix landed upstream in https://github.com/glimmerjs/glimmer-vm/pull/869, but the version of glimmer-vm in use by 3.8+ of Ember does not include the fix.

We should backport that fix to versions of glimmer-vm that are in use by 3.8 and 3.10+ to resolve the issue.

**Comment by locks** [comment] 2020-04-19 11:14
Aside being a duplicate, the fix landed in 3.17 so I'll be closing the issue. Thanks for the report!

**Closed by locks** 2020-04-19 11:14 UTC
Labels: Bug
