### ISSUE TITLE
Unexpected  angle-bracket component invocation.

### ISSUE THREAD

**Issue by lifeart** [emberjs/ember.js#17744] opened 2019-03-15 16:33 UTC
Given:
* component, named `foo-bar`.
* component/controller context.

component-or-controller
```js
this.someName = 'foo-bar'
```

context-related template
```hbs
<this.someName />
```

result

`foo-bar` component rendered, instead of error or `<foo-bar />` tag rendering.

Reproduction:

https://ember-twiddle.com/#/4d2f5e2d56d204de0a74090e6d728b84?openFiles=templates.application.hbs%2C

May be related to:
https://github.com/emberjs/ember.js/commit/1aa4fbb327b28f0422db07590822030adf141cfd#diff-e6d62c9fc48e7201f4f2e4b9a3d52fa7

**Comment by rwjblue** [comment] 2019-03-15 17:09
Ya, this should assert

/cc @chancancode

**Comment by chancancode** [comment] 2019-03-16 22:49
@rwjblue I know how to add the assert via the same ast transform (basically turning it into `{{#let (assertion this.someName) as |__secret__|}}<__secret__ />{{/let}}`). But how do we feel about adding more of that assertion right now given we don't have a dev vs prod mode distinction?

**Comment by ef4** [comment] 2019-05-24 15:58
I don't understand why this would be implemented as an assertion before invocation rather than making sure invocation never supports strings?

I would have thought that invoking a string is an opt-in behavior that requires wrapping in `{{component}}` and that's the only place where *dynamic* string values should be getting resolved into components?

**Comment by chancancode** [comment] 2019-05-24 16:21
Mostly just a hack before implementing it in glimmer can and updating to use the latest glimmer vm here. This assertion already exists for curlies etc. Part of the reason is a lot of the dynamic invocations are themselves hacked on top in ember via ast transforms without proper vm support. The reason the curly/dot rule version fails is because we literally transform them into component helpers, which do support strings.

**Comment by rwjblue** [comment] 2020-09-02 14:46
FYI - I submitted a failing test for this over in https://github.com/glimmerjs/glimmer-vm/pull/1149. Did some digging with @krisselden and @pzuraq to determine what is the real cause (usage of `builder.dynamicComponent`, which is _also_ the same thing that supports `{{component` helper so it includes resolution). I believe that @pzuraq has a fix, that we'll hopefully be able to land for Ember 3.23.0-beta.1...

**Closed** 2020-09-02 19:14 UTC

**Comment by robclancy** [comment] 2021-01-08 02:50
I don't see how this was an issue? I was using this and thought it was a nice feature.

**Comment by ef4** [comment] 2021-01-08 03:13
It’s a big deal because of the way it defeats static analysis. An app that does this anywhere can’t shake out unused components *everywhere*. 

For some alternative ways to get the component invocation you want, see https://github.com/embroider-build/embroider/blob/master/REPLACING-COMPONENT-HELPER.md. Depends on your use case, but the patterns suggested there might help.

**Comment by robclancy** [comment] 2021-01-08 04:10
Well looks like this has done more than stop strings. I get an infinite loop until I run out of memory now if I use a component passed in a hash that is made using the helper.
`<Comp @comps={{hash comp=(component 'something')}} />`
`<@comps.comp />` <- infinite loop crash tab fun

**Comment by ef4** [comment] 2021-01-08 04:18
I just tried to reproduce that and couldn't. If you can make it happen reliably please file an issue with the reproduction and I'll take a look.

**Comment by robclancy** [comment] 2021-01-08 04:54
It was due to something changing with helpers and a `Object.assign` was modifying the original params sent into the helpers whereas before it wouldn't. So a component was calling itself over and over recursively since it replaced the parent version with itself.
