### ISSUE TITLE
Error while evaluating assertion condition in HTMLbars

### ISSUE THREAD

**Issue by grantovich** [emberjs/ember.js#12720] opened 2015-12-17 17:02 UTC
Using Ember 2.2.0 and ember-cli-htmlbars 1.0.1, I accidentally put a quote in the wrong place:

```hbs
<div class='form-field' {{if model.errors.name 'form-field--error'}}>
  ...
</div>
```

For reasons I don't completely understand, this causes an `'options.template.yield' is undefined` error when evaluating the condition for [this assertion](https://github.com/emberjs/ember.js/blob/1a2cd166a86219717a0cde1df4dab497d8dda3e3/packages/ember-htmlbars/lib/helpers/if_unless.js#L86). I'm not sure what the correct behavior should be, but intuitively I'd expect it to just generate an oddly-named property on the element (which would be easy to diagnose).

**Comment by trek** [comment] 2015-12-18 14:47
Can you create a simple https://ember-twiddle.com/ to demonstrate? It will greatly speed our debugging.

**Comment by mixonic** [comment] 2015-12-18 15:23
duplicate of https://github.com/emberjs/ember.js/issues/12661

**Closed by mixonic** 2015-12-18 15:23 UTC
Labels: Needs Submitter Response

**Comment by grantovich** [comment] 2015-12-18 16:03
Thanks for finding that @mixonic, I searched around the issues but apparently wasn't using enough of the right terms. Sorry for the dupe! :sweat_smile:
