### ISSUE TITLE
Passing classNames to View or Component through template breaks event handling

### ISSUE THREAD

**Issue by heycarsten** [emberjs/ember.js#5487] opened 2014-08-25 18:21 UTC
[Example](http://emberjs.jsbin.com/lapeq/2/)

The issue is that in the rare case where you'd want to set `classNames` to a property containing an array of strings it breaks the helper entirely causing the click listener to be seemingly ignored and the underlying anchor element to actually perform navigation to the path set in its `href`.

I've taken a quick look through the source to `{{link-to}}` and don't see any obvious reasons why this happens. The example sources Ember 1.6.1, but it also happens in 1.7.0, and 1.8.0-beta.1.

**Comment by jayphelps** [comment] 2015-01-08 22:25
@selvagsz @mixonic @mmun any of you gentlemen have thoughts on how to handle this? Particularly `{{view classNames=arrayClassNames}}`.

I tried to simply amend [mergeDOMViewBindings](https://github.com/emberjs/ember.js/blob/02db2752474f6796fafc090ed50ac5ccf80b0bd5/packages/ember-htmlbars/lib/system/merge-view-bindings.js#L55) with:
```javascript
if (hash.classNames) {
  classBindings.push(hash.classNames._label);
  delete hash.classNames;
}
```
...but arrays are currently treated as `falsy` for inside `classStringForValue()` which was introduced [here](https://github.com/emberjs/ember.js/commit/714f2d8ea669b25ed301b6a950c0a7918cba831f#diff-d7c8ea596da4f2cfeb899a2647f2dca5R2508) but now lives [here]((https://github.com/emberjs/ember.js/blob/1e087d221ff2b0be7929c42c8686da315ca447ed/packages/ember-views/lib/streams/class_name_binding.js#L83).

**Comment by herom** [comment] 2015-03-09 13:16
The behaviour is shown if you try to observe the `classNames` array by doing

```
didChangeClassNames: function () {
  // ... do your stuff _WITHOUT_ touching this.classNames
}.observes('classNames.[])
```

See http://emberjs.jsbin.com/mucegucuhu/1/edit?html,js,console,output (if you comment out the `didChangeClassNames()` method, everything works as expected.

**Comment by mixonic** [comment] 2015-03-09 19:00
I do not believe `classNames` is observable.

`concatenatedProperties` may be stompable. That would probably be the cause of this. If we land a fix, I would like to land it in the Glimmer branch, as that PR radically changes much of this code. I've got a branch refactoring classNameBindings I can add a test for this on.

**Comment by herom** [comment] 2015-03-09 21:12
>I do not believe classNames is observable.
Ah, ok - I just didn't think of it to be non-observable by means of the error message and stumbled upon it today at work. As this seemed related (at least to me) I thought I just add my input :smile: 

I'm really curious about Glimmer - can't wait to see/code it live and in action :+1:

**Comment by rwjblue** [comment] 2015-08-09 17:05
Specifying `class=` is the way forward here.  `classNames`, `classNameBindings`, etc are going to be much less common once we enable angle bracket components by default.  Closing this with the suggestion to use `class`.

Update of the original demo using `class`: http://rwjblue.jsbin.com/tinuqa/edit?html,js,output.

**Closed by rwjblue** 2015-08-09 17:05 UTC
Labels: Bug, Needs Label Review, Needs Team Discussion, Old: unverified, Regression
