### ISSUE TITLE
Non-Singleton registered dependencies not working as expected for components since Ember 2.10

### ISSUE THREAD

**Issue by adamjmcgrath** [emberjs/ember.js#14719] opened 2016-12-14 15:46 UTC
The behaviour for component factory caching is inconsistent between the `definitionCache` in the `GlimmerEnvironment` and the `factoryCache` in the `container`. The `container` [does not cache factories with dynamic injections](https://github.com/emberjs/ember.js/blob/master/packages/container/lib/container.js#L451), whereas the `GlimmerEnvironment` [does](https://github.com/emberjs/ember.js/blob/master/packages/ember-glimmer/lib/environment.js#L77).

```js
// initializers.app-init.js
import Ember from 'ember';
var id = 0;
export function initialize(application) {
  application.register('foo:bar', Ember.Object.extend({
    id: Ember.computed(function() {
      return ++id;
    })
  }), { singleton: false });
  application.inject('component', 'foo', 'foo:bar');
}
export default {
  name: 'app-init',
  initialize
};

// my-component.hbs
id: {{foo.id}}

// templates.application.hbs
{{ my-component }}
{{ my-component }}
{{ my-component }}
```

In Ember 2.9 the output is:
id: 1
id: 2
id: 3

In Ember 2.10 the output is:
id: 1
id: 1
id: 1

See [Ember Twiddle](https://ember-twiddle.com/1b3c5f63a7bbafd0df1059f4faaae022?openFiles=templates.application.hbs%2C)

And [failing test](https://github.com/adamjmcgrath/ember.js/commit/29e8ccf8304fe426511f631f027eb2b9b1c62588#diff-ba6e92c027902d3a274c30118f1f0e72)

We're refactoring our code that uses this pattern, so don't expect this issue to affect us - this is more an FYI

**Comment by mixonic** [comment] 2017-03-26 06:56
@chancancode this actually seems like we will need to do something regarding the `definitionCache` to fix.

**Comment by bekzod** [comment] 2017-06-26 12:05
looks like fixed in `2.13.*`

**Comment by locks** [comment] 2017-06-26 13:59
Can you confirm @adamjmcgrath ?

**Comment by adamjmcgrath** [comment] 2017-06-26 23:03
No sorry, I'm in the middle of the Pacific. Back September :)

**Comment by jimenglish81** [comment] 2017-06-27 04:49
I work with @adamjmcgrath. I can check it out today

**Comment by jimenglish81** [comment] 2017-06-29 17:53
Sorry for delay. 
I can confirm it is working in `2.13.*`. The twiddle now behaves as it did in `2.9`.
Thanks for letting us know 👍

**Closed** 2017-06-29 20:55 UTC
Labels: Bug, Regression
