### ISSUE TITLE
[Glimmer] View appendTo() not working

### ISSUE THREAD

**Issue by Adriaaaaan** [emberjs/ember.js#11109] opened 2015-05-11 12:18 UTC
In my app we are integrating ember into an existing web application that uses server side rendering. As a result I need to render some ember components (mostly just the top navigation) outside of the ember application element as otherwise there is no way to render anything above the serverside code.

glimmer - expect the word "hello" to appear
http://emberjs.jsbin.com/hesixoqule/2/edit

1.11.3
http://emberjs.jsbin.com/xigivuruwe/4/edit?html,js,output

**Comment by mixonic** [comment] 2015-05-11 12:40
Definitely a regression.

Fwiw, I strongly suggest you use [ember-wormhole](https://github.com/yapplabs/ember-wormhole) to manage attaching your app to different places in the DOM. It attaches the application to body, but lets you target existing element ids on the dom for rendering. Since you can skip using `rootElement`, you will still have proper event handling. The view will live as part the rending cycle when you change routes instead of in its own.

But this is still a regression.

**Comment by Adriaaaaan** [comment] 2015-05-11 13:21
Thanks, that works for me.

**Comment by rwjblue** [comment] 2015-05-12 02:27
Should be fixed by https://github.com/emberjs/ember.js/pull/11131 once it lands...

**Closed** 2015-05-12 09:11 UTC
Labels: Bug
