### ISSUE TITLE
Simple ember app freezes browser

### ISSUE THREAD

**Issue by michelboaventura** [emberjs/ember.js#15743] opened 2017-10-17 03:28 UTC
I'm having a strange bug on which opening an ember app freezes my browser tab. Using chrome task manager I can see the tab is using more and more ram (it goes up to 1.8GB before chrome decides to kill it) with 100% of a cpu (the same happens on firefox). I was able to extract the behavior on a minimum app: https://github.com/michelboaventura/ember_bug

To see the problem you just need to run a ``ember s`` and open the app. Just bear in mind it may crash chrome.

Sadly I can't debug the issue, since the tab is unresponsive and I can't use dev tools.

**Comment by mani-mishra** [comment] 2017-10-17 04:46
Can confirm. Its crashing firefox, safari too.
FF shows below message:

<img width="1415" alt="screen shot 2017-10-17 at 10 11 46 am" src="https://user-images.githubusercontent.com/3315240/31647057-50d11b44-b323-11e7-86db-20869a148e53.png">

On more debugging it seems there is an infinite loop in application's ```activate``` hook.
![infinite-loop](https://user-images.githubusercontent.com/3315240/31647168-26e02c16-b324-11e7-88b5-dad891999b51.gif)

**Comment by makepanic** [comment] 2017-10-17 07:39
@mani-mishra I think your issue is that you're trying to transition in the application routes activate hook.
It means that it aborts the transition and tries to transition to foo which causes the application route to try to activate later on.
This means it'll get stuck in an infinite loop trying to activate -> transition

**Comment by mani-mishra** [comment] 2017-10-17 08:21
Thanks @makepanic 
Although it wasn't my issue, I just debugged the original issue of browser's crashing in @michelboaventura 's app :)

This doesn't seem an issue with ember.js itself.

**Comment by locks** [comment] 2017-10-17 09:22
Thank you for the feedback! I'm closing the issue as it is not a bug with Ember.

**Closed by locks** 2017-10-17 09:22 UTC

**Comment by michelboaventura** [comment] 2017-10-24 14:31
Thank you @mani-mishra for test and @makepanic to show me the problem!
