### ISSUE TITLE
classNameBindings not triggering correctly

### ISSUE THREAD

**Issue by mohlek** [emberjs/ember.js#12814] opened 2016-01-14 12:19 UTC
In Ember 2.2.0 it seems that classNameBindings are not triggering correctly / as before.
I am using the addon ivy-tabs and the active class is not set on changing the tabs.
I dont think its a bug related to ivy-tabs since I got the same problems with my own implementation.

```javascript
classNameBindings: ['active'],
activeClass: 'active',

active: Ember.computed(function() {
    if (this.get('isSelected')) { return this.get('activeClass'); }
  }).property('isSelected'),
```

This should set the active class. But it doesn't.

Was there anything changed in Ember 2?

**Comment by mohlek** [comment] 2016-01-14 12:24
The active property is firing correctly. I can add a console.log('test'); and it will log in console every time i change the tab

**Comment by diogomafra** [comment] 2016-01-14 13:00
Looks like it's working: https://ember-twiddle.com/4def6ecd8f6797d0de43?openFiles=my-component.component.js%2Cstyles.app.css

Try to replicate the problem in a ember-twiddle.

**Comment by mohlek** [comment] 2016-01-14 13:16
Yeah it seems to :-/
https://ember-twiddle.com/4def6ecd8f6797d0de43?openFiles=my-component-parent.component.js%2Capplication.template.hbs

This is something similar to my work which doesn't work on my setup.

Maybe its some addon that crash my ember :-/

```json
{
  "name": "web",
  "version": "0.0.0",
  "description": "Small description for web goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "babel-eslint": "^4.1.6",
    "broccoli-asset-rev": "^2.2.0",
    "ember-ajax": "0.7.1",
    "ember-cli": "2.2.0-beta.1",
    "ember-cli-active-link-wrapper": "0.0.4",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-autoprefixer": "0.5.0",
    "ember-cli-babel": "^5.1.5",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-deploy": "0.5.1",
    "ember-cli-deploy-build": "0.1.0",
    "ember-cli-deploy-git-tag": "0.2.0",
    "ember-cli-deploy-redis": "0.1.1",
    "ember-cli-deploy-revision-data": "0.1.0",
    "ember-cli-htmlbars": "^1.0.1",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.3.1",
    "ember-cli-mirage": "0.1.11",
    "ember-cli-qunit": "^1.1.0",
    "ember-cli-release": "0.2.8",
    "ember-cli-sass": "5.2.1",
    "ember-cli-scroll-to": "0.0.2",
    "ember-cli-sri": "^1.2.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-component-css": "git://github.com/ebryn/ember-component-css.git#69d16a332f0efdb23a51eb5c9d45b71b21b39b20",
    "ember-data": "^2.2.1",
    "ember-disable-proxy-controllers": "^1.0.1",
    "ember-export-application-global": "^1.0.4",
    "ember-intl": "2.0.0",
    "ember-normalize": "0.0.9",
    "ember-page-title": "2.0.7",
    "ember-resolver": "^2.0.3",
    "ember-simple-auth": "1.0.1",
    "ember-simple-auth-token": "1.0.0",
    "ember-suave": "git://github.com/dockyard/ember-suave.git#da1205622b0e7f9b14af0d63230f63cb3c2019ab",
    "ember-truth-helpers": "1.2.0",
    "eslint": "^1.10.3",
    "ivy-tabs": "git://github.com/ivyapp/ivy-tabs.git#aadc121c63801d1e1a1d93365629fd4e6bef76bf",
    "liquid-fire": "0.22.1"
  }
}
```

**Comment by diogomafra** [comment] 2016-01-14 13:35
Have you checked the HTML to confirm that the 'active' class is not being setted? Maybe it's the CSS that is not correct.

**Comment by mohlek** [comment] 2016-01-14 14:00
Ofc I did :)

```html
<div class="ember1204" class="ember-view ivy-tabs">
    <ul id="ember1232" class="ember-view ivy-tab-list" role="tablist" aria-multiselectable="false">
        <li id="ember1260" class="ember-view ivy-tab active" role="tab" aria-expanded="true" aria-selected="true" aria-controls="ember1292" selected="selected" tabindex="0"></li>
        <li id="ember1261" class="ember-view ivy-tab" role="tab" aria-expanded="false" aria-selected="false" aria-controls="ember1293"></li>
        <li id="ember1262" class="ember-view ivy-tab" role="tab" aria-expanded="false" aria-selected="false" aria-controls="ember1294"></li>
        <li id="ember1263" class="ember-view ivy-tab" role="tab" aria-expanded="false" aria-selected="false" aria-controls="ember1295"></li>
        <li id="ember1264" class="ember-view ivy-tab" role="tab" aria-expanded="false" aria-selected="false" aria-controls="ember1296"></li>
    </ul>
    <div id="ember1292" class="ember-view ivy-tab-panel active" role="tabpanel" aria-labelledby="ember1260" style="display: none;"></div>
    <div id="ember1293" class="ember-view ivy-tab-panel" role="tabpanel" aria-labelledby="ember1261" style="display: none;"></div>
    <div id="ember1294" class="ember-view ivy-tab-panel" role="tabpanel" aria-labelledby="ember1262" style="display: block;"></div>
    <div id="ember1295" class="ember-view ivy-tab-panel" role="tabpanel" aria-labelledby="ember1263" style="display: none;"></div>
    <div id="ember1296" class="ember-view ivy-tab-panel" role="tabpanel" aria-labelledby="ember1264" style="display: none;"></div>
</div>
```

As you can see in UL is the first LI active.
At DIV's below its the third one (display: block; which I selected). But there is also the active class "bug"

The switching works great, but not the class binding

**Comment by mohlek** [comment] 2016-01-15 08:18
Got it. It was an addon. Liquid-Fire .. As always ^^

I didn't defined any transitions and that seems to break something. I don't know what.
After defining transitions everything works fine.

I'll go ahead and create an issue at liquid-fire.

Thanks for participating.

**Comment by mohlek** [comment] 2016-01-15 09:02
God damn -.- transitions doesn't seems to fixed this.
I opened the page on a different machine and nothing worked. Holy shit? O.o

Refreshing cache on my computer and it doesn't work either.

**Comment by mohlek** [comment] 2016-01-15 09:25
Now things are getting very strange. I can reproduce the bug on my machine. But i am not able to reproduce in an twiddle.
reloading the page (subroute with tabs directly) kills the classBindinding.
Doing a single transition e.g. to index and back makes everything work.

i don't know what project this bug is related to. Wether ivy-tabs, ember or liquid-fire.
Maybe someone here can give me a hint. I would be very thankful

**Comment by pixelhandler** [comment] 2016-01-15 19:31
@mohlek you mentioned that the twiddle example didn't help to show off the issue. perhaps a simple repo with an app that someone can clone would work.

**Comment by jpoiri** [comment] 2016-03-10 13:14
I am getting the same issue as @mohlek using the latest version of Ember (2.4.2) I issue is happening as well in version 2.3

Here's an example:

When I click on the button the active property of the component is changed however the class is not removed from the button.

```javascript
//custom-button.js
import Ember from 'ember';
export default Ember.Component.extend({
	/**
	 * The list of class names.
	 * @default btn
	 */
	classNames: ['btn', 'btn-primary'],

	attributeBindings: ['label'],

	/**
	 * The class name bindings
	 */
	classNameBindings: ['activeClass'],
	/**
	 * Rendered tag.
	 */
	tagName: 'button',

	activeClass: Ember.computed('active', function () {
                Ember.debug('computed property fired');
		if (!Ember.isNone(this.get('active'))) {
			return 'active';
		}
		return '';
	})
});
```
```handlebars
<!--test template-->
{{custom-button id="btn1" label="Active button" active=active}}
<button onclick={{action "toggleActive"}}>Toggle Active</button>
```

```js
//test controller
import Ember from "ember";

export default Ember.Controller.extend({

	active: true,

	actions: {
		toggleActive() {
			this.toggleProperty('active');
		}
	}
});
```

**Comment by jpoiri** [comment] 2016-03-10 15:44
Please disregard my previous comment found my issue

**Comment by pixelhandler** [comment] 2016-04-22 17:10
@mohlek were you able to create a repo with the code that you suspect is buggy with the same dependencies you have in your app. Perhaps then someone can help debug.

I don't this this is a bug in Ember, so closing this for now. Perhaps reopen the issue if it can be reproduced in an example repo.

**Closed by pixelhandler** 2016-04-22 17:10 UTC
Labels: Needs Bug Verification, Needs Submitter Response
