### ISSUE TITLE
Query params with arrays are turned into strings when route.refresh() is used

### ISSUE THREAD

**Issue by kalanda** [emberjs/ember.js#14715] opened 2016-12-13 17:36 UTC
Query params containing arrays are turned into strings when `route.refresh()` is called and another query param is changed at the same time.

I put here a link to a twiddle using ember2.9.0 and an animated gif to see the testing process. 

The first button sets the `filters` param to an initial value of `['filter1', 'filter2']` and the value is well represented in the URL's query string.

The second button calls an action that just executes `route.refresh()` and the `model()`method of the route is receiving an array with `['filter1', 'filter2']` in the `filters`param.

The third button shows the issue by calling an action that first changes a different query param (`otherParam`) and after that, executes `route.refresh()` and the `model()`method of the route is receiving a `string` instead of an `array` with the value of filters. 

https://ember-twiddle.com/0c3833a0ae05e1350f4e0e8cbd4f125c?openFiles=controllers.application.js%2C

![queryparams-refresh-issue](https://cloud.githubusercontent.com/assets/392687/21150871/d396d196-c160-11e6-82e3-4a4ec52bc72c.gif)

**Comment by nathanhammond** [comment] 2016-12-13 21:59
Known issue, duplicate of https://github.com/emberjs/ember.js/issues/14174

**Comment by Serabe** [comment] 2016-12-13 23:17
Closing as duplicate. Thank you all!

**Closed by Serabe** 2016-12-13 23:17 UTC
