### ISSUE TITLE
Recurring bug in ember-metal/stream/stream (undefined is not an object (evaluating 'this.children[n]'))

### ISSUE THREAD

**Issue by jdurand** [emberjs/ember.js#11166] opened 2015-05-14 18:00 UTC
I regularly hit a case in production that I can't reproduce on my dev environment. I Post JS exceptions to my backend for logging and every now and then I receive `Error: undefined is not an object (evaluating 'this.children[n]')` followed by a stack trace the looks like this :

````
User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 8_1_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12B466
version: xxxxx
account: xxxxx
user: xxxx@xxxxx
get@https://s3.amazonaws.com/static.libroapp.com/assets/application-e2f9c2b17f2ff9f2660dc423c262e42d.js:12:33959
getStream@https://s3.amazonaws.com/static.libroapp.com/assets/application-e2f9c2b17f2ff9f2660dc423c262e42d.js:17:19538
_applyAttributeBindings@https://s3.amazonaws.com/static.libroapp.com/assets/application-e2f9c2b17f2ff9f2660dc423c262e42d.js:17:248
applyAttributesToBuffer@https://s3.amazonaws.com/static.libroapp.com/assets/application-e2f9c2b17f2ff9f2660dc423c262e42d.js:18:51681
createElement@https://s3.amazonaws.com/static.libroapp.com/assets/application-e2f9c2b17f2ff9f2660dc423c262e42d.js:17:52512
i@https://s3.amazonaws.com/static.libroapp.com/assets/application-e2f9c2b17f2ff9f2660dc423c262e42d.js:10:37887
ensureChildrenAreInDOM@https://s3.amazonaws.com/static.libroapp.com/assets/application-e2f9c2b17f2ff9f2660dc423c262e42d.js:18:10763
_ensureChildrenAreInDOM@https://s3.amazonaws.com/static.libroapp.com/assets/application-e2f9c2b17f2ff9f2660dc423c262e42d.js:18:10123
invokeWithOnError@https://s3.amazonaws.com/static.libroapp.com/assets/application-e2f9c2b17f2ff9f2660dc423c262e42d.js:8:29922
flush@https://s3.amazonaws.com/static.libroapp.com/assets/application-e2f9c2b17f2ff9f2660dc423c262e42d.js:8:30362
flush@https://s3.amazonaws.com/static.libroapp.com/assets/application-e2f9c2b17f2ff9f2660dc423c262e42d.js:8:27745
end@https://s3.amazonaws.com/static.libroapp.com/assets/application-e2f9c2b17f2ff9f2660dc423c262e42d.js:8:17155
run@https://s3.amazonaws.com/static.libroapp.com/assets/application-e2f9c2b17f2ff9f2660dc423c262e42d.js:8:17476
l@https://s3.amazonaws.com/static.libroapp.com/assets/application-e2f9c2b17f2ff9f2660dc423c262e42d.js:12:26252
handler@https://s3.amazonaws.com/static.libroapp.com/assets/application-e2f9c2b17f2ff9f2660dc423c262e42d.js:12:59892
https://s3.amazonaws.com/static.libroapp.com/assets/application-e2f9c2b17f2ff9f2660dc423c262e42d.js:17:36916
dispatch@https://s3.amazonaws.com/static.libroapp.com/assets/application-e2f9c2b17f2ff9f2660dc423c262e42d.js:2:17348
handle@https://s3.amazonaws.com/static.libroapp.com/assets/application-e2f9c2b17f2ff9f2660dc423c262e42d.js:2:14021
dispatchEvent@[native code]
sendClick@https://s3.amazonaws.com/static.libroapp.com/assets/application-e2f9c2b17f2ff9f2660dc423c262e42d.js:26:30868
onTouchEnd@https://s3.amazonaws.com/static.libroapp.com/assets/application-e2f9c2b17f2ff9f2660dc423c262e42d.js:26:33727
https://s3.amazonaws.com/static.libroapp.com/assets/application-e2f9c2b17f2ff9f2660dc423c262e42d.js:26:14203
````

It seems to always happen on iPhone/iPad and I'm not even sure if my users experience any glitches...

I have a hunch that this.children is sometimes still `undefined` when the execution reaches this point :  https://github.com/emberjs/ember.js/blob/v1.11.3/packages/ember-metal/lib/streams/stream.js#L41

Which could be linked to this bit of code that seems pretty old : 
https://github.com/emberjs/ember.js/blob/v1.11.3/packages/ember-metal/lib/platform/create.js#L24

I'm on v1.11.3, but the code is the same in v1.13-beta.

I couldn't reproduce this in a JSBin, I only see this in production logs.
I'm posting this here in case someone else has similar issues.

**Comment by cloutierlp** [comment] 2015-06-02 21:22
:+1:

**Comment by MattNguyen** [comment] 2015-06-08 17:35
+1 We're also seeing the same issue only on Mobile Safari.

Ember: 1.12.0
Ember Data: 1.0.0-beta.17
jQuery: 1.11.2
Model Fragments: 0.3.2

**Comment by mixonic** [comment] 2015-06-08 18:07
Can any of you narrow down which version of mobile safari is troublesome?

**Comment by MattNguyen** [comment] 2015-06-08 18:10
@mixonic - just mobile safari 8.0

**Comment by jbourassa** [comment] 2015-06-08 18:21
We've had this with iOS 8.1.2 and 8.2.

It happens on different pages of our app. I know that's very vague but it seems there's always one of our component in the stack trace, that might be a hint.

Here's a stack trace from Sentry, generated with sourcemap support. That probably won't help very much, but anyways:

```
/private/bower_components/ember/ember.prod.js  ? in view
     ret = (item === null || item === undefined) ? String(item) : TYPE_MAP[toString.call(item)] || 'object';
/private/bower_components/ember/ember.prod.js  ? in getStream
     _dispatchEvent: function(object, evt, eventName, view) {
/private/bower_components/ember/ember.prod.js  ? in get
     return view.getStream(path);
/private/didacte/templates/components/enrollment-card-content.js  ? in render
             block(env, morph0, context, "if", [get(env, context, "enrollment.currentLesson")], {}, child0, child1);
/private/bower_components/ember/ember.prod.js  ? in renderHTMLBarsTemplate
   Ember['default'].EnumerableUtils = EnumerableUtils['default'];
/private/bower_components/ember/ember.prod.js  ? in this
             output = renderHTMLBarsTemplate(view, buffer, template);
/private/bower_components/ember/ember.prod.js  ? in this
       if (!this._super.apply(this, arguments)) { return; }
/private/bower_components/ember/ember.prod.js  ? in createElement
       var childViews = this._childViews;
/private/bower_components/ember/ember.prod.js  ? in document
   Ember['default'].EnumerableUtils = EnumerableUtils['default'];
/private/bower_components/ember/ember.prod.js  ? in document
     var canClone = doc && (function(document){
/private/bower_components/ember/ember.prod.js  ? in document
     var canClone = doc && (function(document){
/private/bower_components/ember/ember.prod.js  ? in document
     var canClone = doc && (function(document){
/private/bower_components/ember/ember.prod.js  ? in document
     var canClone = doc && (function(document){
/private/bower_components/ember/ember.prod.js  ? in document
     var canClone = doc && (function(document){
/private/bower_components/ember/ember.prod.js  ? in join
     var canClone = doc && (function(document){
/private/bower_components/ember/ember.prod.js  ? in join
     ret = (item === null || item === undefined) ? String(item) : TYPE_MAP[toString.call(item)] || 'object';
/private/assets/jquery/dist/jquery.min.js  ? in j
 !function(a,b){"object"==typeof module&&"object"==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw n {snip}
/private/assets/jquery/dist/jquery.min.js  ? in fireWith
 !function(a,b){"object"==typeof module&&"object"==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw n {snip}
/private/assets/jquery/dist/jquery.min.js  ? in ready
 !function(a,b){"object"==typeof module&&"object"==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw n {snip}
/private/assets/jquery/dist/jquery.min.js  ? in J
 !function(a,b){"object"==typeof module&&"object"==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw n {snip}
```

**Comment by jdurand** [comment] 2015-06-08 18:32
@mixonic, I'm seeing this on 8.1.x-8.2 as well.

**Comment by kemenaran** [comment] 2015-07-20 09:44
Chiming in: we do have a lot of these exceptions in production, on Mobile Safari `8.*` too.

**Comment by jbourassa** [comment] 2015-07-20 14:20
Not sure if there's a link there but @cloutierlp, @jdurand, @kemenaran and I all appear to be working on apps that are used by french speaking users. I have _no_ idea how that could come into play, but you never know with Mobile Safari... !

On a different note, has anyone updated to 1.13? If so, are you still getting these?

**Comment by jdurand** [comment] 2015-07-20 15:58
@jbourassa, Interesting find, I'll start logging the client locale and see if that checks out!

It could be that I stopped paying attention to this, but I haven't seen this issue in a while now with :
* ember-source (1.12.1)
* ember-data (1.0.0.beta.19.2)

@jbourassa, @cloutierlp, @kemenaran was this ever linked to a user reported issue for you guys?

I'm now regularly seeing a `ajaxError` pop-up in production. I should have fixed ember-source and ember-data 1.13 deprecations & breaking changes in my app by the end of the month. I'll either open a new issue and link it here or just post here depending on what I'm seeing in the logs.

**Comment by jbourassa** [comment] 2015-07-20 16:04
@jdurand Nope, not a single user report for anything that seems to be linked with this.

We've been updating to 1.13 in the last week in hope to fix this. We're still way behind with Ember-Data, that might be the root cause. I'll report back once 1.13 is in production.

Thanks for the update!

**Comment by mmun** [comment] 2015-07-20 17:25
Thanks to everyone for the continued investigation.

**Comment by rwjblue** [comment] 2016-04-14 01:52
Having seen no additional reports, I believe this issue is likely fixed (either by an unrelated change in Ember or by the browser vendor).  Closing...

**Closed by rwjblue** 2016-04-14 01:52 UTC
