### ISSUE TITLE
Ember.js + prototype.js conflict

### ISSUE THREAD

**Issue by pomm0** [emberjs/ember.js#14955] opened 2017-02-24 07:42 UTC
Hey,

we want to add a Ember.js-App to a existing site. The app is something like a widget what you integrate into your website. The website has prototype.js version 1.7.1 and our Ember.js-App has version 2.6 (but I tried 2.11 as well and the ember-twiddle uses 2.11).

Our problem is, methods like .clear on Ember.A() does not work properly because prototype.js overwrites them somehow:

**Twiddle with prototype.js:** https://ember-twiddle.com/20eb8e63e28f608411c315433811f5fe?openFiles=controllers.application.js%2C

**Twiddle without prototype.js:** https://ember-twiddle.com/9c4574a3ee1c4d9e7558b5b0b112abeb?openFiles=controllers.application.js%2C

If you click the "Output the .clear function to console" button to output the code of the .clear function. Those are different.

Is that intended or maybe a bug? Or am I missing something? How can i make that work properly?

Thanks

**Comment by locks** [comment] 2017-02-24 10:30
This is not a bug but a side effect of both libraries extending the Array prototype with the `clear()` method.
Hm, I'm not sure how to effectively solve this.

**Comment by rwjblue** [comment] 2017-02-24 12:50
You have to disable prototype extensions in the running application. There is an addon that you can use to make it very simple (it is included by default in all addons generated so that they ensure they function properly with Embers prototype extensions disabled).

**Comment by rwjblue** [comment] 2017-02-24 12:51
https://github.com/ember-cli/ember-disable-prototype-extensions

**Comment by locks** [comment] 2017-02-24 12:52
@rwjblue how do you subsequently clear the array in a KVO-compliant way?

**Comment by rwjblue** [comment] 2017-02-24 12:52
Closing this issue though as it is not a bug, but rather a SO type of question.

**Closed by rwjblue** 2017-02-24 12:52 UTC

**Comment by pomm0** [comment] 2017-02-24 13:32
I tried `EXTEND_PROTOTYPES: false` already but i'm not able to get it working.

Shouldn't that be enough in the config/environment.js:

`ENV = {
  EmberENV: {
    EXTEND_PROTOTYPES: false
  }
}`

Even with the addon installed i'm not able to get it working.

[Updated twiddle](https://ember-twiddle.com/c667e93c5a78b3bcc9cf130ff31dd8f3?openFiles=twiddle.json%2C) with `EXTEND_PROTOTYPES: false` set

**Comment by rwjblue** [comment] 2017-02-24 14:28
I see, thanks for the quick followup.

The issue is that Ember will not clobber what it considers "native" array methods with `Ember.A`. In your example, you are loading `prototype.js` before Ember, which means that [when Ember checks for which methods on an array are in conflict](https://github.com/emberjs/ember.js/blob/79d7dea2d6bdfc00b66f0cacb59b3b09ba3affb9/packages/ember-runtime/lib/system/native_array.js#L99-L105) it sees `.clear` (from `prototype.js`) and does not add it for `Ember.A()` usage.

The simplest solution to that is to load `prototype.js` _after_ Ember, however I ran into an issue in ember-twiddle when you do that (submitted https://github.com/ember-cli/ember-twiddle/pull/529 to fix it though) there (because now `$` is not jQuery).

A more complex solution would be to create your own `Ember.A` alike, that is aware that `.clear` should be clobbered.

**Comment by rwjblue** [comment] 2017-02-24 14:28
See https://canary.ember-twiddle.com/69cac8191ea8f98869513c76262dd99b?openFiles=twiddle.json%2C (uses canary version of ember-twiddle with https://github.com/ember-cli/ember-twiddle/pull/529 included).

**Comment by pomm0** [comment] 2017-02-24 17:09
Thank you so far for helping! But we do not have access to the website where it gets integrated (is a widget) so i can not switch the script includes. I will try some workarounds for that. Thanks!
