### ISSUE TITLE
[Bug] No acceptance test being generated

### ISSUE THREAD

**Issue by SPOOCQ** [emberjs/ember.js#20103] opened 2022-05-29 12:46 UTC
### 🐞 Describe the Bug
Following the guide I tried to generate the acceptance test using

ember g acceptance-test super-rentals

but no file is being generated.

### 🔬 Minimal Reproduction
Open terminal
cd [project_folder]
ember g acceptance-test super-rentals
watch message
try to open file as mentioned in the guide, but file is missing

### 😕 Actual Behavior
not doing anything except for telling me that it 'installed acceptance-test'

### 🤔 Expected Behavior
Files being generated as mentioned in the tutorial

### 🌍 Environment

- Ember: 4.4.0
- Node.js/npm: 12.22.5
- OS: linux
- Browser: chromium

**Comment by bertdeblock** [comment] 2022-05-29 13:40
Hi, this is a duplicate of https://github.com/emberjs/ember.js/issues/20088 I think. This was already fixed, but we need a new release.

**Comment by SPOOCQ** [comment] 2022-05-29 13:43
Must have missed this.
I'll just create the files by myself in the meantime and wait for a fixed release.
Thanks for the quick answer.

**Comment by bertdeblock** [comment] 2022-05-29 14:18
No worries, thanks for reporting!

**Comment by bertdeblock** [comment] 2022-05-31 15:47
@SPOOCQ `ember-source@4.4.1` was released containing the fix.

**Closed** 2022-06-01 08:31 UTC
