### ISSUE TITLE
Rendering of nested templates broken in 2.8

### ISSUE THREAD

**Issue by splattne** [emberjs/ember.js#14288] opened 2016-09-14 07:42 UTC
I have an issue after upgrading Ember from 2.7.3 to 2.8.0 in one of my apps.

The **application.hbs template isn't rendered** in nested routes anymore. I could reproduce it in this Ember Twiddle:

https://ember-twiddle.com/b9e00452071ad8e4e629a934cfbbb1de?openFiles=routes.base.js%2C&route=%2Fbase%2Ftest

router.js:

```
...
Router.map(function() {
  this.route('base', function() {
    this.route('test');
  });
});
...
```

application.hbs:

```
<h1>Rendering Nested Templates in 2.8</h1>

<h2>Sidebar outlet</h2>

<div>
  {{outlet "side-bar"}}
</div>

<h2>Main outlet</h2>

<div>
  {{outlet}}
</div>
```

routes/base.js:

```
export default Ember.Route.extend({
  renderTemplate() {
    this.render('base.side-bar', { into: 'application', outlet: 'side-bar' }); 
  }
});
```

If you go to the `/base/test` route it only shows the content of the main outlet.

![wrong](https://cloud.githubusercontent.com/assets/200860/18503837/55d3b74e-7a5f-11e6-883f-631f144c81bc.png)

If you change the Ember.js dependency in Twiddle to 2.7.3, it works as expected.

![correct](https://cloud.githubusercontent.com/assets/200860/18503827/50b7a4a0-7a5f-11e6-94ca-17b481e6b232.png)

**Comment by rwjblue** [comment] 2016-09-14 11:27
Thank you for reporting! I'll try to poke at it a bit this morning to determine what has changed to cuase this.

**Comment by trentmwillis** [comment] 2016-09-14 18:35
Poked at this a bit and if you call `this._super(...arguments)` in the `renderTemplate` method, everything works as expected. Trying to figure out why the change in behavior. @rwjblue can you comment on whether it is expected to need to call `_super` for this method? [The docs are a bit ambiguous](https://github.com/emberjs/ember.js/blob/fb4ee34f2ecfbcef0b2435f219becf6c897a0524/packages/ember-routing/lib/system/route.js#L1823-L1853) as to whether you should.

**Comment by krisselden** [comment] 2016-09-14 18:39
This example is buggy

**Comment by krisselden** [comment] 2016-09-14 18:44
Every child route has to render a its route's template into the parent template's main outlet, by not calling this._super() you are not doing this.  I think it is by chance not design that this even happens to work today.

I have many doubts whether this should be fixed.

**Comment by rwjblue** [comment] 2016-09-14 18:57
Thanks for reviewing @krisselden and @trentmwillis! 

I'm going to go ahead and close this for now, but we can reopen if calling `this._super` is not all that is needed.

**Closed by rwjblue** 2016-09-14 18:57 UTC
Labels: Regression

**Comment by splattne** [comment] 2016-09-14 19:17
Sorry guys for having wasted your time on this. I wasn't aware of having to use `this._super(arguments)`.

Thanks!

**Comment by rwjblue** [comment] 2016-09-14 19:23
No worries! Glad we got it straightened out...

**Comment by rmachielse** [comment] 2016-09-16 08:04
We are also having problems with some a nested route using a named outlet on Ember 2.8. In our case nothing except the root element is rendered to the dom at all as soon as we enter the route (not even the parent elements).

Adding `this._super()` in `renderTemplate` indeed solves the problem. It seems a bit strange however, since the parent function only calls `this.render();` which we are already calling from the overridden function.

**Comment by rwjblue** [comment] 2016-09-16 13:20
@rmachielse - Would need a demo to really understand..

**Comment by rmachielse** [comment] 2016-09-16 18:04
I understand, unfortunately I haven't been able to reproduce it in a clean app yet. I will spend some more time on that soon!
