### ISSUE TITLE
Render "into" named outlet in application route broken - Uncaught TypeError: Cannot read property 'routeName' of undefined

### ISSUE THREAD

**Issue by andrewobrien** [emberjs/ember.js#10428] opened 2015-02-12 00:53 UTC
Here is the broken version on Ember 1.12.0-beta.1+canary.61ef0d2b, Its also broken on latest beta release. 
"Uncaught TypeError: Cannot read property 'routeName' of undefined"
http://emberjs.jsbin.com/taqamo/11/edit

And the code that's causing it:
```
if (into && into === parentRoute(route).routeName) {
      into = undefined;
}
```
And a working bin with Ember "1.10.0"
http://emberjs.jsbin.com/taqamo/9/edit

```
var renderOptions = {
    into: options && options.into ? options.into.replace(/\//g, '.') : parentTemplate(route),
    outlet: (options && options.outlet) || 'main',
    name: name,
    controller: controller
};
```

In the working example it seems the code in renderOptions "into" returns application where as it gets set to undefined in the problem code, is there a reason for this? Am I missing something here?

**Comment by rwjblue** [comment] 2015-02-12 00:54
Duplicate of https://github.com/emberjs/ember.js/issues/10416.

**Closed by rwjblue** 2015-02-12 00:54 UTC
