### ISSUE TITLE
Addon treeforAddon has a new this

### ISSUE THREAD

**Issue by BryanCrotaz** [emberjs/ember.js#17229] opened 2018-11-26 06:03 UTC
in an addon `index.js`, it is expected that the hooks are called in order on a single instance of the addon.

However when `treeForAddon()` is called on an addon used as a dependency in another addon, the context is a new instantiation. So this doesn't work:

```
included(app) {
  // get something from app config
  this.featureEnabled = true;
}

treeForAddon(tree) {
  // expect this.featureEnabled to be true
  console.log(this.featureEnabled); // outputs 'undefined'
}
```

**Comment by rwjblue** [comment] 2018-11-26 11:46
This seems like an ember-cli issue (not a bug in Ember itself), mind refiling over in ember-cli/ember-cli instead? I’d also like to see a reproduction, as I would expect included to have been fired before any treeFor* hooks.

**Comment by pixelhandler** [comment] 2018-11-30 16:44
@BryanCrotaz would you mind closing this after re-posting on https://github.com/ember-cli/ember-cli/issues

**Comment by pixelhandler** [comment] 2018-12-28 19:32
@BryanCrotaz did you post the issue on ember-cli's repo?

**Closed** 2022-04-12 07:09 UTC
Labels: Needs Submitter Response
