### ISSUE TITLE
action modifier doesn't fire when inside shadow root

### ISSUE THREAD

**Issue by knownasilya** [emberjs/ember.js#18303] opened 2019-08-23 14:20 UTC
`<button {{action this.clicked}}>` doesn't work while `<button onclick={{action this.clicked}}>` and `<button {{on 'click' this.clicked}}>` does.

Reproduction https://github.com/knownasilya/ember-shadow-dom/blob/master/tests/dummy/app/components/test-shadow/template.hbs#L13

Where the contents inside `<ShadowDom>here</ShadowDom>` are rendered in a shadow root like so:

```hbs
{{#-in-element this.shadow}}
  {{yield}}
{{/-in-element}}
```

and the `this.shadow` is defined like so:

```js
    let selector = this.selector;
    let element = document.querySelector(selector);
    let shadow = element.attachShadow({ mode: 'open' });

    this.set('shadow', shadow);
```

**Comment by rwjblue** [comment] 2019-08-23 14:45
The way the `{{action` modifier works is by adding event handlers to the applications `rootElement` (most often `body` in non-tests), when the template will be rendered into a shadow root it is intentionally disconnected from the event bubbling that would eventually bubble to the document's `body` (or application `rootElement` if configured differently. This is a feature (of the shadow root system), not a bug. The reason `onclick=` works is because the event listener is attached directly to the element in question, and does not rely on any bubbling out of the shadow root.

The "correct" solution here would be to avoid both forms of `{{action` and use `{{on` universally.

**Comment by rwjblue** [comment] 2019-08-23 14:46
Since this isn't really a bug (and `{{on` works properly here already) I'm going to go ahead and close this, mostly as a "wontfix" because its _basically_ impossible to fix...

**Closed by rwjblue** 2019-08-23 14:46 UTC

**Comment by knownasilya** [comment] 2019-08-23 14:54
@rwjblue thanks for the answer and quick reply!
