### ISSUE TITLE
Nested #each on iOS8

### ISSUE THREAD

**Issue by jcohlmeyer** [emberjs/ember.js#5606] opened 2014-09-18 19:40 UTC
Nested #each loops in handlebars do not render in Safari in iOS 8. Cause white screen of death and nothing renders. Returns error in console: TypeError: Attempted to assign to readonly property.

Tried with Ember 1.7.0 and 1.8 beta

Example:
http://emberjs.jsbin.com/vecuz/1/

**Comment by cjroebuck** [comment] 2015-03-08 01:22
Came here to say I'm seeing this issue with latest ember canary only on iPad though. Works ok on iPhone. 

Using iPad 4, iOS 8.1, mobile safari - white screen of death with 'TypeError: Attempted to assign to readonly property.':

![image](https://cloud.githubusercontent.com/assets/12208/6544006/789c1f76-c531-11e4-80f9-55f2bb4d1c80.png)

Ember info/versions:
![image](https://cloud.githubusercontent.com/assets/12208/6544001/44abe3a4-c531-11e4-80ad-4e970be6e42b.png)

**Comment by lolmaus** [comment] 2015-03-08 13:46
Can you please post a reproduction demo on JSBin?

**Comment by stefanpenner** [comment] 2015-03-08 14:03
@cjroebuck can you provide an example app? I can likely narrow it down extremely quickly

**Comment by cjroebuck** [comment] 2015-03-08 14:17
It's actually on our site https://bluebook.io right now, although this was with a beta version of ember-data (traffic is very slow right now so it's not a huge issue for us!)

**Comment by stefanpenner** [comment] 2015-03-08 14:27
Will take a look this afternoon.  I really wish apple would fix this bug....

**Comment by cjroebuck** [comment] 2015-03-09 13:15
@stefanpenner After realising that the bug affects iPhone < 6 users I've rolled back ember and ember-data to their latest beta releases and re-deployed.

The ember/ember-data canary version which is still displaying the bug can now be loaded at https://bluebook.io/?version=canary

Many thanks for taking the time to look into this issue.

**Comment by stefanpenner** [comment] 2015-03-09 19:13
@cjroebuck are you sure its actually `iPhone < 6` users? The bug ^^ is only armv7 devices, which doesn't include iphone 5s or 5

**Comment by stefanpenner** [comment] 2015-03-09 19:16
i have confirmed this is crashing a `iphone 5`

**Comment by stefanpenner** [comment] 2015-03-09 19:38
looks like we are blowing up around: https://github.com/emberjs/ember.js/blob/master/packages/ember-routing-htmlbars/lib/helpers/render.js#L165-L171

**Comment by stefanpenner** [comment] 2015-03-09 19:44
this appears to be the same issue, but different manifestation. I need to run to lunch, will continue the investigation later.

If someone can help me reduce the problem more, that would be great.

**Comment by OrKoN** [comment] 2015-03-09 21:04
@stefanpenner some of our users complained that the app does not work with iphone 5s and ipad running iOS 8.1.2 (white screen). Unfortunately, we have no means to debug the issue but it looks similar to this one.  We use Ember 1.9.1 though...

**Comment by stefanpenner** [comment] 2015-03-09 21:33
@OrKoN hmm, seems likely... This bug is rough, silly apple.

**Comment by stefanpenner** [comment] 2015-03-09 23:20
after many false starts, the problem is hilariously obvious. Our, use strict remover isn't removing the 'use stricts' cc @rwjblue

**Comment by rwjblue** [comment] 2015-03-09 23:39
ugh

**Comment by rwjblue** [comment] 2015-03-10 01:45
@stefanpenner - After review of the `ember.prod.js` output for the following builds:

* [canary](http://builds.emberjs.com/canary/ember.prod.js)
* S3 copy of [v1.11.0-beta.5](http://builds.emberjs.com/tags/v1.11.0-beta.5/ember.prod.js)
* Bower copy of [v1.11.0-beta.5](https://github.com/components/ember/blob/1.11.0-beta.5/ember.prod.js)

The modules containing `REMOVE_USE_STRICT: true` definitely have `'use strict';` removed. We do not (and did not ever) intend to remove `'use strict';` from every module, only those specific ones that we identified hit this JIT problem.

The build system seems to be operating as intended....

**Comment by stefanpenner** [comment] 2015-03-10 01:48
somehow, their prod build has `use strict`, as did ours at work. I'll investigate our end

![screen shot 2015-03-09 at 6 47 11 pm](https://cloud.githubusercontent.com/assets/1377/6567924/c2b3122a-c68c-11e4-9b26-2382c0423c24.png)

**Comment by stefanpenner** [comment] 2015-03-10 01:51
the builds in my app, and this app do contain 'use strict'

https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/utils.js#L1-L5

![screen shot 2015-03-09 at 6 50 30 pm](https://cloud.githubusercontent.com/assets/1377/6567957/2eac11fc-c68d-11e4-97a5-c163073695e5.png)

**Comment by rwjblue** [comment] 2015-03-10 02:36
@stefanpenner - Yes, you are correct. Something funky is going on.  I'm on it....

**Comment by stefanpenner** [comment] 2015-03-10 03:56
@cjroebuck thanks for bringing this to our attention.

@rwjblue we should see if we can find someone to own/champion a more rigorous cross platform testing experience. Insure if this would have caught it.

I know, we are getting many of the apps at work up to canary, to help catch these issues. I'll make sure an armv7 device is included.

**Comment by rwjblue** [comment] 2015-03-10 13:30
>  we should see if we can find someone to own/champion a more rigorous cross platform testing experience

I'd love to have this in general, but in this case Apple needs to fix their stupid JIT.  The issue has been outstanding for quite a while, with no movement on their side.  :rage:

**Comment by rwjblue** [comment] 2015-03-11 01:33
Submitted https://github.com/emberjs/ember.js/pull/10604 to fix the latest round of issues...

**Comment by stefanpenner** [comment] 2015-03-11 05:54
should be fixed again on master.

**Closed by stefanpenner** 2015-03-11 05:54 UTC

**Comment by j-mcnally** [comment] 2015-03-11 06:02
Can this be tested via travis, or does anyone do CI for mobile devices?

**Comment by stefanpenner** [comment] 2015-03-11 06:19
> Can this be tested via travis, or does anyone do CI for mobile devices?

this needs to be tested on a armv7 device (or simulator) we have wanted saucelabs style testing for some time, just lack a champion to move it forward.

**Comment by stefanpenner** [comment] 2015-05-28 15:05
looks like a proposed fix to JSC has landed: https://bugs.webkit.org/show_bug.cgi?id=138038
for those interested, the identify issue and patch are extremely interesting I would suggest reviewing.

**Comment by stefanpenner** [comment] 2015-05-28 21:02
looks like the fix was accepted: http://trac.webkit.org/changeset/184960 we may see it in a seed late june/july

**Comment by borhub** [comment] 2015-05-29 04:59
@stefanpenner Great to hear and thanks for all your work on this!

**Comment by typeoneerror** [comment] 2016-08-24 05:29
Is there a current fix for this issue (I'm using Ember 2.4.3 and seeing this pop up with Mobile Safari iOS 8.2) or do we just recommend that users upgrade their OS?
