### ISSUE TITLE
[BUG routing] Transition to changed query params

### ISSUE THREAD

**Issue by vinilios** [emberjs/ember.js#10504] opened 2015-02-22 16:02 UTC
trying to transition to an updated query params state using `transitionTo` route method within the beforeModel hook, the transition promise seem to get rejected due to a kind of invalid state of handlerInfo objects. I'm not sure if its a bug or something that happens intentionally.

jsbin:
http://emberjs.jsbin.com/qojuve/1/edit?html,css,js,output

**Comment by locks** [comment] 2015-02-22 16:45
The JSBin doesn't accurately reproduce the bug that you mention.

**Comment by vinilios** [comment] 2015-02-22 21:55
@locks i checked on both chrome/firefox. The transition promise always gets rejected and additionally no url params are set on the window location.

**Comment by machty** [comment] 2015-04-27 23:18
This bug looks legit; I'll keep it around but it'll probably disappear in the midst of upcoming query params refactorings.

**Comment by machty** [comment] 2015-04-27 23:18
wrong button

**Comment by kmiyashiro** [comment] 2016-01-12 19:34
I think this is a dupe of #12169, which has more detail now.

**Comment by mmun** [comment] 2016-04-14 02:01
Closing as a dupe. Thanks @kmiyashiro.

**Closed by mmun** 2016-04-14 02:01 UTC
Labels: Bug
