### ISSUE TITLE
1.13 rerender function doest not call render function

### ISSUE THREAD

**Issue by xiujunma** [emberjs/ember.js#11668] opened 2015-07-07 00:17 UTC
```javascript
import Ember from 'ember';

export default Ember.Component.extend({
  render: function(buffer) {
     //
   },
   click: function(e) {
      this.rerender();
   }
});
```

when click the component, rerender will be called, but render won't be called.

This component is work well on previous version.

I don't know it is t a bug or feature?

**Comment by rwjblue** [comment] 2015-07-07 00:23
Duplicate of https://github.com/emberjs/ember.js/issues/11515.

**Closed by rwjblue** 2015-07-07 00:23 UTC
