### ISSUE TITLE
DEPRECATION: `lookup` should not be called on a Registry. Call `lookup` directly on an associated Container instead.

### ISSUE THREAD

**Issue by chrism** [emberjs/ember.js#10177] opened 2015-01-09 13:28 UTC
Hi,

After upgrading to

````
Ember             : 1.11.0-beta.1+canary.dca9c74d
Ember Data        : 1.0.0-beta.14.1
````

with HTMLBars i'm getting lots of deprecation notices like this...

````
DEPRECATION: `lookup` should not be called on a Registry. Call `lookup` directly on an associated Container instead.
`````

...but the stack doesn't really provide any way of helping me find where I need to update to code with the new style.

I remember reading about how this will be important as we move away from a registry to container(s)  - maybe from a Tom Dale blog post I read - but am I missing some documentation on how to address this message, or can anyone offer some advice how to fix this?

Thanks

**Comment by rwjblue** [comment] 2015-01-09 13:52
@chrism - This is coming from `lookup` calls on a registry and is most likely the result of calling `container.lookup` in an initializer. One easy way to find where deprecations are being triggered is to set `Ember.ENV.RAISE_ON_DEPRECATION = true;` which will throw an error instead of printing the deprecation to the console, then you can use the stack to determine who the offenders are in your app.

I am going to close this as a dupe of https://github.com/emberjs/ember.js/issues/10067 (basically the message being not helpful).

**Closed by rwjblue** 2015-01-09 13:52 UTC

**Comment by rwjblue** [comment] 2015-01-09 13:58
http://emberjs.jsbin.com/rwjblue/200/ is a demo of that flag. If you open up the dev tools and setup break on exceptions. You should be able to take a look at the stack, and see what is calling `container.lookup`.

**Comment by chrism** [comment] 2015-01-09 14:40
Hi thanks very much in @rwjblue that makes perfect sense.

I'm just trying out break on exceptions in Chrome to try to see the stack & find the container.lookups.
