### ISSUE TITLE
TransitionAborted when performing a full route transition with changed query params

### ISSUE THREAD

**Issue by skoryky** [emberjs/ember.js#5566] opened 2014-09-09 02:07 UTC
Why does a TransitionAborted error get thrown when performing a full route transition when changing query params?

I am working off of the "Opt-in to full transition via refresh()" example provided at the bottom of the query parameters Ember guide (http://emberjs.com/guides/routing/query-params/).

The only change I made was to log errors:

```
Ember.RSVP.configure('onerror', function(error) {
  Ember.Logger.assert(false, error);
});
```

Here is an updated JS Bin: http://jsbin.com/kinajoginedo/1/edit?console,output

If you click the "Change it" button, you'll see a TransitionAborted error thrown in the console.

I've been trying to upgrade Ember in my app from 1.7.0-beta.1+canary for some time now, but many of my QUnit tests fail when I run them all together. Most of my tests are fine if I run them in isolation. I suspect the TransitionAborted errors may be causing the test failures. However, I'm not sure if TransitionAborted exceptions are normal when performing full transitions. If anyone can confirm one way or the other, that would be very helpful in getting to the root cause of my problems, whatever they might be.

**Comment by btecu** [comment] 2015-03-06 13:41
I'm running into this issue with Ember 1.11.0-beta.4. Updates?

**Comment by gorandev** [comment] 2015-03-13 04:48
Facing this issue too. It only bugs me because it gets logged as an error -- works fine otherwise (I'm doing pagination and the pages change and everything works fine).

**Comment by tim-evans** [comment] 2015-03-17 15:22
Seeing this on 1.11.0-beta.1+canary.26c1084c.

**Comment by r4m** [comment] 2015-03-18 17:18
I'm facing this issue to and as @gorandev it is only logged but it does not compromise the app flow.

**Comment by tim-evans** [comment] 2015-03-18 22:34
Hmm...

This is the behavior that I'm trying to implement (which I'm not able to do at the moment):

A user can type (normally) in a search box, which refreshes the model of a route. Currently, if I swallow the TransitionAborted errors, the typing UI doesn't respond well and will replace the text box with the finished transition. I would prefer to discard requests that pile up rather than wait for them to resolve.

```javascript
export default Ember.Route.extend({
  queryParams: {
    q: { replace: true, refreshModel: true },
    sort: { replace: true, refreshModel: true },
    filter: { replace: true, refreshModel: true }
  },

  model: function(params) {
     return this.store.find('user', params).then(null, (error) => {
        if (error.message === "TransitionAborted") {
          return [];
        }
        throw error;
     });
  }
}
```

**Comment by gerry3** [comment] 2015-04-09 21:24
Seeing this on 1.11.1. App works fine other than logging this error.

**Comment by tcjr** [comment] 2015-04-21 23:31
I am seeing this same issue.  It accounts for nearly all my production "error" messages.  (I'm using Track:js)

I created an updated jsbin (Ember version 1.11.1):  http://jsbin.com/zewuda/1/edit?html,js,output

My only work-around right now is to hack the onerror function to not log the error if it is a TransitionAborted error.

**Comment by louy** [comment] 2015-06-02 20:04
I'm having the same issue, but `refresh()` is never called. It just aborts.

**Comment by tmayr** [comment] 2015-06-23 14:35
Same here in 1.13.3, @skoryky workaround works just fine for now.

**Comment by piotrze** [comment] 2015-09-04 06:55
Solution from @skoryky didn't work for me. I had to wrap refresh() into Ember.run.once to avoid TransitionAborted error(all in your router code).

```js
actions: {
  queryParamsDidChange: function() {
    Ember.run.once(this, this.refresh);
  }
}
```

**Comment by seawatts** [comment] 2015-09-08 22:45
@skoryky's workaround worked for me too on Ember 1.11.3 Thanks guys =)

**Comment by wolfbiter** [comment] 2015-10-13 21:43
@piotrze's solution almost worked for me. had to use `next` instead:

```
//in your router code

actions: {
  queryParamsDidChange: function() {
    Ember.run.next(this, 'refresh');
  }
}
```

**Comment by richmolj** [comment] 2015-12-02 14:31
Looks like @piotrze's `Ember.run.once` solution worked for me on Ember 1.13, but no longer works on 2.2

**Comment by gerry3** [comment] 2015-12-02 17:41
@richmolj the r4m workaround above still works on 2.2

**Comment by izelnakri** [comment] 2016-06-24 08:28
Please reopen this issue. It still occurs on Ember 2.6 when the queryParams have refreshModel: true

**Comment by medokin** [comment] 2016-07-28 12:14
Ember 2.7

`queryParamsDidChange` fires multiple time even if nothing has changed, thats why I additionally compare old and new queryParams values.

```js
    queryParamsDidChange: function(a,b) {
      // Compare to prevent refresh if nothing changed
      if(
        a.page === b.page &&
        a.selectionId === b.selectionId &&
        a.sort === b.sort &&
        a.sortDirection === b.sortDirection
      ){
        return;
      }

      Ember.run.next(this, 'refresh');
    }
```

**Comment by jesseditson** [comment] 2016-09-16 23:10
FYI - still seeing this in `2.8.1`, I worked around it by debouncing the refresh calls - here's a Mixin that you can add to routes that use `refreshModel: true`:

```javascript
import Ember from 'ember';

/**
 * Debounce Refresh
 * Ember routes with queryParams that have refreshModel double-trigger a refresh:
 * see: https://github.com/emberjs/ember.js/issues/5566
 *
 * Mix this in to routes that define queryParams[param].refreshModel to avoid the TransitionAborted error thrown when double-triggering refreshes.
 */
export default Ember.Mixin.create({
  refreshDebounceThreshold: 100,
  refresh() {
    Ember.run.debounce(this, this._super.bind(this, ...arguments), this.get('refreshDebounceThreshold'));
  }
});
```

**Comment by supersabillon** [comment] 2016-10-24 18:46
@jesseditson thanks for the Mixin. There's one issue, when you change the query params of a route, transition to a different page, and then come back to the page with the query params the refresh happens again and causes the error.

**Comment by jesseditson** [comment] 2016-10-24 19:19
@supersabillon ah, when resuming with "sticky" QPs? I've disabled those in the app I'm using, I wonder if that's why I didn't come across that case.

**Comment by vlascik** [comment] 2017-01-22 13:45
still happening in 2.11.0-beta.2.

**Comment by denzo** [comment] 2017-02-16 13:48
Yes, is still happening to me also in `2.10.0` :(

**Comment by aaxelb** [comment] 2017-10-11 19:11
Was this silently fixed in 2.12.0?
https://github.com/emberjs/ember.js/commit/cee49a315b2467f7c1a9193546a51e427dc72bd6

**Comment by wagenet** [comment] 2017-10-11 23:25
@aaxelb not intentionally, but possibly it did fix it. Is the behavior correct in 2.12?

**Comment by rwjblue** [comment] 2017-10-13 13:46
I reproduced the JSBin (with current Ember versions) and it does indeed seem to be fixed.

https://jsbin.com/cajiji/edit?html,js,output

closing....

**Closed by rwjblue** 2017-10-13 13:46 UTC
Labels: Bug, Query Params

**Comment by cesarluis13915** [comment] 2018-10-12 16:46
This error is throwing too on doing this in a route:

`return this.transitionTo(my_route)`

Removing return keyword, fix it.

**Comment by cadeParade** [comment] 2018-11-02 22:03
This was happening to me in a test only, specifically after upgrading tests to the new(ish) RFC. As @cesarluis13915  said, removing `return` fixed my test.

**Comment by enspandi** [comment] 2019-07-03 15:16
Occured in our project with the Ember 3.11.1 upgrade.
`return this.replaceWith(null, id);` makes the test fail with `TransitionAborted`
`this.replaceWith(null, id);` succeeds :man_shrugging:

**Comment by KalachevDev** [comment] 2019-07-05 14:55
https://github.com/emberjs/ember.js/issues/18177 is this the same?

**Comment by allthesignals** [comment] 2019-07-17 18:07
I'm seeing this appear in error tracking service, Sentry

**Comment by wagenet** [comment] 2019-07-17 18:53
@rwjblue ping

**Comment by mehulkar** [comment] 2019-09-20 07:55
Ran into this in 3.11.1. Re-opened in #18416 with a repro. Was able to workaround with @skoryky's solution (thanks!), except that `queryParamsDidChange` isn't an action now, it's just a method.
