### ISSUE TITLE
[Regression]? Component is rerendered when tracked computed is not changed in 3.17.

### ISSUE THREAD

**Issue by stukalin** [emberjs/ember.js#18937] opened 2020-04-28 07:52 UTC
Found something in 3.17 which I consider a regression. Happens in both glimmer and classic components. Say we have a computed which returns an array. This computed depends on another property, but the array is the same all the time. Something like this:

```
export default class extends Component {
  testArray = A([
    'one',
    'two',
    'three'
  ]);

  @tracked val;

  @computed('val')
  get myComputed() {
    return this.testArray;
  }
}
```

Now if I consume this `myComputed` in a component and I somehow manage to update the `val` then the `myComputed` will invalidate but it still will return the same `testArray`. In 3.16 this doesn't cause the component to re-render, but in 3.17 it does. It could be traced by putting the `{{log}}` helper into the loop:

```
{{#each this.myComputed as |value|}}
	{{log value}}
	{{value}}
  <br>
{{/each}}
```

I've created a twiddle to highlight the problem: https://ember-twiddle.com/87769e67be828d914484d36d9aa1e652 (make sure the correct ember version is selected). Could you please review and confirm the issue?

In the case you say this is somehow expected (I doubt that, but....) could you tell me a way of reworking it so it behaves like it used to do in the 3.16.

**Comment by pzuraq** [comment] 2020-04-29 00:39
There are some instances of timing changes in general since we added autotracking, but we did not consider them breaking because we have never guaranteed timing semantics (and they have changed in the past). Is there a specific issue that this is causing that you would like to solve?

More generally, we are moving away from the ability to depend on values that you do not consume in getters in general (so depending on `val` even if it isn't used), so if you're depending on that functionality I'd recommend refactoring away from it.

**Comment by stukalin** [comment] 2020-04-29 04:05
@pzuraq well the more specifically we have the following setup: we do depend on a date value, but then in a getter we calculate a month from that date and then we grab an array depending on that month. So, a user navigating through the same month will always receive the same (cached) piece of data. This piece is rather large, so when a component re-renders on each such change the performance really seems degraded.

**Comment by pzuraq** [comment] 2020-04-29 21:55
Actually just realized you said this was 3.16 to 3.17 and that does seem like more of a regression to me, I wouldn't have expected anything to change in autotracking between those versions. Have you confirmed this regression occurs in production builds? Does it just affect `{{log}}`? (log and debugger are special, due some unusual things)

**Comment by stukalin** [comment] 2020-04-30 03:46
@pzuraq I do see certain glimps and jumps in our application when I use the 3.17. When I change back to 3.16 it works without any and the UI is really smooth. That's why I decided to see what happens there. Then I saw the difference on the _Render Performance_ tab of the Ember Extension: in 3.17 child components were re-rendered whereas in 3.16 they were not. Then I tried the `{{log}}`, which confirmed the case and then I've created this small twiddle to narrow it down.

**Comment by pzuraq** [comment] 2020-09-23 00:00
Sorry I haven't been able to get back to you on this, I've been heads down for quite a while now. I wanted to ask a few followup questions here:

1. Is this still a problem in Ember 3.20? On master?
2. Were these rerenders occurring in a production build? Not development?

**Comment by stukalin** [comment] 2020-09-23 08:38
@pzuraq phew it was quite long time ago. Just tried to recall the details of the issue but I don't seem to remember any more :D 
This ember twiddle is still there; unfortunately there is no option to select the 3.20, but the issue is still there for 3.18.
And from old conversation history with a collegue I could find out that this was a dev issue. Anyways this doesn't cause any issues for our production now.

**Comment by locks** [comment] 2023-07-22 21:44
Closing as no longer relevant since the framework has moved on to tracked properties. Thank you for reporting the issue and the following discussion!

**Closed by locks** 2023-07-22 21:44 UTC
