### ISSUE TITLE
onEventName= vs. oneventname= regression in Ember 3.1-beta

### ISSUE THREAD

**Issue by mwpastore** [emberjs/ember.js#16311] opened 2018-03-02 17:24 UTC
The following template code works in 3.0 (and as far as I know Ember 1.x and 2.x) but not in 3.1-beta:

```hbs
<button onClick={{action 'foo'}}>
```

Down-casing the attribute to `onclick` "solves" the problem. 

Developers coming from other frameworks or vanillajs probably expect this to work. And whether it should or shouldn't work, it will probably break some folks upgrading to Ember >3.0.

**Comment by rwjblue** [comment] 2018-03-02 17:38
Thanks for reporting! I'm not 100% sure if this will end up being considered a regression or not, I'll try to discuss in more detail with the team and decide...

**Comment by tomdale** [comment] 2018-03-02 20:09
Per discussion at the core team meeting, we want to treat this as a regression. Off the top of my head I'm not aware of any changes in the VM that should have caused this, so will need some investigation.

**Comment by rwjblue** [comment] 2018-04-17 13:47
@st-h - TBH, we mostly need someone to dig and help track down why we regressed. Perhaps a great first step is submitting a failing test case PR both here and in glimmer-vm...

**Comment by st-h** [comment] 2018-04-19 12:48
@rwjblue reporting back from my first extensive debugging adventure through the glimmer and ember internals :neckbeard: 
I tried to create a test first, however my efforts to write something that matches the current implementations only showed that the current test setup happily accepts any diffs in case sensitive bindings (both in glimmer.vm and ember.js). Probably the test helpers should be refined... However, there are too many internals involved and I don't know the codebase well enough to make a substantial decision here.
So, I continued to find out what is actually going wrong here and I believe to have found the offending [commit](https://github.com/emberjs/ember.js/commit/30bb21fa907f16a736599277911ecf41cc30a1ad) / [code](https://github.com/emberjs/ember.js/blame/master/packages/ember-glimmer/lib/utils/bindings.ts#L66). This essentially changed using the lower case name of the attribute when setting it within the [install method](https://github.com/emberjs/ember.js/blob/master/packages/ember-glimmer/lib/utils/bindings.ts#L113)
Yet again, being very new to the ember/glimmer internals, I don't feel comfortable deciding what is the best way to fix this. I am happy to help getting this done with a little support though.

**Comment by rwjblue** [comment] 2018-04-19 13:32
Hmm. That change definitely does odd. Do Ember's own tests pass if you remove that `.toLowerCase()`?  I'm unsure how this could be the cause of `<button onClick=(action 'foo')></button)>` not working because it seems like it would only be related to component's attribute bindings right?

**Comment by st-h** [comment] 2018-04-19 14:08
@rwjblue maybe I should have posted that to the [svg related issue](https://github.com/emberjs/ember.js/issues/16477), as I am not totally sure if both issues really do have the same cause. However, I was specifically looking why an attributeBinding like `viewBox` would end up as `viewbox`.
If I do make requested change there is one test which fails, which specifically [tests for case insensitivity](https://github.com/emberjs/ember.js/blob/master/packages/ember-glimmer/tests/integration/components/attribute-bindings-test.js#L238). Honestly this seems a little odd to me, since I am not used to js being case insensitive.

**Comment by st-h** [comment] 2018-04-19 15:36
@rwjblue I believe this issue is fixed by this [commit](https://github.com/glimmerjs/glimmer-vm/commit/d285724874b1e29de1e15c064b0e497ae6cc8c35). 
However, I was only able to write a test within ember.js and not glimmer.vm so far. Is there anything I can look at for some inspiration?

This is what I have done for ember.js within event-dispatcher-test.js:

```
    ['@test case insensitive event handler'](assert) {
      let receivedEvent;

      this.registerComponent('x-bar', {
        ComponentClass: Component.extend({
          clicked(event) {
            receivedEvent = event;
          },
        }),
        template: `<button id="is-done" onclick={{action clicked}}>my button</button>`,
      });

      this.render(`{{x-bar}}`);

      this.runTask(() => this.$('#is-done').trigger('click'));
      assert.ok(receivedEvent, 'change event was triggered');
      assert.strictEqual(receivedEvent.target, this.$('#is-done')[0]);
    }

    ['@test case sensitive event handler'](assert) {
      let receivedEvent;

      this.registerComponent('x-bar', {
        ComponentClass: Component.extend({
          clicked(event) {
            receivedEvent = event;
          },
        }),
        template: `<button id="is-done" onClick={{action clicked}}>my button</button>`,
      });

      this.render(`{{x-bar}}`);

      this.runTask(() => this.$('#is-done').trigger('click'));
      assert.ok(receivedEvent, 'change event was triggered');
      assert.strictEqual(receivedEvent.target, this.$('#is-done')[0]);
    }
```

However, I am not sure if that is the best place for such a test. Maybe that can even be simplified. Please let me know if I should submit a PR for that, or if it should be done differently.

**Comment by st-h** [comment] 2018-04-19 17:38
this seems to be quite a though one, as there have been several non trivial changes in how glimmer vm handles attributes. I tried to debug through some changes and it seems that this issue appears after the DynamicProperty is no longer instantiated with a property manager that contains the normalized attribute. By now this exceeds all my knowledge about glimmer, its intention and development. Hopefully this helps in resolving this issue though. However by now I am pretty sure that other than what we expected, this issue is not related to #16477

**Comment by rwjblue** [comment] 2018-04-19 19:16
@st-h - Those tests look great, a failing test PR would be perfect! 👍

**Closed** 2018-04-21 14:56 UTC
Labels: Bug
