### ISSUE TITLE
"ember generate route about" is not working

### ISSUE THREAD

**Issue by SaimonL** [emberjs/ember.js#13788] opened 2016-07-04 13:23 UTC
Hi I was following the document then I came across the section "https://guides.emberjs.com/v2.6.0/tutorial/routes-and-templates/". 

Then I tried the command
```bash
ember generate route about
```
and I end up getting the error
```bash
installing route
Unknown blueprint: route
```

Here is some information:
I am using Ubuntu 14.04 (64-Bit). 
I have intalled Node.js from their official website (I did "apt-get remove nodejs" first).
I am using **ember-cli-emblem**
```bash
ember -v
ember-cli: 2.6.2
node: 4.4.7
os: linux x64
```

Here is my **bower.json**
```json
{
  "name": "super-rentals",
  "dependencies": {
    "ember": "~2.6.0",
    "ember-cli-shims": "0.1.1",
    "ember-cli-test-loader": "0.2.2",
    "ember-qunit-notifications": "0.1.0",
    "bootstrap": "~3.3.5",
    "font-awesome": "~4.5.0"
  }
}
```

Here is my **package.json**

```json
{
  "name": "super-rentals",
  "version": "0.0.0",
  "description": "Small description for super-rentals goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.4.2",
    "ember-ajax": "^2.0.1",
    "ember-bootstrap": "0.8.0",
    "ember-cli": "2.6.2",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^5.1.6",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-emblem": "0.8.0",
    "ember-cli-htmlbars": "^1.0.3",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.4.0",
    "ember-cli-jshint": "^1.0.0",
    "ember-cli-qunit": "^1.4.0",
    "ember-cli-release": "^0.2.9",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.6.0",
    "ember-export-application-global": "^1.0.5",
    "ember-font-awesome": "2.1.1",
    "ember-load-initializers": "^0.5.1",
    "ember-resolver": "^2.0.3",
    "ember-welcome-page": "^1.0.1",
    "loader.js": "^4.0.1"
  }
}
```

**Comment by SaimonL** [comment] 2016-07-04 13:44
So what I found out is that by installing **ember-cli-emblem** the command lines changes.
When you run:
```bash
ember install ember-cli-emblem
```
The command changes towards emblem or something. Now I am trying to find the command that does **ember generate route about** in emblem command.

**Comment by leo** [comment] 2016-07-04 18:22
If this is a real bug, then it's related to [EmberCLI](https://github.com/ember-cli/ember-cli), not Ember itself. :blush:

**Comment by Serabe** [comment] 2016-07-05 12:34
Hello, @SaimonL.

Thank you for reporting this. Sadly, this only happens when adding `ember-cli-emblem`. There is even a similar issue open in that repo: Vestorly/ember-cli-emblem#41

I don't see any reference to ember-cli-emblem in the linked guide. If there is one, please, let the learning team know by opening an issue in emberjs/guides.

I am closing this since this is not a bug in ember itself, but in an addon.

Thank you for your report!

**Closed by Serabe** 2016-07-05 12:34 UTC

**Comment by locks** [comment] 2016-07-05 12:39
I just want to leave the extra note that since `ember-cli-emblem` is not a "core" package, updates might drag a bit, so using htmlbars is recommended.

**Comment by SaimonL** [comment] 2016-07-07 09:37
Thank you guys. Yes htmlbars it is, I do love HAML
