### ISSUE TITLE
Cursors jump to the end of an input when new value set

### ISSUE THREAD

**Issue by mixonic** [emberjs/ember.js#10481] opened 2015-02-17 17:01 UTC
Some demonstrations:

* [repro with canary](http://emberjs.jsbin.com/jolaboyiye/4/edit?html,js,output)
* [repro with beta](http://emberjs.jsbin.com/jolaboyiye/3/edit?html,js,output)
* [stable is fine](http://emberjs.jsbin.com/jolaboyiye/5/edit?html,js,output)

**Comment by rwjblue** [comment] 2015-02-17 18:29
Duplicate of #10449.

**Closed by rwjblue** 2015-02-17 18:29 UTC
Labels: Bug, Regression
