### ISSUE TITLE
Ember array acting wierd on insertAt (and replace)

### ISSUE THREAD

**Issue by poplevente** [emberjs/ember.js#16824] opened 2018-07-17 09:45 UTC
hi Guys,

since updating to ember 3.x i have alot of errors like method.apply is not a function. it’s happening within array actions like insertAt or replace. an example is below. I’ve tried to reproduce on ember-twiddle, but i cannot with simple arrays. i made a screenshot of my array and the thing i’m doing. i’m simply trying to insert to position 0, the item is already there, but got the error.

![image](https://user-images.githubusercontent.com/29889573/42809531-836b4076-89be-11e8-8392-e558cb639f62.png)

does anyone has an idea why could this happen? it worked well with ember 2.x, the error is at sendEven in ember-metal.

![image](https://user-images.githubusercontent.com/29889573/42809568-9691550a-89be-11e8-8f55-a3fc7f331c9a.png)

interesting, if i do a deep copy of the array, and do the same actions, it’s working. cannot find out why (yet)

Any help is welcome :)
Thanks!

**Comment by poplevente** [comment] 2018-08-13 10:56
I've no idea what guys you did in the ember array, but it's breaking at alot of places. now for example i'm using a simple .setObjects

the source array is a simple array, and the input again. mostly the input array is the same as the initials arrays content, so i'm not sure what's going on. I'm getting almost on all array functions the following error: 
application.js:87 Uncaught TypeError: method.apply is not a function http://localhost:4200/assets/vendor-2179354dfa3f4c4f1537ce1e3ba25a53.js 34255 14 TypeError: method.apply is not a function
    at sendEvent (ember-metal.js:223)
    at arrayContentWillChange (ember-metal.js:1991)
    at replaceInNativeArray (ember-metal.js:1935)
    at Array.replace (array.js:640)
    at Class.replaceContent (array_proxy.js:133)
    at Class.replace (array_proxy.js:115)

source
![array1](https://user-images.githubusercontent.com/29889573/44027821-7eddfd1c-9f00-11e8-9998-31ebe68fed34.png)

input
![array2](https://user-images.githubusercontent.com/29889573/44027839-8da28138-9f00-11e8-808e-d3438d7f8c2b.png)

i cannot reproduce this within ember-twiddle, so i'm not sure what's different on my application.
i see alot of issues here about sorting the arrays not returning array, and also other array related issues. did someone else had similar issues with arrays?

the only workaround is to make a deep copy of the object and using that further

**Comment by poplevente** [comment] 2018-08-27 06:48
@pixelhandler i could not reproduce it in a sample application unfortunately. yes, the only workaround is a deep copy or clone of the innitial array and using that further

i did ask on the community forums, but no answer unfortuantely so i was redirected here.

**Comment by rwjblue** [comment] 2018-09-02 14:31
I’m also wondering what events are being fired? Could be that you have some sort of array oberserver/listener that was broken by a change to array property change notifications...

Also, perhaps I missed it in the bug report, but what are the actual versions in question here? You mentioned that 3.x is broken and that 2.x works, but the real version numbers are much more useful...

**Comment by poplevente** [comment] 2018-09-02 14:47
sorry guys, i could not answer. the 2 version was 2.18 and it brake since version 3. (any of them) i dont have any observer as far as i know. tries to load the exact same values into an array in a simple application and there i cannot break it, so it's very wierd and impossible for me to reproduce ouside our systemm maybe if you guys can have an idea where it could brake based on the info i provided, we could narrow it. donno what to say for now.

**Comment by pixelhandler** [comment] 2019-01-25 18:34
@poplevente Just curious if you've resolved this issue or if perhaps an upgrade to a current Ember release has helped out. Without a reproduction it's not actionable for the community to investigate and fix. The two ways we start off verifying a bug is to create a simple reproduction and/or a failing test. Then someone can PR a proposed solution. I think we may need to close this out without an example reproduction.

**Comment by locks** [comment] 2020-04-19 01:04
Closing due to inactivity. Please re-open if you have a reproduction!

**Closed by locks** 2020-04-19 01:04 UTC
Labels: Needs Reproduction
