### ISSUE TITLE
Component's {{link-to}} tabindex doesn't toggle based on component property when tabindex starts at -1

### ISSUE THREAD

**Issue by melodyma** [emberjs/ember.js#11763] opened 2015-07-15 21:32 UTC
When tabindex starts at -1 for a {{link-to}} in a component and bound to a component's property, the {{link-to}}'s tabindex doesn't toggle based on the component's property even though the property is toggling. It's not updating the DOM.

See jsbin here for example: See jbin: http://emberjs.jsbin.com/zixohejive/edit?html,js,output

Proper tabindex toggling based on state is required for writing accessible components.

**Comment by raytiley** [comment] 2015-07-15 22:15
I imagine this has the same root cause as #11699 
Seems `link-to` has issues with updating attributes after initial render

**Comment by rwjblue** [comment] 2015-08-02 21:16
Closing this in favor of #11699 (trying to consolidate).

**Closed by rwjblue** 2015-08-02 21:16 UTC

**Comment by rwjblue** [comment] 2015-08-03 02:30
Fixed by https://github.com/emberjs/ember.js/pull/11960.

**Comment by rwjblue** [comment] 2015-08-03 02:30
Fixed by https://github.com/emberjs/ember.js/pull/11960.
