### ISSUE TITLE
Attributes with the value `null` are set differently between 3.0.0 and 3.1.0

### ISSUE THREAD

**Issue by blamens** [emberjs/ember.js#16792] opened 2018-07-04 13:48 UTC
Something seems to have changed between 3.0 and 3.1 in the way attributes are set. This issue came to light when I was invesitigating an issue with `ember-power-select`.

I was setting the `placeholder` attribute to `null` of an `input` element to make sure Internet Explorer did not fire any input events. This used to work with ember-source 3.0.0 but with ember-source 3.1.0 this stopped working.

My guess is that before, glimmer compared if the value being set was null or else just did not set it. Now I have to set it to undefined to make sure it does not get passed along.

I have created this tiny demo app to demonstrate this;
https://github.com/blamens/ember-ie11-power-select-test

You will see that input events will be triggered (because IE11 is doing that when the placeholder attr changes, in this case to `null`). If you change `ember-source` to 3.0.0 you'll see that no input events are triggered.

**Comment by cibernox** [comment] 2018-07-04 14:00
To explain further the problem with EPS. It turns out that in Ember 3.1 all `{{power-select-multiple}}` started to open immediately after being rendered in IE11.

That is because in IE11 there is a bug that triggers an `input` event when the placeholder of an input changes (either from the inside or from the outside). This but, stupid as it sounds, it's real, and to deal with it in EPS i detected IE11 and disabled placeholders in it: 
https://github.com/cibernox/ember-power-select/blob/44c84529b804762b8bc90e570bb8f1502f62a507/addon/components/power-select-multiple/trigger.js#L70-L72

But something must have changed in the way this works in Ember (probably even in glimmer) so setting this placeholder to null triggers an `input` event, and EPS is programmed to open when the user types on the searchbox. That is the reason why selects were opening immediately.

**Comment by rwjblue** [comment] 2018-07-09 15:17
Does the same issue happen in Ember 3.2?

**Comment by blamens** [comment] 2018-07-10 08:34
@rwjblue 3.2.0 has the same issue. Did not try any of the 3.3 beta's yet. This might be intended? The way `null` is handled?

**Comment by rwjblue** [comment] 2018-07-10 11:49
No, this doesn’t seem to be intended behavior to me. Ember 3.1 included a fairly major bump in the Glimmer version being used, which explains “why did it start at 3.1?”.

Do we have a minimal reproduction for this that we can dig into? I realize that the EPS issue largely only affected IE11, but it seems to me that the underlying issue should affect all browsers, right?

**Comment by blamens** [comment] 2018-07-17 07:45
Having a hard time reproducing the issue. I would expect the CP of the component in the twiddle below to only trigger on a `null` attr change in 3.0+ but it also triggers on ember versions below 3.0.

Ill investigate it some more with EPS to try and find out what's going on.

https://ember-twiddle.com/17f261e85103491fd12a44e641137f3b?openFiles=twiddle.json%2Ctemplates.components.test-component.hbs

**Comment by pixelhandler** [comment] 2018-10-19 16:04
I updated the twiddle for a current release, https://ember-twiddle.com/e6adf63e05450c6c8df4b6b9ae0b8bab?openFiles=components.test-component.js%2Ctemplates.components.test-component.hbs

**Comment by locks** [comment] 2019-05-30 16:45
If my understanding is correct, the Twiddles above to not appropriately reproduce the bug?
I am closing the issue and considering the bug either fix or no longer relevant. Let us know if you have new developments, though!

**Closed by locks** 2019-05-30 16:45 UTC
Labels: Has Reproduction, Needs Bug Verification
