### ISSUE TITLE
[Bug] 3.26: Router is not setup in a non-application test

### ISSUE THREAD

**Issue by grayt0r** [emberjs/ember.js#19494] opened 2021-04-11 15:50 UTC
### 🐞 Describe the Bug
Ember 3.24 included a change that meant the router service automatically worked in non-application tests (i.e. no need for `this.owner.setupRouter()`) - this worked great in 3.25, but seems to have regressed in 3.26.

### 🔬 Minimal Reproduction
Run the tests in this repo: https://github.com/grayt0r/ember-router-setup-in-tests.

Relevant code changes are [here](https://github.com/grayt0r/ember-router-setup-in-tests/compare/a98cb485063a12c17f4ed8ff42aed50fe8dc3f0e...52ed881a1324696a11991d7b0c7455d725652d02).

### 😕 Actual Behavior
The router is not setup and the test fails with an error (the exact error depends on which router method the component calls):

```
Cannot read property 'generate' of undefined
```

### 🤔 Expected Behavior
The router is setup, the link is correctly rendered and the test passes.

### 🌍 Environment

- Ember: - v3.26.1

### ➕ Additional Context
The test passes if I downgrade to 3.25.4 or if I add `this.owner.setupRouter()` to the test setup.

I think it might be related to this change: https://github.com/emberjs/ember.js/pull/19405.

/cc @Ravenstine @rwjblue

**Comment by rwjblue** [comment] 2021-04-12 21:03
Chatted with @Ravenstine about this today, they are going to work on a failing test reproduction first so we can figure out the right way to fix...

**Comment by chriskrycho** [comment] 2021-08-25 16:18
Hit this as a blocker for upgrading to 3.28. @Ravenstine did you ID the root cause and/or a path forward? Happy to collaborate on landing that!

**Comment by grayt0r** [comment] 2021-09-06 08:40
@chriskrycho sorry for the delay, but that fix appears to solve our issues, thank you very much! 🙌

**Comment by chriskrycho** [comment] 2021-09-06 12:00
Excellent!

**Comment by chriskrycho** [comment] 2022-06-03 20:39
Noticed this was still open despite the issue being resolved, just closed it!

**Closed** 2022-06-03 20:39 UTC
Labels: Bug
