### ISSUE TITLE
EXTEND_PROTOTYPES false by default.

### ISSUE THREAD

**Issue by jdalton** [emberjs/ember.js#9269] opened 2014-10-03 17:58 UTC
Currently Ember extends built-in prototypes of `Array`, `Function`, & `String` by default. Although Ember doesn't require these extensions and they [can be disabled](http://emberjs.com/guides/configuring-ember/disabling-prototype-extensions/), because they are enabled by default they tend to stay that way as evident by sites like vine, twitch, nbcnews, & discourse using the default settings.

The problem with adding methods like `Array#compact`, `Array#without`, `Array#uniq`, `Function#on`, & `String#capitalize` is that it increases the likelihood that they'll be used and cause problems/roadblocks for future built-in language extensions. For example, if ES7 tried to add `Array#without` that behaved in a different way than Ember's `Array#without` newer environments would get the built-in version while older would get Ember's causing an inconsistency and increased possibility of breaking thing. We've seen this recently with MooTools and `Array#contains`, but it's happened before with `Function#bind`, `String#contains`, and even DOM4 `Element#remove`.

**Comment by totaltrek** [comment] 2015-04-16 05:04
+1

Extending native prototypes is always dangerous and usually avoidable. I haven't yet used Ember, and this is the main reason why. I want my apps to gracefully *upgrade* as well as they gracefully *degrade*.

It seems to me that the reason prototypes are extended inside Ember is for syntactic sugar, which, let's be honest, is a fantastic goal. I just worry that it's following such a bad practice that the project itself will suffer in the long term.

As an example, let's look at `Function#property` -- the sugar that lets us "allow you to treat a function like a property" (quoting the docs). If ECMA version 7 defines a radically different `#property` on the native `Function` prototype, **all** ember apps risk immediate and permanent failure without crisis-mode maintenance. Instead of attaching `#property` why is the sugar not defined as follows?

```
App.model = Ember.Object.extend{
    oneAttr: 'a string',
    anotherAttr: [ 'an', 'array' ],
    someAttr: Ember.Property( function () {
        return this.anotherAttr.reverse().concat( this.oneAttr ).reverse()
    } )
}
```

This solves at least three problems: one, interfering with the native prototype; two, replacing sugar with safety and consistency; three, I'm not using Ember yet. The only problem remaining is the dusty example code on stackoverflow, random blogs, codeschool, and the like; most of which is already behind if not broken since it was published.

PLEASE NOTE: I'm not suggesting Ember.Property( *function* ) as an implementation target here. That is pseudocode provided merely to illustrate a potential solution. Looking at [ember-runtime/lib/ext/function.js](https://github.com/emberjs/ember.js/blob/v1.11.1/packages/ember-runtime/lib/ext/function.js#L16) it seems that `Function#property` might be fairly easily portable to a new Property class in the Ember namespace.

**Comment by OrKoN** [comment] 2015-04-16 07:31
@totaltrek 

I think what you suggest is already there (see Ember.computed):

```
var Person = Ember.Object.extend({
  firstName: 'Betty',
  lastName: 'Jones',

  fullName: Ember.computed('firstName', 'lastName', function(key, value) {
    return this.get('firstName') + ' ' + this.get('lastName');
  })
});

```

So one can easily avoid using prototype extensions. And projects such as ember-watson can convert your existing code if you wish: https://github.com/abuiles/ember-watson#ember-watsonconvert-prototype-extensions. Also see this https://github.com/emberjs/guides/pull/110

**Comment by stefanpenner** [comment] 2015-04-16 13:53
So we will be making an effort during the 2 -> 3x lifespan to mitigate the performance issues caused by totally disabling prototype extensions (which is one of the main blockers). There are several ergonomic things that will need to be improved as well, but nothing very hard just laborious. 


I have also thrown together a first pass at updating the guides to prefer non-prototype extension modes for the 2 most common ones. https://github.com/emberjs/guides/pull/110 

A future effort will dig into the array extensions (which are the most gnarly, and without them the current internals will suffer performance issues, but this can be mitigated)

**Comment by totaltrek** [comment] 2015-04-18 03:28
Thank you @OrKoN - I hadn't yet gotten familiar enough with Ember to track those docs down. Much obliged.

That's a huge help, @stefanpenner - thanks. It would have made reading the docs a much more exciting venture because it's obvious that these methods don't extend native prototypes.

As far as arrays are concerned, I'm not at all surprised at the pushback on removing the Array extensions. However, there's already a historical example for *everybody* to already use A([ ]) when they need an Ember-extended array, and that's the crash-and-burn of the early versions of Prototype.js, versus its much smarter (at the time at least) competitor, lodash.

True, forcing the A() call makes each of us work harder to do the same thing we'd currently do with a generic array, but wouldn't it make Ember apps more performant to not rely on this antipattern? If we only wrap our arrays when we know they're going to need extended methods, then any generic array can be left as-is, and suffer no performance drags due to extensions.

What parts of the internals will suffer from performance issues should the Array extensions be removed?

**Comment by stefanpenner** [comment] 2015-04-18 16:47
> What parts of the internals will suffer from performance issues should the Array extensions be removed?

Ya, this isn't entirely obvious but let me explain.

given the following:

```js
{{#each friends as  |friend}}
```

Ember essentially does (yes a liberal simplification):

1. instantiate a collection view
2. the collection view subscribes to the `friends` array change notifications
3. ... renders ...

turns out 2. is the offender, as ember assumes `friends` is a prototype extended array  or an ember array like (array controller/proxy etc). The code is something like `array.addArrayObserver(...)` which forces `Ember.A()` usage to ensure the prototype extensions.

If `EXTEND_PROTOTYPES === true`, `Ember.A` is essentially a no-op, but if it is false `Ember.A` applies all the array extension methods to each array instance it produces. This part is extremely slow.

I believe the resolution to this issue is simple, although it will require some grunt work. Ember internals, should not rely on `addArrayObserver` and the rest of the observable related methods existing on the prototype, rather they should take the same approach used for `set`/`get`.

To mitigate the need for all objects having `get`/ `set` ember internals do the following:

```js
get(obj, 'property');
set(obj, 'property', 'value')
```

rather then:
```js
obj.get('property');
obj.set('property', value);
```

This pattern can and should by applied to the observable array methods as well.

```js
addArrayObserver(array, ...);
removeArrayObserver(array, ...);
pushObject(array, obj);
```

**Comment by stefanpenner** [comment] 2015-04-18 16:49
Also, it is worth noting. `ember-addons` as of recently actually run with prototype extensions disable in there default dummy app harness. This ensure add-ons written are compatible with both modes.

**Comment by stefanpenner** [comment] 2015-04-18 19:13
i started work on this (just now) https://github.com/emberjs/ember.js/pull/10899

**Comment by rwjblue** [comment] 2015-08-09 17:39
Tracking in #10899 for the array scenarios.  We will still need to deprecate the usage of the various function prototype extensions, but that should be relatively simple to do (will need to be supported throughout the 2.x timeframe though).

**Comment by stefanpenner** [comment] 2015-08-09 21:13
With #10899 it will be easier and of less cost for people to do this opt-in. We can even strongly encourage it.

**Comment by locks** [comment] 2016-09-29 08:00
As mentioned, prototype extension is turned off by default in addons. Given this and the effort to not use extensions in Ember's source as well as carefully deprecating some of them, I'm closing this issue. Thanks for the discussion everyone, let's keep working towards a better story!

**Closed by locks** 2016-09-29 08:00 UTC
Labels: Needs Label Review, Needs Team Discussion, Old: BREAKING

**Comment by runspired** [comment] 2016-09-29 08:32
I haven't shipped an app with them on in forever. It's likely that we can full swap on the default for 3.0

**Comment by stefanpenner** [comment] 2016-09-29 17:17
> I haven't shipped an app with them on in forever. It's likely that we can full swap on the default for 3.0

Those apps will suffer from perf issues, until the array `.replace` and `didChange` hooks stuff is sorted out.

**Comment by bartocc** [comment] 2021-02-11 13:41
I am curious about the perf issues you were mentioning @stefanpenner, now that we have Octane, the new reactivity system, ES6 modules, etc… 🤔

Is it still usefull to have `EXTEND_PROTOTYPES` turned on by default in Ember apps?

**Comment by rwjblue** [comment] 2021-02-11 14:45
> Is it still usefull to have EXTEND_PROTOTYPES turned on by default in Ember apps?

It is still somewhat important for array in certain contexts. It depends how far down the Octane path really, you _could_ author without ever using `Ember.A()` (and without using `.pushObject` and friends). I'm just not sure that most folks actually do author that way.
