### ISSUE TITLE
[REGRESSION] In 1.13.x itemController not taken into account anymore

### ISSUE THREAD

**Issue by jdurand** [emberjs/ember.js#11552] opened 2015-06-25 03:27 UTC
As of ember.js 1.13.0, itemController is not taken into account anymore.
This occurs whether the itemController is set in the template (in the `each` loop, see JS Bins bellow) or in the ArrayController like this :

````
App.IndexController = Ember.ArrayController.extend({
  itemController: 'item'
});
````

JS Bins  :

ember.js 1.12.1
http://emberjs.jsbin.com/gunuzafaje/2/edit?html,js,output

ember.js 1.13.2
http://emberjs.jsbin.com/gunuzafaje/edit?html,js,output

**Comment by jaswilli** [comment] 2015-06-26 18:50
I was just about to open a new issue for something similar.  Same kind of thing, but if you `{{#each}}` over an array of controllers (not an ArrayController, an actual array of controllers) the action target is the controller of the context outside the each block in 1.13, while previously it would have been the current controller being iterated over.  I'm assuming it's because before legacy_each_view the controller would have been assigned to a view but now that's not the case...

JSBin for 1.12: http://emberjs.jsbin.com/vapiwe/4/edit?html,js,output

JSBin for 1.13: http://emberjs.jsbin.com/renabi/edit?html,js,output

**Comment by rwjblue** [comment] 2015-06-26 23:17
When using block params (or the deprecated `{{#each item in model}}` syntax) the context (and therefore action context) should absolutely be the same as outside the `{{each}}`. If 1.12 and lower did not exhibit this, then that was a bug (that is now fixed in 1.13).

Even though it is different behavior from prior versions, it is much more in line with the intent of keyword/block param concepts. I do not think this is a regression.

**Comment by rwjblue** [comment] 2015-06-26 23:33
The action targeting behavior that existed in versions prior to 1.13 were emergent behavior that was out of line with the intent of the non-context shifting versions of `{{each}}`.  I absolutely understand that this is a not uncommon pattern, but to fix it in 1.13 is a massive change (just to reintroduce what amounts to a bug!).

I am going to close this issue at this point, I truly hope that this decision makes sense and I'm happy to reevaluate with additional information.

**Closed by rwjblue** 2015-06-26 23:33 UTC

**Comment by mmun** [comment] 2015-06-26 23:54
The correct pattern is to send the action to the parentController together with any contextual data (like the item).

**Comment by jaswilli** [comment] 2015-06-26 23:58
👍 I don't want it "fixed," just putting it out there as something that I
noticed was broken during a 1.12 to 1.13 upgrade.

**Comment by mmun** [comment] 2015-06-27 00:00
@jaswilli Totally understand and it's greatly appreciated.

**Comment by jdurand** [comment] 2015-06-29 16:30
Ok, Good to know.
I'll refactor to something similar to what @mmun described.
Thanks.
