### ISSUE TITLE
Computed Properties broken with @each in 2.1.0

### ISSUE THREAD

**Issue by ameliadowns** [emberjs/ember.js#12475] opened 2015-10-12 18:50 UTC
Every computed property based on something using `@each` has broken with the 2.1.0 upgrade. Here are two examples: 

```javascript
  titleUniqueInCollection: Ember.computed('collection.sections.@each.title', function() {
    const sections = this.get('collection.sections');
    const sectionsWithSameTitle = sections.filterBy('title', this.get('title'));
    return sectionsWithSameTitle.length === 1;
  }),
```

```javascript
  sortedCollectionItems: Ember.computed('collectionItems', 'collectionItems.@each.rankPosition', function() {
    return this.get('collectionItems').sortBy('rankPosition');
  }),
```

The functions are no longer running as expected when an attribute is changed. 
Edited to reflect @stefanpenner's comment.

**Comment by stefanpenner** [comment] 2015-10-12 19:08
can you provide a jsbin or similar to demonstrate the issue in isolation.

Also some little things, hopefully to prevent future confusion:
* these aren't observers just computed properties
* they don't fire, rather in two in they will be marked as dirty, and if someone is interested they will consume (but only if someone like an active template chooses to)

**Comment by Kuzirashi** [comment] 2015-10-12 20:59
I wonder if this is related to #12328.

**Comment by ameliadowns** [comment] 2015-10-12 21:52
Here's a [JS Bin](http://emberjs.jsbin.com/nifowatepa/edit?html,js,output).

I added a broken computed property to the JS Bin from #12328

**Comment by stefanpenner** [comment] 2015-10-13 09:12
may be related to -> https://github.com/emberjs/ember.js/pull/11984

**Comment by adam-knights** [comment] 2015-10-23 07:26
Is this likely to be a 2.1 patch or should we plan to wait for 2.2?

**Comment by g-cassie** [comment] 2015-10-29 13:25
Also looking for guidance on here as to whether this will get patched or if we are looking at a fix for 2.2.  If there is anything that a novice can do to help move things along please let me know.

**Comment by rwjblue** [comment] 2015-10-30 23:35
@g-cassie - I haven't had time to really dig into this, but if a fix is proposed it will definitely be in 2.2 and depending on how invasive it is we could backport to 2.0/2.1 as needed.  The first step is that someone needs to figure it out and fix the bug.

**Comment by davidsteinberger** [comment] 2015-11-02 23:09
@ameliadowns @g-cassie I'm facing the same issue. Has either of you found a way to get the CP listening to `@each.property_name` to recompute?

**Comment by g-cassie** [comment] 2015-11-02 23:17
I just reverted to Ember 2.0 for the time being.  The problem seems to be isolated to 2.1

**Comment by krisselden** [comment] 2015-11-02 23:27
@stefanpenner have you or anyone on this thread confirmed that one of those PRs mentioned caused this issue?  I'll try to get to this soonish, it would help to have a failing test PR if anyone interested in this issue wants to see it addressed sooner.

**Comment by g-cassie** [comment] 2015-11-02 23:29
@krisselden I think #12538 is a failing test PR for this issue.

**Comment by ameliadowns** [comment] 2015-11-09 16:45
@davidsteinberger, I did the same as @g-cassie and reverted to Ember 2.0.

**Comment by stefanpenner** [comment] 2015-11-09 16:51
@krisselden no i have not yet had a chance.

**Comment by stevesims** [comment] 2015-11-12 15:19
+1 from me
We're seeing this issue in our codebase too - we've got a CP that has a dependent key of `record.relatedItem.@each.hasDirtyAttributes` which never updates. even when one of the `relatedItem` records definitely becomes dirty.
I suspect we'll need to revert to Ember 2.0 as well to work around this

**Comment by adam-knights** [comment] 2015-11-12 15:26
@g-cassie I took a look at your test and I think it fails in Ember 2.0 too so not sure it shows this issue.

**Comment by andorov** [comment] 2015-11-12 15:36
I have seen an issue with an array observer ('[]' and not '@each', but possibly the same root cause) not triggering in Ember 2.0.0

**Comment by stevesims** [comment] 2015-11-12 15:47
Further to my earlier note, as per https://github.com/emberjs/data/issues/3911 we've worked around by using a dependent key of `record.relatedItem.content.@each.hasDirtyAttributes`, so fortunately we haven't had to revert to 2.0
Would still be very nice to see this fixed.

**Comment by adam-knights** [comment] 2015-11-18 08:43
I tried Ember 2.2.0 today and we still see issues with @ each.

**Comment by toovy** [comment] 2015-12-08 10:03
I can confirm that this is still not working in v2.3.0-beta.2.

**Comment by adam-knights** [comment] 2015-12-08 10:15
I've played around with some of the unit tests at various levels and I have yet to find something that passes in ember 2.0 and fails in 2.1/2.2, including the pull request above. Has anyone been able to see this regression with non ember data objects?

**Comment by csantero** [comment] 2015-12-08 15:25
@adam-knights I believe this has been broken since at least 2.0. I tested a version of that PR against each major release and the last one it was working on was 1.13.

**Comment by adam-knights** [comment] 2015-12-08 15:47
@csantero I'd love to do some work to help identify the exact commit that did this but my issue was getting your PR to pass on 1.13, I never got it passing, did you modify it in some way?

**Comment by csantero** [comment] 2015-12-08 19:12
@adam-knights IIRC the file with related tests moved between then and now, but otherwise the test was the same.

**Comment by denzo** [comment] 2015-12-22 04:13
Here's a Twiddle
https://ember-twiddle.com/fe54e72463d0cd17d9a0

Does NOT work:
Ember: 2.1.1, 2.2.0,
Ember Data : 2.2.0

Does work
Ember : 2.0.2
Ember Data : 2.2.0

**Comment by stefanpenner** [comment] 2015-12-22 05:18
@krisselden are you able to investigate this, I believe it is related to you work.

**Comment by denzo** [comment] 2016-01-06 04:52
Any updates on this?

**Comment by gabrielrotbart** [comment] 2016-01-06 07:16
@denzo had a very quick chat with @rwjblue on slack and he confirmed that this is a very low priority since very few people are affected. We're a bit stuck as well, thinking about solutions.

**Comment by adam-knights** [comment] 2016-01-06 08:14
I'm surprised this is very low priority, surely this blocks anyone from moving up to Ember 2 who relies on items.@each.myProperty in a computed. There's a whole page dedicated to it's use in the guides.

**Comment by denzo** [comment] 2016-01-06 08:24
I am also very confused how the very core functionality is a very low priority.

**Comment by gabrielrotbart** [comment] 2016-01-06 08:43
Apparently most applications are not affected. I would imagine this issue would have gotten a lot more traffic otherwise.

**Comment by denzo** [comment] 2016-01-06 08:45
That's fair enough.

**Comment by runspired** [comment] 2016-01-06 08:57
A lot of devs steer clear of `@each` to begin with, and this issue appears to only affect the behavior when an arrayProxy is in use, and it has a known work around (use `.content` in your path).

**Comment by fsoumare** [comment] 2016-01-06 08:58
I had the same issue, I tried to look for help on Slack and I raised a ticked to StackOverflow:
http://stackoverflow.com/questions/34058202/model-computed-property-not-updating

I also helped someone else on SO who faced the same problem: http://stackoverflow.com/questions/34043595/computed-each-property-isnt-updated/34065878#34065878

Here is the JSbin I made to replicate the bug: http://emberjs.jsbin.com/keduco/edit?html,js,output

**Comment by adam-knights** [comment] 2016-01-06 09:06
@denzo Your twiddle is a great example of this bug - I tried adjusting it to be allItems.content.@each.status - to use the suggested .content workaround, but this doesn't work for me - do you see the same?

**Comment by balinterdi** [comment] 2016-01-06 09:24
@runspired How do you steer clear of `@each`? Do you just use `posts.[]` instead of `posts.@each.title`?

**Comment by sly7-7** [comment] 2016-01-06 10:41
@adam-knights using the `.content` in dep key workaround is working. I think you modify the wrong properties. The ones used in the template are located in the owner.js file.

This is working without using ember-data at all: https://ember-twiddle.com/5240dcb1bfbb9eee7f25
 
I think what @denzo demonstrated, is that this is has more to do with ember-data than with ember itself. (even using an array proxy with pure ember object is working).

Interrestingly, using an `{async: false}` relation makes the filter working correctly. 
The issue seems like related to: https://github.com/emberjs/data/issues/4046, and the use of PromiseManyArray

**Comment by workmanw** [comment] 2016-01-06 11:53
Our app is effected by this. I guess I didn't realize that this issue would be prioritized based on the number of people who have commented on an issue. If that's the case I would have commented earlier.

**Comment by fivetanley** [comment] 2016-01-06 15:17
I did a bisect of this, and this commit appears responsible for the regression. https://github.com/emberjs/ember.js/pull/12005

**Comment by adam-knights** [comment] 2016-01-06 15:46
In the code comments of https://github.com/emberjs/ember.js/pull/12005 he says that the change could cause issues for people who set `content` in `extend` - is it possible Ember Data does something badly that this commit has shown up?

**Comment by rwjblue** [comment] 2016-01-06 16:30
Do we have a failing test PR for this issue? 

@ef4 - Do you have any time to look into this?

**Comment by csantero** [comment] 2016-01-06 16:53
@rwjblue #12622 contains a failing test for `Ember.computed.filterBy`.

**Comment by runspired** [comment] 2016-01-06 17:29
@workmanw you can steer clear in most cases, but for the most part I'm simply pointing out that this isn't likely to be as wide spread as you might think.  Every case I've seen so far is ED related.

I was curious though, so went code spelunking.

ED grabs mixes `Ember.PromiseProxyMixin` with `Ember.ArrayProxy` [code here](https://github.com/emberjs/data/blob/master/addon/-private/system/promise-proxies.js#L36) to create `PromiseArray`.

It then `extends` PromiseArray with property definitions that lookup `content` to proxy a few methods through.

```
function proxyToContent(method) {
  return function() {
    var content = get(this, 'content');
    return content[method].apply(content, arguments);
  };
}
```
https://github.com/emberjs/data/blob/master/addon/-private/system/promise-proxies.js#L99-L104

I replicated the `PromiseArray` in twiddle sans any ED code to see if it was maybe just the PromiseProxyMixin playing poorly with ArrayProxy, it does not appear to be so: https://ember-twiddle.com/ae91bbc89d233f878046?numColumns=1&openFiles=application.controller.js%2C

I also looked at the twiddle provided by @denzo above, that twiddle was victim of an array reference error, `allItems` contained content that looked similar but did not actually reference `owner.items`.  When I fixed that, the twiddle operates as expected. https://ember-twiddle.com/8264d680a46f3c738372

**Comment by runspired** [comment] 2016-01-06 17:30
I also replicated `PromiseManyArray` to see if that additional `proxyToContent` was at fault, but still could not replicate a failing scenario.  It seems probable to me that there's something deeper in ED going on potentially causing an array change notification to not be sent, than for `computed.@each` itself to be the source of the bug.

**Comment by runspired** [comment] 2016-01-06 17:38
This is the link to the `PromiseManyArray` replication: https://ember-twiddle.com/01c42457eb8c5c74fe56?numColumns=1&openFiles=application.controller.js%2C

**Comment by alkamin** [comment] 2016-01-06 17:54
@runspired If I'm not mistaken, the twiddle you references as working properly (https://ember-twiddle.com/8264d680a46f3c738372) is still not working properly. The clean/dirty lists are not updating when the status of the items changes.

**Comment by runspired** [comment] 2016-01-06 18:17
@alkamin updated, I didn't save the fix that was relying on the model. https://ember-twiddle.com/8264d680a46f3c738372

**Comment by adam-knights** [comment] 2016-01-11 11:33
For those following this issue it looks likely that this is entirely down to Ember Data code issues as explained in https://github.com/emberjs/data/issues/4046.

**Comment by jgwhite** [comment] 2016-01-11 11:46
@adam-knights I believe there is a problem with PromiseManyArray in ED but *also* a more serious issue with dependent keys of the form `foos.@each.bar.baz`.

One more twiddle demonstrating the issue: https://ember-twiddle.com/efc125d794b6e8820e10

**Comment by runspired** [comment] 2016-01-11 12:17
@jgwhite that is not a supported behavior, you can only go one leaf beyond the `@each`

**Comment by jgwhite** [comment] 2016-01-11 12:20
@runspired I’m sure you’re right but could you point me to documentation on that?

**Comment by jgwhite** [comment] 2016-01-11 12:21
@runspired [found it](https://guides.emberjs.com/v1.10.0/object-model/computed-properties-and-aggregate-data/). Thanks all the same.

**Comment by jeradg** [comment] 2016-01-11 16:45
Confirming this bug in Ember 2.2.0 with Ember Data 2.2.0.

Bug does not occur with Ember 2.0.2 and Ember Data 2.2.0.

(Twiddles below.)

In my case, I'm trying to display a tree of items, each of which can have a parent that is either another item, or `null` if it's a root item. The inverse relationship (an item's `children`) needs to be computed on the client side.

```js
// models/item.js
export default DS.Model.extend({
  owner: DS.belongsTo('owner'),
  name: DS.attr('string'),
  parent: DS.belongsTo('item', {inverse: null}),
  children: Ember.computed.filter('owner.items', function(item) {
  	return item.get('parent.content') === this;
  }).property('owner.items.@each.parent')
});

// models/owner.js
export default DS.Model.extend({
  items: DS.hasMany('item')
});

// application/controller.js
export default Ember.Controller.extend({
  rootItems: Ember.computed.filter('owner.items', function(item) {
    return item.get('parent.content') === null;
  }).property('owner.items.@each.parent'),

  // ...
});
```

Working Twiddle with Ember 2.0.2: https://ember-twiddle.com/3ae725bf74a0b6eefefe?openFiles=models.item.js%2Capplication.controller.js

Twiddle demonstrating broken @each with Ember 2.2.0: https://ember-twiddle.com/298eb7e29cba2a9b30da?openFiles=models.item.js%2Capplication.controller.js

Using `.property('owner.items.@each.parent.content')` is not possible. Adding `{async: true}` to the `parent` relationship does not fix the bug. Downgrading to Ember Data 1.13.15 also does not work.

**Comment by YoranBrondsema** [comment] 2016-01-14 15:25
FWIW we're seeing the same issue which prevents us from upgrading to Ember 2.1.

**Comment by nybblr** [comment] 2016-01-14 18:57
Same issue on a project I'm running w/ Ember 2.2, happens when observing through PromiseManyArrays.

Interestingly, if I render a property in a template (forcing an access) within the `.@each`, it forces a recompute I guess and observation works.

**Comment by stefanpenner** [comment] 2016-01-14 19:13
Sorry guys, the last little while has been hectic. I'll try to carve out some time in the next week or so (feel free to ping me If i don't respond again in a week, that means I just forgot).

**Comment by jeradg** [comment] 2016-01-14 19:16
@stefanpenner You're a champ.

**Comment by ef4** [comment] 2016-01-19 03:44
Folks who are watching this issue and interested in exploring the problem should check out the test cases in https://github.com/emberjs/ember.js/pull/12832

It looks like there is at least one longstanding bug in ember-metal that's contributing to this problem, and it was revealed by more recent changes.

**Comment by stefanpenner** [comment] 2016-01-20 18:54
> @jgwhite that is not a supported behavior, you can only go one leaf beyond the @each

@runspired / @jgwhite we should make this a warning

**Comment by jgwhite** [comment] 2016-01-20 20:04
@stefanpenner good idea. Submitted my attempt in #12847.

**Comment by mmun** [comment] 2016-01-23 10:32
Hey @fivetanley, I had a similar bug in my app that I was also able to bisect down to the same commit. With the help of @krisselden we believe the issue is that the offending PR changed `content` to be a computed property, but this computed property is clobbered by https://github.com/emberjs/data/blob/c8f03a5c1c7b91160e6c3ad51b80638efd1b0413/addon/-private/system/record-arrays/record-array.js#L44. It may also be clobbered in other places, I haven't looked closely.

**Closed** 2016-02-04 22:25 UTC
Labels: Bug, Regression

**Comment by gabrielrotbart** [comment] 2016-02-05 00:36
Thanks a lot @mmun. Really appreciated, even though the solution is not ideal

**Comment by YoranBrondsema** [comment] 2016-02-08 14:15
@mmun Thanks for fixing! One question though: as far as I can see, the bugfix #12908 has only been released for 2.3 and 2.4. However, this bug is preventing us from upgrading from 2.0 to 2.1. We would like to avoid having to upgrade straight to 2.3 from 2.0. Would you be able to do a bugfix release for 2.1 and 2.2 as well? Or has the code diverged too much and is causing many conflicts.

**Comment by rwjblue** [comment] 2016-02-08 16:07
We generally do not backport bugfixes to all affected versions. 2.0/2.1/2.2/2.3 are all compatible versions, I am not aware of any breaking changes amongst them.

**Comment by stefanpenner** [comment] 2016-02-08 17:03
> Or has the code diverged too much and is causing many conflicts.

Its just a time thing

**Comment by erichonkanen** [comment] 2018-03-21 19:30
just ran into this on ED 3.0.2 where:
```
    productCount: computed('cart_lines.@each.quantity', function() {
```
if triggered upon line item create but not upon quantity update of existing. however this:
```
    productCount: computed('cart_lines.content.@each.quantity', function() {
```
does fire when it updates... is this supposed to still be happening in the latest Ember Data?
