### ISSUE TITLE
[Bug] 3.20.6+ regression: two-way binding no longer works for classic components

### ISSUE THREAD

**Issue by EvgenyOrekhov** [emberjs/ember.js#19461] opened 2021-03-16 13:05 UTC
### 🐞 Describe the Bug
Starting with Ember 3.20.6, two-way binding no longer works when using classic components and tracked properties.

### 🔬 Minimal Reproduction
Minimal reproduction: https://github.com/Axcient/ember-bug
This commit adds the example, a test case, and uses Ember 3.20.5 which works correctly: https://github.com/Axcient/ember-bug/commit/9b45acc15093cb4ff9da3c58ad564aa47f3d86df
This commit upgrades Ember to 3.20.6, and the example and the test stop working correctly: https://github.com/Axcient/ember-bug/commit/ef7918cf42c7c4970ffe2df590107d4b92140968

### 😕 Actual Behavior
When clicking on the checkbox, the "NOT checked" text doesn't change.

![image](https://user-images.githubusercontent.com/8045060/111312405-4d85b700-8670-11eb-81fb-c7c8e7041b5f.png)

### 🤔 Expected Behavior
When clicking on the checkbox, the "NOT checked" text should change to "checked".

![image](https://user-images.githubusercontent.com/8045060/111312787-b2411180-8670-11eb-87a3-6111eea6523e.png)

### 🌍 Environment

- Ember: 3.20.6 (and any later version)
- Node.js/npm: 14.16.0/6.14.11
- OS: Windows
- Browser: Chrome, Firefox

### ➕ Additional Context
We have a real-world project that uses that kind of two-way data binding extensively, and we can't upgrade Ember to 3.20.6 or any later version because it breaks ~30% of our components and tests.

**Comment by EvgenyOrekhov** [comment] 2021-03-17 09:10
It just occurred to me that maybe it's incorrect to call this example "two-way binding". Sorry if I'm using terms incorrectly.

**Comment by pzuraq** [comment] 2021-03-17 14:43
The PR which caused this change is this one: https://github.com/emberjs/ember.js/pull/19138

I believe the specific issue is that prior to this change, tracked properties were not part of the computed property system fully, and when updated with `set()` they would trigger an explicit `notifyPropertyChange`. This leads to a split in behavior, if you use `set()` or `toggleProperty()` then the two way binding worked, but if you set the tracked property directly it would not.

This was not intended behavior in the first place, and adding a full `notifyPropertyChange()` to tracked properties would introduce more overhead. Removing tracked properties from the computed-property system could cause a number of issues, so I don't think should revert that portion of the change either. Given that, I don't believe we should restore this functionality. If you want to use two-way-binding with classic components, then you should use classic idioms such as `Ember.set()` _without_ `@tracked`.

**Comment by EvgenyOrekhov** [comment] 2021-03-17 19:23
Removing `@tracked` from [`my-checkbox.js:8`](https://github.com/Axcient/ember-bug/blob/ef7918cf42c7c4970ffe2df590107d4b92140968/app/components/my-checkbox.js#L8) indeed fixes the example.



Thanks, @pzuraq! I will try this with our production components and see how it goes.

**Comment by sandstrom** [comment] 2023-06-30 19:33
Closing for reason in https://github.com/emberjs/ember.js/issues/19461#issuecomment-801141786

**Closed by sandstrom** 2023-06-30 19:33 UTC
