### ISSUE TITLE
ember goes into an infinite loop when I return a promiseobject from a helper

### ISSUE THREAD

**Issue by adam-knights** [emberjs/ember.js#14456] opened 2016-10-12 09:44 UTC
Reproduction here:

https://ember-twiddle.com/18b75f7761ba740567c1829660ce28e1?openFiles=templates.application.hbs%2C

To reproduce simply goto the application.hbs, and add the final ```{{/if}}``` **warning this will cause your browser and computer to cry**

Can see in the console that 'in' is printed over and over.

I imagine I need to do better here (and will be trying ember-resolve-promise-helper) with what i'm trying to achieve, but didn't know whether Ember should get into a loop like this?

----

The twiddle is an abstract example of what I am trying to achieve. Part of a workflow in our real app adds the child to the store (but doesn't save), until that child is created, or is already there, we don't show a particular button. You cant use myParent.child directly as its an async belongsTo and so returns truthy even though there is no child.

----
The other thing to say is this approach works fine from a computed in a component:

```
  availablity: Ember.computed('myParent.child', function() {
    return DS.PromiseObject.create({
      promise: this.get('myParent.child').then(child => {
        return { isAvailable: child !== undefined };
      })
    });
  }),
```

**Comment by rwjblue** [comment] 2016-10-12 11:36
I believe this is a duplicate of https://github.com/emberjs/ember.js/issues/14351, but haven't looked super deeply to confirm. Can you double check and see if you think it is a dupe?

**Comment by adam-knights** [comment] 2016-10-12 11:41
Its hard to tell, the above occurs in Ember 2.8 whereas that looks Glimmer2 related in 2.9? But it does look very similar. Im happy to add my twiddle to that thread and monitor and reopen if a fix for that doesnt fix mine?

**Closed** 2016-10-12 11:43 UTC
