### ISSUE TITLE
Transitions to the same route with different model + QPs throws Error

### ISSUE THREAD

**Issue by cibernox** [emberjs/ember.js#13954] opened 2016-07-29 19:30 UTC
The exact error message is:

> You didn't provide enough string/numeric parameters to satisfy all of the dynamic segments for route view

I was able extract a failing example of a big app and reduce it to the minimum.

Life demo: https://demo-transition-bug.development.pagefrontapp.com
Code: https://github.com/cibernox/demo-transition-bug

@raytiley This PR of yours (https://github.com/emberjs/ember.js/pull/13273) can be related? I think that this PR should be part of 2.7 because 2.7 was the current beta when it was merged, but I still get the error.

**Comment by cibernox** [comment] 2016-07-29 19:33
I just confirm that this is present in 2.8.0-beta.1 too.

**Comment by Serabe** [comment] 2017-07-13 16:03
Duplicate of #13395. Closing this. Thank you!

**Closed by Serabe** 2017-07-13 16:03 UTC
Labels: Has Reproduction, Query Params
