### ISSUE TITLE
Ember.Select doesn't select the correct value by default when the content is an array of resolved promises

### ISSUE THREAD

**Issue by nbudin** [emberjs/ember.js#10492] opened 2015-02-19 15:05 UTC
As of commit 2960f22ab23f11ee0ce1bcf2e692eba7594c616d, it looks like Ember.Select is attempting to properly handle the case of content being an array of promises.  Nice!  Unfortunately, it doesn't seem to always behave properly.

Specifically, if the promises are already resolved by render time, it looks as if the Select itself is unsetting the value by rendering itself.  @bryanalves and I have tried to trace through the sequence of events, and what we think happens is:

1. The value gets correctly set by `Ember.Select.valueDidChange`.
2. `Ember.Select._selectionDidChangeSingle` runs and sees that the content has a `then` method, which causes it to schedule that to be called later.
3. The HTML `<select>` renders onto the page, and triggers a `change` event, which Ember is listening for.
4. There is no actual selection yet, because that was deferred in step 2.  So instead, Ember.Select thinks the selection just changed to nothing.
5. Finally the `then` method does get called, but it's too late - the underlying value has already been set to undefined.

I've got two JSFiddles demonstrating this problem:

* [Here's one with an Ember.Select.  When I run it, the value gets unset on page load.](http://jsfiddle.net/nbudin/c7fwu9q4/)
* [Here's the exact same thing with the Ember.Select removed.  When I run it, the value stays at French Fries.](http://jsfiddle.net/nbudin/sftn4fn1/1/)

Simply having the Ember.Select on the page alters the value of the property on page render.

**Comment by miguelcobain** [comment] 2015-02-20 15:35
I'm also having these issues with Ember.Select on version 1.10.0.
A failing test for this would be nice.

**Comment by nbudin** [comment] 2015-02-21 17:28
After trying to write a test for this, I'm thinking the problem might be a little subtler than I originally thought.  It doesn't look as if Ember.Select is supposed to support having an array of Promises as its content, but it does support having its `selection` property set to a Promise.

The way I ran into this was trying to upgrade an old codebase that's still using DeferredMixin in some places, including (in this case) the content of the Select.  So they aren't actually Promises, but were being treated as such incorrectly because they have a `then` property (in this case, the one from DeferredMixin).  Maybe there is a better way for Ember.Select to determine if something is a Promise?  I will think more about this and post when I have a better idea.

**Comment by nbudin** [comment] 2015-02-22 17:08
One non-deprecated way to trigger the same issue appears to be to use an array of ObjectProxies with PromiseProxyMixin as the content of the Select.  This is at least non-deprecated, but it's not clear to me if this is a supported use of Ember.Select.  Does anyone know?

**Comment by stefanpenner** [comment] 2015-02-23 21:11
most certainly a duplicate of https://github.com/emberjs/ember.js/issues/5259

**Comment by nbudin** [comment] 2015-02-23 21:21
@stefanpenner: I agree, but it's not clear to me what that actually means.  Should we expect that no issues in Ember.Select will be fixed until it is rewritten from scratch?

**Comment by rwjblue** [comment] 2015-02-23 23:11
@nbudin - Patches to fix bugs will absolutely be accepted (and I am glad to help folks through the `Ember.Select` minefield in a PR), but keeping many issues open at once for a piece with known issues (that we intend to replace) drags down our ability to triage issues.

**Comment by nbudin** [comment] 2015-02-23 23:48
@rwjblue - thanks so much!  I'm thinking of trying to make Ember.Select support thenables as its content; I'll make a fork and let you know when I have anything worth looking at.

**Comment by rwjblue** [comment] 2015-08-10 01:09
`Ember.Select` is deprecated, and no longer ships with Ember 2.0.0 by default.

Closing...

**Closed by rwjblue** 2015-08-10 01:09 UTC
