### ISSUE TITLE
Ember 1.8 seems to break HTML 5 tags in IE 8

### ISSUE THREAD

**Issue by jneurock** [emberjs/ember.js#9495] opened 2014-11-05 06:50 UTC
After giving IE 8 a try with Ember 1.8 I noticed my layouts appeared broken. When I inspected the markup I noticed that the HTML 5 tags appeared to be self-closing (`nav`, `header`, `main`, etc.). This is not the case with Ember 1.7. I have toyed fairly extensively with the following examples in an effort to thoroughly rule out the other libraries I've loaded. I'm wondering if the addition of metal-views could be part of the issue.

See these two JSBins in IE 8 to compare Ember 1.8 and 1.7:
Ember 1.7.0: http://jsbin.com/comihoquzu
Ember 1.8.1: http://jsbin.com/qavurosato

Note:
* The same problem occurs with 1.8.0 and 1.8.1.
* The inclusion of Foundation (along with Respond.js and the rem unit polyfill) is simply to illustrate the problem more clearly by using a grid system. The same problem could be seen if the application template simply contained:
```
<header>
  <h3>This is a header</h3>
</header>
```

**Comment by ghedamat** [comment] 2015-01-14 18:13
Just did another round of testing with Ember 1.10-beta4
http://emberjs.jsbin.com/xexodoyenu

it seems to be working fine in WindowsXP IE8
without HTML5shiv

thanks guys!

**Comment by jreading** [comment] 2015-01-14 21:22
Broken in 1.9.1, but I'm just +1'ing anyway...

**Comment by rjfranco** [comment] 2015-01-21 21:07
I can confirm html5shiv isn't working when used in conjunction with Ember 1.9.1 ... does anyone have a workaround that can be used for now?

**Comment by wagenet** [comment] 2015-01-21 23:47
I've been told this is fixed by 1.10. Let me know if this turns out to not be the case.

**Closed by wagenet** 2015-01-21 23:47 UTC
Labels: bug, REGRESSION
