### ISSUE TITLE
Ember.Object with ownerInjection cannot be JSON.stringified

### ISSUE THREAD

**Issue by rynam0** [emberjs/ember.js#15248] opened 2017-05-17 20:02 UTC
Hi!

I ran into an issue (offirgolan/ember-cp-validations#507) while introducing `ember-cp-validations` into a project where creating `Ember.Object`s with an `ownerInjection` results in `TypeError: Converting circular structure to JSON`.  I have provided an Ember Twiddle https://ember-twiddle.com/979d8fc762574b457e04393cd9852159?openFiles=controllers.index.js%2C that demonstrates this behavior.

As the default Ember Data `ajaxOptions` function calls `JSON.stringify`, I overrode this function in my app to ignore the `__OWNER__` property.

I don't know that addressing the circular reference makes sense in this context as the entire instance would then appear in the stringified representation so perhaps Ember Data is the correct repo to report this in?  If that is the case, please let me know and I'll close this in favor of an issue in the Ember Data repo.  Thanks :)

**Comment by stefanpenner** [comment] 2017-05-17 20:18
* which version of ember? 
* can you provide a reproduction?

**Comment by rynam0** [comment] 2017-05-17 20:26
I included a link to an Ember Twiddle that reproduces this: 
https://ember-twiddle.com/979d8fc762574b457e04393cd9852159?openFiles=routes.index.js%2C

Ember Version 2.12.0 per `twiddle.json`:

    {
      "version": "0.12.1",
      "EmberENV": {
        "FEATURES": {}
      },
      "options": {
        "use_pods": false,
        "enable-testing": false
      },
      "dependencies": {
        "jquery": "https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.3/jquery.js",
        "ember": "2.12.0",
        "ember-template-compiler": "2.12.0",
        "ember-testing": "2.12.0"
      },
      "addons": {
        "ember-data": "2.12.1"
      }
    }

**Comment by stefanpenner** [comment] 2017-05-17 20:56
@rwjblue I thought we moved owner stuff to meta?

**Comment by rwjblue** [comment] 2017-06-04 02:04
We should implement a `toJSON` on [Ember.ApplicationInstance](https://github.com/emberjs/ember.js/blob/master/packages/ember-application/lib/system/application-instance.js), that emits useful information but avoids the circular reference.

**Comment by rynam0** [comment] 2017-08-22 14:05
For what its worth, I recently upgraded from ember 2.12 to ember 2.14 and the `__OWNER__` property appears to have been replaced by `__OVERRIDE_OWNER__`

**Comment by vincent99** [comment] 2017-10-13 18:37
In case this helps anyone in a similar situation... Our product has a custom datastore with models that also need to have owner set but also be JSON.stringified.  We solved/hacked this by defining the owner ourselves instead of using `Ember.setOwner(obj, val)` directly.

setOwner just sets `obj[OWNER] = val` but the tricky bit is knowing what the`OWNER` constant is, since it changes all the time and is not easily accessible.

```javascript
function getOwnerKey() {
  const x = {};
  Ember.setOwner(x);
  return Object.keys(x)[0];
}

const model = Ember.Object.create(data);

Object.defineProperty(model, getOwnerKey(), {
  value: Ember.getOwner(this), 
  enumerable: false}
});
```

**Comment by rynam0** [comment] 2017-10-15 20:28
@rwjblue: if you could describe what you would consider "useful information" I would be glad to give this a try.

**Comment by pixelhandler** [comment] 2018-09-28 17:06
@rwjblue @rynam0 @stefanpenner @vincent99 is this still an issue, perhaps we should close or create a new reproduction of this, what do you think?

**Comment by vincent99** [comment] 2018-09-28 21:52
I mean we just use the hackaround as I described above in our product, but it is still an issue..  All you really need to reproduce it is:

```
    var cycle = Ember.Object.create();
    cycle.set('cycle', cycle);
  
    var x = Ember.Object.create();
    Ember.setOwner(x, cycle);
    
    try {
      JSON.stringify(x);
    } catch (e) {
     alert(e);
    }
```
Here's a twiddle of the same: https://ember-twiddle.com/b11d1084021dd0ff1dcf19226f2d7d01

And the fix would be to have `setOwner()` define it as a non-enumerable property as I did above.

**Comment by locks** [comment] 2020-04-19 00:36
Thanks everyone for the discussion. Closing as not relevant in a post-Octane world.

**Closed by locks** 2020-04-19 00:36 UTC
Labels: Has Reproduction, Help Wanted

**Comment by rynam0** [comment] 2020-04-20 15:26
Confirmed.  I was able to delete my overridden `ajaxOptions` function. Thanks!
