### ISSUE TITLE
transitionTo() not passing query params to the url when link is being opened in a new tab

### ISSUE THREAD

**Issue by anudeepkollapudi1** [emberjs/ember.js#16925] opened 2018-08-30 10:24 UTC
Query params are not getting passed when opening the link in a new tab but they are getting passed when opening the link in the same tab.

**Comment by locks** [comment] 2019-05-30 17:23
Closing this issue due to lack of reproduction. There is also an [RFC about routing helpers](https://github.com/emberjs/rfcs/pull/339) that is relevant and should be of help here, because they can be implemented by the user using the router service.
If you're still encountering this problem, let us know @anudeepkollapudi1 and please submit a reproduction of the problem :)

**Closed by locks** 2019-05-30 17:23 UTC
