### ISSUE TITLE
{{link-to}} can cause infinite rendering loop

### ISSUE THREAD

**Issue by raytiley** [emberjs/ember.js#11555] opened 2015-06-26 00:03 UTC
So I don't really under stand what was going on here. Was working with @krisselden today on list-view for glimmer and we ran into an issue with the `{{link-to}}` helper causing an infinite render loop.

I have noticed that I will periodically see errors that `you have modified view.href twice in a single render...`

Removing all the `{{link-to}}` from my list resolved the issue. Kris saw the stack trace an noted something about a setState in willRender.

Sorry for the vague report. I don't quite get it, but I will do my best to recreate in a jsbin. This issue may also be related: https://github.com/emberjs/ember.js/issues/11302

**Comment by jmurphyau** [comment] 2015-06-26 00:17
Can you paste the template that produces the error?

**Comment by raytiley** [comment] 2015-06-26 00:48
@jmurphyau yup. Just brain dumping after a long pairing session today. Will try to gather some details / reproduction ASAP.

**Comment by raytiley** [comment] 2015-06-26 01:37
`"You modified view.href twice in a single render. This was unreliable in Ember 1.x and will be removed in Ember 2.0"`

Its being triggered by this set: https://github.com/emberjs/ember.js/blob/stable/packages/ember-routing-views/lib/views/link.js#L448

Which is being called like this `{{link-to item.show.title "shows.edit" item.show.id }}`

I guess the edge case here is that `show` is a `DS.belongsTo` `{async: true}` relationship. That said the relationship should be loaded. All the data for this route is side loaded.

**Comment by rwjblue** [comment] 2015-06-26 01:40
Just discussed with @raytiley in slack, and I think this is a duplicate of https://github.com/emberjs/ember.js/issues/11519 (because `item` in his template snippet above comes from a block param).

**Comment by rwjblue** [comment] 2015-06-26 01:40
@raytiley - Can you confirm (and if it is a dupe can you comment on the other issue)?

**Comment by rwjblue** [comment] 2015-07-01 03:27
I'm going to close this, as I think it was fixed by https://github.com/emberjs/ember.js/pull/11570 (which is available in release, beta, and canary channel builds now). 

@raytiley - I'm happy to reopen if this is not solved on your end...

**Closed by rwjblue** 2015-07-01 03:27 UTC
