### ISSUE TITLE
Template Rendering issue when creating an HTML option tag with an variable also called option

### ISSUE THREAD

**Issue by devotox** [emberjs/ember.js#18736] opened 2020-02-11 08:39 UTC
[Twiddle](https://ember-twiddle.com/d1c42546b6528f05685d2b8bdb51ad9d?openFiles=templates.application.hbs%2C)

This was first noticed in `Ember 3.16.1` but creating the twiddle shows it is happening at `Ember 3.4` as well.

As the title says there is an issue when you try and create an option tag with option as a variable i.e.

```javascript
options: ['oranges', 'apples', 'pears']
```

```hbs
<select>
  {{#each options as |option|}}
      <option
        value={{option}}
      >
        {{option}}
      </option>
  {{/each}}
</select>
```

The error produced:
```
"Error: Assertion Failed: Could not find component named "oranges" (no component or template with that name was found)
    at new EmberError (https://cdn.jsdelivr.net/npm/ember-source@3.4.3/dist/ember.debug.js:2932:31)
    at assert (https://cdn.jsdelivr.net/npm/ember-source@3.4.3/dist/ember.debug.js:1794:23)
    at RuntimeResolver.lookupComponentDefinition (https://cdn.jsdelivr.net/npm/ember-source@3.4.3/dist/ember.debug.js:26830:56)
    at resolveComponent (https://cdn.jsdelivr.net/npm/ember-source@3.4.3/dist/ember.debug.js:11824:35)
    at Object.evaluate (https://cdn.jsdelivr.net/npm/ember-source@3.4.3/dist/ember.debug.js:11968:38)
    at AppendOpcodes.evaluate (https://cdn.jsdelivr.net/npm/ember-source@3.4.3/dist/ember.debug.js:10891:27)
    at LowLevelVM.evaluateSyscall (https://cdn.jsdelivr.net/npm/ember-source@3.4.3/dist/ember.debug.js:13734:28)
    at LowLevelVM.evaluateInner (https://cdn.jsdelivr.net/npm/ember-source@3.4.3/dist/ember.debug.js:13706:22)
    at LowLevelVM.evaluateOuter (https://cdn.jsdelivr.net/npm/ember-source@3.4.3/dist/ember.debug.js:13698:22)
    at VM.next (https://cdn.jsdelivr.net/npm/ember-source@3.4.3/dist/ember.debug.js:15626:28)"
```

**Comment by pzuraq** [comment] 2020-02-11 13:12
Duplicate of https://github.com/emberjs/ember.js/issues/16826

Fundamentally, the issue is that now that angle bracket invocation syntax exists, in that context `<option>` is trying to treat the value as a component. I believe there is a lint rule that guards against using html element names as local variables for this reason. 

In the long term, this will be the norm, and we should likely through a better error for users when it happens. In the short term, it was a regression since this was technically allowed before. Going to close this for now as a dup, but thank you for the detailed bug report!

**Closed by pzuraq** 2020-02-11 13:12 UTC

**Comment by devotox** [comment] 2020-02-11 14:55
Haaaaa off course the beautiful angle brackets invocation. That makes a lot of sense and now at least gives me something to watch out for. I think the dependency lint for this issue either didn't pop up or gave some cryptic message. Either way, thank you for pointing me to the ticket and I can follow there for updates!
