### ISSUE TITLE
 Using Modal Dialogs - undefined error in canary

### ISSUE THREAD

**Issue by iamjstates** [emberjs/ember.js#10416] opened 2015-02-10 18:26 UTC
In canary the below code does not work and yields the following error:

Uncaught TypeError: Cannot read property 'routeName' of undefined

It points to *return this.render(modalName, *

```javascript
App.ApplicationRoute = Ember.Route.extend({
  actions: {
    openModal: function(modalName) {
      return this.render(modalName, {
        into: 'application',
        outlet: 'modal'
      });
    }
  }
});
```

**Comment by ilkkao** [comment] 2015-02-11 13:10
I noticed the same problem in my Selenium tests this morning. I didn't have time to debug so I went back to beta1 which fixed the problem.

**Comment by iamjstates** [comment] 2015-02-11 15:02
Thanks @ilkkao - I guess the team is aware of the problem?

**Comment by stefanpenner** [comment] 2015-02-11 15:08
@ef4 this may be related to the recent outlet fixes/refactoring

**Comment by ilkkao** [comment] 2015-02-11 20:57
I just bisected the problem to https://github.com/emberjs/ember.js/pull/10372

In my case I use modals exactly as instructed here: http://emberjs.com/guides/cookbook/user_interface_and_interaction/using_modal_dialogs/

Maybe the example from there can be upgraded to use canary version to demonstrate the problem?

**Comment by ilkkao** [comment] 2015-02-11 21:10
Wasn't too hard. Demo here: http://emberjs.jsbin.com/dupufilora/1/edit?html,js,output

**Comment by ilkkao** [comment] 2015-02-11 21:35
This is a duplicate of https://github.com/emberjs/ember.js/issues/10427

**Comment by rwjblue** [comment] 2015-02-11 21:40
The error is being thrown from: [ember-routing/lib/system/route.js](https://github.com/emberjs/ember.js/blob/b186e6e3fa000f1960c8837530dff7416a1e7e0a/packages/ember-routing/lib/system/route.js#L1969-L1971).  Basically, when rendering into an outlet in the `application` route, there are is no parent route and we are calling `routeName` on `undefined`.

@ef4 - Should we just guard against this (`parentRoute(route)` being `undefined`), or is there a better solution?

**Comment by ef4** [comment] 2015-02-11 21:53
Just adding a guard should be sufficient. I can work on it tonight if nobody gets to it first.

We should also make sure we add a regression test for this case.

**Closed** 2015-02-12 12:03 UTC

**Comment by iamjstates** [comment] 2015-02-12 17:19
The fix works for opening modals, but this:

```javascript
closeModal: function() {
    return this.disconnectOutlet({
      outlet: 'modal',
      parentView: 'application'
    });
  }
```

now yields:  Uncaught TypeError: Cannot read property 'routeName' of undefined

**Comment by ef4** [comment] 2015-02-12 19:19
@iamjstates I just submitted another PR that takes care of disconnection too. 

Thanks for being a beta tester. I've added all these scenarios to the integration tests so we never break these behaviors on people again.

**Comment by iamjstates** [comment] 2015-02-12 21:10
@ef4 - No worries, glad to help out in anyway.
