### ISSUE TITLE
[3.15] Each does not rerender

### ISSUE THREAD

**Issue by boris-petrov** [emberjs/ember.js#18643] opened 2019-12-28 17:46 UTC
Not sure if this happened before `3.15`, probably did.

[Here is a reproduction](https://github.com/boris-petrov/ember-each-rerender-bug).

Setting `shouldRender` to `true` causes the `push-to-array` helper to be rendered, it pushes to the service's array, but that doesn't get rendered in the `EachComponent`. I think this is a bug.

P.S. Sorry, run the tests to see it fail. The `push-to-array-test`.

**Comment by pzuraq** [comment] 2019-12-28 19:25
As noted in #18644, this is expected behavior. Ember does not rerender if you update state during a render. You must schedule the state change to happen later, in the next render.

**Comment by boris-petrov** [comment] 2019-12-28 19:33
@pzuraq - thanks for digging into this. I'm OK with the synchronous-render-and-modify not being supported (although it would be nice but I guess you have your reasons) but this issue here is something else I think. The `EachComponent` component is already rendered when `shouldRender` is set to `true` and the array is updated. I am correct about this, right? (after all, the `await render` line has already finished) So why isn't this working? And even if you if you give me some reason, this should at least throw some error or deprecation or something - otherwise this is impossible to debug.

**Comment by pzuraq** [comment] 2019-12-28 20:38
@boris-petrov Glimmer renders in a linear fashion, from top-to-bottom, inside-out (children first), for _every_ render pass. It checks each component to see if it has changed, so when you run `this.set('shouldRender', true);`, it does the following steps in order:

1. Checks `<EachComponent/>` to see if anything has changed. It has not, so it outputs the previous output, and continues.
2. Runs the `(push-to-array)` helper, which mutates the array.

By the time step 2 runs, step 1 is complete, and the DOM it outputs is locked in, which is why it doesn't update like you expect. This is what the assertion in #18644 is supposed to prevent, though it appears that rerenders are somehow missing those tags, and the assertion isn't being triggered, and that definitely is a bug.

**Comment by pzuraq** [comment] 2020-02-11 19:43
Closing this since the rerender assertion has been fixed.

**Closed by pzuraq** 2020-02-11 19:43 UTC
