### ISSUE TITLE
Adding 'queryParams' to controller throws 'Ember.get' exception

### ISSUE THREAD

**Issue by tsteuwer** [emberjs/ember.js#15274] opened 2017-05-24 16:11 UTC
**Issue**
I was just looking over the documentation on adding query params to my controller. Upon refreshing the page I experience two exceptions. I then tried to do it in the route, and the same thing happens.

Controller Code:
```
queryParams: ['star'],
star: null,
```

Route code:
```
queryParams: {
    star: {
        refreshModel: false,
    },
},
```

Exception:
```
ember.debug.js:29034 Error while processing route: site Assertion Failed: Cannot call `Ember.get` with an empty string Error
    at assert (http://localhost:4200/assets/vendor.js:21708:13)
    at Object.assert (http://localhost:4200/assets/vendor.js:33459:34)
    at Object.get (http://localhost:4200/assets/vendor.js:38097:22)
    at Object.calculateCacheKey (http://localhost:4200/assets/vendor.js:45273:31)
    at http://localhost:4200/assets/vendor.js:42638:47
    at Array.forEach (native)
    at http://localhost:4200/assets/vendor.js:42634:21
    at Class.setup (http://localhost:4200/assets/vendor.js:42645:11)
    at callHook (http://localhost:4200/assets/vendor.js:72296:36)
    at _handlerEnteredOrUpdated (http://localhost:4200/assets/vendor.js:73907:5)
logError @ ember.debug.js:29034
error @ ember.debug.js:28975
triggerEvent @ ember.debug.js:29132
trigger @ ember.debug.js:56465
trigger @ ember.debug.js:57007
finalizeTransition @ ember.debug.js:58393
(anonymous) @ ember.debug.js:57768
tryCatch @ ember.debug.js:59077
invokeCallback @ ember.debug.js:59092
publish @ ember.debug.js:59060
(anonymous) @ ember.debug.js:38900
invokeWithOnError @ ember.debug.js:346
flush @ ember.debug.js:405
flush @ ember.debug.js:529
end @ ember.debug.js:599
run @ ember.debug.js:713
join @ ember.debug.js:744
run.join @ ember.debug.js:22747
hash.success @ rest.js:622
fire @ jquery.js:3317
fireWith @ jquery.js:3447
done @ jquery.js:9272
(anonymous) @ jquery.js:9514
ember.debug.js:18023 Assertion Failed: Cannot call `Ember.get` with an empty string
Error
    at assert (http://localhost:4200/assets/vendor.js:21708:13)
    at Object.assert (http://localhost:4200/assets/vendor.js:33459:34)
    at Object.get (http://localhost:4200/assets/vendor.js:38097:22)
    at Object.calculateCacheKey (http://localhost:4200/assets/vendor.js:45273:31)
    at http://localhost:4200/assets/vendor.js:42638:47
    at Array.forEach (native)
    at http://localhost:4200/assets/vendor.js:42634:21
    at Class.setup (http://localhost:4200/assets/vendor.js:42645:11)
    at callHook (http://localhost:4200/assets/vendor.js:72296:36)
    at _handlerEnteredOrUpdated (http://localhost:4200/assets/vendor.js:73907:5)
```

**Version Info**
```
ember: 2.12.0
ember-cli: 2.12.1
http_parser: 2.7.0
node: 6.0.0
v8: 5.0.71.35
uv: 1.9.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 48
openssl: 1.0.2g
os: linux x64
3.8.6
```

**Comment by Serabe** [comment] 2017-05-26 12:36
Hello @tsteuwer,

I cannot reproduce the problem with this data. [Here is my try in a twiddle](https://ember-twiddle.com/1a1071d708dccbd8494d9503bde88f32?openFiles=twiddle.json%2C&route=%2Fqp%3Fstar%3Dhola).

Can you please send a reproduction?

Thank you!

**Comment by tsteuwer** [comment] 2017-05-28 18:58
So I've delved a bit deeper into this. It seems it only happens when I have a catchall route using params:

Repository: https://github.com/tsteuwer/ember-catchall-route-query-params-error

Instructions to recreate:

# ember s
# localhost:4200/this-should-get-caught
# open up console and see the error

**Comment by tsteuwer** [comment] 2017-05-29 12:58
@Serabe, or anyone looking into this , I'm managed to track this down to https://github.com/emberjs/ember.js/blob/8d4ec0019f0810e6c33016fa2cd393a83c6c2e30/packages/ember-routing/lib/utils.js#L88

If you follow the post from above and visit that page, the `values` being passed in to it are:

```
application: {...},
something: {
    "": 'this-should-get-caught",
}
```

Where "" throws the Ember.get error. Changing https://github.com/emberjs/ember.js/blob/8d4ec0019f0810e6c33016fa2cd393a83c6c2e30/packages/ember-routing/lib/utils.js#L88 to:

```
var partRemovedPrefix = part.indexOf(cacheValuePrefix) === 0 ? part.substr(cacheValuePrefix.length + 1) : part;
if (partRemovedPrefix === '') {
   value = values[cacheValuePrefix][partRemovedPrefix];
} else {
   value = _emberMetal.get(values[cacheValuePrefix], partRemovedPrefix);
}
```

Fixes the issue, but I can't find where in the world it creates that key in the first place.

**Comment by rwjblue** [comment] 2017-05-29 16:15
Awesome, thanks for continuing to dig @tsteuwer!  

I have reproduced the error you are seeing [in this twiddle](https://ember-twiddle.com/0f4f9edb13b63d7b6a0a0f518429ca9f/2425a5ded72dc2981b8f710e33898bd3dea286fa?openFiles=router.js%2C) and tracked down why `""` is the key in that object.  When using glob/wildcard routes in Ember they should be defined with a name (e.g. `path: '*someNameHere'`).  That name is used to pass the wildcard value just like any other dynamic segments value (e.g. `path: ':some_model_id'`).  The reason `""` is being used in your scenario (and in my twiddle just above) is because the path is `'*'` (essentially creating a model param who's reference position is `<route-name>.`).

The solution to your error is to provide a name for that wildcard like [in this revision of the twiddle](https://ember-twiddle.com/0f4f9edb13b63d7b6a0a0f518429ca9f/2425a5ded72dc2981b8f710e33898bd3dea286fa?openFiles=router.js%2C).

---

In the end this isn't a bug per-se in the `calculateCacheKey` method, but instead I believe it should have been an assertion much earlier when the `Router.map` is evaluated (to tell you that a name is needed for this glob route path).  I submitted https://github.com/tildeio/route-recognizer/pull/137 to address that angle...

**Comment by rwjblue** [comment] 2017-05-29 16:17
@tsteuwer it would be great if you could go back and double check the docs that you used to determine how glob/wildcard routes were defined and perhaps submit a PR tweaking the language to make this fairly subtle point a bit more clearly...

Since I think the above comments address the reported issue, I'm going to close this. Please let me know if I have misdiagnosed and we can reopen and dig in further...

**Closed by rwjblue** 2017-05-29 16:17 UTC
Labels: Needs Submitter Response

**Comment by tsteuwer** [comment] 2017-05-29 18:26
You're solution was spot on @rwjblue! Absolutely will submit a PR in the docs for this. Thanks so much for looking into this. I've literally been going through the ember source trying to figure this all out. I feel like I can work on query params now if there is ever a ticket lmao.
