### ISSUE TITLE
[3.6.0] Regression when creating a MutableArray implementation

### ISSUE THREAD

**Issue by boris-petrov** [emberjs/ember.js#17282] opened 2018-12-07 14:41 UTC
We have the following code that works fine in 3.5.1:

```typescript
  const properties = {
    ...
    replace(index, amount, objects = []) {
      // do some special magic
      return this;
    },
  };

  const result = Mixin
    .create(MutableArray, Observable, properties)
    .without(['length'])
    .apply([]);
```

And this worked fine - e.g. when calling `result.pushObject` or `result.insertAt` or `result.removeAt` that would call our version of `replace` and we could handle it specially. This is broken in 3.6.0. I see [here](https://github.com/emberjs/ember.js/blob/v3.6.0/packages/%40ember/-internals/runtime/lib/mixins/array.js#L109) that a "generic" *replace* function is called while in 3.5.1 it was implemented in a [different way](https://github.com/emberjs/ember.js/blob/v3.5.1/packages/ember-runtime/lib/mixins/array.js#L1257) and that's why what we did worked before. Not sure if we were using private APIs or something which was never supported but I think I've read in the documentation that when you want to create your own type of array, you should just implement `replace` and all else will work with it. That seemed to be true before but now it is broken. Is that OK? How are we supposed to do something like what we were doing before?

**Comment by pixelhandler** [comment] 2018-12-07 16:38
@boris-petrov I see that replace is documented here:

- https://emberjs.com/api/ember/3.5/classes/MutableArray/methods/replace?anchor=replace
- https://github.com/emberjs/ember.js/blob/v3.6.0/packages/%40ember/-internals/runtime/lib/mixins/array.js#L1607-L1614

Which appears to be the same as an 3.6

- https://github.com/emberjs/ember.js/blob/v3.6.0/packages/%40ember/-internals/runtime/lib/mixins/array.js#L1191-L1208

I don't know how this is used...

- https://github.com/emberjs/ember.js/blob/v3.6.0/packages/%40ember/-internals/runtime/lib/mixins/array.js#L1607-L1614

What I think will be helpful is if you can create simplified reproduction of the issue, perhaps in an ember-twiddle or a public repo.

**Comment by boris-petrov** [comment] 2018-12-09 16:48
Well, [here is a reproduction](https://github.com/boris-petrov/ember-mutable-array-bug). Run `ember server`and open the page. You won't see the `console.log` in the console. If you checkout the previous commit (before the upgrade to Ember 3.6) and run the server, you'll see it print in the console.

This is a showstopper for us. Is it a bug or is this expected and we were using something private that changed?

**Comment by rwjblue** [comment] 2018-12-09 17:18
I’ll try to poke at the repro later today (assuming I don’t freeze, fall off a ladder, or electrocute myself while hanging holiday lights 😝)....

**Comment by devdemi** [comment] 2018-12-10 15:35
I get next error message in console:
```
rsvp.js:24 Uncaught RangeError: Maximum call stack size exceeded at WeakMap.get () at getCacheFor (metal.js:25) at ComputedProperty.get (metal.js:2350) at Array.CPGETTER_FUNCTION [as []] (metal.js:752) at Function.jQuery.extend.jQuery.fn.extend (jquery.js:261) at Function.jQuery.extend.jQuery.fn.extend (jquery.js:282) at Function.jQuery.extend.jQuery.fn.extend (jquery.js:282) at Function.jQuery.extend.jQuery.fn.extend (jquery.js:282) at Function.jQuery.extend.jQuery.fn.extend (jquery.js:282) at Function.jQuery.extend.jQuery.fn.extend (jquery.js:282)
```
I figured out that reason of it `store.query` request in `init` in one of my components:
```javascript
this.get('store').query('user', { 'filter': { 'type': '1', 'gender': 'male' } }).then(tutors => {
    this.set("tutors", tutors);
});
```

**Comment by boris-petrov** [comment] 2018-12-14 07:44
@rwjblue - did you get a chance to see the reproduction and do you have any ideas what we can do? We cannot update to 3.6 because of that. :(

**Comment by jacobq** [comment] 2018-12-19 15:45
@devdemi what you mentioned sounds related to https://github.com/emberjs/ember.js/issues/17373 which should be fixed in 3.6.1, which was just released.

**Comment by boris-petrov** [comment] 2018-12-19 15:53
@jacobq - any idea about the original issue? It's not fixed in 3.6.1 unfortunately.

**Comment by boris-petrov** [comment] 2018-12-19 21:57
Thanks for the response. It's probably easy to find which commit did it - right now the code is written to not support our use case so I just have to find out what did it. I'll write tomorrow so if anyone wants to help, they can start from there. :)

**Comment by sandstrom** [comment] 2023-06-30 20:14
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.

**Comment by boris-petrov** [comment] 2023-07-03 08:14
@sandstrom well, it's still an issue, i.e. I still have to use the workaround (copying and pasting `insertAt`, `removeAt`, `pushObject` and `unshiftObject` in my own implementation of `MutableArray`). I guess it's never going to be fixed as Ember is going away from `MutableArray` so probably the issue can be closed. I'll leave you to decide.

**Comment by sandstrom** [comment] 2023-07-03 08:47
@boris-petrov Thanks for the update!

I'll close it for now, to keep the list more manageable.

It'll still be indexed by google, so others with this issue can still find it.

**Closed by sandstrom** 2023-07-03 08:47 UTC
Labels: Needs Reproduction
