### ISSUE TITLE
Observer detects change in array length but does not update injected property

### ISSUE THREAD

**Issue by JackEllis** [emberjs/ember.js#14959] opened 2017-02-24 22:25 UTC
If you head over to my twiddle: https://ember-twiddle.com/1ee1410ad19daa93d445b277491d84b0?openFiles=templates.application.hbs%2Ctemplates.components.component-here.hbs

I've put together some demo code. Long story short, a template derived action call ({{action 'blah' 'New Data'}} works fine but this.send('blah', 'new Data'}} does not.

This isn't a case of 'there is another way to do this', I understand I can monitor with .@each, but this functionality should still work and seems like a bug.

What do you think?

edit: Better demo from Alex: https://ember-twiddle.com/7de9d8c2698445aec0762b5eabe838c1?openFiles=templates.components.component-here.hbs%2Ctemplates.components.component-here.hbs

**Comment by JackEllis** [comment] 2017-02-24 22:29
Better demo from Alex: https://ember-twiddle.com/7de9d8c2698445aec0762b5eabe838c1?openFiles=templates.components.component-here.hbs%2Ctemplates.components.component-here.hbs

**Comment by stefanpenner** [comment] 2017-02-25 07:18
This does seem strange. What appears to be happening is not due to a difference between `send` and `{{action` but rather that the `send` is being triggered by a parent updating a child components attributes, and the `send` then trying to mutate its parent again.

While a component is receiving attribute changes from its parent, it is not allowed to make attribute changes back to that parent.  This is to prevent both correctness and performance problems:

--- 

The guard in question is https://github.com/emberjs/ember.js/blob/85bfc2ea3af21945e12adfc6b528e961a4885383/packages/ember-glimmer/lib/component.js#L588

--

@chancancode  / @wycats you guys may want to confirm

**Comment by pixelhandler** [comment] 2018-09-14 19:03
@JackEllis @chancancode @pixelhandler @stefanpenner is this still an issue, perhaps we should close or create a new reproduction of this, what do you think?

**Comment by rwjblue** [comment] 2018-12-10 00:30
@stefanpenner's analysis here was really good (thank you @stefanpenner!).

Yes, this is still an issue, but its somewhat fundamental and has likely been around for a very long time (possibly as long as 1.13).  I do not think there is a trivial way to solve this without introducing some pretty serious penalties. Most likely the best path forward is to migrate away from `Ember.Component` (e.g. [sparkles-component](https://github.com/rwjblue/sparkles-component) or a "soon to be proposed glimmer components RFC") which would avoid this short coming (and likely direct folks away from observers with side effects to boot).

I'm going to close this issue for now since IMHO there is nothing we can reasonably do to address it...

**Closed by rwjblue** 2018-12-10 00:30 UTC
Labels: Has Reproduction, Needs Bug Verification
