### ISSUE TITLE
Variable lost when using partials in Handlebars template

### ISSUE THREAD

**Issue by CrushedPixel** [emberjs/ember.js#15637] opened 2017-09-06 22:23 UTC
I'm using [ember-models-table](https://github.com/onechiporenko/ember-models-table/) to try and display models from Ember Data in a table - this does not work as expected though, as the table rows themselves have empty cells.

I've digged through the source code of ember-models-table and found the code responsible for the rendering of cell data. The [`models-table.hbs`](https://github.com/onechiporenko/ember-models-table/blob/19785d8ddc753246d3bf4685168412bf34075e5b/addon/templates/components/models-table.hbs#L38-L40) looks like this:

```hbs
{{#each visibleContent as |record index|}}
    {{partial rowTemplate}}
{{/each}}
```

and the [`rowTemplate` partial](https://github.com/onechiporenko/ember-models-table/blob/76806da8b119cb0b75e7f1afd39dcca91dd1496a/app/templates/components/models-table/row.hbs#L20) displays the record variable like this:
```hbs
{{get record column.propertyName}}
```

The problem is that the `record` variable is set to `undefined` in the partial - I've added some debug code to show the issue:

```hbs
{{#each visibleContent as |record index|}}
     {{log 'record is' record}}
     {{log 'record name is' (get record 'name')}}
     {{partial rowTemplate}}
{{/each}}
```
```hbs
{{log 'record now is' record}}
{{get record column.propertyName}}
```

and this is my console output: ![console output](http://i.imgur.com/3QOsevU.jpg)

Why may the `record` variable become `undefined` in the partial?

Thanks for any help.

**Comment by Serabe** [comment] 2017-09-06 22:46
Duplicate of #15621 

Thank you!

**Closed** 2017-09-06 22:47 UTC
