### ISSUE TITLE
Collisions between helpers and properties with the same name

### ISSUE THREAD

**Issue by tim-evans** [emberjs/ember.js#11987] opened 2015-08-05 16:26 UTC
When upgrading an addon I maintain, I've changed over to use a single word helper, which is a fairly common word in applications: title. I've found that trying to render a property with that name in any app results in the page to simply not load with a lookup error. Any ideas on a way forward?

See https://github.com/paddle8/ember-document-title/issues/20 for the original issue.
See http://ember-twiddle.com/c6d82babe1913fa68d82 for a reproduction.

**Comment by rwjblue** [comment] 2015-08-05 17:04
The issue is ultimately with the ember-cli resolver (and there is a tracking issue over in https://github.com/ember-cli/ember-resolver/issues/101).  

Basically, what is happening is that if you use a dashless helper without ordered or hash arguments, we end up trying to look for an `helper:@content-helper` ([deep inside HTMLBars](https://github.com/tildeio/htmlbars/blob/dc4bbf197853ab6f868163bf43c654427f95d2ab/packages/htmlbars-runtime/lib/hooks.js#L755)), and the ember-cli resolver has been updated to use `@` as a namespace separator (so it expects `helper:addon-name@helper-name` format) so it does not have a `fullnameWithoutType` (which it is using to do a regexp match against).

We need to fix the [parseName](https://github.com/ember-cli/ember-resolver/blob/master/packages/ember-resolver/lib/core.js#L52-L85) function to deal with `helper:@content-helper` properly.

**Comment by rwjblue** [comment] 2015-08-05 17:07
Also, this error occurs with or without shadowing a property.

Demo http://ember-twiddle.com/66a300bd7e8ecee24379

**Comment by pixelhandler** [comment] 2015-08-07 19:34
@tim-evans @rwjblue can this issue be closed since the issue is being tracked on the ember-cli/ember-resolver project ?

**Comment by rwjblue** [comment] 2015-08-07 19:38
I still have changes to make in Ember too (in the stable branch). I'd like to land those changes in Ember 1.13.7 so that the changes in the resolver are not required.

**Comment by rwjblue** [comment] 2015-08-12 23:22
Fixed by #12067.

**Closed by rwjblue** 2015-08-12 23:22 UTC

**Comment by tim-evans** [comment] 2015-08-13 02:04
@rwjblue :heart: Thanks for handling this in a quick and responsive manner.
