### ISSUE TITLE
Should visit test helper call Location#getURL?

### ISSUE THREAD

**Issue by tjni** [emberjs/ember.js#14036] opened 2016-08-06 09:19 UTC
I am trying to create a custom implementation of the location API to do some preprocessing on the URL before it arrives at the router and discovered that I could not write an acceptance test for this because the visit helper does not pass the supplied URL through my getURL implementation. This also affects ApplicationInstance#visit, but this was coincidentally fixed in 631260968d626ae702fa38491c207c5b20ad1182.

I don't mind creating a PR if folks agree that this is the right thing to do.

**Comment by rwjblue** [comment] 2016-11-10 01:08
Sure, seems good to call `getURL`. Happy to review a PR for this...

**Comment by rwjblue** [comment] 2017-02-19 16:44
@tjni - I'm going to close the issue since it doesn't really seem like a regression, but I'd still love a PR if you have the time...

**Closed by rwjblue** 2017-02-19 16:44 UTC
Labels: Needs Submitter Response
