### ISSUE TITLE
Modal dialog fails to render when app is build for production

### ISSUE THREAD

**Issue by BryanHunt** [emberjs/ember.js#17544] opened 2019-02-01 18:27 UTC
I have an application that displays a modal dialog.  Running the application in your typical dev environment (ember s) works fine.  If you `ember build -dev`, that also works.  As soon as you `ember build -prod`, the application throws the following exception when you try to render the modal dialog:

```
vendor-39e87a83c6850fcbd535898cfb1ba104.js:3074 Uncaught TypeError: Cannot read property 'manager' of null
    at Object.evaluate (vendor-39e87a83c6850fcbd535898cfb1ba104.js:3074)
    at e.evaluate (vendor-39e87a83c6850fcbd535898cfb1ba104.js:2962)
    at e.evaluateSyscall (vendor-39e87a83c6850fcbd535898cfb1ba104.js:3237)
    at e.evaluateInner (vendor-39e87a83c6850fcbd535898cfb1ba104.js:3229)
    at e.evaluateOuter (vendor-39e87a83c6850fcbd535898cfb1ba104.js:3229)
    at e.next (vendor-39e87a83c6850fcbd535898cfb1ba104.js:3370)
    at e.execute (vendor-39e87a83c6850fcbd535898cfb1ba104.js:3369)
    at i.handleException (vendor-39e87a83c6850fcbd535898cfb1ba104.js:3300)
    at e.handleException (vendor-39e87a83c6850fcbd535898cfb1ba104.js:3315)
    at e.throw (vendor-39e87a83c6850fcbd535898cfb1ba104.js:3295)
```

I have created a minimal application that reproduces this failure at: https://github.com/BryanHunt/prod-bug

If you run that application with `ember s` and click the button, you will see the modal dialog.

If you build that application with `ember build -prod` and then build and run the Docker image, clicking the button will reproduce the exception.

**Comment by pixelhandler** [comment] 2019-02-22 16:45
@BryanHunt I only see one application template in that repo, and there is a `bs-modal` where is that component defined in your repo?

**Comment by BryanHunt** [comment] 2019-02-22 16:47
`bs-modal` comes from the `ember-bootstrap` add-on.

**Comment by pixelhandler** [comment] 2019-02-22 16:50
@BryanHunt maybe the bug has more to do with ember-bootstrap then ember.js itself?

**Comment by BryanHunt** [comment] 2019-02-22 16:52
Maybe, but given the only change is `--dev` vs `--prod`, I'm pointing the initial finger at ember.

**Comment by BryanHunt** [comment] 2019-03-20 01:35
Updating EmberJS and dependencies made this go away.

**Comment by BryanHunt** [comment] 2019-03-20 02:22
Closed this too soon.  I just did another build after finding it was not using --prod.  The problem still exists with Ember 3.8

**Comment by noahgelman** [comment] 2019-05-22 00:38
Hey my dude, the issue isn't with Ember, it's with Ember-Bootstrap.

Your {{#bs-form}} has "formLayout=formLayout" but formLayout doesn't exist.

Swap it to an allowed value as noted in their docs: https://www.ember-bootstrap.com/api/classes/Components.Form.html#property_formLayout

**Comment by simonihmig** [comment] 2019-05-24 23:45
@BryanHunt This is indeed the problem you ran into, as @noahgelman explained it rightly.

It is a bit unfortunate that the example on ember-bootstrap.com contain some dynamic properties (in this case `formLayout` is a dynamic property on the controller, being updated by a pulldown to show different form layouts) which do not work if you just copy and paste them, without either replacing that dynamic property with a constant (here the string defining the form layout) or defining the dynamic property on the context (controller). I will try to improve these samples to make them more easily "copy-pastable".

Also there was an assertion for a correct `formLayout` (see the existing issue https://github.com/emberjs/ember.js/issues/17544), but this seems missing for Bootstrap 4. Will fix it.

So this indeed is not an issue with Ember, so this one can be close! And it *does*  work properly in ember-bootstrap if the property is correctly set. Will just try to improve the DX here...

**Comment by BryanHunt** [comment] 2019-05-25 13:02
I understand now why my code is broken.  I don't understand why it didn't fail in development mode.  One would expect development mode to function the same as production.

**Comment by locks** [comment] 2020-04-19 11:06
Closing as the problem was traced back to ember-bootstrap. Thanks for the help!

**Closed by locks** 2020-04-19 11:06 UTC
