### ISSUE TITLE
Tests with Pretender.js are broken, should upgrade to the latest RSVP.js

### ISSUE THREAD

**Issue by szines** [emberjs/ember.js#10314] opened 2015-01-30 09:46 UTC
We use pretender.js in tests in our huge ember app. Those tests were fine until Ember 1.7. Unfortunately pretender.js cannot work together with the actual Ember builds.

The problem is in `Promise.prototype._onError`, inside RSVP.js.
This problem already solved on RSVP.js repository, but EmberJS project is not updated, still using v `3.0.14`
The latest version of RSVP.js is `3.0.16`

The `3.0.14` verison of `_onError` is the following:

```
    Promise.prototype = {
      constructor: Promise,

      _guidKey: guidKey,

      _onerror: function (reason) {
        config.trigger('error', reason);
      },
```

The `3.0.16` version is:

```
    Promise.prototype = {
      constructor: Promise,

      _guidKey: guidKey,

      _onError: function (reason) {
        config.async(function (promise) {
          setTimeout(function () {
            if (promise._onError) {
              config['trigger']('error', reason);
            }
          }, 0);
        }, this);
      },
```

I am just wondering, is it possible to update the RSVP.js in EmberJS 1.10 beta channel, maybe?

**Comment by rwjblue** [comment] 2015-01-30 12:13
No, we cannot upgrade RSVP for 1.10, it is possible still for 1.11. The last time we attempted to update there were some odd errors that we haven't tracked down yet.

Also, as of Pretender 0.5.0 all requests are actually done asynchronously (they were previously sync).  If I am understanding the issue you are describing, this should solve it.

**Comment by szines** [comment] 2015-01-31 04:51
Thanks for your response. Hopefully it's going to solve our problem, however we have to update our tests to be compatible with the new asynchronous behaviour.

**Comment by stefanpenner** [comment] 2015-01-31 05:09
> however we have to update our tests to be compatible with the new asynchronous behaviour.

likely a good thing, if its async in real life, it should be async in your tests

**Comment by rwjblue** [comment] 2015-02-07 01:29
Closing as I believe we have a solution (and the issue was caused by older versions of Pretender being sync).

**Closed by rwjblue** 2015-02-07 01:29 UTC
