### ISSUE TITLE
[BUG] Ember.Select no longer defaults to first option when value is undefined (as of 1.13)

### ISSUE THREAD

**Issue by rondale-sc** [emberjs/ember.js#12141] opened 2015-08-18 17:56 UTC
Here is a jsbin that illustrates the issue:

http://emberjs.jsbin.com/xabokiyoco/edit?html,css,js,output

If you change the Ember version to 1.13 you'll no longer see "red" show up.

**Comment by btecu** [comment] 2015-08-18 23:49
I think `Ember.Select` has more issues and there's not motivation for it to be fixed, since it's use is deprecated. You should write your own component or use an addon...

**Comment by rwjblue** [comment] 2015-08-19 01:37
@rondale-sc - This is a ultimately a duplicate of https://github.com/emberjs/ember.js/issues/10984, but @btecu is correct and `Ember.Select` is deprecated.

**Comment by pixelhandler** [comment] 2015-08-22 00:23
@rondale-sc have you tried the x-select component? see emberaddons.com

**Comment by rwjblue** [comment] 2015-08-23 13:52
I have chatted with @rondale-sc a bit about this, and while I agree that this is a regression from from 1.11 (but not related to Glimmer work in 1.13) it is unlikely to be addressed.

I would happily review a PR and release another 1.13.x version if someone wants to tackle it though.

**Closed by rwjblue** 2015-08-23 13:52 UTC

**Comment by rondale-sc** [comment] 2015-08-23 15:10
@rwjblue  :+1: 

@pixelhandler Thanks, I did look into that one, but decided to roll my own for now.  :)
