### ISSUE TITLE
Ember adds event listeners for events my App doesn't care of

### ISSUE THREAD

**Issue by nonmanifold** [emberjs/ember.js#11653] opened 2015-07-06 09:42 UTC
This is just stupid, to run event handlers for touch move, mouse move and so on when my app uses only point-and-click navigation! 
If someone is interested in event, you add listener and remove it after no one is interested in it anymore.

**Comment by DeeSee** [comment] 2015-07-06 12:05
+1

**Comment by Akhrameev** [comment] 2015-07-06 12:06
+1

**Comment by rlivsey** [comment] 2015-07-06 12:06
See #11540 for discussion on this.

> This is just stupid

As an aside, [please be respectful](http://emberjs.com/guidelines/) when you're opening issues, it may seem "stupid" but there are reasons for the way it works like this and doing it the way you suggest is actually rather nuanced and complicated, as discussed on #11540 and other similar issues.

**Comment by rwjblue** [comment] 2015-07-06 12:14
Well said @rlivsey.

Closing this as a duplicate of #11540.

**Closed by rwjblue** 2015-07-06 12:14 UTC
