### ISSUE TITLE
[1.13.beta-2 Regression] Cannot call get with 'currentPath' on an undefined object.

### ISSUE THREAD

**Issue by jakehow** [emberjs/ember.js#11293] opened 2015-05-27 16:54 UTC
Usage of currentPath() is no longer working in our test suite.

Our suite passes on 1.13.beta-1.   Using currentPath() in our acceptance tests on 1.13.beta-2 results in the following error: 

`Assertion Failed: Cannot call get with 'currentPath' on an undefined object.`

Here is a sample usage from our suite:

```javascript
  visit('start');
  andThen( () => {
    equal(currentPath(), 'display.accounts');

    let accountsDiv = find('.accounts');
    ok(accountsDiv.length, 'shows accounts div');

    accounts.forEach(function(account){
      ok(accountsDiv.find(`:contains(${account.name})`).length,
         `has account with name ${account.name}`);
    });
  });
```

**Comment by rwjblue** [comment] 2015-05-27 17:57
Take a look at http://emberjs.jsbin.com/rwjblue/552/edit, which seems to be working in the simple case.

Can you tweak this JSBin to show how the error is introduced?

**Comment by jakehow** [comment] 2015-05-27 18:15
@rwjblue when I switched to master to test the service issue these tests pass also for me.  If your gist is using master maybe this was also resolved in a commit pending release?

**Comment by funtusov** [comment] 2015-05-27 22:06
For what it's worth, still passes with current beta instead of canary: http://emberjs.jsbin.com/vulemibubi/1/edit?html,css,js,output

**Comment by rwjblue** [comment] 2015-05-28 01:29
OK, so looks like this is working on latest beta so I'm going to close this, but I'm happy to reopen with a reproduction...

**Closed by rwjblue** 2015-05-28 01:29 UTC
