### ISSUE TITLE
Assertion Failed: You attempted to access the `size` property

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember.js#16259] opened 2018-02-19 16:10 UTC
on Ember 3.1.0-beta.1:

> Assertion Failed: You attempted to access the `size` property (of <DS.Errors:ember1800>).
Since Ember 3.1, this is usually fine as you no longer need to use `.get()`
to access computed properties. However, in this case, the object in question
is a special kind of Ember object (a proxy). Therefore, it is still necessary
to use `.get('size')` in this case.
>
> If you encountered this error because of third-party code that you don't control,
there is more information at https://github.com/emberjs/ember.js/issues/16148, and
you can help us improve this error message by telling us more about what happened in
this situation.

This seems to be caused by Ember Data using `isEmpty()` on a `DS.Errors` object. Since `isEmpty()` checks `obj.size` unconditionally it is causing the error above.

**Comment by Turbo87** [comment] 2018-02-19 16:13
Seems to be related to https://github.com/emberjs/ember.js/pull/9414

/cc @mixonic

**Comment by rwjblue** [comment] 2018-02-19 20:15
This was fixed in https://github.com/emberjs/data/pull/5340. The issue is that the DS.Errors unknownProperty returned null instead of undefined (and our proxy assertion only “allows” undefined).

**Closed** 2018-02-23 08:01 UTC
