### ISSUE TITLE
[Glimmer] `each` helper breaks glimmer and app when component fails

### ISSUE THREAD

**Issue by adrigzr** [emberjs/ember.js#17717] opened 2019-03-07 11:35 UTC
Hi,

When you render a component inside an `each` helper and the component fails, glimmer will crash on every `rerender`. 

Here is the [twiddle](https://ember-twiddle.com/b43f4369fdcdc570ff6e91ed6555126d) to reproduce it.

Steps:

1. Load twiddle and open inspector. You will see the component crash on the console.
2. Click on the button to force a `rerender` on Glimmer.
3. Error is thrown.

Error:

```
Uncaught TypeError: Cannot read property 'nextSibling' of null
    at DOMChanges.insertAfter (runtime.js:2096)
    at ListBlockOpcode.evaluate (runtime.js:3868)
    at UpdatingVM.execute (runtime.js:3638)
    at RenderResult.rerender (runtime.js:3943)
    at RootState._this30.render (ember-glimmer.js:4075)
    at TransactionRunner.runInTransaction (ember-metal.js:406)
    at InteractiveRenderer._renderRoots (ember-glimmer.js:4340)
    at InteractiveRenderer._renderRootsTransaction (ember-glimmer.js:4372)
    at InteractiveRenderer._revalidate (ember-glimmer.js:4412)
    at invoke (backburner.js:247)
```

Regards,

**Comment by swarnavallis** [comment] 2019-05-21 14:38
Replace the code in my-component.hbs

{{#each list as |item|}}
	{{component item}}
{{/each}}

as

{{#each list as |item|}}
	**<div>{{component item}}</div>
{{/each}}**

**Comment by swarnavallis** [comment] 2019-05-21 14:41
Replace the code in my-component.hbs as

{{#each list as |item|}}
<div>
{{component item}}
</div>
{{/each}}

**Comment by locks** [comment] 2023-07-22 21:01
Closing as no longer relevant due to usage of older `Ember.Component` API. Thanks for having provided a reproduction!

**Closed by locks** 2023-07-22 21:01 UTC
Labels: Bug, Has Reproduction
