### ISSUE TITLE
Uncaught TypeError: Cannot convert object to primitive value

### ISSUE THREAD

**Issue by caseklim** [emberjs/ember.js#14922] opened 2017-02-09 23:56 UTC
I'm seeing the following error upgrading from 2.9 to 2.11.0:
```
Uncaught TypeError: Cannot convert object to primitive value
```

`toString` is being called on an array containing objects of label/value pairs:

![screen shot 2017-02-09 at 3 46 15 pm](https://cloud.githubusercontent.com/assets/2915936/22808094/2181b794-eedf-11e6-979e-deac35c4abaf.png)

`toString` appears to be initiated from an `assert` statement in the `set` function:

![screen shot 2017-02-09 at 3 46 39 pm](https://cloud.githubusercontent.com/assets/2915936/22808096/23367d90-eedf-11e6-803d-4e64ba00d434.png)

I believe `set` is being initiated on a component property in a template from a helper. In this case, the `group` helper simply returns the params that were passed into it:
```
checkboxes=(group
  (hash label="Foo" value="foo")
  (hash label="Bar" value="bar")
)
```

I created an Ember Twiddle but I was unable to reproduce the error:
https://ember-twiddle.com/ae1d147bd798f9ba0c499c271c743eb3?openFiles=templates.application.hbs%2Ctemplates.components.my-component.hbs

**Comment by Serabe** [comment] 2017-02-10 00:43
Can you please check that my answer for https://github.com/emberjs/ember.js/issues/14921#issuecomment-278823446 does not solve this issue?

Thank you!

**Comment by caseklim** [comment] 2017-02-10 01:09
Your answer to #14921 solved that issue, but now I'm seeing this same issue in another place:
![screen shot 2017-02-09 at 5 08 15 pm](https://cloud.githubusercontent.com/assets/2915936/22809942/6940fc74-eeea-11e6-97d8-143cf92bd442.png)

I fixed #14921 by having our `group` helper now return `params.slice()` rather than just `params`

**Comment by Serabe** [comment] 2017-02-10 09:49
I would need more context to solve it. Can I see the computed property? The array is coming from a group?

**Comment by rwjblue** [comment] 2017-02-10 16:11
The rough issue is this:

![screenshot](https://monosnap.com/file/inWJFTQlXGqWchqBoXN4TlC7XO0YuJ.png)

The assertion is attempting to convert `content` to a string (to make the error message nice), but calling `Object.create(null) + ''` throws an error...

**Comment by caseklim** [comment] 2017-02-10 19:12
For anyone else who encounters this issue, we narrowed it down to the built-in `hash` helper. As a workaround, we overrode this built-in helper in our app until a fix makes it into Ember:
```
export function hashObj(_, obj) {
  const returnObj = {};

  for (const key in obj) { // eslint-disable-line
    returnObj[key] = obj[key];
  }

  return returnObj;
}
```

**Comment by rwjblue** [comment] 2017-02-10 19:17
I had some time and paired with @caseklim on the root cause of the issues that were being hit above.

I need to discuss with @chancancode  / @krisselden  / etc, but I suspect that we need to make the `(hash` helper not return an `EmptyObject` (possibly using the technique that @caseklim and I came up with and she pasted above)...

**Comment by rwjblue** [comment] 2017-02-24 13:49
Now that we have tracked down the issue (thanks @caseklim for pairing with me to figure it out!), I'm going to close this issue in favor of https://github.com/emberjs/ember.js/issues/14738 (which is for the same issue).

**Closed by rwjblue** 2017-02-24 13:49 UTC
Labels: Needs Submitter Response

**Comment by mrgenesis** [comment] 2018-09-27 20:56
> The rough issue is this:
> 
> ![screenshot](https://camo.githubusercontent.com/897dcfcc139da5a7ae97efaaea06f16b1390f18c/68747470733a2f2f6d6f6e6f736e61702e636f6d2f66696c652f696e574a4654516c58477157636871426f584e34546c4337584f3059754a2e706e67)
> 
> The assertion is attempting to convert `content` to a string (to make the error message nice), but calling `Object.create(null) + ''` throws an error...

**It really solved my trouble.** I did put an object in `string ${val}`, this was having error.
