### ISSUE TITLE
transitionTo() enhancement

### ISSUE THREAD

**Issue by rotatingJazz** [emberjs/ember.js#10151] opened 2015-01-06 01:09 UTC
`transitionTo`/``transitionToRoute` won't do anything when you point it to the same route with the same model. This calls for workarounds like having an action on the router that will do a `this.refresh()` and call that from the controller instead. Also causes complications in the template where you have to conditionally use an `action` instead of a `link-to` (think of pagination).

Perhaps add an optional parameter to the function that will enable the "reload the same model" behavior when needed?

**Comment by mmun** [comment] 2015-01-06 01:26
:+1: The specific use case I had trouble with is refreshing the model if you click on the "Page 1" link but you're already on Page 1. I think this is what web page users expect to happen.

/cc @machty @wycats @tomdale

**Comment by ef4** [comment] 2015-01-06 14:58
If you pass a model to transitionTo or link-to you're explicitly saying "use this model, it's ready to go."

If you want to cause lookup again, just transition to its ID instead. So 

    {{link-to "page" current}}

Becomes

    {{link-to "page" current.I'd}}

**Comment by mmun** [comment] 2015-01-06 15:00
@ef4 The issue is that in the second case it doesn't refresh the model if you link-to the same arguments.

**Comment by machty** [comment] 2015-01-06 15:02
The router will look at the params you pass in and see if they match the serialized params of the existing model loaded into that route, without calling any model hooks.

**Comment by ef4** [comment] 2015-01-06 15:32
Ah, I didn't realize it optimized like that. Carry on then...

**Comment by rwjblue** [comment] 2016-04-13 23:13
Features are generally discussed in the https://github.com/emberjs/rfcs/ repository. You can create an issue there for feature requests or a pull request to propose a new feature.  I'm closing this issue (this isn't really a bug in the framework), but please follow up with an RFC issue/PR if you are interested in taking this further.

**Closed by rwjblue** 2016-04-13 23:13 UTC
Labels: Feature, Needs Team Discussion
