### ISSUE TITLE
Template only glimmer components not working in 3.2?

### ISSUE THREAD

**Issue by lougreenwood** [emberjs/ember.js#16737] opened 2018-06-11 11:36 UTC
Seems that in 3.2 `template-only-glimmer-components` do not work.

Steps to reproduce:

* Enable `template-only-glimmer-components` feature toggle
* Create a new component
* Add some content to template
* Remove the component js file
* See that rendered HTML still has `ember-view` div wrapper

**Comment by rwjblue** [comment] 2018-06-11 13:41
Hmm, this seems to be working for me. I did the following:

```
ember new testing-togc
cd testing-togc
ember install @ember/optional-features
ember feature:enable template-only-glimmer-components
ember generate component template-only
rm app/components/template-only.js
echo '{{template-only}}' >| app/templates/application.hbs
echo 'Hi!' >| app/templates/components/template-only.hbs
ember s
```

When I look at the [DOM for this I see](http://assets.rwjblue.com/2018-06-11_09-14-31_hiz5k_Developer_Tools_-_httplocalhost4200.image.png):

```html
<body class="ember-application">
    <script src="/assets/vendor.js"></script>
    <script src="/assets/test-template-only-glimmer-components.js"></script>

    <div class="ember-view" id="ember274">Hi!
    </div>
</body>
```

Notice that there is no `div` wrapper for the component we created, however there is a single `class="ember-view"` / `id="ember888"` (which is actually representing the application wrapper, not the component).  Maybe this was what you were seeing?

You can also get rid of that `div` if you'd like, via this command:

```
ember feature:disable application-template-wrapper
```

Once that has been ran the DOM looks like:

```html
<body class="ember-application">
    <script src="/assets/vendor.js"></script>
    <script src="/assets/test-template-only-glimmer-components.js"></script>
Hi!
</body>
```

**Comment by rwjblue** [comment] 2018-06-11 13:55
I _believe_ this is working correctly (demo'ed above), so I'm going to go ahead and close this issue. Please let me know if I've made a mistake, I'm happy to reopen to dig into a reproduction...

**Comment by lougreenwood** [comment] 2018-06-11 15:29
Strange - your demo also works for me too (although the demo installs ember 3.1, but I manually upgraded to and tested 3.2 as well), however I still get the problem on my main project - I suppose it's a conflict somewhere else so I'll probably have to trawl through my add-ons to figure out the cause... :(

**Comment by nightire** [comment] 2018-06-11 18:06
@lougreenwood some addon will inject properties/states into components implicitly, so it's impossible(I guess?) to create the template-only component. AFAIK, ember-css-modules is one of them.

**Comment by lougreenwood** [comment] 2018-06-11 19:25
@nightire interesting - I don't use `ember-css-modules`, but I do use `ember-responsive` which looks like it may do something like this....

Are you aware of any way to track down which other add-ons may do this?

**Comment by lougreenwood** [comment] 2018-06-12 08:27
On further thought, I suppose that unless there's some other magic/not-obvious way in which addons can inject into components, then initialisers will probably be the way to identify addons which may be injecting?

**Comment by dpatz** [comment] 2018-08-17 05:34
@lougreenwood I'm also running into this issue. Did you ever figure out what the issue was?

**Comment by dpatz** [comment] 2018-08-17 06:04
@rwjblue I followed the steps you posted and it worked when Ember 3.1 was installed. However, when I upgraded to Ember 3.3, it seemed like both template only and application wrapper optional features both stopped working. Here's a repo showing the issue: https://github.com/dpatz/testing_togc

**Comment by lougreenwood** [comment] 2018-09-08 11:38
I'm still getting this on 3.4... :( 

Any advice on how to track down any add ons which may be injecting properties into components (aside from uninstalling add ons).

Is there some debug flag I can enable to observe this?

**Comment by nightire** [comment] 2018-09-08 12:27
@lougreenwood maybe you can try to contact @dfreeman to see if he can helps you. He just has solved the same issue caused by his ember-css-modules, see https://github.com/salsify/ember-css-modules/pull/99

**Comment by rwjblue** [comment] 2018-09-08 12:28
Thanks for the reproduction @dpatz, sorry I missed that. 

I’ll try to test that out and see if I can spot what’s going on...

**Comment by lougreenwood** [comment] 2018-09-08 13:26
@nightire For my issue you're 100% correct. Seems that my use of `ember-cli-notifications` was pulling in `ember-css-modules`, which was breaking my template-only components.

Adding this to my package.json fixed it for me:

```
  "resolutions": {
    "ember-cli-notifications/**/ember-css-modules": "1.0.0-beta.1"
  }
```

**Comment by dpatz** [comment] 2018-09-13 06:43
@rwjblue Any idea what's going on yet? Is there anyway I can help?

**Comment by rwjblue** [comment] 2018-09-13 09:57
@dpatz - the reproduction repo you shared above does not depend (dep or devDep) on `@ember/optional-features` at all. The presence of `config/optional-features.json` only works if `@ember/optional-features` is installed...

**Comment by rwjblue** [comment] 2018-12-10 00:19
Whoops, missed closing this one out when resolved.

**Closed by rwjblue** 2018-12-10 00:19 UTC
