### ISSUE TITLE
Asserting error thrown no longer works as of 2.11

### ISSUE THREAD

**Issue by ykaragol** [emberjs/ember.js#15013] opened 2017-03-14 09:04 UTC
The following  test, no longer run after we start to use 2.11.1.

```
test('it throws error my-custom-input is called', function(assert) {
    assert.throws(() => {
        this.render(hbs`{{my-custom-input}}`);
    }, /my-custom-input component error/, 'Error must have been thrown');
});
```

I saw mocha users had faced with nearly the same problems: https://github.com/emberjs/ember-mocha/issues/141

SO Question: http://stackoverflow.com/questions/42781085/ember-render-hbs-swallowing-thrown-error
Slack Archive: https://embercommunity.slack.com/archives/-testing/p1489479464001332

**Repro**
https://ember-twiddle.com/47c4cfbb571ac3fa83ab912f605ebc6a?fileTreeShown=false&openFiles=tests.integration.components.i-throw-test.js%2C

**Comment by efx** [comment] 2017-03-14 12:47
I am seeing identical errors with should.js and expect style assertions, also using mocha. Though, I only see this when bumping from 2.11.2 to 2.11.3.
similar pattern failing using expect and should.js: 
```
(function() {
	this.render(hbs`{{async-image}}`);
}).should.throw('need a source');
```

**Comment by pixelhandler** [comment] 2017-03-17 15:43
Is this something that can be replicated using ember-twiddle?

**Comment by efx** [comment] 2017-03-17 16:00
@pixelhandler i'm struggling getting an ember-mocha twiddle set up, any tips / examples?
started here: https://ember-twiddle.com/49a310682db5d8433dff5ef98ab75211?

**Comment by mupkoo** [comment] 2017-03-17 16:02
I tried to reproduce it without any success. Maybe something related to the Ember versions in the Twiddle 

https://ember-twiddle.com/8932ace19517f83ef12693068381b6a3?openFiles=twiddle.json%2C

**Comment by ykaragol** [comment] 2017-03-17 19:25
As one of the Stackoverflow [comment](http://stackoverflow.com/questions/42781085/ember-render-hbs-swallowing-thrown-error) says they could not reproduced it in twiddle. 
But checkout this repo: https://github.com/feanor07/ember-component-init-error-swallowed

**Comment by nickiaconis** [comment] 2017-03-22 23:16
I've reproduced this in a Twiddle. The key to reproduction is to run any acceptance test before running the test that asserts the thrown error. Running the acceptance test populates `Ember.Test.adapter`, and it is that adapter that handles the error before `assert.throws` can receive it.

https://ember-twiddle.com/47c4cfbb571ac3fa83ab912f605ebc6a?fileTreeShown=false&openFiles=tests.integration.components.i-throw-test.js%2C

**Comment by nickiaconis** [comment] 2017-03-24 23:03
Here's a work-around for QUnit:

```javascript
import Ember from 'ember';
import QUnit from 'qunit';
import { QUnitAdapter } from 'ember-qunit';

// Work-around for https://github.com/emberjs/ember.js/issues/15013
const originalAssertThrows = QUnit.assert.throws;
const rethrowAdapter = QUnitAdapter.extend({
  exception(error) {
    throw error;
  },
}).create();
QUnit.assert.throws = () => {
  const originalAdapter = Ember.Test.adapter;
  Ember.Test.adapter = rethrowAdapter;

  originalAssertThrows.apply(this, arguments);

  Ember.Test.adapter = originalAdapter;
};
```

**Comment by efx** [comment] 2017-04-19 19:23
I've narrowed down the problem to the following change: https://github.com/emberjs/ember.js/commit/a90fa0641d16f12566cbfef16ea2604e68ed6dd9#diff-33ff1529a427727ffe2425f145375540L24. Reverting this to `getOnerror()` produces the expected assertions in my project. I'm going to keep tinkering if there is a way to exempt test assertions from dispatching the entire events. 
that said workmanw might have the better/quicker solution here.
/cc @workmanw

**Comment by tzellman** [comment] 2017-05-03 16:54
Just came across this same issue while attempting to update an addon from ember/cli `2.9`. Has anyone found a decent workaround `ember-cli-chai` usage?

**Comment by alvincrespo** [comment] 2017-05-11 01:58
I'm currently working on our ember-link-with-follower update and running across this issue in our tests: https://github.com/echobind/ember-links-with-follower/pull/191. We're using ember-cli-mocha.

**Comment by pixelhandler** [comment] 2017-11-03 16:59
@ykaragol I'm curious if this is still an issue in 2.16.x ?

**Comment by alexlafroscia** [comment] 2017-11-04 19:20
I tried a quick reproduction on Twiddle and it seems like it's maybe fixed in 2.16?

https://ember-twiddle.com/7a54c0cb1c5c6fd186b810e1130818de?openFiles=tests.integration.components.my-component-test.js%2Ctemplates.components.my-component.hbs

Not sure about whether it works in Mocha, but it seems to be working on QUnit at least

**Comment by ykaragol** [comment] 2017-11-06 08:40
@pixelhandler I didn't test it. I'd just use the workaround shown in the [StackOverflow Question](http://stackoverflow.com/questions/42781085/ember-render-hbs-swallowing-thrown-error).

**Comment by rwjblue** [comment] 2017-11-06 15:41
The [ember-qunit-assert-helpers](https://github.com/workmanw/ember-qunit-assert-helpers) addon was specifically created to handle this scenario...

**Comment by rwjblue** [comment] 2017-11-28 22:01
This was fixed by https://github.com/emberjs/ember.js/pull/15871, which essentially reverts https://github.com/emberjs/ember.js/pull/14898 and adds a **bunch** of tests.

**Closed by rwjblue** 2017-11-28 22:01 UTC
Labels: Has Reproduction
