### ISSUE TITLE
Binding `selected` to `<option>`s via handlebars values doesn't add attributes

### ISSUE THREAD

**Issue by Kerrick** [emberjs/ember.js#15709] opened 2017-10-05 21:30 UTC
[Ember Twiddle](https://ember-twiddle.com/13c4c20e05678041ad3a8a1fea3cfc39?openFiles=templates.application.hbs%2C)

If you have the following Handlebars in an Ember application:
```hbs
<select>
  <option disabled>--Select One--</option>
  <option>hello</option>
  <option selected={{true}}>goodbye</option>
  <option>maybe</option>
</select>
```

You'd expect the "goodbye" option to be selected and to have a `selected` boolean HTML attribute. It _is_ selected, but it _does not_ have the attribute. This means you do indeed see the "goodbye" in a closed select menu, but using CSS to style `option[selected]` does not work because the attribute is missing.

**Comment by Serabe** [comment] 2017-10-13 13:28
Thank you!

**Comment by raido** [comment] 2017-10-30 19:45
I also stumbled upon in my component that wraps bootstrap-select which uses selected attribute to set up it's own logic.

Workaround for now:

```
{{#if somethingShouldBeSelected}}
  <option selected="selected">...</option>
{{else}}
  <option>...</option>
{{/if}}
```

**Comment by pixelhandler** [comment] 2018-09-28 17:35
@Kerrick @Serabe @raido is this still an issue, perhaps we should close or create a new reproduction of this, what do you think?

**Comment by raido** [comment] 2018-09-28 18:41
My project is still has workaround as above so probably but I’ll confirm this in few days.

**Comment by Serabe** [comment] 2018-09-29 00:01
@pixelhandler updated https://ember-twiddle.com/63f5290e898dfeee90f7266ce01af5ef?openFiles=controllers.application.js%2C

Still a bug.

**Comment by rwjblue** [comment] 2018-09-29 13:03
Hmm, I don’t really grok the twiddle. It’s not clear to me what is expected for each of those selects. Some don’t make a ton of sense to me (e.g. having multiple `option`s with selected but not marking the select as a multi select).

**Comment by Kerrick** [comment] 2018-09-29 19:41
Yep, the first example in the twiddle is the actual use-case, the rest was just messing around.

**Comment by raido** [comment] 2019-01-08 09:05
It seems same happens when you do:

```
export default Component.extend({
  tagName: 'option',
  attributeBindings: ['isSelected:selected']
});
```

<option> is actually selected, doing but no attribute in DOM.

**Comment by mixonic** [comment] 2020-04-24 18:58
I'm closing this issue as the described behavior is not a bug. That said, I and FW core agree that it is confusing! We consider the mis-match in expectation and behavior a design flaw.

Ember follows a "prop-first if prop available, fallback to attribute" approach to setting a property or attribute when there is a binding in a template. `<option selected={{true}}>` will set the property of the option element, as expected since `selected` is a property on the DOM node for an option.

In _many_ cases property values are reflected as attributes, however in this case (`selected` prop on an option element) the DOM does **not** have that behavior! In many ways the gap in expectation and behavior is a failing of the DOM API, and not of Ember.

However it **is** confusing and changing Ember is, relatively, a lot easier than changing the DOM API :-) I have some followups for this:
* @rwjblue says he has a writeup with more details about how this works today in Ember. He will share that here.
* The FW core team has been thinking about this problem for a long time, and we think we have a path forward that wasn't as clear a year or two ago. I'm taking away an action item to draft the RFC for making Ember templates "attribute only, prop via a modifier" and we can continue this conversation there!

**Closed by mixonic** 2020-04-24 18:58 UTC
Labels: Bug, Has Reproduction, Rendering

**Comment by rwjblue** [comment] 2020-04-24 19:50
This is _basically_ what Ember is doing today:

1. create the element
2. determine if the attribute from the template is also a property of the element (e.g. `'selected' in element`)
3. if it is a property, set it (e.g. `element.selected = true`)
4. if it is an attribute, call `setAttribute` (e.g. `element.setAttribute('selected', true)`)

Here is a (working) pseudo implementation that may make the steps above make more sense:

```js
let normalizedPropertiesByTag = new Map();

function selectAttributeOrPropertyFor(element, name) {
  let propertiesForTag = normalizedPropertiesByTag.get(element.tagName);
  
  if (propertiesForTag === undefined) {
    let propertiesForTag = new Map();
    for (let key in element) {
      propertiesForTag.set(key.toLowerCase(), key);
    }
    normalizedPropertiesByTag.set(element.tagName, propertiesForTag);
  }

  let propertyName = propertiesForTag.get(name.toLowerCase());
  if (propertyName) {
    return { type: 'property', name: propertyName };
  }

  return { type: 'attribute', name };
}

function populateAttributeOrProperty(element, attributeOrProperty, value) {
  let details = selectAttributeOrPropertyFor(element, attributeOrProperty);

  if (details.type === 'property') {
    element[details.name] = value;
  } else {
    element.setAttribute(details.name, value);
  }
}

// when rendering for <div data-foo="asdf"></div>
let el = document.createElement('div');
populateAttributeOrProperty(el, 'data-foo', 'asdf');
```
