### ISSUE TITLE
Explicitly setting a component property via an attribute when including causes it to be immutable

### ISSUE THREAD

**Issue by cdl** [emberjs/ember.js#11388] opened 2015-06-09 20:04 UTC
**Affects:** `v1.13.0-beta.1`, `v1.13.0-beta.2`

**Steps to reproduce (have included the example data for reference in parentheses):**
- Create a component (`auth-modal`) that has an attribute (`showSignup`), and rely on that attribute in some way in the contents of the component template (e.g: use an `unless` or `if` to swap out the content depending on the value of `showSignup`, or just output the content of `showSignup`).
- Then, set it explicitly via an attribute when including the component (`{{auth-modal showSignup=false}}`), and then try to mutate that property via an action (`this.toggleProperty('showSignup')`).

**Expected results:**
- Property would be mutated in the component (visible in the Ember inspector), DOM would update accordingly.

**Actual results:**
- Property mutates in the component (visible in the Ember inspector, as well as in `Ember.debug`s), but the DOM doesn't reflect the new property.

[I've made up a JSBin demonstrating this behaviour](http://emberjs.jsbin.com/kukume/3/edit). This all functions fine if you remove the explicit declaration of the property when including the component (remove `showSignup=false` from the `index` template in the HTML). This could very easily be something that was added in v1.13 that I'm just missing, however.

**Comment by bantic** [comment] 2015-06-16 14:56
I think I discovered the same issue when experimenting with new computed property getter and setters. It appears to happen when the passed-in property is a literal value (i.e. `false`, or a `"string"`). When the passed-in property is another property name, the proper behavior exists (although the property is two-way bound to the outside of the component scope).  For example, changing your jsbin to pass  in a property `shouldShowSignup` rather than the literal `false` allows the `switchAuthModal` action to update the value as expected:
http://emberjs.jsbin.com/wuzefu/edit?html,css,js,output

Here's a [pretty involved jsbin](http://emberjs.jsbin.com/meweba/edit?html,css,js,output) showing the same issue when using computed property getter/setters. It has the same broken behavior: passing in string literals breaks the expected behavior, passing in bound properties instead restores the expected behavior.

**Comment by locks** [comment] 2016-04-15 10:03
@cdl @bantic is this still applicable? thanks

**Comment by bantic** [comment] 2016-04-15 14:21
I will check it today

**Comment by bantic** [comment] 2016-04-18 14:17
@locks Confirmed this on `v1.13.0-beta.1`, `v1.13.0-beta.2`, `v1.13.1` and `v1.13.2`. Versions `1.13.3` and greater do not seem to have this problem.

I've cleaned up the JSBin to do a better job explaining the bug: http://emberjs.jsbin.com/wuzefu/7/edit?html,js,output

**Comment by Serabe** [comment] 2016-04-18 14:25
It is working on [2.5.0](http://emberjs.jsbin.com/vipexo/1/edit?html,js,output) as well. Since this only seem to affect old versions of 1.13, I am closing this. Feel free to reopen if you feel it is needed.

Thank you!

**Closed by Serabe** 2016-04-18 14:25 UTC
Labels: Ember 1.13
