### ISSUE TITLE
after upgrading to ember "2.14.0" app is throwing random different errors in safari

### ISSUE THREAD

**Issue by ivpusic** [emberjs/ember.js#15468] opened 2017-07-07 01:09 UTC
Hi,

I just upgraded to ember 2.14.0. Everything works great in Chrome/Firefox, but app in Safari is broken. In previous ember release (2.13.2) worked perfectly, but now I am getting errors like:

```
owner.lookup is not a function. (In 'owner.lookup('-view-registry:main')', 'owner.lookup' is undefined)

or
null is not an object (evaluating 'm.isInitialized')

or
undefined is not an object (evaluating '_ember.default.getOwner(this).lookup')

or
undefined is not an object (evaluating '(0, _emberUtils.getOwner)(this).__container__') (1)
```

These happen randomly...on page load... when I click on some link...

Do you have an idea what might be the problem? Again, Ember 2.13.2 worked in Safari as well.

**Comment by pieter-v** [comment] 2017-07-07 09:32
We have the same problem. Some routes of our app work, other don't.
I have the impression that routes that return a unresolved promise from the beforeModel hook are the ones that fail.
Tried to debug this:
in the route beforeModel hook: Ember.getOwner(this) returns an object
afterwards, in Route.paramsFor: Ember.getOwner(this) returns undefined ('this' is still the same route instance)

**Comment by locks** [comment] 2017-07-07 09:38
@pieter-v can you provide some code?

**Comment by simonihmig** [comment] 2017-07-07 11:49
Just run into this myself. Was first reported as a bug in ember-bootstrap (https://github.com/kaliber5/ember-bootstrap/issues/374), but does not seem related. I was able to reduce the reproduction @varunsudhakar made to the bare minimum:

https://github.com/simonihmig/ember-2-14-safari

It still uses an external dependency (ember-cp-validations), but I don't _think_ the root issue comes from there. However I was not able to reproduce without it /cc @offirgolan

I recorded the following piece showing the reproduction using the repo above:

![demo](https://raw.githubusercontent.com/simonihmig/ember-2-14-safari/master/safari-bug.gif)

* you have to enter a bunch characters (the occurance of the exception seems to be not really deterministic, just happens more or less randomly)
* when that is the case, you can see that the meta object of that component is `null`. Also most properties seem to return `null`, although we still have a valid component in DOM

This also happens only in Safari (Mac, Version 10.1.1 (12603.2.4)), and only with ember 2.14.0.

**Comment by nragaz** [comment] 2017-07-07 20:26
In our case this also appears to only affect the development builds. Test and production builds work fine.

**Comment by Kilowhisky** [comment] 2017-07-10 15:40
This is occurring for me in production builds on safari only on OSX and iOS (10.3).  It seems to happen when i trigger a number of actions / inputs quickly.  CPU usage during this is also abnormally high.

**Comment by bekzod** [comment] 2017-07-11 06:09
found why it is failing in development at least 
https://github.com/simonihmig/ember-2-14-safari helped out (thanks @simonihmig )

there is two issue here: 
1. DEBUG flag is incorrectly replaced https://cl.ly/3e1a0c2Z2t1L/Image%202017-07-11%20at%2011.02.10%20AM.png

2. in meta file one debugger counter was missing `counters.peakPrototypeWalks` (added that https://github.com/emberjs/ember.js/pull/15486)

I think 1 issue should be fixed by person who understands DEBUG striping process

@locks

**Comment by rwjblue** [comment] 2017-07-11 10:54
I'm not spotting the issue in the image, can you explain how DEBUG is mishandled there?

**Comment by bekzod** [comment] 2017-07-11 11:07
Is it normal behavior to have leftover curly braces? Should it be 'if(true){ counter... }'

**Comment by backspace** [comment] 2017-07-11 15:15
We deployed Ember 2.14.0 on `travis-web` yesterday and got ratelimited by Sentry for the number of events logged; our plan allows for 200 events a minute. Here’s the various errors showing up starting yesterday:

![image](https://user-images.githubusercontent.com/43280/28075120-7b660fe2-6628-11e7-914d-042b12860213.png)

I’ve rolled back to Ember 2.13.4 for now and the errors have dropped off:

![image](https://user-images.githubusercontent.com/43280/28075217-d56203d4-6628-11e7-9440-34ede913be6a.png)

These errors were happening on a production deployment.

I made [this test deployment](https://bd-team-flags.test-deployments.travis-ci.org) before the reversion, it’s still on Ember 2.14.0. I can’t manage to reproduce the errors in Safari locally, frustratingly enough.

If there’s any information I can provide to help figure out what’s happening, let me know!

**Comment by baileymiller182** [comment] 2017-07-12 18:24
After upgrading an app from Ember 2.11 to Ember 2.14, it's unusable on Safari 10.1. @simonihmig's comment best describes reproduction steps.

The app also uses `ember-cp-validations`, which may or may not be a coincidence.

**Comment by simonihmig** [comment] 2017-07-14 09:06
For the record, as this has not been mentioned here yet: seems we have a fix ready: https://github.com/emberjs/ember.js/pull/15502. Awesome debugging work, thanks to @krisselden & @stefanpenner! 👏

**Closed** 2017-07-14 14:19 UTC

**Comment by stefanpenner** [comment] 2017-07-14 14:21
Looks like we hit a gnarly safari 10 JIT issue, luckily we were able to work around it. It also seems like safari 11 has already fixed the issue... so that's a good thing.

Backports are in, pending release.
