### ISSUE TITLE
Nesting templates with {{render}} is not working

### ISSUE THREAD

**Issue by selvaa89** [emberjs/ember.js#10892] opened 2015-04-17 07:30 UTC
I have the following code.

application.hbs
    {{render "top-bar"}}
    {{outlet}}

top-bar.hbs
    {{render "search"}}

search.hbs
    <p>Search Bar</p>

But this results in the following error: 
ember.debug.js: 18955 Uncaught TypeError: undefined is not a function

JS Bin: http://jsbin.com/fovutedeve/3
Ember Version: 1.11.1

**Comment by rwjblue** [comment] 2015-04-17 10:30
Duplicate of https://github.com/emberjs/ember.js/issues/10827, fixed in https://github.com/emberjs/ember.js/pull/10843 and included in 1.11.3.

**Closed by rwjblue** 2015-04-17 10:30 UTC
