### ISSUE TITLE
Manual refresh of nested child route causes unexpected refresh of parent routes including the application route

### ISSUE THREAD

**Issue by sarus** [emberjs/ember.js#12707] opened 2015-12-12 20:44 UTC
Based on the documentation for router.refresh (found here: http://emberjs.com/api/classes/Ember.Route.html#method_refresh and pasted below) it would seem that refreshing a route should only ever cause the refreshed route and its children to refresh.  

```
Refresh the model on this route and any child routes, firing the beforeModel, model, and afterModel hooks in a similar fashion to how routes are entered when transitioning in from other route.
```

However, when I refresh a leaf route in my application from the controller using `this.get('target.router').refresh()` I've found that the parent routes actually refresh including the application route's `beforeModel`, `afterModel`, and `model` hooks.  

This is what my route configuration looks like:

```
  this.route('explore', function(){
    this.route('tag', {path:'tag/:tag_id'}, function(){
      this.route('comments', {path:'comments'});
    });
  });
```

From inside the `comments` controller if I call `this.get('target.router').refresh()` it ends up triggering the `model()` hook on the application route, the explore route and the tag route.

Here is a JSBIN I put together to demonstrate the issue:

http://emberjs.jsbin.com/moxigefegi/1/edit?html,js,output

If you click through the links until you get down to the `Reload Comments Route` button you can watch the console output to see all the parent routes refreshing.  

Is this a bug or just incorrect/unclear documentation? Am I just using `refresh` wrong and this is expected behavior? 

Thank you!

**Comment by SalamonDharamaraj** [comment] 2016-05-17 05:38
u can define the action inside the route , instead of controller with "this.refresh()"
it will refresh the current route alone

**Comment by GramozKrasniqi** [comment] 2016-05-19 15:09
@sarus the documentaction sais that you should call the method on the Route that you want to refresh instead you are doing the refresh on the target(RouterMain).router which is the routerJs, Basically what you are doing is commanding the router of the MainRouter to refresh and of course that it will refresh everything including the ApplicationRoute and the other routes.
But we should try it also refreshing a specific route and if that has the same effect than the documentation is wrong or we have a bug.

**Comment by jcano** [comment] 2016-10-03 23:01
@SalamonDharamaraj @GramozKrasniqi I'm struggling with the same issue. The only way I found of refreshing the model is by calling `this.get( "target.router" ).refresh()`.

I know I have to call refresh from the router, but it's not possible to define actions on the route (unless you use an addon), so the action was implemented in the controller. How can I get the route to trigger this refresh? Or, how can I get the current route handler from the controller?

**Comment by Serabe** [comment] 2016-10-03 23:19
@jcano: you can send an action from the controller to the route just by using the `send` method.

I've fixed @sarus' jsbin. There were some typos there:

1. Route was named `ExploreTagCommentRoute` instead of `ExploreTagCommentsRoute`. That is the reason the send method was not finding the right route.

2. In `ExploreTagCommentsRoute.model`, the user can only see the params for that part, so I use `this.modelFor`.

3. Last, I send the action.

I cannot save a snapshot of the JSBin right now, it is giving me some problem with CORS :(

Here is the main part:

```js
App.ExploreTagCommentsRoute = Ember.Route.extend({
  model: function(params) {
    console.info("Model Hook of Explore.Tag.Comments Route Called");
    return this.modelFor('explore.tag');
  },
  actions: {
    refreshOnlyComments: function() {
      this.refresh();
    }
  }
});

App.ExploreTagCommentsController = Ember.Controller.extend({
  actions:{
    reloadComments: function(){
      this.send('refreshOnlyComments');
    }
  }
});
```

Can you please @sarus and @jcano check my comments above fix your problems. Thank you!

**Comment by SalamonDharamaraj** [comment] 2016-10-04 06:01
@jcano You can call route's action from controller's action.
Inside route's action you can use this.refresh();

**Comment by jcano** [comment] 2016-10-04 08:10
@Serabe I can confirm the solution works. I was confused because closure actions don't work when defined on the route, but routes can handle "normal" actions. Thanks!

**Comment by pixelhandler** [comment] 2016-10-22 22:39
@jcano there is an addon for using route actions, see https://github.com/DockYard/ember-route-action-helper

**Comment by Serabe** [comment] 2016-10-28 10:37
Ok, closing this then. Thank you all!

**Closed by Serabe** 2016-10-28 10:37 UTC
Labels: Needs Bug Verification, Needs Submitter Response
